include::config.adoc[]

== 簡介
A simple http://asciidoc.org[AsciiDoc] document.

A **paragraph** followed by a _simple_ list with #square bullets#.

[square]
* 測試**中文粗體字**
* 測試__中文斜體字__
* 測試 [underline]#文字加底線#
* 測試 [line-through]#刪除線#
* 測試 #改變顏色#

IMPORTANT: `[underline]` 和 `[line-through]` 前面必須有一個空格，否則無效。

=== Hello, World!

底下是一個以 C# 撰寫的 ``Hello, World!`` 函式：

.Create a basic PDF document using Prawn
[source,c#]
----
public void Hello()   <1>
{
    Console.WriteLine("Hello, World!");   <2>
}
----
<1> 函式宣告
<2> 輸出文字

NOTE: 這只是一個簡單範例。點一下 btn:[OK] 按鈕結束。 icon:[heart]

TIP: Tip

WARNING: 版權沒有，藏私必究。

CAUTION: Caution

IMPORTANT: Important

 縮進一格 [underline]#底線#
 縮進一格 <1>

[literal,indent=10]
--
兩個減號
Open Block -10 [underline]#底線# literal
--

[example,indent=10]
--
**兩個__減號__** +
兩個減號 +
Open Block -10 [underline]#底線# example
--

[source,indent=10]
--
**兩個__減號__**
兩個減號
Open Block -10 [underline]#底線# source
--

----
**四個__減號__**
四個減號 [underline]#底線#
四個減號 <u>底線</u>
----

++++
**四個__加號__**
四個加號 [underline]#底線#
四個加號 <u>底線</u>
++++

....
**四個__句號__**
四個句號 [underline]#底線#
四個句號 <1>
....    

====
**四個__等號__** +
四個等號 [underline]#底線# +
四個等號 <1>
====

****
**四個__星號__** +
四個星號 [underline]#底線# +
四個星號 <1>
****

____
**四個__底線__** +
四個底線 [underline]#底線# +
四個底線 <1>
____

[width="80%",options="header"]
|===============================================
|分割區	|掛載點		|分割區標籤	|檔案系統
|sda1	|/boot/efi	|ESP		|vfat
|sda2	|/boot		|Linux Native	|ext4
|sda3	|/		|Linux Native	|ext4
|sda4	|		|Linux Swap	|swap
|===============================================
