== 影音裝置

=== 影音硬體




==== 內核模組
內核支援的 USB 影像裝置硬體驅動模組，位於 `/usr/lib/modules/$(uname -r)/kernel/drivers/media/usb/`

==== 外部介面


=== 攝影裝置

==== 內核模組

如果是屬於符合 *UVC*(USB 視訊類別) 規格的**網路攝影機**(webcam) 裝置，內核就會以 `uvcvideo` 模組來驅動。
同時產生一到多個 `/dev/video_N_` 形式的資料裝置，以及 `/dev/media_N_` 形式的控制裝置（_N_ 均由 0 起算）。
萬一裝置確實有支援 UVC 卻沒有被內核辨認出來，可以利用 `lsusb` 找出它的**裝置識別碼**（參見〈系統裝置：USB：裝置資訊〉），然後嘗試輸入：
====
root# *echo _VID_ _PID_" > /sys/bus/usb/drivers/uvcvideo/new_id*
====



==== 臉部辨識
Linux 目前標準組態並不支援臉部辨識，需要安裝基於 OpenCV 函式庫的第三方軟體（例如 `pam-face`
footnote:[pam-face 的 GitHub 頁面 <https://github.com/philippmeisberger/pam-face>]
以及整合至登入程序所需的 `pam-python`
footnote:[pam-python 的 SourceForge 頁面 <https://pam-python.sourceforge.net/>]；
或者是 `howdy`
footnote:[howdy 的 GitHub 頁面 <https://github.com/boltgolt/howdy>]
搭配 `python-pam`
footnote:[python-pam 的 GitHub 頁面 <https://github.com/FirefighterBlu3/python-pam>]。）

基本的臉部辨識硬體衹需要一般的網路攝影機即可，但是如果要支援偵測體溫的臉部辨識登入軟體，
就需要額外具備紅外線鏡頭的攝影裝置，才能產生所需的原始影像格式。

==== 設定測試
如果系統中缺乏能夠存取網路攝影機的應用軟體，還可以利用網站 https://webcamtests.com/ 來測試網路攝影機。

如果播放影片時出現畫面跳格播放，這是由於無法維持正常顯示速度，為了要影音同步，因而導致畫面跳格播放。

=== 攝影工具程式

=== 蜂鳴裝置
在還沒有音訊裝置的終端機時代，就有配備**蜂鳴器**(buzzer) 做為發出警示音(beep) 的方式。
蜂鳴器的硬體構造可以分為壓電式與電磁式兩種，而驅動方式則分為通電後就可以發出內建單一音調的有源蜂鳴器，以及還需要提供頻率信號的無源蜂鳴器。

舊式通用的內核模組是 `pcspkr` ，而 `snd_pcsp` 則是較新的模組。
標準的工具程式是 `beep` ，但是需要先手動以 `modprobe` 命令載入上述的模組。
因為內核預設不會自動將蜂鳴器驅動為一般的音訊裝置，以免得到難以接受的播放音樂效果。

=== 音訊裝置
早期電腦的音效是由音訊晶片配合其他輔助晶片，以電腦擴充插卡的形式出現。
隨著技術的進步，基本的音訊功能衹需要單一的整合晶片即可完成，成為嵌入主機板的標準元件。

單晶片系統的整合晶片中，也將處理音訊的部分包含了進來。
在系統韌體設定中可能出現的 Azalia 啟用項目，就是 Intel 的內建音訊規格控制器代號，做為取代 AC97(音訊編解碼 '97) 的 HDA(高解析音訊) 標準。

==== 內核模組
內核會以 `soundcore` 與 `snd` 模組做為基礎，再搭配系統硬體平臺的模組進行驅動。
後續層級是與 HDA-Intel 規格相容的 `snd_hda_intel` 通用模組，從 `lspci` 的輸出就可以看到整合的音訊控制器。
在嵌入式系統中可能會以 SOC 類型取代 HDA 類型，相應載入的基礎模組則改為 `snd_soc_core` 。
HDA-Intel 裝置還分為類比與數位兩種模式，萬一驅動模組發生了誤判，就需要設定內核參數來指定模式。
透過 `snd_hda_intel` 模組參數，還可以進行調整的項目範例：

個別版本的內核模組，針對不同晶片編解碼器的支援程度也不相同。
例如來自 Realtek 品牌的各類 ALC_nnn_ 型號，都需要 `snd_hda_codec_realtek` 內核模組
想要找到編解碼器的型號，需要透過命令 `dmesg` 而非 `lspci` 的篩選輸出：
====
root# *dmesg | grep codec | sed 's/[^:]*: //'*
autoconfig for ALC888-VD: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
   speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
   hp_outs=1 (0x1b/0x0/0x0/0x0/0x0)
   mono: mono_out=0x0
   inputs:
     Mic=0x19
====
以上可以看到編解碼器的型號是 ALC888-VD，輸出介面的線路類型則為 speaker。
如果名稱出現 Generic 就表示內核雖然偵測到編解碼器，但無法辨識出晶片型號，有可能可以藉由模組參數來調整，讓部份的功能仍然可用。

由於部分顯示器規格（HDMI, DisplayPort）也包含了聲音輸出，因此常常附屬於支援此類顯示器規格的晶片組，並且大多會進一步整合於單晶片系統之中。
某些 AMD 平臺會預設停用外部 HDMI 音訊裝置，可能就需要類似 `radeon.audio=1` 的內核參數來開啟，但新版的 `amdgpu` 模組已經完成支援。
除了需要像是 `snd_hda_codec_hdmi` 之類的編解碼器驅動模組之外，音訊功能的開啟也會受到顯示驅動模組的影響。
如果預設顯示器音訊為啟用，卻想在系統啟動時期就關閉它，則可以利用將負責的內核模組（例如 `snd_hda_codec_hdmi` ）列入黑名單來達成。

HDMI 的音訊功能，還可能受到 IOMMU(輸入輸出主記憶體管理單元) 的影響。
萬一出現問題的時候，可以考慮選用下列的內核參數： `intel_iommu=on`, `amd_iommu=off`, `iommu=pt`, `iommu=soft` 。
對於某些舊型的 HDMI，可能需要設定 `snd_intel_dspcfg` 的模組參數 `dsp_driver=1` 後才會有聲音。


對於不論基於何種原因而無法存取內建音訊裝置的系統，也可以使用 USB 介面的可攜式音訊裝置，直接會附帶音訊的輸入輸出插座。
與附帶音訊輸入的整合式網路攝影機裝置相同，在內核模組方面是由 `snd_usb_audio` 負責，而大多數用於 `snd_hda_intel` 的模組參數也都適用。


==== 模組參數
大部分可用的模組參數是針對內核模組 `snd_hda_intel` ，例如在自行建立的 `/etc/modprobe.d/snd-hda-intel.conf` 檔案中，
會出現類似 `options snd_hda_intel model=auto` 的內容，其中 `model=` 項目的可選值眾多，提供使用者依情況採用。
例如 `basic`, `generic`, `genericx`, `ref`, `ideapad`, `3stack-dig`, `3stack-6ch`, `3stack-6ch-dig`, `6stack-hp`,
`laptop`, `laptop-amic`, `laptop-dmic`, `headset-mic`, `dell-headset-dock`, `dell-headset-multi`, `acer-headset-multi` …等等。
除此之外，模組 `snd_hda_intel` 還有許多可設定的參數，使用者可以參考選用：

./etc/modprobe.d/snd-hda-intel.conf (部分)
....
options snd_hda_intel id=Generic index=1
options snd_hda_intel dmic_detect=0
options snd_hda_intel position_fix=2
options snd_hda_intel patch=,clevo
options snd_hda_intel single_cmd=1
options snd_hda_intel probe_mask=1
options snd_hda_intel enable_msi=1
options snd_hda_intel power_save=0
options snd_hda_intel power_save_controller=0
options snd_hda_intel snoop=0
options snd_hda_intel align_buffer_size=1
....

如果想要避免每次開機後的編號都會受到內建裝置影響而不固定，可以使用 `snd_usb_audio.index=0` 這樣的內核參數。
在內建與外接裝置混用的情況下，還可以藉由內核參數 `snd.cards_limit=1` 或 `snd.slots=snd_usb_audio,snd_hda_intel` ，來強制設定裝置插槽的數量或順位。

==== 內部介面
i^2^s(音效晶片整合介面) 是晶片之間用來傳遞數位聲音訊號的介面。
簡單的接線方式衹會用到三或五個腳位，常常整合於 M.2 介面之中，需要再接上 *DAC*(數位類比轉換器) 才能做為音訊輸出。

DAC 的輸入腳位通常稱為 AIN(analog input)，輸出腳位則是 Vout(analog output)。 

==== 主機接頭
與 DAC 接腳的層級互相對應，外部的直接輸入介面稱為 *Line-in* ，純粹接出而沒有額外功率放大的外部介面稱為 *Line-out* 。
由於功率較小的嘜筒可能無法驅動 Line-in，通常都會設置成為調整過的 *Mic-in* ，而同樣經過放大以適合耳機的介面則稱為 *Phone-out* 或 *Speaker-out* 。
加在音訊晶片之外的電路，也有可能因為要節約成本，而直接整合於晶片之中，此時從 Vout 接出來的介面已經是 Phone-out，就不需要再多加放大給耳機的線路了。

如果喇叭或嘜筒是內建的型式，就衹會在主機板上留有插槽，而不會有對外的接頭。

因此 Mic-in/Phone-out 或 Line-in/Line-out 兩組介面，其中的電路實作（途徑、阻抗、功率）並不相同，而前者的外部接頭多為插孔(jack) 型式，後者則可能為針腳型式。
5.1 聲道指的是 5 個全音域喇叭加上一個重低音喇叭，由不同的接頭輸出至不同的喇叭。
立體聲則是 2.0 聲道，但是實際上 2.1 聲道才能形成真正的立體聲音。 
有些型式的多極接頭同時連接了 DAC 的多個接腳，必須注意搭配設備端的接頭型式，才能發揮完整的功能。

音訊接頭的顏色是由**個人電腦設計規範**（俗稱 PC97/PC2001）所定義。
接頭形式如果是輸入輸出合併的**複合插孔**(combo jack)，即在立體聲之外加上了嘜筒的功能，而插孔外殼圖示應改為附嘜筒的耳機。

==== 設備接頭
與複合插孔對應的 TRRS 插頭規格又可分為兩種（主機板上的插孔電路可能設計成兩種規格都相容）：

[square]
* CTIA: 由尖端往後為 [左聲道][右聲道][接地][嘜筒]
* OMTP: 由尖端往後為 [左聲道][右聲道][嘜筒][接地]

當複合插孔中衹插入耳機，系統可能會以為也有插入嘜筒，而關閉了其他輸入裝置（主機內建或是網路攝影機內附）。
萬一出現了這種狀況，可以嘗試將外部嘜筒的接線，以 `hdajackretask` 命令設定為斷線（軟體方式停用）。

至於外部負責音訊輸入輸出的人機整合介面，有許多不同的型式：
從最單純的塞耳式耳機(earphone)、附有包線嘜筒的耳嘜(headphone)，到掛耳式耳機加上突出嘜筒的頭戴耳嘜組(headset)。

==== 驅動框架
Linux 的音訊次系統框架，如同顯示次系統一樣，是以「客戶端－伺服端」的網路模式來驅動。
從早期的 OSS(開放音效系統), ALSA(進階 Linux 音效架構) 演變到目前的 PulseAudio(脈衝音訊), PipeWire(管道線路)，仍舊在持續地加強功能。
每一代的框架都有各自的伺服程式與工具程式，而新一代的框架則會取代舊框架所用的服務行程與應用程式介面。
考慮到操作的相容性，系統通常也會提供舊式框架的虛擬介面，以便能繼續使用舊式的硬體、驅動模組、工具程式與應用軟體。

由於安全的考量，音訊框架伺服程式是在個別使用者環境中才啟動的，甚至有些散佈版還在系統管理者登入時，預設將它停用。
從 `ps aux` 指令所輸出的行程列表，應該可以看到相關的行程名稱，並由此判斷系統所使用的主導音訊框架：
例如 `pulseaudio` 明顯來自 PulseAudio，而 `pipewire-pulse` 則是代表 PipeWire 框架。

==== 輸出輸入次裝置
每個音訊裝置之下，可能包含零到多個輸入或輸出次裝置，是由驅動框架所負責控制。

==== X 視窗系統
支援音訊的外部螢幕（HDMI/DP），其音訊組態會隨著 EDID 資料回傳給系統，並會影響到 X 視窗系統的顯示模組行為，而正常情況下預設為啟用：
====
root# *xrandr --output _HDMI-A-0_ --set audio on*
====
使用 DP 螢幕的**多重串流傳輸**(MST) 功能時，有可能會預設關閉音訊功能，此時也需要手動開啟。
在其他的異常組態下，例如當螢幕的規格支援但實際上並沒有音訊介面時，可能需要關閉音訊功能以免產生誤判：
====
root# *xrandr --output _DP1_ --set audio off*
====
或是強制指定介面的型式，以解決因為使用了轉接線而造成的混淆：
====
root# *xrandr --output _HDMI1_ --set audio force-dvi*
====

=== 音訊工具程式

==== 組態
ALSA 音訊驅動框架的原始設定檔位於 `/usr/share/alsa/alsa.conf` ，初始化各裝置的設定檔則在 `/usr/share/alsa/init/` 目錄中。
如果系統想變更音訊驅動服務的組態，則要增添項目到 `/etc/asound.conf` 檔案。
例如想要動態設定預設音效卡號及裝置編號（萬一桌面環境沒有做到的話），就可以建立一個符合 UDEV 的規則檔：

./etc/udev/rules.d/90-usb-soundcard.rules
....
KERNEL=="pcmC[D0-9cp]*", ACTION=="add", PROGRAM="/bin/sh -c 'K=%k; K=$${K#pcmC};
  K=$${K%%D*}; echo defaults.ctl.card $$K > /etc/asound.conf;
  echo defaults.pcm.card $$K >>/etc/asound.conf'"
KERNEL=="pcmC[D0-9cp]*", ACTION=="remove", PROGRAM="/bin/sh -c 'echo defaults.ctl.card 0 > /etc/asound.conf;
  echo defaults.pcm.card 0 >> /etc/asound.conf; echo defaults.pcm.device 0 >> /etc/asound.conf'"
....

另外與之配合的 UCM(用例管理器) 格式的組態檔，存在於 `/usr/share/alsa/ucm*/*` 各目錄中，
而較新版的散佈版將其分出為套件 `alsa-ucm` 或 `alsa-ucm-conf` ，較多用於低階或內嵌於 CPU 的音效晶片。

PulseAudio 音訊驅動框架的設定檔位於 `/etc/pulse/` 目錄內，其中的 `client.conf` 是客戶端軟體的設定。
如果有修改的需求，就刪去列首的符號以取消備註後再變更內容：

./etc/pulse/client.conf (部分)
....
; default-sample-format = s16le 
; default-sample-rate = 48000
; default-sample-channels = 2
; default-channel-map = front-left,front-right
....

服務程式啟動時的設定檔則是 `/etc/pulse/default.pa` ，但衹用於以個別使用者模式所啟動的服務。
例如調整 `module-udev-detect` 模組，以減少初始播放時聲音的跳動；
預設載入 `module-switch-on-port-available` 模組，以配合插拔耳機時應有的切換輸出動作；
或是安裝了套件 `webrtc-audio-processing` 之後，就可以預設載入減少背景回聲的模組：

./etc/pulse/default.pa (部分)
....
load-module module-udev-detect tsched=0
#
load-module module-switch-on-port-available
#
load-module module-echo-cancel source_name=echosource aec_method=webrtc
set-default-source echosource
....

當 PulseAudio 做為主導的音訊框架時，與 ALSA 相容部分的設定可能要參考 `/usr/share/pulseaudio/alsa-mixer/` 目錄中的內容。

==== 偵測
目前系統所支援的音訊框架版本，可以利用各框架提供的工具程式來獲取：
====
user$ *alsactl --version* +
alsactl version 1.2.11 +
user$ *pactl --version* +
pactl 16.1 +
以 libpulse 16.1.0 編譯 +
以 libpulse 16.1.0 連結 +
user$ *pipewire --version* +
pipewire +
Compiled with libpipewire 1.0.3 +
Linked with libpipewire 1.0.3
====

ALSA 驅動框架的虛擬資訊目錄位於 `/proc/asound/` ，例如其中的 `cards` 檔案就列出了系統所含的音效卡（音效晶片）。
`arecord` 與 `aplay` 是 ALSA 驅動框架的工具程式，分別提供錄音與放音功能，加上選項 `-l` 則會列出（實體/邏輯）的錄音或放音裝置。
====
user$ *arecord -l* +
**** List of CAPTURE Hardware Devices **** +
card 0: PCH [HDA Intel PCH], device 0: ALC888-VD Analog [ALC888-VD Analog] +
  Subdevices: 0/1 +
  Subdevice #0: subdevice #0 +
card 1: Camera [Integrated Camera], device 0: USB Audio [USB Audio] +
  Subdevices: 0/1 +
  Subdevice #0: subdevice #0 +
user$ *aplay -l* +
**** List of PLAYBACK Hardware Devices **** +
card 0: PCH [HDA Intel PCH], device 0: ALC888-VD Analog [ALC888-VD Analog] +
  Subdevices: 0/1 +
  Subdevice #0: subdevice #0 +
card 2: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0] +
  Subdevices: 0/1 +
  Subdevice #0: subdevice #0 +
card 2: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1] +
  Subdevices: 1/1 +
  Subdevice #0: subdevice #0 +
card 2: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2] +
  Subdevices: 1/1 +
  Subdevice #0: subdevice #0
====

`pactl` 是 PulseAudio 驅動框架的主要管理工具，加上引數 `info` 會得到音訊框架的基本資訊：
====
user$ *pactl info* +
伺服器字串：/run/user/1000/pulse/native +
函式庫協定版本：35 +
伺服器協定版本：35 +
是否為本地端：是 +
客戶端索引：76 +
並排大小：65472 +
使用者名稱：user +
主機名稱：localhost.localdomain +
伺服器名稱：PulseAudio (on PipeWire 1.3.82) +
伺服器版本：15.0.0 +
預設樣本規格：float32le 2ch 48000Hz +
預設聲道對應表：front-left,front-right +
預設輸出槽點：alsa_output.pci-0000_00_1f.3.analog-stereo +
預設輸入來源：alsa_input.pci-0000_00_1f.3.analog-stereo +
訊餅：9985:3cc1
====
引數 `list` 則可列出音訊次系統的詳細資訊，或是附加第二引數來限定組成的類型，例如代表輸入來源的 `sources` 或是代表輸出槽點的 `sinks` 。
其中輸入來源或輸出槽點的編號，就是做為設定時指定類型的命令引數。


==== 設定
桌面環境附屬設定工具中的音訊裝置部分，通常是做為驅動框架工具程式的前端介面，但是很多細節的設定仍然需要工具程式才能達成。

由於歷經了多種驅動框架的更替，系統為了相容性而留下許多類似功能的工具程式，從命令名稱的前幾個字母就可以猜到它們的來源。
同樣的設定常常可以經由不同的指令達成，但是各自引數中的編號、名稱、選項命令與選項值格式並不一定會相同。

針對音訊裝置有一些常用的傳統工具，例如全螢幕文字介面的 `alsamixer` ，可以調整放音裝置與錄音裝置的個別音量以及總音量。
音訊裝置的設定中有所謂的**推進**(boost)/**過放**(overamplification) 選項，可以用來將裝置的音量放大為超過建議的安全值。
萬一推進選項造成了音訊裝置的**反饋**(feedback) 效果，則有另一項**自動靜音**(auto-mute) 功能可以用來自動過濾尖銳聲音。

相對應的命令列介面指令是 `amixer` ，同樣由 `alsa-utils` 套件所提供。
例如設定預設的輸出槽點可用：
====
root# *amixer cset numid=3 0* #auto +
root# *amixer cset numid=3 1* #headphones +
root# *amixer cset numid=3 2* #hdmi
====

當 `amixer` 命令要指定裝置時，主要是利用 `-c` 選項加上音效卡（音訊晶片）的編號。
以打開裝置的靜音功能（停用裝置）來說，相關的指令範例如下：
====
root# *amixer set Master mute* +
root# *amixer -c _0_ sset Speaker mute* +
root# *amixer set Capture nocap* +
root# *amixer -c _0_ sset Mic nocap*
====
使用者應該參考指令 `amixer scontents` 輸出的名稱與內容，依照需求選擇適合的指令。
如果要取消裝置的靜音功能（啟用裝置），必須將上述指令中的 `mute` 改為 `unmute` 、 `nocap` 改為 `cap` ；
而要設定裝置的音量時，直接將該參數替換為 0%~100% 的百分比值即可。
另外，停用**自動靜音模式**(auto-mute mode) 也可能對於減少噪音有點幫助：
====
root# *amixer -c _0_ sset "Auto-Mute Mode" Disabled*
====
指令 `alsactl store` 會將目前音訊裝置的組態，儲存於 `/var/lib/alsa/asound.state` ，以便下次啟動系統時能夠載入而回復設定。

PulseAudio 音訊驅動框架的文字介面工具程式，包含於 `pulseaudio-utils` 套件。
服務設定檔 `/etc/pulse/*.pa` 中的指令，也都可以做為 `pactl` 命令的引數以進行動態設定。
例如想要手動停用自動選取輸出裝置的模組：
====
root# *pactl unload-module module-switch-on-connect* +
root# *pactl unload-module module-device-manager*
====

`pactl` 命令選項中的部分字串 `source` 表示輸入來源，要改為指稱輸出槽點時則以 `sink` 替代。
後面接續的是類型代號，接受由 PulseAudio 服務依輸入輸出分開的索引編號，或是來源或槽點的符號名稱。
例如動態改變預設的輸入來源：
====
root# *pactl set-source-port _3_ analog-input-mic* +
root# *pactl set-default-source _3_*
====
或是與輸入來源音量相關的設定：
====
root# *pactl set-source-mute _53_ 1* #mute +
root# *pactl set-source-mute _53_ 0* #unmute +
root# *pactl set-source-volume _53_ 50%*
====

套件 `pavucontrol` 包含了同名的圖形介面設定程式，適合進行一般的項目操作。

==== 測試
單純測試喇叭功能可以用 `speaker-test` 命令：
====
user$ *speaker-test --device hw:CARD=Generic_1,DEV=0 --channels 2 --rate 48000*
====
或是由 `alsa-utils-alsabat` 套件提供的 `alsabat` 命令。
其中的裝置名稱的寫法可以參考 `aplay -L` 指令的輸出，或是簡化為形似 `hw:0` 的模式，做為命令 `aplay` 與 `arecord` 等命令的 `-D` 指定選項值。

同樣為了操作相容性的原因，系統也會提供對應的 `parecord` 與 `paplay` 命令，功能類似但是命令引數略有不同。

