== 開機韌體
此處所稱的開機韌體，一般稱呼為 *BIOS*(基本輸入輸出系統)。
這是由於長期以來主流的 X86/X64 PC 架構中，BIOS 便是開機韌體的標準規格。
但是在非 X86/X64 架構或是近期的 PC 規格中，BIOS 卻是不適用或是逐漸被取代的規格。

=== 硬體開機
由於硬體打開電源後的行為，很大程度取決於它的架構，因此這裡的描述僅以常見的 x86_64(PC) 為主，其他架構可能是由不同的韌體所控制（uboot/redboot）。
而 PC 架構開機韌體的提供者，除了知名的幾家 BIOS 供應商之外，還有開放原始碼的 Libreboot
footnote:[Libreboot project <https://libreboot.org/>]。

==== 自我檢查
電腦主機板在接通電源之後，即會觸發進行硬體 *POST*(上電後自我檢查)。
首先 CPU 會讀取韌體中的設定、載入重要硬體元件的基本驅動程式（主要包括輸入、顯示、儲存裝置），然後檢查各元件是否準備就緒。
最明顯的例子就是：當忘了插入記憶體時，上電後立刻會聽到警示音（通常是蜂鳴器發出的重複長嗶聲）。
當聽到一短嗶聲，代表自我檢查作業正常，如果有外接測試板，則會顯示 00/FF 的結果代碼。
比較狹義的開機流程，則會將這個階段排除於衹限軟體的開機流程之外。

硬體 POST 完成之後，如果偵測到使用者按下了特殊鍵（通常是 kbd:[Esc]、kbd:[Del]、kbd:[F2] 或 kbd:[F12]），
便會進入對應的開機韌體設定畫面或是優先開機裝置選單。

==== 開機模式
傳統上，韌體資料都是儲存於主機板或介面卡上的唯讀記憶晶片，所以能夠執行的指令與驅動程式十分有限。
但是在目前已成為業界標準的 *UEFI*(統一可延伸韌體介面) 開機模式中，部分的韌體程式移到了一般儲存媒體上，
因此 UEFI 韌體程式所在的磁碟分割區，不論是裝置型式或檔案系統都受到限制，不過接續載入的位置卻較以往自由許多。
而原來的開機模式則稱為 *Legacy*(舊式) BIOS，或是直接叫做 BIOS，而做為 UEFI 的一個**相容支援模組**(CSM) 保留下來。
如果還有 *Dual*(雙重) 模式的選項，表示兩種模式都支援，但是會根據另外設定的兩者優先順序。

Legacy BIOS 中的程式碼規範為 16 位元，可以搭配 16 位元以上的 CPU 以及作業系統。
早期 UEFI 仍為 32 位元程式碼，可以搭配 32 位元以上的 CPU 以及作業系統。
目前的 UEFI 則為 64 位元程式碼，衹能搭配 64 位元（或以上）的 CPU 以及作業系統。

UEFI 的定義中，基於相容性而納入了舊式的規範，目標則是全面轉為 Class 3：

[square]
* UEFI Class 0: 完全使用 Legacy BIOS
* UEFI Class 1: 完全使用 UEFI CSM
* UEFI Class 2: 使用 UEFI 但具備 CSM 選項
* UEFI Class 3: 使用不含 CSM 的 UEFI

如果開啟了安全啟動，則相當於將 Class 數字附加 \+ 號。

==== 本地開機
電腦系統硬體開機後是由韌體程式所控制，接著依照可開機裝置的優先順序，逐項嘗試進行軟體開機程序。
所有的本地儲存裝置，都有機會做為開機裝置，而開機韌體的支援，則決定其是否歸屬於可開機裝置。
儲存裝置上的分割區模式與檔案系統相容性，以及開機檔案的完整性，則是能否成功開機的條件。

本地儲存裝置大致可以分為以下幾類：

[square]
* SATA: 包括 SATA SSD、SATA Slim、mSATA、M.2 SATA
* MMC: 包括 SD、eMMC
* NVM: 包括 M.2 NVMe
* USB: 包括 On-Board USB、M.2 USB、USB Disk、USB CD/DVD

==== 網路開機
相對於本地儲存裝置，如果系統還支援利用網路儲存裝置來開機，就需要區域網路上有其他機器提供 *PXE*(開機前執行環境) 服務。
PXE 是由 *DHCP*(動態主機設定協定) 服務與 *TFTP*(簡單檔案傳輸協定) 服務共同組成，分別由同名的伺服程式基於同名的網路協定所提供。
開機韌體發出 DHCP 請求後，從 DHCP 服務的回應中取得 IP 位址與組態，以及 TFTP 服務位址和其中對應開機模式的檔案路徑。

PXE 提供從網路下載或掛載檔案，因此各層級的開機程式都必須啟用**網路堆疊**(network stack)，
並且還要載入網路卡驅動程式與網路檔案系統的存取程式。
PXE 韌體是由晶片廠商所提供，再由系統廠商包入開機韌體之中，連網部分則使用符合 UNDI 規格的網卡介面程式。

老舊的機型通常衹支援 Legacy BIOS 搭配 IPv4、TFTP 的組合，UEFI 模式由於在開機韌體中提供了更多可用的程式空間，
因此才可能額外支援 IPv6，以及利用 HTTP 替代 TFTP 的傳輸協定。一般會出現在設定畫面的選項包括（括號內表示常被省略的部分）：

[square]
* Legacy (IPv4)(TFTP)
* UEFI IPv4 (TFTP)
* UEFI IPv6 (TFTP)
* UEFI IPv4 HTTP
* UEFI IPv6 HTTP

或是再加上依次嘗試的組合選項：

[square]
* Legacy/UEFI (IPv4)(TFTP)
* UEFI IPv4/IPv6 (TFTP)
* UEFI IPv4/IPv6 HTTP

=== 開機韌體設定
安裝測試用的作業系統前，應該先進入開機韌體設定畫面。
通常是在開機嗶聲之後，按下 kbd:[Del]、kbd:[Esc] 或 kbd:[F2] 之一。
選取「重新載入預設值」後儲存再重新開機，以免受到之前進行其他相容性測試的影響。
此項動作是藉由抹除 CMOS 中的使用者設定值，而回復由開機韌體所預設的各項初始值。

晶片過熱可能會導致離開 BIOS 設定畫面後直接關機而不重啟。

==== 開機相關
裝置的開機優先順序是開機韌體設定中的項目，衹有已啟用的裝置才會成為選項。
系統中如果包括多個可開機裝置，就要依靠各裝置的優先順序進行開機嘗試。
當優先的裝置無法開機時，就會依序嘗試下一個裝置。

開機韌體內部的開機選單，與開機優先順序是相關但不同的設定。
通常在安裝作業系統的最後階段，會執行 `efibootmgr` 命令將自己加入韌體開機選單。
有可能機器是設為本地裝置優先於網路裝置，但安裝前本地裝置上沒有系統，因此使用網路裝置開機；
但安裝後偵測到本地裝置上已有可開機系統，因此自動將其調整為預設開機項目。

**安全啟動**(secure boot) 是 UEFI 開機模式所引入的規範，依靠限制使用者安裝開機軟體的自由，來達到保持既有系統的安全。
設定後包括開機載入程式、內核以及呼叫的驅動程式，都需要事先具備適當的**數位簽章**(digital signature)，才能被允許執行。
由於安全啟動是附屬於 UEFI 開機模式的功能，因此與 Legacy BIOS 開機模式之間是互斥的設定。
雖然目前大多數的 Linux 安裝軟體都已支援此項要求，但是操作過程中碰到問題時，仍是以關閉安全啟動為優先考慮的選項。

==== 隱藏項目
設定畫面中的項目，其實衹佔全部開機韌體可設定項目的一部分，許多項目在機型開發時期就被決定要隱藏起來。
有些設定畫面會先對不同類型的裝置做區分，然後在下一層中設定個別裝置的屬性。
有些項目會要求使用者先設定好密碼，甚至要按下隱藏的組合鍵之後，才能夠修改預設值。




