== 系統韌體
**系統韌體**(system firmware) 除了在開機時負責初始化硬體、引導作業系統之外，也會於開機後提供系統軟體與硬體之間的溝通介面與中斷設定。
傳統上以 *BIOS*(基本輸入輸出系統) 來稱呼系統韌體，這是由於長期以來個人電腦主流的 X86 架構中，BIOS 便是系統韌體的工業標準，
但是在非 X86 架構或是近期的 X64 規格中，BIOS 卻是不再適用而將逐漸被取代。

=== 硬體開機
由於硬體打開電源後的行為，很大程度取決於它的架構，因此這裡的描述僅以常見的 64 位元個人電腦為主，其他架構可能是由不同的韌體所控制（uboot/redboot）。
而系統韌體的提供者，除了知名的幾家供應商之外，還有開放原始碼的 Libreboot
footnote:[Libreboot project <https://libreboot.org/>]（源自 coreboot）。
但是較新的 Intel 與 AMD CPU 都在晶片上內嵌額外的小型微處理器，做為更低階的控制單元，
衹有簽署認證過的系統韌體才能執行，因此並不容易直接使用此類小眾的開放原始碼韌體。

==== 自我檢查
主機板在接通電源之後，CPU 會執行系統韌體晶片記憶體中的程式，並且觸發硬體的 *POST*(上電自檢) 動作。
首先 CPU 會讀取韌體中的設定、載入重要硬體元件的基本驅動程式（主要包括輸入、顯示、儲存裝置），然後檢查各元件是否準備就緒。
最明顯的例子就是：當忘了插入記憶體時，上電後立刻會聽到警示音（通常是蜂鳴器發出的重複長嗶聲）。
若是聽到一短嗶聲，代表自我檢查作業正常，如果有外接測試板，則會顯示 00/FF 的結果代碼。
較為狹義的開機流程，則會將這個階段排除於僅限軟體的開機流程之外。

硬體 POST 階段完成之後，如果偵測到使用者按下了特殊鍵（通常是 kbd:[Esc]、kbd:[Del]、kbd:[F2] 或 kbd:[F12]），
便會進入對應的系統韌體設定畫面或是優先開機裝置選單。

==== 開機模式
傳統的韌體資料都是儲存於主機板或介面卡上的唯讀記憶晶片，所以能夠執行的指令與驅動程式十分有限。
但是在目前已成為業界標準的 *UEFI*(統一可延伸韌體介面) 開機模式中，部分的韌體程式移到了一般儲存媒體上。
雖然因此 UEFI 韌體程式所在的磁碟分割區，不論是裝置型式或檔案系統都受到較多限制，但是接續載入的位置卻較以往自由許多。
如果還有 *Dual*(雙重) 模式的選項，表示兩種模式都支援。而原來的開機模式
便稱為 Legacy(舊式) BIOS，或是直接稱作 BIOS，並做為 UEFI 的一個 *CSM*(相容支援模組) 保留下來，但是會依設定來決定兩者的優先順序。

BIOS 中的程式碼規範為 16 位元，可以搭配 16 位元以上的 CPU 以及作業系統。
早期 UEFI 仍為 32 位元程式碼，可以搭配 32 位元以上的 CPU 以及作業系統。
目前的 UEFI 則為 64 位元程式碼，衹能搭配 64 位元（或以上）的 CPU 以及作業系統。
UEFI 的定義中，基於相容性而納入了舊式的規範，目標則是全面轉為 Class 3：

[square]
* UEFI Class 0: 完全使用 BIOS
* UEFI Class 1: 完全使用 UEFI CSM
* UEFI Class 2: 使用 UEFI 但具備 CSM 選項
* UEFI Class 3: 使用不含 CSM 的 UEFI

當系統開啟了安全啟動，就以 Class 後方的數字再附加 (+) 號來表示。
想要判定目前的系統啟動自 BIOS 或是 UEFI 時，可依據 `/sys/firmware/efi` 目錄是否存在，如果有就代表系統是以 UEFI 模式開機。

==== 本地開機
電腦硬體開機後，系統是由韌體程式所控制，接著依照可開機裝置的優先順序，逐項嘗試以進行軟體開機程序。
所有的本地儲存裝置，都有機會做為開機裝置，而系統韌體的支援，則決定其是否歸屬於可開機裝置。
儲存裝置上的分割區模式與檔案系統相容性，以及開機檔案的完整性，則是能否成功開機的條件。

本地儲存裝置大致可以分為以下幾類：

[square]
* SATA: 包括 SATA SSD、SATA Slim、mSATA、M.2 SATA
* MMC: 包括 SD、eMMC
* NVM: 包括 M.2 NVMe
* USB: 包括 On-Board USB、M.2 USB、USB Stick/Disk、USB CD/DVD

==== 網路開機
相對於本地儲存裝置，如果系統還支援利用網路儲存裝置來開機，就需要區域網路上有其他機器提供 *PXE*(開機前執行環境) 功能。
PXE 是由 *DHCP*(動態主機設定協定) 服務與 *TFTP*(簡易檔案傳輸協定) 服務共同組成，分別由同名的伺服程式基於同名的網路協定所提供。
建置 PXE 伺服器的方法，請參考前一章〈開機前執行環境〉的說明。

系統韌體發出 DHCP 請求後，從 DHCP 服務的回應中取得網路位址與組態，以及 TFTP 伺服器位址和其中對應開機模式的檔案路徑。
因為需要從網路下載或掛載檔案，因此各層級的開機程式都必須啟用**網路堆疊**(network stack)，還要載入網路卡驅動程式與網路檔案系統的存取程式。
PXE 韌體是由晶片廠商所提供，再由系統廠商包入系統韌體之中，連網部分則使用符合 *UNDI*(通用網路驅動介面) 規範的程式。

老舊的機型通常衹支援 BIOS 搭配 IPv4、TFTP 的組合，UEFI 模式由於在系統韌體中提供了更多可用的程式空間，
因此便有可能額外支援 IPv6，以及利用 HTTP 替代 TFTP 的傳輸協定。
一般會出現在設定畫面的選項包括（方括號內表示常被省略顯示的部分）：

[square]
* [Legacy] BIOS [IPv4] [TFTP]
* UEFI IPv4 [TFTP]
* UEFI IPv6 [TFTP]
* UEFI IPv4 HTTP
* UEFI IPv6 HTTP

或是再加上會依序嘗試的組合選項：

[square]
* [Legacy] BIOS/UEFI [IPv4] [TFTP]
* UEFI IPv4/IPv6 [TFTP]
* UEFI IPv4/IPv6 HTTP

=== 韌體設定
安裝測試用的作業系統前，應該先確認系統韌體的組態。
通常是在開機嗶聲之後，按下 kbd:[Esc]、kbd:[Del] 或 kbd:[F2] 之一，就會進入設定畫面。
選取「重新載入預設值」後，儲存再重新開機，以免受到之前做過的其他測試項目影響。
重新載入預設值的動作，其實是藉由抹除現有的使用者設定值，從而回復由系統韌體所預設的各項初始值。

系統韌體是儲存於主機板上的 *NVRAM*(非揮發性記憶體) ，但使用者設定值卻是儲存於需要持續供給電力的區域。
萬一發生韌體設定混亂而無法正常修復的情形，可以考慮取下主機板電池，等待使用者設定值自動消除後再裝回。
口語中會以早期這種晶片的 *CMOS*(互補式金屬氧化物半導體) 製程，或是所屬的 *EEPROM*(電子抹除式可複寫唯讀記憶體)、**Flash** 類型…等等，做為此一裝置的代稱。由於主機板製造商、系統韌體供應
商的實作各不相同，常常會將其集成到別的晶片組中，再加上目前處於轉換開機模式的過渡期，因此指涉的名稱並不一致。

GRUB 開機管理選單支援 `fwsetup` 指令，用來提供進入系統韌體設定的選項。
在作業系統中則有指令可以強制立即重啟系統，再直接進入系統韌體設定畫面：
====
user$ *systemctl reboot --firmware-setup*
====

晶片過熱可能會導致離開系統韌體設定畫面後，直接關機而不重新啟動。
如果韌體程式回應開機管理程式或內核的時間太長，也有可能產生偶發的逾時錯誤而導致開機失敗。

==== 安全啟動
**安全啟動**(secure boot) 是 UEFI 開機模式所引入的規範，依靠限制使用者安裝開機軟體的自由，來達到保持既有系統的安全。
設定後包括開機載入程式、內核以及呼叫的驅動程式，都需要事先具備適當的**數位簽章**(digital signature)，才能被允許執行。
由於安全啟動是附屬於 UEFI 開機模式的功能，因此與 BIOS 開機模式之間是互斥的設定。
雖然目前多數的 Linux 散佈版安裝軟體都已支援此項要求，但是操作過程中碰到問題時，仍是以關閉安全啟動為優先考慮的選項。
在系統韌體設定中關閉安全啟動時，最好也將相伴的「抹除現有安全啟動內容」項目開啟，以免受到留存資料的影響。
切換安全啟動之前，記得先拔除所有非必要的周邊裝置，並且不要更動系統的儲存裝置組態，否則此項操作有可能會被系統韌體忽略。

如果想要知道運行中系統的安全啟動狀態，可以輸入指令：
====
user$ *mokutil --sb-state* +
SecureBoot enabled +
user$ *mokutil --list-sbat-revocations* +
sbat,1,2023012900 +
shim,2 +
grub,3 +
grub.debian,4
====
或是在 `dmesg` 命令的輸出中搜尋相關的字串。
至於程式內含的數位簽章，則可在安裝 `sbsigntools` 套件後，利用指令 `sbverify --list _已簽章檔案_` 來列出記錄，
或是在必要時以 `sbattach` 命令來**附掛**(attach)╱**卸離**(detach) 數位簽章。

==== 開機順序
裝置的開機優先順序是系統韌體設定中的項目，衹有已啟用的裝置才會成為選項。
系統中如果包含多個可開機裝置，就會依據各裝置的優先順序進行開機嘗試。

萬一優先的裝置無法開機時，則將依序嘗試下一個裝置。
例如：機器目前設定為本地裝置優先於網路裝置，但安裝作業系統前本地裝置上沒有任何系統，因此使用網路裝置開機；
但安裝後偵測到本地裝置上已有可開機系統，因此自動將其調整為預設開機項目。

==== 開機選單
由於 UEFI 系統韌體有較多的程式與資料儲存空間，因此能夠自行提供獨立開機選單的功能，但是與硬體開機後的開機管理程式所提供的開機選單相較，彼此並不相同且功能獨立。
UEFI 支援的開機優先順序與選單，與 BIOS 所支援的相似但有差異：UEFI 版本是以開機系統做為侯選項目，而 BIOS 版本多以開機裝置做為侯選項目。

儲存於 NVRAM 中的 UEFI 開機選單，是由系統韌體自動偵測後寫入。
至於偵測儲存裝置時，每個開機分割區是否支援多個開機系統，則會依各供應商的實作而有不同。
在使用者空間中，可以藉由 `efibootmgr` 命令建立、刪除、排列或指定開機順序：
====
root# *efibootmgr -c -d _/dev/sda_ -p _1_ -l _/EFI/散佈版/shimx64.efi_* +
root# *efibootmgr -B -b _0002_* +
root# *efibootmgr -o _0000,0001_* +
root# *efibootmgr -n _0003_*
====
作業系統在安裝的最後階段，也可能會執行該命令將自己加入韌體開機選單。

==== UEFI Shell
有些 UEFI 系統韌體會啟用內建的 UEFI Shell，做為韌體開機選單的項目之一。
除了內建於開機韌體，UEFI Shell 也能以外部檔案的形式被載入執行，使用體驗就如同簡化過的新版 DOS 命令環境。
UEFI 韌體程式可以視為一個微型的作業系統，而 UEFI Shell 就是它的命令殼。

UEFI 規範的開放原始碼實作稱為 TianoCore
footnote:[UEFI 規範的開放原始碼實作 <https://github.com/tianocore>]，提供社群版本的開發環境，
各個系統韌體供應商則會參考這個規範，推出專屬但功能略有不同的版本。
即便簡單的 UEFI 命令殼環境測試，仍需配合適當的命令或命令稿，可能要搜尋看看是否有專為 UEFI 平臺編寫的測試程式。

==== 使用者讀取
系統韌體實際上是由數個模塊共同組成，有些會以 sysfs 檔案系統的形式，在 `/sys/firmware/` 目錄中曝露出來，例如 `acpi/`, `dmi/`, `memmap/` 等等。
設定畫面中的項目，其實衹佔全部系統韌體可設定項目的一部分，許多項目在機型開發時期就被決定要隱藏起來。
有些設定畫面會對不同類型的裝置做區分，必須先啟用裝置類型，才會在下一層中出現個別裝置的屬性。
另外有些項目則會要求使用者先設定好密碼，甚至要按下隱藏的組合鍵之後，才能夠修改預設值。
使用系統韌體供應商提供的工具，才能夠讀取到所有已被匯出為變數的設定值。

*SMBIOS*(韌體系統管理) 並非是指一段韌體區塊，而是定義存取系統韌體資料所用的結構與方法。
其舊稱為 DMIBIOS，因為它與 DMI(桌面管理介面) 有緊密的互動關係。
依據 SMBIOS 規範所獲取的資料表，是硬體廠商提供硬體狀態的標準應用程式讀取介面。
系統傳統上提供了 `dmidecode` 命令，部分資訊取自 `/sys/class/dmi/id/` 目錄下的檔案內容，
並藉由 SMBIOS 讀取目前硬體的狀態，因而 `dmidecode` 無法在沒有 SMBIOS 的硬體架構中使用：
====
root# dmidecode -t bios
====

=== 更新韌體
主機板上的系統韌體，通常是燒錄在一顆具有八隻較粗腳位的晶片。
更新韌體的動作，當然會受到安全啟動的設定所限制。
刷新系統韌體之後，會有一次的重置介入需求，以便與 CPU 產生連結。如果更新了規格不符的韌體檔案，導致發生失誤無法開機，
就需要拆下晶片或以專用夾具轉接在燒錄器（一般是 USB 裝置）上，然後以附屬的軟體配合韌體檔案燒錄。

適用於 BIOS 開機模式的韌體映像，以 `file` 命令檢視時，會被視為普通的 data(資料) 檔案；
而支援 UEFI 開機模式的韌體映像，則被視為如同 `.efi` 檔案一樣的 MS-DOS/PE32/PE32+ executable(可執行) 類型。

==== 供應商工具
系統韌體供應商所提供的相關整合工具，會依照運行平臺而有不同版本。
這些整合工具常常是開放原始碼與封閉原始碼的混合軟體，個別的使用授權以及再散佈的規定也必須要特別注意。

適用於 UEFI 命令殼的工具程式，是以 `*.efi` 的可執行檔案形式提供，通常直接搭配韌體映像檔案執行即可。 而在使用者空間中執行的工具，由於需要進行讀寫韌體的內核空
間動作，因此可能會包括內核模組以便調用。
由於內核模組需要配合實際使用的內核版本，所以必須提供原始碼才能編譯使用，
否則事先編譯好的模組，衹能適用於編譯時所用的特定內核版本，有些模組甚至還要求與內核使用相同版本的編譯器。
應用程式通常是文字介面，以達到最大的執行相容性，但有些廠商也會提供圖形介面的相近功能軟體。

各家供應商提供的工具，雖然相同功能的軟體名稱並不一致，但是通常包括以下幾類：

[square]
* 韌體更新程式：以韌體映像檔案做為命令參數進行更新，需要注意是否有控制更新模組範圍的選項。刷新後首次進入韌體設定畫面時，最好先載入預設值並儲存後再重新開機。
* 韌體設定程式：利用檔案參數或是字串選項來讀取或寫入設定值。修改的是儲存於 CMOS 中的外加設定值，而在 *MMIO*(記憶體對映輸入輸出) 模式下的速度會比較快。
* 特殊編輯程式：用來編輯韌體設定的預設值、SMBIOS 表格變數、開機畫面標章…等資料。匯出前後的硬體組態必須維持相同（沒有熱插拔異動），否則匯入操作可能會失敗。

==== LVFS 工具
由於每個韌體供應商的工具各不相同且不相容，造成 Linux 使用者更新時的不便，
因此出現了 *LVFS*(Linux 供應商韌體服務) 組織，做為統一上傳與下載韌體的管理中心，且不限於系統韌體，還包括其他周邊硬體所含的裝置韌體。
在 Linux 作業系統中，是由 `fwupd`(firmware update) 服務軟體做為此功能的客戶端實作。

依據 LVFS 網站
footnote:[Linux 供應商韌體服務組織 <https://fwupd.org/>] 
的說明，使用 LVFS 的條件如下：

[square]
* 系統韌體本身支援 UEFI 的**膠囊式更新**(capsule update)。
* 硬體供應商於官網註冊，並上傳所屬機型的韌體封存檔案。
* 作業系統中安裝 `fwupd` 套件。
* 操作前關閉安全啟動，操作後載入一次預設值。

`fwupd` 套件提供了一些指令，用來列出目前系統中的硬體裝置，可以藉此了解各裝置的資訊，以及是否受到 LVFS 計畫的支援，
例如： `fwupdtool hwids` 或是 `fwupdmgr get-devices` 。
如果是韌體開發者要進行本機測試，需要先開啟一項信任設定，然後重新啟動 `fwupd` 服務：
====
root# *cd /etc/fwupd* +
root# *sed -i 's|OnlyTrusted=.++*++|OnlyTrusted=false|' fwupd.conf* +
root# *systemctl restart fwupd*
====

韌體封存檔案需要用 `.cab`(cabinet) 的格式打包，而在 Linux 作業系統中可以依照下面的步驟製作：

. 安裝需要的 `fwupd`, `gcab` 套件。
. 準備好韌體映像檔案 `_韌體映像_.bin` 。
. 編輯需要的 XML 組態檔。
. 製作封存檔案： +
====
user$ *gcab -czv _韌體映像_.cab _韌體映像_.metainfo.xml _韌體映像_.bin*
====
上述的 `gcab` 打包命令還能利用 `-x` 選項，來解開已經製作好的封存檔案。
XML 格式的組態檔內容，則可以參考 LVFS 提供下載的既有範例
footnote:[穩定版韌體列表 <https://cdn.fwupd.org/downloads/firmware.xml.gz>]。
其中需要注意的是不同映像版本格式間的轉換，例如號碼 0xXXYYZZZZ 改寫成 triplet(三連數) 則為 0xXX.0xYY.0xZZZZ，或是一律以十進位表示。
裝置供應商將韌體封存檔案上傳至 LVFS 官網，就可以讓具備特定裝置的機器進行網路更新（實際上需要通過好幾道確認程序）。

如果能事先取得製作完成的封存檔案，建議先在本機測試安裝一下：
====
root# *fwupdmgr install _韌體映像_.cab*
====
有些安全保護比較嚴格的系統，還需要先重新掛載留存 EFI 所用韌體檔的目錄：
====
root# *mount -o remount,rw /sys/firmware/efi/efivars*
====
至於特別為此創建的假擬檔案系統 efivarfs ，在此命令中可被省略而不須指明。

`fwupdmgr` 命令也接受附加 `--allow-reinstall` 或 `--allow-older` 選項，用來安裝相同或是較舊版本的韌體映像。
確認沒有問題之後，就可以在其他尚未更新的機器進行網路更新：
====
root# *fwupdmgr refresh --force* +
root# *fwupdmgr get-updates* +
root# *fwupdmgr update*
====

正常情況下，執行完安裝指令後的第一次重新開機前，會將韌體映像檔案拷貝到 EFI 系統分割區，並且暫時調整 UEFI 開機順序，將韌體安裝程式列為優先。
接著於第二次重新開機後，出現韌體安裝畫面，這是因為實際執行讀取或寫入作業時，仍然會呼叫韌體映像中內建的供應商工具。
第三次重新開機後，才會進行正常的開機程序，但是由於安裝時會自動載入韌體預設值，因此可能還需要手動調整一下自訂值。

==== 其他工具
`flashrom` 是通用的讀寫韌體工具，除了系統韌體之外，也支援存取許多不同的硬體裝置。
使用者可以利用引數指定目標晶片的名稱與裝置記憶體位置，並以檔案的形式讀出或寫入資料。
像是前述的 `fwupd` 服務如果沒有支援某項裝置，還可以載入通用的 `libflashrom` 函式庫模組試試是否可行。

有一些其他散佈版收錄的套件，或是由第三方所提供的工具程式可以參考：

[square]
* `efivar`: 存取位於假擬目錄 `/sys/firmware/efi/efivars/` 中的 UEFI 匯出變數值。
* `me_cleaner`: 衹能清除 UEFI 韌體中部分的 ME 組件。完全取代 UEFI ROM 的映像檔仍在開發中，而且需要額外的電路藉由 SPI 接腳才能燒錄進去。
* `fwts`: 檢查韌體完整性的套裝軟體。用於偵測韌體中可能的錯誤，並嘗試提供修正或變通方法。
* `pi-sct`: 平臺初始化自我驗證測試。依照 UEFI 規範來調整特定平臺上的介面，以及驗證韌體的相容性。
