== 系統韌體
**系統韌體**(system firmware) 除了於開機時負責初始化硬體、引導作業系統之外，也會於開機後提供系統軟體與硬體之間的溝通介面與中斷設定。
傳統上以 *BIOS*(基本輸入輸出系統) 來稱呼系統韌體，這是由於長期以來主流的 X86/X64 PC 架構中，BIOS 便是系統韌體的標準規格，
但是在非 X86/X64 架構或是近期的 PC 規格中，BIOS 卻是不適用或逐漸被取代的規格。

=== 硬體開機
由於硬體打開電源後的行為，很大程度取決於它的架構，因此這裡的描述僅以常見的 x86_64(PC) 為主，其他架構可能是由不同的韌體所控制（uboot/redboot）。
而 PC 架構系統韌體的提供者，除了知名的幾家供應商之外，還有開放原始碼的 Libreboot
footnote:[Libreboot project <https://libreboot.org/>]（源自 coreboot）。
但是較新的 Intel 與 AMD CPU 都在晶片上內嵌另一個小型的微處理器，做為更低階的控制單元，
衹有簽署認證的系統韌體才能執行，因此並不容易直接使用此類的自由韌體。

==== 自我檢查
電腦主機板在接通電源之後，CPU 會執行系統韌體晶片記憶體中的程式，並且觸發硬體的 *POST*(上電後自我檢查) 動作。
首先 CPU 會讀取韌體中的設定、載入重要硬體元件的基本驅動程式（主要包括輸入、顯示、儲存裝置），然後檢查各元件是否準備就緒。
最明顯的例子就是：當忘了插入記憶體時，上電後立刻會聽到警示音（通常是蜂鳴器發出的重複長嗶聲）。
當聽到一短嗶聲，代表自我檢查作業正常，如果有外接測試板，則會顯示 00/FF 的結果代碼。
比較狹義的開機流程，則會將這個階段排除於衹限軟體的開機流程之外。

硬體 POST 完成之後，如果偵測到使用者按下了特殊鍵（通常是 kbd:[Esc]、kbd:[Del]、kbd:[F2] 或 kbd:[F12]），
便會進入對應的系統韌體設定畫面或是優先開機裝置選單。

==== 開機模式
傳統上，韌體資料都是儲存於主機板或介面卡上的唯讀記憶晶片，所以能夠執行的指令與驅動程式十分有限。
但是在目前已成為業界標準的 *UEFI*(統一可延伸韌體介面) 開機模式中，部分的韌體程式移到了一般儲存媒體上，
因此 UEFI 韌體程式所在的磁碟分割區，不論是裝置型式或檔案系統都受到限制，不過接續載入的位置卻較以往自由許多。
而原來的開機模式則稱為舊式(legacy) BIOS，或是直接稱做 BIOS，或做為 UEFI 的一個 *CSM*(相容支援模組) 保留下來。
如果還有 *Dual*(雙重) 模式的選項，表示兩種模式都支援，但是會根據另外設定的兩者優先順序。

BIOS 中的程式碼規範為 16 位元，可以搭配 16 位元以上的 CPU 以及作業系統。
早期 UEFI 仍為 32 位元程式碼，可以搭配 32 位元以上的 CPU 以及作業系統。
目前的 UEFI 則為 64 位元程式碼，衹能搭配 64 位元（或以上）的 CPU 以及作業系統。
UEFI 的定義中，基於相容性而納入了舊式的規範，目標則是全面轉為 Class 3：

[square]
* UEFI Class 0: 完全使用 BIOS
* UEFI Class 1: 完全使用 UEFI CSM
* UEFI Class 2: 使用 UEFI 但具備 CSM 選項
* UEFI Class 3: 使用不含 CSM 的 UEFI

當系統開啟了安全啟動，就以 Class 後方的數字再附加 (+) 號來表示。
想要判定目前的系統啟動自 BIOS 或是 UEFI 時，可依據是否存在 /sys/firmware/efi 目錄，如果存在則代表系統是以 UEFI 模式開機。

==== 本地開機
電腦系統硬體開機後是由韌體程式所控制，接著依照可開機裝置的優先順序，逐項嘗試進行軟體開機程序。
所有的本地儲存裝置，都有機會做為開機裝置，而系統韌體的支援，則決定其是否歸屬於可開機裝置。
儲存裝置上的分割區模式與檔案系統相容性，以及開機檔案的完整性，則是能否成功開機的條件。

本地儲存裝置大致可以分為以下幾類：

[square]
* SATA: 包括 SATA SSD、SATA Slim、mSATA、M.2 SATA
* MMC: 包括 SD、eMMC
* NVM: 包括 M.2 NVMe
* USB: 包括 On-Board USB、M.2 USB、USB Disk、USB CD/DVD

==== 網路開機
相對於本地儲存裝置，如果系統還支援利用網路儲存裝置來開機，就需要區域網路上有其他機器提供 *PXE*(開機前執行環境) 服務。
PXE 是由 *DHCP*(動態主機設定協定) 服務與 *TFTP*(簡單檔案傳輸協定) 服務共同組成，分別由同名的伺服程式基於同名的網路協定所提供。
系統韌體發出 DHCP 請求後，從 DHCP 服務的回應中取得 IP 位址與組態，以及 TFTP 服務位址和其中對應開機模式的檔案路徑。

PXE 提供從網路下載或掛載檔案，因此各層級的開機程式都必須啟用**網路堆疊**(network stack)，
並且還要載入網路卡驅動程式與網路檔案系統的存取程式。
PXE 韌體是由晶片廠商所提供，再由系統廠商包入系統韌體之中，連網部分則使用符合 UNDI 規格的網卡介面程式。

老舊的機型通常衹支援 BIOS 搭配 IPv4、TFTP 的組合，UEFI 模式由於在系統韌體中提供了更多可用的程式空間，
因此才可能額外支援 IPv6，以及利用 HTTP 替代 TFTP 的傳輸協定。一般會出現在設定畫面的選項包括（括號內表示常被省略的部分）：

[square]
* BIOS (IPv4)(TFTP)
* UEFI IPv4 (TFTP)
* UEFI IPv6 (TFTP)
* UEFI IPv4 HTTP
* UEFI IPv6 HTTP

或是再加上依次嘗試的組合選項：

[square]
* BIOS/UEFI (IPv4)(TFTP)
* UEFI IPv4/IPv6 (TFTP)
* UEFI IPv4/IPv6 HTTP

=== 韌體設定
安裝測試用的作業系統前，應該先進入系統韌體設定畫面。
通常是在開機嗶聲之後，按下 kbd:[Del]、kbd:[Esc] 或 kbd:[F2] 之一。
選取「重新載入預設值」後儲存再重新開機，以免受到之前進行其他相容性測試的影響。
重新載入預設值的動作，就是藉由抹除其中所有的使用者設定值，從而回復由系統韌體所預設的各項初始值。
萬一發生韌體設定混亂而無法正常修復的情形，可以考慮取下主機板電池，等待使用者設定值自動消除後再裝回。

系統韌體的使用者設定值，儲存於主機板上的 *NVRAM*(非揮發性記憶體) 晶片。
口語中會以早期這種晶片的 *CMOS*(互補式金屬氧化物半導體) 製程，或是所屬的 *EEPROM*(電子抹除式可複寫唯讀記憶體) 或 *Flash* 類型來代表儲存的位置。
由於主機板製造商、系統韌體供應商的實作各不相同，再加上處於轉換開機模式的過渡期，因此指涉的名稱十分雜亂。

在作業系統中可以利用命令來強制立即重啟系統後，直接進入系統韌體設定畫面：
====
user$ *systemctl reboot --firmware-setup*
====

晶片過熱可能會導致離開系統韌體設定畫面後直接關機而不重啟。
如果韌體程式回應開機管理程式或內核的時間太長，也有可能產生偶發的逾時錯誤而導致開機失敗。

==== 安全啟動
**安全啟動**(secure boot) 是 UEFI 開機模式所引入的規範，依靠限制使用者安裝開機軟體的自由，來達到保持既有系統的安全。
設定後包括開機載入程式、內核以及呼叫的驅動程式，都需要事先具備適當的**數位簽章**(digital signature)，才能被允許執行。
由於安全啟動是附屬於 UEFI 開機模式的功能，因此與 BIOS 開機模式之間是互斥的設定。
雖然目前多數的 Linux 散佈版安裝軟體都已支援此項要求，但是操作過程中碰到問題時，仍是以關閉安全啟動為優先考慮的選項。
在系統韌體設定中關閉安全啟動時，最好也將相伴的「抹除現有安全啟動內容」項目開啟，以免受到留存資料的影響。
關閉安全啟動之前，最好不要更動系統的儲存裝置組態，否則此項操作有可能會被系統韌體忽略。

如果想要知道運行中系統的安全啟動狀態，可以輸入指令：
====
user$ *mokutil --sb-state* +
SecureBoot enabled
====
或是在 `dmesg` 命令的輸出中搜尋相關的字串。
至於程式內含的數位簽章，則可安裝 `sbsigntools` 套件後，利用指令 `sbverify --list _已簽章檔案_` 來列出記錄。

==== 開機順序
裝置的開機優先順序是系統韌體設定中的項目，衹有已啟用的裝置才會成為選項。
系統中如果包括多個可開機裝置，就要依靠各裝置的優先順序進行開機嘗試。

當優先的裝置無法開機時，就會依序嘗試下一個裝置。
例如：機器是設為本地裝置優先於網路裝置，但安裝前本地裝置上沒有系統，因此使用網路裝置開機；
但安裝後偵測到本地裝置上已有可開機系統，因此自動將其調整為預設開機項目。

==== 開機選單
由於 UEFI 系統韌體有較多的程式與儲存空間，因此能夠額外提供開機選單的功能，但是與硬體開機後的開機管理程式所提供的開機選單，彼此並不相同而功能獨立。
UEFI 支援的開機優先順序與開機選單，與 BIOS 所支援的相似但有差異：UEFI 版本是以開機系統做為侯選項目，而 BIOS 版本多以開機裝置做為侯選項目。

儲存於 NVRAM 中的 UEFI 開機選單，可由系統韌體自動偵測後寫入。
至於偵測儲存裝置時，每個開機分割區是否支援多個開機系統，則會依各供應商的實作而有不同。
在使用者空間中，可以藉由 `efibootmgr` 命令建立、刪除或調整開機順序：
====
root# *efibootmgr -c -d _/dev/sda_ -p _1_ -l _/EFI/fedora/shimx64.efi_* +
root# *efibootmgr -B -b _0002_* +
root# *efibootmgr -o _0000,0001_* +
root# *efibootmgr -n _0003_*
====
作業系統在安裝的最後階段，也可能會執行 `efibootmgr` 命令將自己加入韌體開機選單。

==== UEFI Shell
有些 UEFI 系統韌體會啟用內建的 UEFI Shell，做為韌體開機選單的選項之一。
除了內建於開機韌體，UEFI Shell 也能以外部檔案的形式載入執行，使用體驗就如同新版的簡化 DOS 作業系統。
UEFI 韌體程式可以視為一個微型的內核，而 UEFI Shell 就是它的命令殼。
UEFI 規範的開始原始碼實作稱為 TianoCore，提供社群版本的開發環境，
各個系統韌體供應商則會參考這個規範，推出專屬但功能略有不同的版本。
簡單的 UEFI Shell 環境測試，可以利用命令殼命令或命令稿，否則就需要搜尋是否有專為 UEFI 平臺編寫的測試程式。

==== 隱藏項目
設定畫面中的項目，其實衹佔全部系統韌體可設定項目的一部分，許多項目在機型開發時期就被決定要隱藏起來。
有些設定畫面會先對不同類型的裝置做區分，然後在下一層中設定個別裝置的屬性。
有些項目會要求使用者先設定好密碼，甚至要按下隱藏的組合鍵之後，才能夠修改預設值。

==== 使用者讀取
系統韌體實際上是由數個部分共同組成，有些會以 sysfs 檔案系統的形式在 `/sys/firmware/` 目錄中曝露出來，例如 `acpi/`, `dmi/`, `memmap/` 等。
使用系統韌體供應商提供的工具，應該能讀寫到大部分有被匯出為變數的設定值。

*SMBIOS*(韌體系統管理) 並非是指一段韌體區塊，而是定義存取系統韌體資料所用的結構與方法。
其舊稱為 DMIBIOS，因為它與 DMI(桌面管理介面) 有緊密的互動關係。
依據 SMBIOS 規範所獲取的資料表，是硬體廠商提供硬體狀態的標準應用程式讀取介面。
系統傳統上提供了 `dmidecode` 命令，部分資訊來自 `/sys/class/dmi/id/` 目錄下的檔案內容，
藉以經由 SMBIOS 讀取目前硬體的狀態，因而 `dmidecode` 無法在沒有 SMBIOS 的硬體架構中使用：
====
root# dmidecode -t bios
====

=== 更新韌體
系統韌體在主板上，通常是燒錄在一顆具有較粗八隻腳位的晶片。
刷新系統韌體之後，會有一次的重置介入需求，以便與 CPU 產生連結。
如果失誤更新了規格不符的韌體檔案導致無法開機，就需要拆下晶片或以專用夾子轉接在燒錄器上（一般是 USB 裝置），然後以正確的軟體配合韌體檔案燒錄。

更新韌體的動作當然會被安全啟動的設定所限制。
僅用於 BIOS 開機模式的韌體映像，以命令殼中的 `file` 命令檢視時，會被視為普通的 data(資料) 檔案；
而支援 UEFI 開機模式的韌體映像，則被視為如同 .efi 檔案一樣的 MS-DOS executable(可執行) 類型。

==== 供應商工具
系統韌體供應商會提供相關的整合工具，並依照運行平臺而有不同版本。
這些整合工具常常是開放原始碼與封閉原始碼的混合軟體，個別的使用授權以及再散佈的規定也有所差異。

適用於 UEFI 命令殼的程式，是以 `*.efi` 的可執行檔案形式提供，通常直接搭配韌體檔案執行即可。
而在 Linux 使用者空間中執行的工具，由於需要進行讀寫韌體的內核空間動作，因此可能會包括內核模組。
由於內核模組必須配合實際使用的內核版本，因此必須提供原始碼才能編譯使用，
否則事先編譯好的模組，衹能適用於編譯時所用的特定內核版本，甚至有些模組還要求與內核使用相同版本的編譯器。
應用程式通常是文字介面，以達到最大的執行相容性，而有些廠商也會提供圖形介面的相近功能軟體。

各家供應商提供的工具軟體，雖然相同功能的軟體名稱並不一致，但是通常包括以下幾類：

[square]
* 韌體更新程式：以韌體檔案做為命令參數進行更新，還要注意是否有控制更新模組範圍的選項。刷新後首次進入韌體設定畫面時，最好先載入預設值並儲存後重新開機。
* 韌體設定程式：利用檔案參數或是字串選項來讀取或寫入設定值。修改的是儲存於 CMOS 中的外加設定值，在 *MMIO*(記憶體對映輸入輸出) 模式下的速度會比較快。
* 特殊編輯程式：用來編輯韌體設定預設值、SMBIOS 表格變數、開機畫面標章…等資料。匯出後的硬體組態必須維持相同（沒有熱插拔異動），否則匯入操作可能會失敗。

==== LVFS 工具
由於每個韌體供應商的工具各不相同且不相容，造成 Linux 使用者更新時的不便，
因此出現了 *LVFS*(Linux 供應商韌體服務) 組織，做為統一上傳與下載韌體的管理中心，且不限於系統韌體，還包括其他的硬體裝置所含的韌體。
在 Linux 作業系統中，是由 `fwupd` 軟體做為此功能的實作。
WARNING: 支援這個更新機制前，系統韌體最好先具備自我備份、死機還原的功能。

依據 LVFS 官方網站(https://fwupd.org/) 的說明，使用 LVFS 的條件如下：

[square]
* 系統韌體本身支援 UEFI 的**膠囊式更新**(capsule update)。
* 硬體供應商於官網註冊，並上傳所屬機型的韌體封存檔案。
* 作業系統中安裝 `fwupd` 套件。
* 操作前關閉安全啟動，操作後載入一次預設值。

`fwupd` 套件提供了一些指令，用來列出目前系統中的硬體裝置，可以藉此了解各裝置的資訊，以及是否受到 LVFS 計畫的支援，
例如： `fwupdtool hwids` 或是 `fwupdmgr get-devices` 。
如果是韌體開發者要進行本機測試，需要先開啟一項信任設定，然後重新啟動 `fwupd` 服務：
====
root# *cd /etc/fwupd* +
root# *sed -i 's|OnlyTrusted=true|OnlyTrusted=false|' fwupd.conf* +
root# *systemctl restart fwupd*
====

韌體封存檔案需要用 .cab(cabinet) 的格式打包，而在 Linux 作業系統中可以依照下面的步驟製作：

. 安裝需要的 `fwupd`, `gcab` 套件。
. 準備好韌體映像檔案 `_foobar_.bin` 。
. 編輯需要的 XML 組態檔。
. 製作封存檔案： +
====
user$ *gcab -czv _foobar_.cab _foobar_.metainfo.xml _foobar_.bin*
====
上述的 `gcab` 打包命令還可以利用 `-x` 選項來解開已製作的封存檔案。
XML 格式的組態檔內容，可以參考 LVFS 提供下載的既有範例
footnote:[穩定版韌體列表 <https://cdn.fwupd.org/downloads/firmware.xml.gz>]。
其中需要注意的是不同版本格式間的轉換，例如號碼 0xXXYYZZZZ 改寫成 triplet(三連數) 則為 0xXX.0xYY.0xZZZZ，或是一律以十進位表示。
裝置供應商將韌體封存檔案上傳至 LVFS 官網，就可以讓具備特定裝置的機器進行網路更新（實際上還需要通過好幾道確認程序）。

如果能事先取得製作完成的封存檔案，建議先在本機測試安裝一下：
====
root# *fwupdmgr install _foobar_.cab*
====
有些安全保護比較嚴格的系統，還需要先重新掛載留存 EFI 所用韌體檔的目錄：
====
root# *mount -o remount,rw /sys/firmware/efi/efivars*
====
至於特別為此創建的虛擬檔案系統 `efivarfs` ，在此命令中可被省略而不須指明。
`fwupdmgr` 命令也接受附加 `--allow-reinstall` 或 `--allow-older` 選項，用來安裝相同或是較舊版本的韌體映像。
確認沒有問題之後，就可以在其他尚未更新的機器進行網路更新：
====
root# *fwupdmgr refresh --force* +
root# *fwupdmgr get-updates* +
root# *fwupdmgr update*
====

正常情況下，執行完安裝指令後的第一次重新開機前，會將韌體映像檔案拷貝到 EFI 系統分割區，並且暫時調整 UEFI 開機順序，將韌體安裝程式列為優先。
接著於第二次重新開機後，出現韌體安裝畫面，因為實際執行讀取或寫入作業時，仍然會呼叫韌體映像內建的供應商工具。
第三次重新開機後，才會進行正常的開機程序，但是由於安裝時被自動載入韌體預設值，因此可能還需要手動調整一下。

==== 其他工具
`flashrom` 是通用的讀寫韌體工具，除了系統韌體之外，也支援存取許多不同的硬體裝置。
可以利用引數指定目標晶片的名稱與裝置記憶體位置，並以檔案的形式讀出或寫入資料。
像是前述的 `fwupd` 如果沒有支援某項裝置，還可以載入通用的 `libflashrom` 函式庫模組試試是否可行。

另外有一些散佈版收錄的套件，或是由第三方所提供的工具程式可以參考：

[square]
* `efivar`: 存取位於虛擬目錄 `/sys/firmware/efi/efivars/` 中的 UEFI 匯出變數值。
* `me_cleaner`: 衹能清除 UEFI 韌體中部分的 ME 組件。完全取代 UEFI ROM 的映像檔仍在開發中, 而且需要額外的電路藉由 SPI 接腳才能燒錄進去。
* `fwts`: 檢查韌體完整性的套裝軟體。用於偵測韌體中可能的錯誤，並嘗試提供修正或變通方法。
* `pi-sct`: 平臺初始化自我驗證測試。依照 UEFI 規範來調整特定平臺上的介面，以及驗證韌體的相容性。
