== 軟體開機
在電腦相關的術語中，習慣使用 boot 來表示**開機**。
boot 是 booting 的簡化說法，而後者又是來自 bootstrapping，
詞語的根源 bootstrap 指的是：靴子開口後側用來提腳的環狀小帶子（或稱為提靴帶）。
由於靴子太長，不容易將腳直接套入靴底，因此需要將腳伸入部分之後，再藉由提靴帶的幫助，逐步將整隻穿入。
而開機流程剛好和這個過程十分類似，從啟動到完成並非一氣呵成，而是歷經不同的階段，前後接續才會達到最終狀態。

狹義的開機，僅限於從載入開機裝置上的啟動程式碼，到**內核**(kernel)載入完成為止。
廣義的開機，則擴大包含了之前的韌體開機，以及之後的作業環境初始化階段。

=== 開機啟動
在 BIOS 模式下，會執行開機裝置開頭的 MBR，並讀取**分割區表**(partition table)；
而在 UEFI 模式下，則會依據開機裝置的分割區表，尋找 ESP 裡面 `EFI/_散佈版_/` 子目錄下的 `*.efi` 類型檔案。
UEFI 規格並未限制 ESP 必須是開機裝置的第一個分割區，相容性高的系統韌體甚至支援使用整顆磁碟而不必分區（如同光碟或小容量隨身碟的模式）。
預設的啟動檔案名稱會依硬體架構而有所不同，一般 64 位元電腦系統為 `BOOTx64.efi` ，最後則會執行其中的**開機載入程式**(boot loader) 以進入下一階段。

目前啟動規範處於過渡時期，許多系統韌體同時支援兩種開機模式，再加上可調整優先順序的混合模式。
甚至在可開機的儲存裝置上，也允許同時存在分別適用不同開機模式的啟動軟體。
由於 MBR 的空間有限，衹能容納少量的程式碼，因此後方的分割區配置如果不符舊式規格
（例如起始磁柱位置或分割區容量過大），就有可能導致無法啟動。

NOTE: 在衹有 UEFI 模式的系統韌體上想要啟動 BIOS 模式的簡單作業系統，可以試試 CSMWrap
footnote:[提供 CSM 與 VBIOS 的 UEFI 軟體 <https://github.com/FlyGoat/csmwrap>] 專案。

=== 開機載入程式
為了增加相容性與選擇性，流行的開機載入程序並不會直接載入內核，而是會先執行**開機管理程式**(boot manager)，再由其負責後續的載入工作。
除了取用更多的檔案系統驅動程式之外，也能提供選擇不同作業系統內核的機會，或是調整傳入內核的參數設定值。
開機管理程式也可以視為一個微型的內核，與實際的作業系統並無必然的依存關係。
安裝的位置可能在作業系統儲存區之外，或是附屬於作業系統儲存區之內。
在 UEFI 模式下，常常會直接用開機管理程式替代開機載入程式，以整合開機的流程。

==== GRUB
目前最普遍使用的開機管理程式是 GRUB(大一統開機載入程式)，兩種開機模式都有支援。
假設想要將 GRUB 安裝在第一顆 SATA 類型磁碟上，需要輸入指令 `grub2-install /dev/_sda_` 。

在 BIOS 模式下安裝 GRUB 時，會在 MBR 區段內寫入引導 GRUB 核心（位於資料分割區之外）的指令。
因此可以經由檢查 MBR 中的文字，來檢查系統是否有安裝 GRUB：
====
root# *dd count=1 if=/dev/sda status=none | strings | grep GRUB* +
GRUB
====
GRUB 的核心在某些平臺是以 `core.img` 的檔案型態出現，而在 UEFI 模式下則位於 `grubx64.efi` 檔案之中，可以視為一個簡化的內核附帶初始記憶體磁碟。
每個 UEFI 開機裝置可以分別執行各自的 GRUB 核心、讀取各自的組態檔，但是選單中的選項依然能夠互通。

GRUB 的行為由組態檔所控制，運行過程又可以分成數個次級階段。
產生組態檔的指令為 `grub2-mkconfig -o __組態檔路徑__` ，得到適用於 BIOS 模式的組態檔將位於 `/boot/grub2/grub.cfg` ；
而配合 UEFI 模式的組態檔，則藉由 `/boot/efi/EFI/_作業系統名稱_/grub.cfg` 間接引入前項檔案。
GRUB 組態檔是開機檔案中較為脆弱的部分，一旦發生毀損，開機時可能會進入 GRUB 內建的命令殼畫面。
如果採用拷貝另一個類似系統中的檔案來重建，除了要注意內核的版本號碼之外，還要特別比對磁碟的 UUID 是否匹配。

兩種開機模式都會在 `/etc/` 目錄中建立對應的符號鏈結檔，以下是兩個檔案簡化後的內容範例：

./etc/grub2.cfg
....
set default=1   <1>
set timeout=5   <2>
set timeout_style=hidden   <3>
menuentry 'GNU/Linux (BIOS)' {   <4>
	insmod all_video   <5>
	insmod part_msdos   <6>
	insmod ext2   <7>
	insmod gzio   <8>
	set root='hd0,msdos1'   <9>
	linux /boot/vmlinuz ro root=/dev/sda1   <10>
	initrd /boot/initramfs.img   <11>
}
....

./etc/grub2-efi.cfg
....
set default=1   <1>
set timeout=5   <2>
set timeout_style=menu   <3>
menuentry 'GNU/Linux (UEFI)' {   <4>
	insmod all_video   <5>
	insmod part_gpt   <6>
	insmod ext2   <7>
	insmod gzio   <8>
	set root='hd0,gpt2'   <9>
	linux /boot/vmlinuz ro root=/dev/sda2   <10>
	initrd /boot/initramfs.img   <11>
}
....
<1> 設定預設項目（從 1 開始）
<2> 設定自動執行延遲秒數
<3> 設定延遲形式（隱藏或選單）
<4> 設定選單項目標題
<5> 載入顯示驅動模組
<6> 載入分割區驅動模組（MSDOS/MBR 或 GPT）
<7> 載入檔案系統驅動模組（其他選項 `fat` 或 `xfs` ）
<8> 載入解壓縮模組（支援壓縮過的內核與初始記憶體磁碟）
<9> 組態檔案路徑的基準根目錄（從 0 開始的磁碟編號與從 1 開始的分割區編號）
<10> 設定載入內核的方式、檔案路徑、參數
<11> 設定讀入初始記憶體檔案系統的檔案路徑

GRUB 選單項目的部分，已依照不同的組態拆分至 `/boot/loader/entries/*.conf`。
雖然變更開機參數的正確方法是編輯 `/etc/default/grub` 中的設定值，再以 `grub2-mkconfig` 命令重新產生 GRUB 組態檔，
但是一般的散佈版在安裝新的內核時，還是會檢查 GRUB 組態檔是否被手動修改過，並將變更的部分自動匯入新的項目檔案。

GRUB 開機管理程式讀取組態檔之後，先設定諸如等待時間之類的變數值，然後為每個 `menuentry` 指令產生選單中的一條項目。
外掛的功能或驅動程式，是藉由指令 `insmod` 載入 GRUB 專用的模組來達成。
預設的選擇項目如果是在次選單中，還可以使用 `set default="2>0"` 之類的指令。

選單出現時，如果在預設的等待時間之內按下 kbd:[C]，就會進入 GRUB 內建的指令殼畫面。
不過很少會需要，在這裡將項目中的指令自行輸入，而是比較常去執行一些偵錯指令：
例如 `vbeinfo` 用來列出目前額外支援的顯示狀態，如果沒反應表示不支援 VBE(VESA BIOS 擴充功能)。
也可以利用下列指令來檢視檔案內容：
====
grub> *ls* +
(hd0) (hd0,gpt2) (hd0,gpt1) +
grub> *insmod cat* +
grub> *set pager=1* +
grub> *cat _(hd0,gpt2)/etc/hostname_* +
localhost.localdomain
====

=== 變更開機載入程式
由於開機模式逐步過渡到 UEFI，因此許多衹支援 BIOS 模式的開機管理程式便漸漸無人關注。
萬一無法以重新安裝來達成變更開機載入程式的需求，也要先做好系統備份再開始操作。

==== 救援 GRUB
如果 EFI 系統分割區（假設是 `/dev/sda1` ，而 `/dev/sda2` 是根分割區）毀損，
需要先以另外的 Linux 系統（假設位於 `/dev/sdb` ）開機後：
====
root# *mkfs.vfat /dev/sda1* +
root# *mount /dev/sda2 /mnt* +
root# *mount /dev/sda1 /mnt/boot/efi* +
root# *for i in dev proc run sys; do mount -B /$i /mnt/$i; done* +
root# *chroot /mnt* +
root# *grub2-install /dev/sda* +
root# *grub2-mkconfig -o /boot/efi/EFI/_散佈版_/grub.cfg*
====
有些散佈版可能還需要執行 `update-grub` 命令。
最後利用 `blkid` 命令檢查一下 `/dev/sda1` 的 UUID，是否與 `/etc/fstab` 中的記載相符。
如果不同的話，就需要修改 `/etc/fstab` 檔案的內容。

==== 支援不同模式
原來安裝成適合 BIOS 開機模式的系統，如果要改為 UEFI 也可開機，應該注意以下移植步驟的重點:

. 磁碟分割最好是 GPT 模式，新的系統韌體未必會接受原本的 MBR 模式。
. 建立一個新的 ESP 類型，必要時先縮減磁碟末端的分割區。
. 執行 `mkdir /boot/efi ; mount /dev/sda1 /boot/efi` 指令，並將掛載設定寫入 `/etc/fstab` 檔案。
. 安裝 `grub2-efi`, `grub2-efi-modules`, `efibootmgr` 等套件，以及與安全啟動相關的 `shim` 套件。
. 執行 `cp /boot/grub2/grub.cfg /boot/efi/EFI/_散佈版_/` 指令。
. 將 `/boot/efi/EFI/_散佈版_/grub.cfg` 中的 `linux`, `initrd` 分別改為 `linuxefi`, `initrdefi` 。
. 執行 `grub2-install --target=x86_64-efi` 指令。

切/更換到 UEFI 模式開機的機器後，如果系統韌體選單中看不到目標選項，可能還需要以另外的 Linux 先開機，
然後執行 `efibootmgr` 命令以加入 UEFI 開機選單。

原來安裝為 UEFI 開機模式的作業系統，如果想要改為 BIOS 模式也可以開機:
====
root# *dnf install grub2-pc grub2-tools* +
root# *grub2-install --target=i386-pc --root-directory=/ _/dev/sda_*
====
不過第二條指令可能無法成功，因為 BIOS 模式需要一個隱藏區塊(post-MBR gap)，用來放置 GRUB 的核心程式。
這也是為什麼大多數的分割區工具程式，預設的第一分割區起始磁區並非從頭開始，而是一個稍大的數字（例如 1024）。
可以試試用另外但相同版本的 Linux 系統開機之後，執行以下的指令將 GRUB 核心程式移到別的地方，看看能不能成功：
====
root# *mount _/dev/sda2_ /mnt* +
root# *grub2-install --target=i386-pc --root-directory=/mnt --force _/dev/sda_*
====
有些原來以舊版 GRUB 做為開機啟動程式的系統，要移植為新版 GRUB2 時也會發生類似的問題。

==== SYSLINUX
曾經流行的開機載入程式為 LILO，而較新的 rEFInd 雖然支援 UEFI 但很少人使用。
Systemd 系統初始模式本身有提供一個簡易開機載入軟體 `systemd-boot` ，但是仍未受到一般使用者的注意。
SYSLINUX 則是目前足以與 GRUB 並稱的多用途開機載入軟體家族，其中適用於 BIOS 模式的稱為 EXTLINUX。
如果想要換用 EXTLINUX，安裝步驟的範例如下：
====
root# *dnf install syslinux syslinux-extlinux* +
root# *extlinux --install /boot/extlinux* +
root# *cd /usr/share/syslinux* +
root# *dd bs=440 count=1 conv=notrunc if=mbr.bin of=/dev/sda* +
====
接著還要編輯在 `/boot/extlinux/` 目錄下，檔案 `extlinux.conf` 與 `linux.conf` 的內容。
在 UEFI 模式下也有 `syslinux.efi` 可以用來代替 `grubx64.efi` 的功能，但是使用情況並不普遍，同時也要注意儲存裝置的驅動支援程度。

=== 載入內核
如果開機管理程式設定了多重開機選項，而且沒有設定為隱藏，就會在運行時顯示開機選單。
使用者可以利用 kbd:[Up] / kbd:[Down] 與 kbd:[Enter] 來選擇不同的組態，或是等待數秒後進入預設的項目。
若是按下 kbd:[E] 鍵，表示要修改目前反白選項的內容，完成後則按 kbd:[F10] 套用內容（但無法存入磁碟）。
此時開機管理程式會執行隱含的 `boot` 指令，將系統控制權轉移給內核，由其讀入初始記憶體檔案系統。

==== 載入過程
開機時最重要的步驟即為載入內核，這是掌控整個作業系統運行的軟體核心，堪比 CPU 在主機板上扮演的角色。
內核核心以外的功能，是以**內核模組**(kernel module) 的軟體形式載入。
開機管理程式中使用 `linux` 指令來載入內核，有些 Linux 散佈版會為了區分 UEFI 開機模式而使用 `linuxefi` ，
但是在與安全啟動選項同時使用的狀態下，使用者必須要注意 `linuxefi` 的相容性。
萬一要使用舊式參數（例如 `vga=`），可能就要搭配 `linux16` 來代替 `linux` 指令。

載入指令後方的參數，標明了內核檔案所在的路徑，是相對於之前 GRUB 指令 `set root=` 所設定的基準位置。
接下來就是傳給內核的**內核參數**(kernel parameter)，或是稱為**內核密技碼**(kernel cheatcode)，有時也會全部移到可選的 `options` 指令後方。
如果遇到了 `--` 參數，則表示之後的參數即使以 `-` 開頭，也會被視為完整的參數而非選項。

內核載入系統的過程可以分為幾個階段：

. 讀入指定的檔案做為初始記憶體檔案系統
. 以唯讀方式掛載根目錄檔案系統裝置
. 以可讀可寫方式重新掛載根目錄裝置

==== 初始記憶體檔案系統
`initramfs.img` 是以 CPIO 格式所封裝的小型檔案系統階層，將記憶體檔案系統當做根檔案系統來使用，有些散佈版還會將封裝檔案進一步壓縮。
讀入初始記憶體檔案系統的 `initrd` 指令，得名自舊式的初始記憶體磁碟，實際上做為載入內核指令的補充。
如果所用的散佈版以 `initrdefi` 指令搭配 `linuxefi` 用於 UEFI 開機模式，萬一出問題時可以嘗試改回標準指令看看。

產生初始記憶體檔案系統的基本命令是 `dracut` ，也可以使用散佈版自行提供的**前端程式**(frontend) 來製作檔案，但是工具的名稱與用法會依不同的散佈版而有差異。
手動再製初始記憶體檔案系統時，要注意目標內核所支援的壓縮規格，否則會造成開機解包時的編碼錯誤。

如果要對既有的初始記憶體檔案系統進行精細調整，就需要先解除打包，然後以**回送**(loopback) 裝置的形式掛載；
而手動修改完之後，重新打包的命令與引數必須要與原本的格式完全一致或相容。

初始記憶體檔案系統由內核載入後，展開到記憶體並掛載於根目錄。
它提供初始系統時所需要的內核模組，尤其是為了驅動磁碟上的檔案系統。
如果某些模組是開機時硬體所必需，卻未內嵌於內核也未包含於初始記憶體檔案系統，就有可能在開機時造成系統宕機。

每當內核的組態有所變更，系統會依據實際的狀況，動態收集需求而建立新的封裝檔案。
對於嵌入式系統而言，如果編譯內核時已經包含所有啟動時需要的模組，那麼讀入初始記憶體檔案系統的階段就不是必須的。

==== 根目錄檔案系統
內核參數 `root=` 表明了實際根目錄所在的檔案系統裝置，首先會依照另一個內核參數 `ro` 的指示，以唯讀的方式掛載於初始記憶體檔案系統之下。
如果開機程序在鍵盤燈亮之前停住，可能是磁碟分割區毀損，或是分割區表中數值與實際容量不符，而無法正確讀取檔案系統。
參數後的裝置名稱支援不同的標示方法：

[square]
* root=/dev/_sda1_
* root=UUID=_07c5ac72-4edd-4701-8923-c404a4e4903e_
* root=LABEL=_SYSTEM_

不使用第一種 `/dev/` 之下傳統裝置節點的好處，在於變更（新增、刪除、搬移）系統上的磁碟組態後，仍然能夠指到正確的裝置。
內核接著會利用 `chroot` 將系統實際的根目錄切換到這個掛載點上，同時將它重新掛載為可讀寫的檔案系統。

==== 模組載入
取得系統控制權之後，內核會依據系統韌體的設定值，以及自主偵測到的硬體組態載入所需的模組。
內核模組分為內建與外掛兩種：內建模組在製作內核時就已嵌入內核，會隨著系統啟動而載入記憶體。
外掛模組則是編譯為分離的模組檔案(`\*.ko`)，一般位於 `/usr/lib/modules/` 目錄下的內核版本子目錄，而其中的 `modules.builtin` 檔案則記載了內建模組的列表。
內核模組的名稱如果是由多個部分組成，通常會以底線(_) 相連，但是在檔案名稱中則會替換為短橫線(-)，並且實際儲存時會經過壓縮而加上相應的擴充檔名(`*.ko.xz`)。

`lsmod` 命令會列出目前系統中已載入的外掛模組，也可以查看 `/proc/modules` 檔案的內容，但是 `/sys/module/` 假擬目錄中才會同時看到已載入的內建模組項目。
開機時如果未載入某個驅動程式，可利用 `modinfo` 命令加上模組名稱做為參數，來確認硬體裝置代號是否包括在該模組支援的列表中。

內核模組與其參數名稱的組合，也可以視為一種內核參數來使用，因此能夠透過開機管理程式進行設定。
如果額外想要在內核啟動時期一併載入與設定的話，分別要在目錄 `/etc/modules-load.d/` 與 `/etc/modprobe.d/` 中建立相應的組態檔案。
在系統執行時期，用來動態載入或卸載外掛內核模組的命令是 `modprobe` ，它的參數可以做為內核模組的參數賦值。
對於已經載入的內核模組，還可以嘗試利用 `echo` 命令將設定值寫入 `/sys/module/_模組名稱_/parameters/_參數名稱_` 來動態變更。

模組的**黑名單**(blacklist) 代表在載入模組的過程中，必須被刻意排除的模組名稱，可以經由內核參數 `modprobe.blacklist=` 或 `rdblacklist=` 來設定。
後者僅於初始記憶體檔案系統中有作用，需要加上 `/usr/lib/modprobe.d/` 目錄中檔案內容的黑名單設定，才能相當於前者的效果。

有些模組於載入時，還需要參照額外的裝置韌體。
裝置韌體做為執行於裝置微控制器上的**微碼**(microcode)，是由內核驅動模組透過 UDEV 機制將其載入裝置。
雖然也叫做「韌體」，卻與系統韌體不同，而是由裝置製造商發布的二進位檔案，包括了不想公開放在模組中的程式與設定。
產生初始記憶體檔案系統時，如果出現無法參照特定裝置韌體的訊息，表示內核已更新至可以偵測到新裝置的版本，但裝置韌體的版本並未跟上。
裝置韌體版本愈新愈好，至少應該等於現用的內核；可以直接上內核網站下載，或是嘗試安裝散佈版提供的新版裝置韌體套件。

==== 編譯模組
有些內核模組並未隨附內核而散佈：也許是衹存在於開發者儲存庫中，尚未被內核所接受；更有可能是由廠商提供的裝置驅動程式，其中包含了不適合匯入內核開發分支的部分。
一般來說，測試人員需要將這類軟體下載後，自行編譯成外掛模組的形式再使用。

自行編譯內核模組除了基本的 `gcc`, `make` 等編譯工具之外，還需要先安裝內核的開發套件 `kernel-devel` ，以及內核的標頭檔套件 `kernel-headers` 。

NOTE: 內核模組對於內核版本的依存性非常地高，必須配合與編譯時相同的內核版本才可以載入。

==== 內核版本
64 位元的 X64 CPU 在設計時，便已決定向下相容於 32 位元的 X86 CPU，而個人電腦開機的各個階段之間也有很明顯的隔離性質。
因此以 32/64 位元的開機載入程式、32/64 位元的內核、32/64 位元的使用者空間來說，彼此也有可能混合運行（除了 32 位元內核無法搭配 64 位元使用者空間之外）。
另外 UEFI 與開機載入程式的軟體位元必須相同，而且內核或使用者空間的軟體位元均不可高於 CPU 的硬體位元。

執行中的系統可以經由 `uname -r` 命令取得內核版本，如果要確認目前的內核參數，可以查看 `/proc/cmdline` 的內容。

NOTE: 有些散佈版的內核並不完全照基底的版本來命名，實際的版本編號需要參考 `/proc/version` 或 `/proc/version_signature` 的內容。

==== 內核偵錯
內核初始化時，會將偵測到的各項資訊記錄在 `/sys/kernel/debug/` ，而內核參數 `loglevel=0` 可以取消印出部分的錯誤訊息。
如果以超級使用者身分仍因權限不足而無法讀取，則需要關閉系統韌體設定中的安全啟動選項。
各個項目的實際數值，有可能於執行時期動態變更，或是於裝置重置之後重新偵測。

如果想要動態變更內核參數，可用 `sysctl` 命令，例如 `sysctl -w kernel.sysrq=1` 可於系統宕機時按下 kbd:[Alt]+kbd:[SysRq]+kbd:[R] 取得控制權。
`sysctl -a` 以及 `/proc/sys/kernel/` 目錄中的內容能夠顯示部分內核參數值，而 `/boot/config-$(uname -r)` 則包含目前內核組建時的設定。
部分內核模組的當前參數值，允許利用 `sysfsutils` 套件中的 `systool` 命令取得。
`sysctl` 命令僅能暫時變更部分的內核模組參數值，嘗試確認後則需要建立 `/etc/sysctl.d/` 中的組態檔才能保持下去。

使用內核參數 `rd.break enforcing=0` 來強制中斷開機流程，並於讀入初始記憶體檔案系統之後進入緊急模式。
由於多數系統的單人模式預設仍然需要密碼，如此避開後即可手動掛載磁碟：
====
root# *mount -o remount,rw /sysroot* +
root# *chroot /sysroot* +
root# *passwd*
====
除了利用 `passwd` 命令來修改密碼之外，必要時還可執行 `dracut` 命令來重建初始記憶體檔案系統。
如果本來有啟用 SELinux 的話，可能還需要以下的指令（或是衹需要最後一列）來重置它：
====
root# *restorecon -v /etc/shadow* +
root# *setenforce 1* +
root# *touch /.autorelabel*
====
完成後再連續輸入兩次 `exit` 命令來重新啟動系統。
