== 系統裝置
直接內嵌於主機板上的裝置，通常稱之為系統裝置或內嵌裝置，一般是以整顆晶片、部分晶片或是韌體模擬的形式出現。



=== CPU
*CPU*(中央處理器) 無疑是整個電腦系統中最重要的元件。
今日的 CPU 早已不是單純的一顆處理晶片，除了封裝多重的處理器核心以外，
還涵括了**浮點處理單元**(FPU)、**繪圖處理單元**(GPU)，甚至未來**神經處理單元**(NPU) 的功能。
而在嵌入式的 *SoC*(單晶片系統) 中，又包入了記憶體、匯流排介面等模塊。

==== 基本資訊
基本的命令是 `lscpu` ，它會提取 `/proc/cpuinfo` 中的資訊來顯示，其中比較特別的項目說明如下：

[square]
* Stepping: 製造步進等級，代表相同規格下對於電路或製程的修改版本，通常以 [字母][數字] 的組合表示，例如 A0, B2, C1,...。
* BogoMIPS: 相對的運算速率，這是內核對於 CPU 效能的不嚴謹指標，但不會受到記憶體的影響。
* Virtualization: 支援虛擬化（KVM 加速）的 CPU 功能，Intel 的規格稱為 VT-X，而 AMD 則以 AMD-V 表示。
* Flags: 具備的功能旗標。
** msr: 可以藉由 `msr-tools` 套件中的 `rdmsr` 命令來讀取 CPU 的 MSR 資料。
** smep, smap: Intel 產品具備的「Intel OS Guard」功能，可有效防止惡意程式奪取核心權限。
** vmx/svm: 分別指明 Intel/AMD 的 CPU 所使用的虛擬化技術。
* Vulnerability: 已知安全漏洞的對策。
** Mitigation: 由軟體（通常是內核）提供的緩解方式。
** Microcode: 由 CPU 廠商提供給系統韌體供應商，做為公版的不可變部分，用以將機器語言碼轉為更低階的真實 CPU 指令。

`dmidecode -t processor` 指令的輸出中，也有許多由系統韌體所認知的 CPU 相關資訊。
另外還有一項與虛擬化相關功能，利用裝置記憶體虛擬/實體位址轉換來增進虛擬機效能，在 Intel/AMD 平臺上分別稱為 VT-d/IOMMU。
由於 `lscpu` 或 `dmidecode` 命令未必能顯示 VT-d/IOMMU 的狀態，因此需要以其他方式進行檢測。
例如依據指令 `dmesg|grep DMAR` 的輸出，就能夠判斷作業系統是否可以使用此一功能。
如果沒有輸出或是顯示停用的話，原因可能是 CPU 本身不支援、系統韌體將其關閉，或是設定了內核參數 `iommu=off` 。

==== 溫度
想要取得 CPU 的溫度以及風扇轉速，可以利用 `lm_sensors` 套件中的 `sensors-detect` 與 `sensors` 命令。
溫度的數值來自 `/sys/class/thermal/thermal_zone?/temp` ，單位為千分之一攝氏度，
也可以藉由圖形介面的 `psensors` 或 `xsensors` 軟體獲得。

==== 頻率
想要知道系統內個別 CPU 目前的工作頻率，可以利用 `lscpu` 命令的 `-e` 選項，
實際上則是讀取 `/sys/devices/system/cpu/cpu?/cpufreq/scaling_cur_freq` 的值。
另外 `kernel-tools` 套件中的工具程式 `cpupower` 也可以顯示 CPU 頻率，而變動的調頻結果則由 `turbostat` 命令顯示。

內核中負責 CPU 調頻的次系統，記載於 `/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver` 檔案，
利用第三方套件 `cpufrequtils` 的 `cpufreq-info` 命令，也能看到相關資訊，
內容一般會是 `acpi-cpufreq` ，或是支援較新規格的 `intel_pstate` 。
如果開機過程中斷或是偵測不到外接裝置，可以試試加入內核參數 `intel_pstate=disable` 以改回傳統的 `acpi-cpufreq` 模式。

==== 效能
文字模式下的 `sysbench` 工具程式，一般會在命令中加入與核心數目相同的執行緒參數，
可以在輸出中提供事件頻率(Events/sec)，以評估處理器計算質數的效能：
====
user$ *sysbench cpu --threads=2 run*
====
將內核對於 CPU 缺失的修補停用可以增加一些效能。
其他的命令包括由同名套件提供的 `s-tui` 或 `mangohud` ，可以監看 CPU 與 GPU 的即時負載。

=== 晶片裝置
晶片製程的演進: MOSFET, FinFET(鰭式場效), FD-SOI(環繞閘極), CFETS(互補場效)。

==== RTC
*RTC*(實時時鐘) 通常位於南橋晶片組，共存於儲存系統韌體使用者設定值的晶片中，並由此讀寫日期時間的資料。
依據主機板的不同實作，也有可能使用獨立晶片或是嵌入到其他晶片，而經由諸如 I^2^C 或 SPI 的匯流排與系統連接。
關機時 RTC 仍在運作，維持硬體時鐘與 CMOS 資料。

作業系統運作時依據的時鐘稱之為**系統時鐘**(system clock)，是基於硬體時鐘再加以微調而得。
電池失效或是晶片過熱，可能會造成硬體時間不準或經常重置，甚至無法開機或是軟體運行時驗證相關的動作失敗。

實時時鐘的虛擬裝置節點位於 `/dev/rtc` ，一般來說並不會直接存取。
傳統上利用 `hwclock` 命令來管理硬體時鐘與系統時鐘的設定值，而 `systemd` 套件中則提供較新的 `timedatectl` 命令做為控制程式。
使用者取用日期時間的工具程式是 `date` 命令，常見於命令稿中輸出時間戳記的範例如下：
====
user$ *date -Is* +
2025-03-22T13:03:26+08:00
====

==== EC
*EC*(嵌入控制器) 普遍存在於筆記型電腦中，與南橋之間是以 LPC 匯流排相連。
它有自己的韌體，常常與系統韌體連動更新。
EC 於部分系統負責鍵盤控制、指示燈與風扇，用以統合周邊設備。
關機狀態下，EC 則用來偵測電源按鍵以通知系統開啟電源。

系統必要時可以透過 `ec_sys` 內核模組，來讀取 EC 的設定值。
有些散佈版出於安全的考量，並未將其內建在標準組建的內核中，或是沒有啟用自動載入。
若要即時變更設定值，必須在內核模組設定檔案內開啟可寫的選項：

./etc/modprobe.d/ec_sys.conf
....
options ec_sys write_support=1
....
如此就能透過 `/sys/kernel/debug/ec/ec0/io` 虛擬檔案的內容來存取設定值。
有些筆記型電腦系統則是利用輸入輸出埠 0x80, 0x81，分別向 EC 讀取與寫入資料。

==== Super I/O
主機板上的 *Super I/O*(超級輸入輸出) 晶片，用來做為低頻寬設備的介面，以往需要透過 ISA 匯流排，目前則常併入 EC 而透過南橋晶片上的 LPC 匯流排與 CPU 連接。
`coreboot-utils` 套件中有 `superiotool` 程式，可以偵測並提供暫存器內容。
如果在系統啟動時期被 ACPI 占住資源，可以利用內核參數 `acpi_enforce_resources=lax` 來排除問題。
除了常用來提供平行埠、序列埠，以及監測溫度、風扇速度之外，有些型號還會具備看門狗計時器的功能（參看〈輸入輸出埠〉）。

==== TPM
*TPM*(信賴平臺模組) 是安全密碼的處理裝置。
由專用晶片所提供的 TPM 功能稱為 dTPM(discrete TPM)，而由系統韌體所模擬提供的則為 fTPM(firmware TPM)，不論何者通常都可以透過韌體設定啟用或停用。
版本 2.0 是安裝新的 Windows 作業系統時所要求的配備，並且僅適用於 UEFI 開機環境。

內核偵測到 TPM 之後，就會啟動內建的 `tpm` 驅動模組，並且產生 `/dev/tpm0` 與 `/dev/tpmrm0` 裝置。
測試時可以使用套件 `tpm2-tools` 中的工具程式：
====
root# *tpm2 gettestresult* +
status:   success +
data:   0010aa2900000000000000 +
root# *tpm2 getcap pcrs* +
  - sha1: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ] +
  - sha256: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ] +
root# *tpm2 getrandom --hex _8_* +
32eefe49546a1a64root#
====
最後一條範例指令會產生 8 個位元組的亂數，而這些功能也會被其他的加/解密應用軟體（例如 `clevis` ）所利用。

==== 主記憶體
目前主流的主記憶體是使用**同步動態隨機存取記憶體**(SDRAM)，規格發展的版本以第幾代來區分。
例如 DDR5 表示第五代的雙倍資料速率，而每一代新規格都改進了更低的工作電壓以及更高的傳輸速率。
記憶體所使用晶片顆粒的等級，由高到低可分為：Major(原廠)、eTT(有效測試)、uTT(未測試)，之下則稱為 Downgrade(次級品)。
記憶體模組上有一顆**序列存在檢測**(SPD) 晶片，用來記載模組的資訊，讓系統韌體不需存取記憶體就能檢測組態。

主機板上許多晶片的暫存器，也都有對映到主記憶體的區塊，因此依照規格書就可以查到相應的位址。
主記憶體除了被內核獨佔一部分，圖形介面卡也會共用/佔用一塊區域，另外還有記憶體映射輸入輸出(MMIO) 機制，通常在系統韌體設定中可以調整用量大小。
由於此項映射機制，當開機出現螢幕花屏（掃描線段漏失）並附帶宕機時，也有機率是記憶體未插好或是接觸不良所造成。
非官方套件 `devmem2` 提供讀寫記憶體位址的同名命令，但新版的內核已預設關閉此一讀取 `/dev/mem` 的功能。

有時候增加主記憶體反而造成無法開機，一方面插入多條記憶體模組，可能會出現彼此或是與主機板之間不相容，而造成系統不穩定、畫面閃爍等情形。
另一方面也許是 BIOS 開機模式對特定系統的記憶體分配不正確，或是與 32 位元作業系統分配給顯示的後段記憶體有關，可以嘗試用內核參數 `mem=` 來限制記憶體容量。
如果以 `mem_encrypt=on` 內核參數啟用了記憶體的加密功能，也有可能因此造成初始化其他裝置時宕機。
萬一開機過程中出現了類似 `Memory corruption detected in low memory` 的錯誤訊息，導致無法啟動作業系統卻又不適合更換記憶體的情況，
可以先試試加入內核參數 `memory_corruption_check=0` 的變通方案，希望能爭取一些進入系統補救與檢測的機會。

許多散佈版的安裝光碟都包含了 `memtest86+` 這個 UEFI 的應用軟體，用來做為測試記憶體的工具，而進入系統後則有 `memtester` 套件提供的同名命令可以使用。
基礎命令 `free` 命令整理了 `/proc/meminfo` 中的資訊：
====
user$ *free -h* +
               total        used        free      shared  buff/cache   available +
Mem:            31Gi       2.4Gi        26Gi       660Mi       2.2Gi        27Gi +
Swap:          4.0Gi          0B       4.0Gi
====
其中最常注意的項目，應該是位於 Mem: 列 total 欄的記憶體總量，以及 free 欄的未使用記憶體總量。
如果要看個別軟體行程的記憶體用量，則需要由 `top` 命令提供的文字全螢幕動態畫面來提供，而 `nvtop` 則是針對 GPU 的同類程式。
另外從 `dmidecode -t memory` 指令所得出的資訊中， `Speed:` 項目顯示記憶體實際的速度，而 `Configured Clock Speed:` 項目則表示系統韌體中所設定的速度（可能超頻或降頻）。

文字模式下的 `sysbench` 工具程式，內建的選項可以在輸出中提供傳輸速率(MiB/sec)，
做為衡量系統記憶體的寫入效能：
====
user$ *sysbench memory run* +
... +
70482.11 MiB transferred (7047.10 MiB/sec) +
...
====


=== 匯流排
**匯流排**(bus) 是指主機板上的一組線路，用於連接多個內部裝置（晶片）或外部裝置（埠口）。
不同規格的匯流排定義了不同的線路數量、傳輸時脈與訊號模式，適應傳輸資料對於不同流量、距離以及容錯率的要求。

==== PCI
電腦系統中的 *PCI*(周邊元件互連標準) ，是用來連結主機板與外部裝置的主要匯流排類型。
外部裝置包括同樣位於主機板上的內嵌裝置，以及以插槽介面外接的擴充裝置。
PCI 取代了許多舊式的匯流排，而目前最通用的類型則為序列式的高速進階版 *PCIe*(PCI express) 。

可用 `lspci` 命令列出系統中所有 PCI 裝置的資訊：
====
user$ *lspci* +
00:00.0 Host bridge: ...... +
00:02.0 VGA compatible controller: ...... +
00:14.0 USB controller: ...... +
00:16.0 Communication controller: ...... +
00:16.3 Serial controller: ...... +
00:19.0 Ethernet controller: ...... +
00:1b.0 Audio device: ...... +
00:1f.0 ISA bridge: ...... +
00:1f.2 SATA controller: ...... +
00:1f.3 SMBus: ...... +
02:00.0 PCI bridge: ...... +
====
輸出資料的第一欄是插槽編號，由冒號之前的匯流排編號以及冒號之後的裝置編號與功能編號組成；第二欄冒號之前的資料表示裝置所屬的類型，之後則是裝置的名稱（已省略）。
`lspci` 命令加上選項 `-k` ，可以看到目前使用中的內核驅動模組名稱。
選項 `-n` 則會顯示代表裝置硬體識別號(PCI ID) 的供應商代碼與裝置代碼，這也是軟體從識別號列表中找出裝置名稱的依據。
識別號列表是名為 `pci.ids` 的文字檔案，可以透過 `update-pciids` 命令從內建的網址隨時更新到本機端。
如果想要顯示特定裝置的詳細資訊，可以參考指令範例：
====
user$ *lspci -s _00:19.0_ -nnvvxxx*
====
PCI 裝置有各自的組態暫存器、輸入輸出埠與裝置記憶體，而 `lspci` 的 `-x` 選項，能夠以十六進位值來顯示裝置的**組態空間**(configuration space)，其中也能找到硬體識別號。
NOTE: 以超級使用者身分執行 `lspci` 命令可以獲得更多資訊。

`setpci` 命令則是用來設定 PCI 裝置組態空間中，特殊暫存器的值。
例如 `setpci --dumpregs` 指令可以列出可存取的裝置暫存器，據此來顯示及設定特定裝置的特定暫存器內容。
下列三條範例的原本用途分別為：顯示狀態、設定亮度、啟用喚醒，實際使用時會依裝置種類與型號而有差異：
====
root# *setpci -s _02:00.0_ _STATUS_* +
0010 +
root# *setpci -s _00:02.0_ _F4.B=55_* +
root# *setpci -s _00:14.0_ _7C.W=0108_*
====

=== USB
由於 *USB*(泛用序列匯流排) 支援熱插拔機制，它的外接型式是目前最流行的連接介面，隨著規格不斷地擴充與演進，大有一統個人電腦周邊設備介面的趨勢。
主要世代與相應的主端控制器驅動規格，以及介面速度理論值如下：

[square]
* USB 1.0: OHCI 1.5Mbps
* USB 1.1: OHCI 12Mbps
* USB 2.0: EHCI 480Mbps
* USB 3.0: XHCI 5000Mbps
* USB 3.1: XHCI 10Gbps
* USB 3.2: XHCI 20Gbps

但是由於 USB 技術開發的速度太快，官方的規格名稱也不斷變動，以下列出目前各種名稱分類的對應表：

[square]
* USB 3.2 Gen 1×1 (= USB 3.0 = USB 3.1 Gen 1)
* USB 3.2 Gen 1×2 (= USB 3.0 & Type-C)
* USB 3.2 Gen 2×1 (= USB 3.1 = USB 3.1 Gen 2)
* USB 3.2 Gen 2×2 (= USB 3.1 & Type-C)

近期還發表了速度可達 40Gbps 甚至更高的 USB 4.0 規格，未來可能衹以傳輸速度做為分類依據。
為了簡化說明，以下僅以 USB1, USB2, USB3 代表主要的不同技術規格。

==== 接頭
USB1 與 USB2 多使用 Type-A 接頭，還有數種已經過時的型式，而 USB3 裝置則有 Type-A 或 Type-C 兩種型式的區分。
USB3 Type-A 接頭中除了相容於 USB2 的四支接腳之外，另外還有較小的五支擴充接腳。
相同 USB 規格的 Type-C 接頭速度規格通常會比 Type-A 快，使用轉接線的結果則可能會變慢。
Type-A 接頭隔板的顏色是由**個人電腦設計指導**(俗稱 PC97 或 PC2001) 所定義，會依 USB 規格而有所不同：

[square]
* 黑色：USB2 或以下（標準供電 500mA）
* 藍色：USB3（標準供電 900mA）
* 紅色：附加額外電力供應

不過實際在硬體設計時，常會由於協調配色的原因而忽略此項準則，以致於使用者必須察看接頭附近的圖示或標貼，才能確認規格是否匹配。
由於設計上使用者拿起 USB Type-A 插頭時，是以右手拇指按住有 USB 圖示符號的一側為基準，
因此主機上具有方向性的插座，如果沒有配合這種操作姿勢來建置，就會產生不方便的使用情境。
再加上 Type-A 接頭的金屬外框部分，如果材質不好就可能會氧化而造成接觸不良，更加速了從 Type-A 過渡為 Type-C 的趨勢。

==== 控制晶片
有些單晶片系統中已內含多個 USB 的**主端控制器**(host controller)，而主機板上的控制器則依靠 PCI 匯流排與系統通訊。
不同規格的 USB 介面，通常是由不同的晶片所控制，並受到不同的內核模組所驅動。
一個主端控制器可以控制多個內含的**根集線器**(root hub)，後者與外接集線器同被視為 USB 裝置。
每個根集線器提供多個埠口用來與裝置通訊，而每個埠口之下還包括多組的組態介面，以及不同的設定與端點。
例如外接的 USB **擴充基座**(docking station)，就是藉由 USB 可以分支並聯的特性，再搭配各種不同的轉換晶片，達到由一個 USB 接頭衍生出多種輸入輸出埠的效果。

雖然設計上已經有考慮相容性，但是不同規格的裝置與接頭有時仍會出現不匹配，需要在驗證時進行交叉測試。
例如像是以 USB3 的裝置開機後，有可能會發生共用集線器的其他 USB 接頭卻無法使用 USB1 裝置的情況。
驅動不同規格的內核模組之間，雖然是設計來可以並存使用，但是在少數的情況下，還是會互相影響。
因此偵錯時可以嘗試在系統韌體設定中，先停用部分的支援規格再進行測試。

USB3 的標準傳輸頻寬為 5Gbps，而其差動訊號(differential signaling) 必須達到 2.5GHz，由於和無線網路的 2.4GHz 頻寬很接近，有可能會引起干擾。
USB3 除了標準模式之外還定義了許多**替換模式**(alternate mode)，用以支援超高速傳輸、視訊輸出等功能。
當支援替換模式的設備插入不支援此模式的主機，或是角色對調的情況發生時，依據規格該設備應該要展露出一個**告示牌裝置**(billboard device)，好讓主機端能偵測到並且通知使用者這個模式不匹配的訊息。

==== 裝置資訊
個別 USB 設備的簡略資料，可以透過 `lsusb` 命令來顯示：
====
user$ *lsusb* +
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub +
Bus 001 Device 002: ID 046d:c077 Logitech, Inc. Mouse +
Bus 001 Device 003: ID 046d:082b Logitech, Inc. Webcam C170 +
Bus 001 Device 004: ID 04d9:010b Holtek Semiconductor, Inc. USB Keyboard +
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub +
Bus 002 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub +
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub +
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub +
Bus 004 Device 002: ID 8087:8008 Intel Corp. Integrated Rate Matching Hub
====
其中的匯流排編號與裝置編號，可以組成位置編號（例如 1-1 或 4-2）；
而後方的十六進位裝置識別碼欄位，則是由**供應商識別碼**(VID) 與**產品識別碼**(PID) 以冒號分隔所共同組成，兩者在許多其他的指令中都會用到。

`lsusb` 命令加上選項 `-t` 還能看到驅動個別裝置所用的內核模組名稱：
====
user$ *lsusb -t* +
/:  Bus 001.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/14p, 480M +
    |__ Port 006: Dev 002, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M +
    |__ Port 009: Dev 003, If 0, Class=Video, Driver=uvcvideo, 480M +
    |__ Port 009: Dev 003, If 1, Class=Video, Driver=uvcvideo, 480M +
    |__ Port 009: Dev 003, If 2, Class=Audio, Driver=snd-usb-audio, 480M +
    |__ Port 009: Dev 003, If 3, Class=Audio, Driver=snd-usb-audio, 480M +
    |__ Port 010: Dev 004, If 0, Class=Human Interface Device, Driver=usbhid, 12M +
    |__ Port 010: Dev 004, If 1, Class=Human Interface Device, Driver=usbhid, 12M +
    |__ Port 010: Dev 004, If 2, Class=Human Interface Device, Driver=usbhid, 12M +
/:  Bus 002.Port 001: Dev 001, Class=root_hub, Driver=ehci-pci/2p, 480M +
    |__ Port 001: Dev 002, If 0, Class=Hub, Driver=hub/8p, 480M +
/:  Bus 003.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/6p, 5000M +
/:  Bus 004.Port 001: Dev 001, Class=root_hub, Driver=ehci-pci/2p, 480M +
    |__ Port 001: Dev 002, If 0, Class=Hub, Driver=hub/6p, 480M
====

如果 `lsusb` 命令加上了 `-v -d _裝置識別碼_` 選項，就可以列出個別裝置的內容說明。
圖形介面的檢測工具選擇則有 `usbview` ，能夠顯示個別 USB 裝置之間的連接關係以及詳細資訊。

==== 裝置驅動
在系統韌體的選單中可以找到是否允許從 USB 裝置開機的選項，連帶地也可以決定相對於其他開機裝置的開機優先順序。
此項方便的功能有時反而會造成無法開機：如果該裝置上的開機機制安裝或清除不完全，會導致系統誤判而啟動失敗；
或是主機與設備間的傳輸介面速率，無法協調一致而造成無限迴圈；
也有可能是裝置的回應速度（由於介面規格、傳輸線、電源供應）太慢，而超過了系統韌體預設的等待時間。

驅動 USB 匯流排的核心內核模組為 `usbcore` ，由此而下為各類別的裝置準備了通用的類別驅動程式，並以其類別代碼與子類別代碼來區分。
特殊情況下可以藉由內核參數的設定，來變更特定型號 USB 裝置的特定性質，例如 `usbcore.quirks=__供應商識別碼__:__產品識別碼__:gn` 可以調整反應時間的延遲。

在內核為了裝置所準備的 `/dev` 假擬檔案系統中，USB 裝置是依據其功能與相應的內核模組來分配位置。
其中的量體儲存(mass storage) 類別驅動模組 `usb_storage` ，採用的是 SCSI 傳輸協定，因而在裝置目錄節點中，會被視為一種 SCSI 磁碟： `/dev/sd__X__` 。
當系統連接了多個同類的 USB 裝置（例如外接的音效卡或是轉出的通訊埠）時，裝置的位置代號則會隨 USB 埠被偵測到的順序而變動，甚至每次重新開機後都可能不同。
如果編寫程式而需要引用某裝置的位置代號，就必須參考裝置所連接的匯流排（PCI 或 USB）編號才能確認。

==== 熱插拔機制
有些 USB 裝置（尤其透過集線器連接）在啟動初期不會被識別出來，而要等到系統載入完整後才能夠存取。
可能是因為系統韌體、開機啟動程式或者初始記憶體磁碟中，沒有包含適當的驅動模組，必須依賴後續的熱插拔機制才能偵測到。
順利使用裝置的前提，還包括匯流排是否能夠負荷多個裝置的電流量與資料量。

內核模組原始碼中如果使用了 `MODULE_DEVICE_TABLE` 巨集，就可以藉由 `depmod` 命令將目標裝置登記於熱插拔的自動載入表中，就不需要依靠觸發 *UDEV*(使用者空間裝置命名) 的規則來被動載入。
否則內核於開機時，就會為已經插入系統的冷插拔裝置記錄冷插拔事件，然後再交由 `udevd` 產生熱插拔事件並觸發相應動作。
USB 儲存裝置的熱插拔通常都會伴隨著**自動掛載**(automount) 的機制，則是需要藉由 UDEV 的規則來完成。

==== 隨用機制
USB 的 *OTG*(隨用) 規格，讓裝置可以扮演主控的角色用以連接其他的裝置，或是反過來讓主控裝置扮演附屬裝置的角色用以接受刷寫映像檔。
通常所謂的 OTG 線材衹是不同接頭規格的轉接線，實際是否連接成功除了規格的支援外，還要考慮：
足夠的電力供應、支援的檔案系統格式（FAT32 較相容）、USB3 裝置需要中繼一個 USB2 的集線器。

==== 軟體重置
在某些情況下需要對 USB 裝置進行重置，但是又不適合透過開關機或者熱插拔的物理動作，就要考慮經由軟體命令來達到此一效果。

比較簡單的重置方法是利用 `usbutils` 套件提供的 `usbreset` 命令（如果散佈版套件未含入，可自行從原始碼中取出編譯），執行時加上裝置識別碼做為參數：
====
root# *usbreset _供應商識別碼:產品識別碼_*
====
或者使用 `usb_modeswitch` 命令：
====
root# *usb_modeswitch -R -v _供應商識別碼_ -p _產品識別碼_*
====

也可以嘗試藉由寫入假擬檔案系統的方式，透過開關不同的硬體層級來達成：
====
# 透過控制器 +
root# *echo -n _0000:插槽編號_ > /sys/bus/pci/drivers/ehci\_hcd/unbind* +
root# *echo -n __0000:插槽編號__ > /sys/bus/pci/drivers/ehci\_hcd/bind* +
# 透過模組 +
root# *echo __位置編號__ > /sys/bus/usb/drivers/usb/unbind* +
root# *echo __位置編號__ > /sys/bus/usb/drivers/usb/bind* +
# 透過集線器 +
root# *echo _位置編號_ > /sys/bus/usb/drivers/hub/unbind* +
root# *echo _位置編號_ > /sys/bus/usb/drivers/hub/bind* +
# 透過裝置 +
root# *echo 0 > /sys/bus/usb/devices/_位置編號_/authorized* +
root# *echo 1 > /sys/bus/usb/devices/_位置編號_/authorized*
====

==== 測試應用
使用者空間的 USB 功能呼叫是由 `libusb` 函式庫負責，但是版本 0.x 與 1.x 並不相容，因此安裝與使用應用軟體時必須注意。
如果想使用 Python 語言編寫相關程式，則需要匯入 `pyusb` 模組。

`dmesg` 與 `journalctl` 的輸出中，也會留下 USB 裝置於系統運行時留下的記錄。
過往的記錄則會儲存於 `/var/log/messages*` 或是 `/var/log/syslog` 檔案之中。
套件 `usbmon` 可以用來嗅探 USB 裝置的資料流。

因為 USB 有一統裝置介面的趨勢，許多特殊的應用也針對它而開發出來。
例如，原本附屬於遠端桌面軟體的 USB 裝置網路導向功能，如今也有單獨的商業軟體可以使用。

=== I^2^C
*I^2^C*(積體匯流排電路) 是一種雙線、慢速的序列匯流排，和其衍生的 *SMBus*(系統管理匯流排) 均常用於輕量裝置與系統間的通訊。
常見的內核模組像是 `i2c-i801`, `at24` 等等，內核會將其映射為 `/dev/i2c-0` 、 `/dev/i2c-1` 類型的裝置。

`i2c-tools` 套件中的工具是用來讀寫暫存器的值，例如想要偵測此類裝置是否存在，
就可以利用其中的 `i2cdetect -l` 指令或是 `lm_sensors` 套件中的 `sensors-detect` 命令。
而套件 `i2c-tools-perl` 中的 `decode-dimms` 命令，則是藉由 I^2^C 的介面來讀取記憶體的組態資料。

