== 系統裝置
直接內嵌於主機板上的裝置，通常稱之為系統裝置或內嵌裝置，一般是以整顆晶片、部分晶片或是韌體模擬的形式出現。

=== CPU
*CPU*(中央處理器) 無疑是整個電腦系統中最重要的元件。
今日的 CPU 早已不是單純的處理單元，尤其在嵌入式的 *SoC*(單晶片系統) 之內，涵括了浮點運算、繪圖處理的功能，
加入了記憶體、匯流排介面等模塊，甚至還封裝了多重的處理器核心。

==== 基本資訊
基本的命令是 `lscpu` ，它會提取 `/proc/cpuinfo` 中的資訊來顯示，其中比較特別的項目說明如下：

[square]
* Stepping: 製造步進等級，代表相同規格下對於電路或製程的修改版本，通常以 [字母][數字] 的組合表示，例如 A0, B2, C1,...。
* BogoMIPS: 相對的運算速率，這是內核對於 CPU 效能的不嚴謹指標，但不會受到記憶體的影響。
* Virtualization: 支援虛擬化（KVM 加速）的 CPU 功能，Intel 的規格稱為 VT-X，而 AMD 則以 AMD-V 表示。
* Flags: 具備的功能旗標。
** msr: 可以藉由 `msr-tools` 套件中的 `rdmsr` 命令來讀取 CPU 的 MSR 資料。
** smep, smap: Intel 產品具備的「Intel OS Guard」功能，可有效防止惡意程式奪取核心權限。
* Vulnerability: 已知安全漏洞的對策。
** Mitigation: 由軟體（通常是內核）提供的緩解方式。
** Microcode: 由 CPU 廠商提供給系統韌體供應商，做為公版的不可變部分，用以將機器語言碼轉為更低階的真實 CPU 指令。

`dmidecode -t processor` 指令的輸出中，也有許多由系統韌體所認知的 CPU 相關資訊。

==== 溫度
想要取得 CPU 的溫度以及風扇轉速，可以利用 `lm_sensors` 套件中的 `sensors-detect` 與 `sensors` 命令。
溫度的數值來自 `/sys/class/thermal/thermal_zone?/temp` ，單位為千分之一攝氏度，
也可以藉由圖形介面的 `psensors` 或 `xsensors` 軟體獲得。

==== 頻率
想要知道系統內個別 CPU 目前的工作頻率，可以利用 `lscpu` 命令的 `-e` 選項，
實際上則是讀取 `/sys/devices/system/cpu/cpu?/cpufreq/scaling_cur_freq` 的值。
另外 `kernel-tools` 套件中的工具程式 `cpupower` 也可以顯示 CPU 頻率，而變動的調頻結果則由 `turbostat` 命令顯示。

內核中負責 CPU 調頻的次系統，記載於 `/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver` 檔案，
利用第三方套件 `cpufrequtils` 的 `cpufreq-info` 命令，也能看到相關資訊，
內容一般會是 `acpi-cpufreq` ，或是支援較新規格的 `intel_pstate` 。
如果開機過程中斷或是偵測不到外接裝置，可以試試加入內核參數 `intel_pstate=disable` 以改回傳統的 `acpi-cpufreq` 模式。

=== 晶片裝置
晶片製程的演進: MOSFET, FinFET, FD-SOI, CFETS。

==== RTC
*RTC*(實時時鐘) 通常共存於儲存系統韌體使用者設定值的晶片中，並從中讀寫日期與時間的資料。
依據主機板的不同實作，也有可能使用獨立晶片或是嵌入到其他晶片之中。
關機時 RTC 仍在運作，維持系統時鐘與 CMOS 資料。
系統時鐘如果不準，可能是晶片過熱所導致。
如果是電池失效，也可能會造成時間不準或經常重置，甚至無法開機或是軟體運行時驗證相關的動作失敗。

==== EC
*EC*(嵌入控制器) 普遍存在於筆記型電腦中，用以統合周邊設備。
它有自己的韌體，常常與系統韌體連動更新。
關機狀態下，EC 用來偵測電源按鍵以通知系統開啟電源。
EC 於部分系統還負責鍵盤控制與風扇，與南橋之間是以 LPC 匯流排相連。

==== TPM
*TPM*(信賴平臺模組) 是安全密碼的處理裝置。
由專用晶片所提供的 TPM 功能稱為 dTPM(discrete TPM)，而由系統韌體所模擬提供的則為 fTPM(firmware TPM)，不論何者通常都可以透過韌體設定啟用或停用。
新的版本 2.0 是安裝 Windows 作業系統時所要求的配備，並且僅適用於 UEFI 開機環境。

內核偵測到 TPM 之後，就會載入 `tpm` 驅動模組，並且產生 `/dev/tpm0` 與 `/dev/tpmrm0` 裝置。
測試時可以使用套件 `tpm2-tools` 中的工具程式：
====
root# *tpm2 getrandom --hex _8_* +
32eefe49546a1a64root#
====
範例指令會產生 8 位元組的亂數，而這些程式也會被其他的加/解密應用軟體（例如 `clevis` ）所利用。

==== RAM
記憶體所使用晶片顆粒的等級，由高到低可分為：
Major(原廠)、eTT(有效測試)、uTT(未測試)，之下則稱為 Downgrade(次級品)。

基礎命令 `free` 命令整理了 `/proc/meminfo` 中的資訊：
====
user$ *free -h* +
               total        used        free      shared  buff/cache   available +
Mem:            31Gi       2.4Gi        26Gi       660Mi       2.2Gi        27Gi +
Swap:          4.0Gi          0B       4.0Gi
====
其中最常注意的項目，應該是位於 Mem: 列 total 欄的記憶體總量，以及 free 欄的未使用記憶體總量。
如果要看個別軟體行程的記憶體用量，則需要由 `top` 命令提供的文字全螢幕動態畫面來提供。

另外非官方套件 `devmem2` 提供讀寫記憶體位址的命令。
由於主機板上許多晶片的暫存器，都有對映到系統記憶體的區塊，因此依照規格書就可以查到相應的位址，但新版的內核已預設關閉此一讀取 `/dev/mem` 的功能。

有時候增加系統記憶體反而造成無法開機，也許是 BIOS 開機模式對特定系統的記憶體分配不正確，
或是與 32 位元作業系統分配給顯示的後段記憶體有關，可以嘗試用內核參數 `mem=` 來限制記憶體容量。

=== 匯流排
**匯流排**(bus) 是指主機板上的一組線路，用於連接多個晶片或埠口。
不同規格的匯流排定義了不同的線路數量、傳輸時脈與訊號模式，適應傳輸資料對於不同流量、距離以及容錯率的要求。

==== PCI
*PCI*(外部連結標準) 是電腦系統中，用來連結主機板與外部裝置的主要匯流排類型。
外部裝置包括同樣位於主機板上的內嵌裝置，以及以插槽介面外接的擴充裝置。
PCI 取代了許多舊式的匯流排，而目前最通用的類型則為高速進階版的 *PCIe*(PCI express) 。

可用 `lspci` 命令列出系統中所有 PCI 裝置的資訊：
====
user$ *lspci* +
00:00.0 Host bridge: ...... +
00:02.0 VGA compatible controller: ...... +
00:14.0 USB controller: ...... +
00:16.0 Communication controller: ...... +
00:16.3 Serial controller: ...... +
00:19.0 Ethernet controller: ...... +
00:1b.0 Audio device: ...... +
00:1f.0 ISA bridge: ...... +
00:1f.2 SATA controller: ...... +
00:1f.3 SMBus: ...... +
02:00.0 PCI bridge: ...... +
====
輸出資料的第一欄是插槽編號，由冒號分隔的匯流排編號與裝置編號組成。
第二欄冒號之前的資料表示裝置所屬的類型，之後則是裝置的名稱（已省略）。
`lspci` 命令加上選項 `-n` ，會顯示代表裝置硬體識別號(PCI ID) 的供應商代碼與裝置代碼，這也是軟體從識別號列表中找出裝置名稱的依據。
識別號列表是名為 `pci.ids` 的文字檔案，可以透過 `update-pciids` 命令從內建的網址隨時更新到本機端。
如果想要顯示特定裝置的最詳細資訊，可以參考指令範例：
====
user$ *lspci -s _00:19.0_ -nnvvxxx*
====
NOTE: 以系統管理者身分執行 `lspci` 命令可以獲得更多資訊。

`setpci` 命令則是用來設定 PCI 裝置中，特殊暫存器的值。
例如 `setpci --dumpregs` 指令可以列出可存取的裝置暫存器，用來顯示及設定特定裝置的特定暫存器內容：
====
root# *setpci -s _02:00.0_ _STATUS_* +
0010 +
root# *setpci -s _00:02.0_ _F4.B=55_* +
root# *setpci -s _00:14.0_ _7C.W=0108_*
====
三條範例的原本用途分別為：顯示狀態、設定亮度、設定喚醒，實際使用時會依裝置型號而有差異。

==== USB
*USB*(泛用序列匯流排) 是目前最流行的接頭型式，隨著規格不斷地擴充與演進，大有一統個人電腦周邊設備介面的趨勢。
主要規格世代與相應的驅動程式（內核模組），以及介面速度理論值如下：

[square]
* USB 1.0: ohci 1.5Mbps
* USB 1.1: ohci 12Mbps
* USB 2.0: ehci 480Mbps
* USB 3.0: xhci 5000Mbps

==== HID
USB HID 介面的狀態有可能會受鍵盤的鎖定燈號影響：
====
root# *usbhid-dump -m VID:PID -es*
====

==== VCP
**虛擬序列埠**(VCP) 介面的 /dev/ttyUSB* 無法以 setserial 設定，而是以 stty 命令：
====
root# *stty -a -F /dev/ttyUSB0* \#顯示目前設定值 +
root# *stty -F /dev/ttyUSB0 19200 -parenb cs8 -cstopb -ixon* +
root# *cat < /dev/ttyUSB0 |xxd -g 1*
====
IMPORTANT: 最好先停用或移除 ModemManager 套件以免 VCP 受到影響。

如果想要將十六進位的字元直接寫入裝置中，可參考下面的例子：
====
root# *echo -en _'\x01\x01\xCA\x60\x00\x03\xA9'_ > /dev/_ttyUSB0_*
====
或是借助 xxd -r -p 命令，先進行轉換再輸出：
====
root# *echo -n '_01 01 CA 60 00 03 A9_' | xxd -r -p > /dev/_ttyUSB0_*
====

==== I^2^C
*I^2^C*(積體匯流排電路) 是一種慢速的序列匯流排，內核會將其視為 `/dev/i2c-0` 、 `/dev/i2c-1` 等裝置。
常見於嵌入式設備中，可以用 `i2c-tools` 套件中的工具來讀寫暫存器值。

==== SPI
*SPI*(序列周邊介面) 由四條線路組成的簡單傳輸匯流排，與 I^2^C 均常見於嵌入式系統。

=== 輸入輸出介面
用來連接外部輸入或輸出裝置的埠口或插槽。

==== PS/2

==== Super I/O
主機板上的 *Super I/O*(超級輸入輸出) 晶片，用來做為低頻寬設備的介面，以往需要透過 ISA 匯流排與 CPU 連接，目前則透過南橋晶片上的 LPC 匯流排。
常用來偵測溫度，也同時會提供 *Watchdog Timer*(看門狗計時器) 的功能。
`coreboot-utils` 套件中有 `superiotool` 程式，可以偵測並提供暫存器內容。
如果在系統啟動時期被 ACPI 占住資源，可以利用內核參數 `acpi_enforce_resources=lax` 來排除問題。

==== GPIO
內核於系統初始化時，如果偵測到 *GPIO*(通用型輸入輸出) 就會產生 `/dev/gpiochip0` 的對應裝置，裝置的資訊則可以從 `/sys/kernel/debug/gpio/` 中得到。

利用 `/sys/class/gpio/` 來初始化與使用 GPIO 的範例：
====
root# *echo _5_ > /sys/class/gpio/export* +
root# *echo in > /sys/class/gpio/_gpio5_/direction* +
root# *echo out > /sys/class/gpio/_gpio5_/direction* +
root# *echo 1 > /sys/class/gpio/_gpio5_/value* +
root# *echo _5_ > /sys/class/gpio/unexport*
====
安裝 `libgpiod-utils` 套件（或者名為 `gpiod` ）後，就可以使用其中的 `gpioinfo`, `gpiodetect`, `gpioget`, `gpioset` 等工具程式。

==== SDIO
*SD*(安全數位卡) 是用來取代 *MMC*(多媒體記憶卡) 的標準，而以 SD 介面來連接外部裝置的應用稱之為 *SDIO* 。
未來 SDIO 可能會取代 GPIO 的 SPI 傳輸模式介面。

==== SATA
當舊式磁碟裝置所用的 *ATA*(先進技術附件) 介面，已無法跟上整體電腦系統的處理速度時，*SATA*(序列 ATA) 就被提出做為取代的介面。
Linux 將其視為擴充定義後的 *SCSI*(小型電腦系統介面) 來驅動，對應的裝置目錄則由 `/dev/hd*` 改為 `/dev/sd*` 。
初期由儲存晶片組成的模組(disk on module) 稱為 SATA DOM，但部分插槽需要外接電源因而較少使用，後來又衍生出 SATA Slim 的形式。

低階格式化程式通常是指硬體廠商提供的私有工具軟體，用來更新、修復或重設控制器上的韌體資料。
有一些通用指令： `smartctl -i /dev/sda` 或 `hdparm -i /dev/sda` 可以獲得包括韌體版本的資訊。
如果無法取得專屬工具，就衹能試試 `hdparm`, `setpci`, `sdparm` 等程式，或是 `sg3_utils` 套件中的工具。

==== M.2
*M.2* 舊名為 *NGFF*(次世代形制)，並非是一種匯流排或線路介面，而是新定義的主機板擴充槽規格。
由於規格定義未限定資料傳輸的協定，因此可以相容 PCIe, miniPCIe, SATA, USB3 等匯流排的訊號，並利用不同的防呆腳位來區分。
常見的模組型式有 B-Key, E-Key, M-Key，其防呆腳位大略依序為靠左、靠中、靠右。
存儲裝置通常使用 B-Key 或 M-Key 型式，而無線網路裝置則較常使用 M-Key 型式。

