== 命令列模式
在電腦還沒有圖形介面的時候，使用者是靠著在終端機前面輸入命令來操作系統。
時至今日，一般使用者已經很少機會需要直接輸入命令，而是依賴滑鼠來傳達想要的動作。
對於測試人員而言，了解命令列模式的操作仍然是必要的，
不僅因為在測試過程中無法避免，而且透過命令列才能真正地深入系統。

=== 終端機
傳統的 UNIX 系統，是以個別的**主控臺**(console)來提供多人使用。
每一組主控臺的基本配備，包括了終端機螢幕與鍵盤。
而在今日以個人電腦為主的介面中，便轉化為以下兩種操作模式。

Linux 系統的命令列模式，可以藉由在圖形介面中開啟**終端機模擬器**(terminal emulator)應用軟體後進入。
它就像是一臺傳統的終端機螢幕，但是以一個軟體視窗的形式出現在桌面上。
終端機模擬軟體衹負責搭建單色的背景舞臺，實際與使用者互動的軟體則是**命令殼**(shell)。

大多數的 Linux 系統會額外支援**虛擬終端機**(VT)，透過按下組合鍵 kbd:[Ctrl+Alt+F1] 至 kbd:[Ctrl+Alt+F6] 之一的方式進入。
每個虛擬終端機都需要分別輸入賬號與密碼之後，才會出現命令殼的提示符號。
如同將現代的電腦螢幕，轉變為多臺合一的復古形式終端機。
實際的終端機數目依照各系統設定而有不同，逐項組合鍵按一輪之後會發現，圖形顯示的桌面也屬於其中一員。
在某些無法進入桌面的情況下，可以做為一個重要的救援手段。

=== 命令殼
使用者進入命令列模式，其實就是向一個執行中的命令殼程式輸入指令。
當我們提到命令殼的時候，所指的含義有可能是以下三種之一：

[square]
* 一種命令稿程式語言
* 這種程式語言的實作程式，可以做為**命令稿**(shell script)的**解譯器**(interpreter)
* 單獨執行這個程式所進入的互動式命令介面

`bash` 是 Linux 系統最常做為預設命令殼的軟體選項，在命令列模式中以互動的方式接受使用者的輸入。
所有合乎 BASH 程式語言規範的指令，都可以做為輸入 BASH 命令殼的命令。
輸入 `bash` 命令會疊加執行命令殼程式，並且進入新的**作業階段**(session)；
如果此時再輸入 `exit` 命令，則會退出目前的命令殼，回到前一個作業階段。

==== 提示符號
命令殼執行時會出現**提示符號**(prompt)，而閃爍的游標表示等待著輸入命令。
通常也用來提供目前的賬號、主機以及工作目錄等資訊。
一般使用者的預設提示符號會以**錢號**($)做為結尾，而以管理者的身分進入系統時，提示符號的末端字元則預設為**井號**(#)。
依照軟體所設計使用的介面不同（參考〈軟體概念：軟體分類〉），執行期間會暫停命令殼的運作，
除非使用者按下組合鍵 kbd:[Ctrl+C]，表示向執行中的命令發送中斷訊號。
大多數的軟體在收到這個訊號之後，會立即停止運行，而由命令殼顯示已經**砍除**(kill)該命令的訊息。
當命令不論是正常還是異常結束之後，才會重新出現提示符號，代表準備好去接受新的命令。

如果使用者不想等待命令完全結束，就想要馬上能夠執行下一條命令，
可以在命令末端額外打上一個**和號**(&)再按 kbd:[Enter] 輸入，此時命令殼會**叉生**(fork)一條**行程**(process)，
並在其中執行這條命令，也就是手動指定多工，將命令丟到背景中執行。
當然也可以開啟一個新的終端機，接著在隨行的命令殼中下達命令。

==== 環境變數
命令殼的環境變數，其實就是命令殼程式語言中的變數。
習慣上由大寫字母組成，依需要常會混合數字或底線符號。
賦值時是以**等號**(=)來將右側的值指定給左側的變數，必須注意等號的兩側不能有空格。
取值時必須前置一個錢號，如果要避免與後方的字元混淆，可以將變數名稱夾在大括號之間。
--
　　user$ *unset _MYVAR_* +
　　user$ *_MYVAR="My Value"_* +
　　user$ *echo _${MYVAR}s_* +
　　My Values +
--

做為一種命令稿程式語言，有一些變數在語言本身就有定義。
另外有一些基本變數，在命令殼軟體讀入初始化檔案時，就被賦予適當的預設值。
命令殼本身的行為會受到這些內建變數的影響，部分命令也會參考這些變數目前的設定值。
使用者自己編寫的命令稿，當然也可以引用內建變數，或是創建私有的變數。

賦值敘述不需要前導的命令字組，就可以設定命令殼的**本地變數**(local variable)。
如果希望這個變數除了在目前的命令殼中有效，還能被由此叉生出來的作業階段所存取，
就需要使用前導的 `export` 命令，表示匯出到可供繼承的環境中。
--
　　user$ *_VAR="Old Value"_* +
　　user$ *bash* +
　　user$ *echo _$VAR_* +
　　+
　　user$ *exit* +
　　user$ *export _VAR_*
　　user$ *bash* +
　　user$ *echo _$VAR_* +
　　Old Value +
　　user$ *export _VAR="New Value"_* +
　　user$ *exit* +
　　user$ *echo _$VAR_* +
　　Old Value
--

==== 前置處理
使用者在提示符號之後輸入的一串文字，先要經過**前置處理**(pre-processing)，才會被視為命令殼指令而進一步解析。
也就是說，原始的命令字串要先經過以下的處理程序，才會真正確認指定的命令，以及傳遞給它的資料數目與內容：

[square]
. 辨識備註與賦值
. 分割多重命令
. 單一或複合命令
. 命令代換為輸出
. 變數代換為值
. 路徑名稱擴展
. 分割字組

由以上敘述可知，命令殼會利用一些不是字母或數字的**中繼字元**(meta-character)，做為前置處理的重要依據。
如果的確要使用中繼字元的**實字**(literal)意義，例如出現在檔案或目錄名稱中，還可以利用一些特殊字元來進行遮蔽：

[square]
* 雙引號(")：前後夾住的一對雙引號可以遮蔽除了本身、錢號、反斜線、反引號、驚歎號以外的中繼字元。
* 單引號(')：前後夾住的一對單引號可以遮蔽除了本身以外的中繼字元。
* 反斜線(\)：前置的反斜線做為逸出字元可以遮蔽包括本身的所有中繼字元。

前置處理過後得到的單一命令中，會以第一個**字組**(token)做為命令的名稱，後續的字組則做為命令的**引數**(argument)。
如果要再細分，引數還可以分為**選項**(option)與**參數**(parameter)。
選項代表可選、可變的屬性，習慣上會以兩條**短橫線**(dash)開頭，不過仍然存在舊式的命令，以一條（甚至沒有）短橫線做為選項的開頭。
參數則代表命令將要處理的主體，通常是檔案名稱或是某種目標名稱，但是也不排除要輸入的名稱恰好就是以短橫線啟始。

=== 命令執行
命令殼能夠執行的命令包括以下幾類：

[square]
* 內部命令：命令殼軟體做為一種程式語言，本身就具備的程式指令
* 擴充命令：藉助內建指令所定義出來的**別名**(alias)或**函式**(function)
* 外部命令：可供執行的檔案名稱

==== 內部命令
接收到單純名稱的命令字組後，命令殼首先會在**內建**(built-in)的功能表中查詢，
如果剛好有符合的已實作命令，就會由當前的命令殼程式直接處理。
執行大多數的內部命令時，會維持在目前的命令殼作業階段，亦即具有相同的環境變數組成。
--
　　user$ *echo _"Hello, World!"_* +
　　Hello, World!
--

==== 擴充命令
藉由 `alias` 或是 `function` 指令， `bash` 程式語言支援創建新的命令，做為內部命令的擴充。
--
　　user$ *alias _hello-world='echo "Hello, World!"'_* +
　　user$ *_hello-world_* +
　　Hello, World! +
　　user$ *unalias _hello-world_* +
　　bash: hello-world：指令找不到
--
或是藉助程式語言內部的函式宣告，創建一個自訂的函式名稱。
--
　　user$ *function _\_hello-world { echo "Hello, World!"; }_* +
　　user$ *_\_hello-world_* +
　　Hello, World! +
　　user$ *unset -f _\_hello-world_* +
　　bash: \_hello-world：指令找不到
--
擴充命令衹在創建時的同一個作業階段中有效，如果希望在每個命令殼中都能使用，
可以將其寫入個人的命令殼初始化檔案，甚至是整個系統的命令殼初始化檔案中。

==== 外部命令
如果指令敘述的第一個字組包含了斜線符號(/)，表示這是一個直接執行檔案的命令。
命令殼不會考慮它是否是內部或擴充命令，而會依照絕對或相對路徑的規則（參見〈檔案與目錄：路徑名稱〉），嘗試去執行指定的檔案。
能夠直接執行的檔案可以分為兩類，經過編譯的二進制檔案或是文字形式的指令稿，同時必須具備可執行的檔案屬性（參見〈檔案與目錄：檔案屬性〉）：
--
　　user$ *ls -l _hello-world.sh_* +
　　-rw-r--r-- 1 user user 10  2月 18 13:09 hello-world.sh +
　　user$ *./_hello-world.sh_* +
　　bash: ./hello-world.sh：拒絕不符權限的操作 +
　　user$ *chmod +x _hello-world.sh_* +
　　user$ *ls -l _hello-world.sh_* +
　　-rwxr-xr-x 1 user user 10  2月 18 13:10 hello-world.sh +
　　user$ *./_hello-world.sh_* +
　　Hello, World!
--
NOTE: vfat 檔案系統不支援檔案的可執行屬性，因此無法以 *chmod* 命令變更。
NOTE: 當然也可以呼叫解譯器程式，將指令稿檔案當做參數來執行。

如果命令字組不包含斜線符號，且在內部命令與擴充命令的列表中，搜尋不到使用者輸入的命令，
命令殼就會將其視為外部命令，並改以搜尋外部命令的機制來處理。
外部命令的搜尋是由 `PATH` 環境變數所控制，其中包含了一連串的目錄路徑，彼此之間以冒號分隔。
Linux 系統預設的 `PATH` 變數內容，基於安全的原因並不包括當前的目錄，因此無法直接執行工作目錄中的程式。
若是讀者想要暫時體驗一下單獨直接以名稱呼叫程式的方法，可以參考以下的命令：
--
　　user$ *ls -l _hello-world.sh_* +
　　-rwxr-xr-x 1 user user 10  2月 18 13:11 hello-world.sh +
　　user$ *_hello-world.sh_* +
　　bash: hello-world.sh：指令找不到 +
　　user$ *PATH=$PATH:.* +
　　user$ *echo $PATH* +
　　/home/user/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/usr/bin:. +
　　user$ *_hello-world.sh_* +
　　Hello, World!
--
NOTE: 有些內部命令同時還存在外部命令的版本（例如： `/usr/bin/echo` ），雖然功能通常相同，
而且除非明確指定否則不會被執行，但是某些情況下仍然可能有用（或誤用）。


