== 命令列模式
在電腦還沒有圖形介面的時候，使用者是靠著在終端機前面輸入命令來操作系統。
時至今日，一般使用者已經很少機會需要直接輸入命令，而是依賴滑鼠來傳達想要的動作。
對於測試人員而言，了解命令列模式的操作仍然是必要的，
不僅因為在測試過程中無法避免，而且透過命令列才能真正地深入系統。

=== 終端機
傳統的 UNIX 系統，是以多個分開的主控臺來提供多人使用。
每一組主控臺的基本配備，包括了終端機螢幕與鍵盤。
而在今日以個人電腦為主的介面中，便轉化為以下兩種操作模式。

Linux 系統的命令列模式，可以藉由在圖形介面中開啟**終端機仿真器**(terminal emulator) 應用軟體後進入。
它就像是一臺傳統的終端機螢幕，但是以一個軟體視窗的形式出現在桌面上。
終端機模擬軟體衹負責搭建貌似終端機畫面的背景舞臺，實際與使用者互動的軟體則是**命令殼**(shell)。

每個虛擬終端機都需要分別輸入賬號與密碼之後，才會出現命令殼的提示符號，如同將現代的電腦螢幕，轉變為多臺合一的復古形式終端機。
實際的終端機數目依照各系統設定而有不同，逐項組合鍵按一輪之後會發現，圖形顯示的桌面也屬於其中一員。
虛擬終端機即使還未登入前，也有可能支援重新開機的組合鍵 kbd:[Ctrl - Alt - Del]。
在某些無法進入桌面的情況下，可以做為一個重要的救援手段。

=== 命令殼
當我們提到命令殼的時候，所指的對象有可能是以下三種之一：

[square]
* 一種指令稿程式語言，據此寫出的程式稱為**命令稿**(shell script)。
* 這種程式語言的實作程式，可以做為命令稿的**解譯器**(interpreter)。
* 單純執行這個程式所進入的互動式(interactive) 命令介面。

使用者進入命令列模式，就是在上述第三項的情境中，對一個執行中的命令殼程式輸入指令。
命令殼在此是以中介者的身分，扮演使用者與系統之間的溝通角色。

`bash` 是 Linux 系統最常做為預設命令殼的軟體選擇，所有合乎 BASH 程式語言規範的指令，都可以做為輸入 BASH 命令殼的命令。
互動式程式開發環境又稱為**REPL**(讀取—求值—輸出循環)，而能夠方便地存取系統資源、執行外部程式，才是命令殼與其他互動式介面區別之處。
由於傳統因素或是在特定情境下具有優點，其他的命令殼程式也有少數的愛用者。

在命令列模式中應該學會的第一個命令是 `man`(manual)，會將後方字串視為命令名稱，而把附帶的使用手冊顯示出來。
重複輸入 `bash` 命令會疊加執行命令殼程式，並且進入新的**作業階段**(session)，
不僅具備了新的命令殼環境，也被所有其中**叉生**(fork) 的**行程**(process) 所依附。
如果此時再輸入 `exit` 命令，則會退出目前的命令殼，回到前一個作業階段。

==== 提示符號
命令殼執行時會出現**提示符號**(prompt sign)，而閃爍的游標表示等待著輸入命令。
通常也用來提供目前的賬號、主機以及工作目錄等資訊。
一般使用者的預設提示符號會以**錢號**($) 做為結尾符號，而以超級使用者的身分進入系統時，提示符號的末端字元則預設為**井號**(#)。
藉由修改環境變數 `PS1` 的值，使用者可以自訂偏好的提示符號組成：
====
user$ *PS1='\[\e[43;30m\]\u@\w>\[\e[0m\] '* +
#user@~># ▊
====

提示符號狀態下支援一些有用的編輯鍵，例如：kbd:[Up] 或 kbd:[Down] 可以遍歷之前輸入過的指令；
先按 kbd:[Ctrl - R] 之後再輸入部分字串，會輪流顯示以此為首的過往指令；
而輸入起始字串後再按 kbd:[Tab]，則會自動補完命令的名稱；
甚至在事先適當設定的狀況下，還可以自動帶出後續選項、目錄或是檔案名稱。

依照軟體所設計使用的介面不同（參考〈軟體概念：軟體分類〉），執行期間會暫停命令殼的運作，
除非使用者按下組合鍵 kbd:[Ctrl - C]，表示向執行中的命令發送中斷訊號。
NOTE: 在命令列模式中，kbd:[Ctrl - C]/kbd:[Ctrl - V] 並無拷貝/貼上的功能，有些終端機則支援 kbd:[Ctrl - Shift - C]/kbd:[Ctrl - Shift - V] 的組合。
大多數的軟體在收到這個訊號之後，會立即停止運行，而由命令殼顯示已經**砍除**(kill) 該命令的訊息。
當命令不論是正常還是異常結束之後，才會重新出現提示符號，代表準備好去接受新的命令。
如果使用者不想等待命令完全結束，就希望能夠立即執行下一條命令，
也可以開啟一個新的終端機，接著在隨之而起的命令殼中下達命令。

==== 環境變數
命令殼的環境變數，其實就是命令殼程式語言中的變數。
習慣上由大寫字母組成，依需要常會混合數字或底線符號。
賦值時是以**等號**(=) 來將右側的值指定給左側的變數，必須注意等號的兩側不能有空格。
賦值敘述依據等號的分割操作優先於前置處理，因此會具備如同遮蔽字元的效果。

如果命令列中衹有賦值敘述，那麼就會在目前的命令殼作業階段中運行；
而當賦值敘述位於命令列最前端，後方再接著其他命令時，則會在新的作業階段中執行該賦值敘述。
取值時必須前置一個錢號，如果要避免與後方的字元混淆，可以將變數名稱夾在大括號之間。
====
user$ *unset _VAR_* +
user$ *_VAR="Old Value"_* +
user$ *_VAR="New Value"_ echo _$VAR_* +
Old Value +
user$ *_VAR="New Value"_ printenv _VAR_* +
New Value +
user$ *echo _${VAR}s_* +
Old Values +
====

做為一種命令稿程式語言，有一些變數在語言本身就有定義。
另外有一些基本變數，在命令殼軟體讀入初始化檔案時，就被賦予適當的預設值。
命令殼本身的行為會受到這些內建變數的影響，部分命令也會參考這些變數目前的設定值。
使用者自己編寫的命令稿，當然也可以引用內建變數，或是創建私有的變數。

賦值敘述不需要前導的命令字組，就可以設定命令殼的**局部變數**(local variable)。
如果希望這個變數除了在目前的命令殼中有效，還能被由此叉生出來的子行程所存取，
就需要使用前導的 `export` 命令，表示匯出到目前的環境以供繼承。
====
user$ *unset _VAR_* +
user$ *_VAR="Old Value"_* +
user$ *bash* +
user$ *echo _$VAR_* +
 +
user$ *exit* +
user$ *export _VAR_* +
user$ *bash* +
user$ *echo _$VAR_* +
Old Value +
user$ *export _VAR="New Value"_* +
user$ *exit* +
user$ *echo _$VAR_* +
Old Value
====
這也是單獨執行 `set` 與 `env` 命令時，輸出變數範圍的差別。

==== 前置處理
使用者在提示符號之後輸入的一串文字，先要經過**前置處理**(pre-processing)，才會被視為命令殼指令而得到進一步的**剖析**(parsing)。
也就是說，原始的指令字串要先經過以下的處理程序，才會真正確認指定的命令，以及傳遞給它的資料數目與內容：

[square]
* 檢查備註與賦值：**井字號**(#) 後方的字串，將會視為備註；檢查首項字組是否為含有等號(=) 的賦值命令。
* 分割多重指令：利用分割符號 ;, &, ||, && 區分出多重指令的左右兩側。
* 輸出入管線重導：管線與重導符號 |, <, > 表示變更命令的輸入來源或輸出目標。
* 檢查複合命令：是否有跨越多列的區塊符號 \(...), \{ ... }、條件命令 if, case 或迴圈命令 for, while。
* 代換指令輸出：執行以代換指令符號 \`...\`, $() 所括住的指令。
* 變數代換為值：代換以 ${} 括住或簡化情況下以 $ 前置的變數值。
* 擴展路徑名稱：符號 ~, \*, ?, [], [!] 會進行檔案及目錄的名稱**萬用匹配**(globbing)。
* 擴展列表字組：展開 \{__字組一__,__字組二__} 或 \{__字組一__..__字組二__} 類型的列表。
* 分割字組：最後根據空格 kbd:[Space]、跳格 kbd:[Tab]、換列 kbd:[Return] 等字元來分割字組。

NOTE: 上述列表大致符合前置處理的先後順序。 	
	
由前置處理程序可知，命令殼會利用一些不是字母或數字的**中繼字元**(meta-character)，做為前置處理的重要依據。
如果想要使用中繼字元的**實字**(literal) 意義，例如出現在檔案或目錄名稱中，就需要利用一些特殊字元來進行遮蔽：

[square]
* 雙引號(")：前後夾住的一對雙引號可以遮蔽除了本身、錢號、反斜線、反引號、驚歎號以外的中繼字元。
* 單引號(')：前後夾住的一對單引號可以遮蔽除了本身以外的中繼字元。
* 反斜線(\)：前置的反斜線做為**逸出**(escape 或稱**轉義**) 字元可以遮蔽包括本身的所有中繼字元。

==== 引數
前置處理過後得到的單一指令中，會以第一個**字組**(token) 做為命令的名稱，後續的字組則做為命令的**引數**(argument)。
如果要再細分，引數還可以分為**選項**(option)、**選項值**(option value) 與**參數**(parameter)；
或是將前兩項合稱為**選用參數**(optional parameter)，而將後項稱為**位置參數**(positional parameter)。
選項代表可選、可變的屬性，習慣上會以兩條**短橫線**(dash) 開頭，不過仍然存在舊式的命令，接受以一條短橫線做為選項的開頭。
如果單純的開關或切換無法滿足選項的功能，就需要在後方緊接一個選項值做為補充設定。
不以短橫線開頭的有限選項，代表這個命令可能是許多次命令(sub-command) 的集合。
參數則代表命令將要處理的主體，通常是檔案名稱或是某種目標名稱，但是也不排除要輸入的名稱恰好就是以短橫線啟始。
一般而言，選項或參數都可能是非必要的，差別在於選項的選擇範圍是有限的，而參數的可選值卻是無限多的。

==== 輸入輸出
命令列模式中命令，是以**標準輸入**(stdin) 做為預設的**資料流**(data stream)輸入來源，對應到終端機裝置的鍵盤。
命令 `read` 預設會將標準輸入的值或列表，儲存在做為參數的變數名稱或列表之中。
以鍵盤模擬檔案輸入時，組合鍵 kbd:[Ctrl - D] 則用來代表**檔案結尾**(EOF) 字元。

預設的輸出目標則是**標準輸出**(stdout)，對應到終端機裝置的畫面。
另外也有**標準錯誤**(stderr)，代表預設的錯誤訊息輸出目標，同樣對應到終端機裝置的畫面。
NOTE: 少數命令（例如 `ls` ）的輸出，在終端機環境與重導後的格式有些不同。

命令的輸入與輸出還可以透過管線(pipe) 或重導(redirection) 符號來操控。常用的形式包括：

[square]
* `|`: 管線符號左側指令的輸出，做為右側指令的輸入。
* `>`: 重導符號左側指令的輸出，做為右側檔案的內容。
* `<`: 重導符號右側檔案的內容，做為左側指令的輸入。
* `>>`: 重導符號左側指令的輸出，附加到右側檔案的內容。
* `<<`: 重導符號左側指令的輸入來自標準輸入，直到出現右側的字串。

另外 `&>`、`&>>` 與 `|&` 都表示將左側指令的輸出，同時附加上錯誤訊息再送出。
使用管線符號時需要注意，會隱含產生**子命令殼**(subshell) 來執行各段指令。
重導符號如果配合 `exec` 命令，還能夠固定重導當前行程的輸入或輸出。

將指令包括在成對的**反引號**(`) 或是相同功能的 $( 與 ) 之間，用來代換整個指令的輸出，可以做為其他命令的部分引數。
前者是傳統且相容性較高的寫法，而後者則具有支援巢狀使用的優點。

==== 退出狀態
每個命令結束時，都會返回一個隱含的數值，範圍是從 0 到 255 的整數，這個值稱為命令的**退出狀態**(exit status)。
其中數值 0 表示正常結束，其他值表示不正常結束。
某些非 0 值具有特殊的含意，但實際各值所代表的狀況，仍然會依軟體而不同。
內建命令 `true` 和 `false` 分別會返回 0 和 1 的退出狀態，而內建命令 `test` 則是最常用於條件敘述中的判斷命令
（或是它的同義命令 `[` 且最後一個參數必須是 `]` ）。
利用內建變數 `?` ，可以存取上一條指令執行的退出狀態：
====
user$ *false* +
user$ *[ "$?" -ne 0 ]* +
user$ *echo $?* +
0
====
命令執行開始至結束期間，經由標準輸出與標準錯誤所印出到畫面的資料，與這裡提到的退出狀態並不相同，而且兩者之間沒有必然的關連。
通常衹要命令執行沒有出錯，就不會送出任何訊息到標準錯誤，代表著「沒有消息就是好消息」的理念；
不過是否成功達到要求，還要從退出狀態來辨識。

WARNING: 在許多其他的程式語言中，退出狀態也會稱為**傳回值**(return value)。
當它為 0 時通常意指**假**(false) 值，非 0 才代表**真**(true) 值。

=== 命令執行
命令殼能夠執行的命令包括以下幾類：

[square]
* 內建命令：命令殼軟體做為一種程式語言，本身就具備的程式指令。
* 擴充命令：藉助既有指令所定義出來的**別名**(alias) 或**函式**(function)。
* 外部命令：可供執行的檔案名稱。

使用內建命令 `type` 可以顯示做為參數的名稱字串屬於哪一種命令。

==== 內建命令
接收到單純名稱的命令字組後，命令殼首先會在**內建**(built-in) 與**關鍵字**(keyword) 的列表中查詢，
如果剛好有符合的已實作命令，就會由當前的命令殼程式直接處理。
執行大多數的內建命令時，會維持在目前的命令殼作業階段，亦即具有相同的環境變數組成。
====
user$ *echo _"Hello, World!"_* +
Hello, World!
====
如果存在同名的擴充或外部命令而產生執行實體的疑慮時，可以將命令名稱做為前置命令 `builtin` 的參數，或者是加上前置逸出字元(\) 來限縮執行命令的種類。

==== 擴充命令
藉由 `alias` 命令， `bash` 程式語言支援創建新的命令，做為內建命令的擴充：
====
user$ *alias _hello-world='echo "Hello, World!"'_* +
user$ *_hello-world_* +
Hello, World! +
user$ *unalias _hello-world_* +
user$ *_hello-world_* +
bash: hello-world：指令找不到
====
不過擴充別名不會由子命令殼繼承，因此可以藉助程式語言內建的 `function` 函式宣告，創建一個自訂的函式命令：
====
user$ *function _hello-world { echo "Hello, World!"; }_* +
user$ *_hello-world_* +
Hello, World! +
user$ *unset -f _hello-world_* +
user$ *_hello-world_* +
bash: hello-world：指令找不到
====
擴充命令是由創建它的命令殼解譯後執行，因此衹在創建時的作業階段中有效。
如果希望在每個開啟的命令殼中都能使用，必須將其寫入個人的命令殼初始化檔案，甚至是整個系統的命令殼初始化檔案中。

==== 外部命令
如果指令敘述的第一個字組包含了**斜線**(/) 符號，表示這是一個直接執行檔案的命令。
命令殼不會考慮它是否是內建或擴充命令，而會依照絕對或相對路徑的規則（參見〈檔案與目錄：路徑名稱〉），嘗試去執行指定的檔案。
能夠直接執行的檔案可以分為兩類，經過編譯的二進制檔案或是文字形式的指令稿，同時必須具備可執行的檔案屬性（參見〈檔案與目錄：檔案屬性〉）：
====
user$ *ls -l _hello-world.sh_* +
-rw-r--r-- 1 user user 10  2月 18 13:09 hello-world.sh +
user$ *bash _hello-world.sh_* +
Hello, World! +
user$ *_./hello-world.sh_* +
bash: ./hello-world.sh：拒絕不符權限的操作 +
user$ *chmod +x _hello-world.sh_* +
user$ *ls -l _hello-world.sh_* +
-rwxr-xr-x 1 user user 10  2月 18 13:10 hello-world.sh +
user$ *_./hello-world.sh_* +
Hello, World!
====
NOTE: vfat 檔案系統不支援檔案的可執行屬性，因此無法以 *chmod* 命令變更。

如果命令字組不包含斜線符號，且在內建命令與擴充命令的列表中，搜尋不到使用者輸入的命令，
命令殼就會將其視為外部命令，並改以搜尋外部命令的機制來處理。
外部命令的搜尋是由 `PATH` 環境變數所控制，其中包含了一連串的目錄路徑，彼此之間以冒號分隔。
命令殼會執行在路徑串列中，最先找到符合名稱的程式。
使用擴充命令 `which` 可以顯示參數名稱做為外部命令時，實際上會執行的程式檔案路徑。

Linux 系統預設的 `PATH` 變數內容，基於安全的原因並不包括當前的目錄，因此無法直接執行工作目錄中的程式。
若是讀者想要暫時體驗一下單獨直接以名稱呼叫程式的方法，可以參考以下的命令：
====
user$ *ls -l _hello-world.sh_* +
-rwxr-xr-x 1 user user 10  2月 18 13:11 hello-world.sh +
user$ *_hello-world.sh_* +
bash: hello-world.sh：指令找不到 +
user$ *PATH=$PATH:.* +
user$ *echo $PATH* +
/home/user/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/usr/bin:. +
user$ *_hello-world.sh_* +
Hello, World!
====
WARNING: 有些內建命令同時還存在外部的版本（例如： `/usr/bin/echo` ），雖然功能通常相同，
而且除非明確指定否則不會被執行，但是某些情況下仍然可能有用（或誤用）。
NOTE: 嵌入式系統為了節省空間，會將命令殼（包括內建命令）以及常用的外部命令實作於單一的程式中，
依據鏈結的檔名來變換程式扮演的命令（著名的 `busybox` 工具）。

=== 複雜命令
大部分在命令列模式中輸入的指令，是由一個名稱字組搭配零至多個引數所形成的單純命令。
但是有些動作沒有辦法僅靠單純命令完成，需要利用以下幾種形式的複雜命令，而執行的過程往往受到其中命令的退出狀態所影響。

==== 包繞命令
如果一個命令的引數含有其他命令的名稱，而且作用就是要在原本命令的執行時期呼叫這個子命令，那麼就可以將其歸類為**包繞命令**(wrapper)。
子命令的執行通常會引發一個子行程，它的執行環境由原本命令所建構，而子命令的退出狀態則有可能會影響原本命令的流程走向。
除了之前介紹過的 `sudo` 之外，常用的包繞命令列舉如下：

[square]
* `env`: 設定指定的環境變數後執行子命令，用於舊式指令稿的首列程式呼叫。
* `eval`: 將子命令再次前置處理後執行，用於複雜的命令殼指令巨集代換。
* `exec`: 執行子命令並取代目前的命令殼行程。
* `source`: 將子命令稿的內容讀入，並在原命令殼中執行（單一句點為其內建別名）。
* `time`: 測量子命令執行花費的時間。
* `timeout`: 限制子命令執行花費的時間。
* `watch`: 持續顯示子命令周期執行的結果，用於監控子命令的輸出。
* `xargs`: 重複以標準輸入做為子命令的引數後執行，用於依序處理從管線輸入的資料。

==== 多重命令
命令列模式中的每一列指令，預設會按照換列符號的分隔而依次執行。
某些情況下想要多個命令寫在同一列中，可以利用分號(;) 將它們分開來。
如果一列敘述中使用了**和號**(&)，亦即通常是在指令末端額外打上一個和號再按 kbd:[Enter] 輸入，
此時命令殼會叉生一條子行程，並在其中執行和號之前的指令，亦即將指令丟到背景中多工執行。
這樣便與上節提到的**讀取執行**(sourcing) 有很大區別，不需等到前面指令執行結束，就會立即執行後面的指令。

另外還可以使用**雙重直線**(||) 或是**雙重和號**(&&) 來分隔兩個命令：
前者表示當第一個命令的退出狀態為「假」時，才會執行第二個命令，而整體的退出狀態，是由兩個命令的退出狀態進行**或運算**(or-operation) 而得；
後者表示當第一個命令的退出狀態為「真」時，才會執行第二個命令，而整體的退出狀態，是由兩個命令的退出狀態進行**且運算**(and-operation) 而得。

==== 複合命令
在命令列模式中輸入指令並按下 kbd:[Enter] 之後，命令殼程式會先進行前置處理。
如果判定名稱字組屬於需要多列輸入的命令，而且目前整列敘述也沒有出現終結字組，
那麼命令殼並不會出現原本的提示符號，而是會進入下一層的等待輸入狀態，直到使用者輸入終結字組為止。

最簡單的複合型式，是以成對的大括號 `{}` 或小括號 `()` 包圍多條指令所形式的指令區塊，整個指令區塊可以視為單一指令。
大括號區塊功能的解讀，目前衹限於宣告函式的 `function` 命令。
小括號區塊則表示以額外的子命令殼，具備與當前命令殼相同的環境複本，來執行所包圍的指令，而不僅僅是叉生新的子行程。

比較複雜的複合型式，甚至結合了包繞型式、多重型式與其他的複合型式，
像是 `if` 條件分支命令、 `case` 多重分支命令、 `for` 定量迴圈命令、 `while` 不定迴圈命令以及 `function` 函式宣告命令。
這些命令都有特殊的多列語法，但是如果能夠熟練到在一條敘述中完成，將會對命令列模式的操作大有幫助。
以下範例指令是針對工作目錄中的檔案，依照由大到小的順序，逐個確認是否要刪除：
====
user$ *for f in $(ls -S); do rm -i "$f"; done*
====
另一個範例是遍歷工作目錄以下的所有檔案與目錄，並將名稱改為全部小寫：
====
user$ *find . | while read f; do mv "$f" "${f,,}"; done*
====

==== 命令稿
依據命令殼程式語言規範所寫出的指令集合檔案，就是可以經由命令殼解譯後執行的命令稿。
當命令列模式中的指令，不足以完成複雜的動作，或是需要重複執行類似的程序，那麼就是命令稿發揮作用的時刻。
有些特殊的變數與命令，衹有在命令稿中才有意義，有興趣進一步研究的讀者請參考手冊資料
footnote:[Bash Reference Manual <https://www.gnu.org/software/bash/manual/bash.html>]。

即使沒有文字編輯軟體，仍然能夠藉由重導符號的特殊功能，在命令列模式下建立命令稿檔案，
也常常做為在命令稿中產生另外一個命令稿的方法：
====
user$ *cat > _mt9x9.sh_ << _EOF_* +
*for i in {1..9..3}; do* +
*for (( j = 1; j <= 9; j++ )); do* +
*for k in \$i \$((i+1)) \$((i+2)); do* +
*printf '%dx%d=%2d\t' \$k \$j \$((k*j))* +
*done* +
*printf '\n'* +
*done* +
*echo* +
*done* +
*EOF* +
user$ *ls -l _mt9x9.sh_* +
-rw-r--r-- 1 user user 131  6月 11 23:56 mt9x9.sh
====
但是要注意其中前置錢號的變數仍會進行取值操作，而一對反引號所標示的輸出替代功能也依然有效，
就如同被另類的雙引號括住一樣，因此要加上反斜線將它遮蔽。
