== 顯示裝置
顯示裝置的表現取決於螢幕的解析度、訊號線的規格版本、繪圖介面卡的能力，以及內核驅動模組與 X 顯示模組的支援程度。


=== 繪圖晶片
早期影片的編解碼需要外接的影像擷取卡，等到 CPU 威力足夠之後，就由軟體來負責編解碼的工作。
當處理影像的需求日益繁重時，便出現了以 GPU(繪圖處理單元) 為核心的繪圖介面卡。
早期繪圖介面卡經由特殊規格的內部通道接收訊號，如今多透過 PCIe 匯流排與系統連接。
外接繪圖卡還會額外附加記憶體，其上的 GPU 也會依照位元數來區分等級。
之後 GPU 開始嵌入於 CPU，又漸漸將編解碼的工作轉移給前者。

不同世代的 GPU 有不同的代號，不同世代的 CPU 也有不同的代號。
GPU 和 CPU 合併起來的模組（亦即附帶核顯的中央處理單元）也有不同的代號，而與相關系統晶片組成的 SoC(單晶片系統) 也會有各自的產品名稱，且因製程不同又有區分。
SoC 再加上記憶體、南北橋元件之後的硬體模組則稱為 SoM(單模組系統)，但若不製成模組形式而是所有晶片都配置在單一小板上的電腦系統，則稱之為 SBC(單板電腦)。

==== 裝置韌體
電腦系統會向螢幕發出 *EDID*(擴充顯示識別資料) 需求，螢幕則回應 EDID 資料。
`xrandr --verbose` 指令的輸出中包含了 EDID 的十六進位資料，直接將其透過管線符號導向至 `edid-decode` 命令，就可以得到詳細的內容。
類似功能的命令還有 `monitor-edid` ，以及第三方套件 `read-edid` 中的 `get-edid` 與 `parse-edid` 命令組合。

螢幕名稱也是儲存於裝置韌體，透過解讀 EDID 資料再參照 `/etc/udev/hwdb.bin` 與 `/usr/share/hwdata/pnp.ids` 檔案中的對照表而來。
特定機型的螢幕如果固定要轉為直立，應該在裝置韌體中就將長寬調換，就不需要再由軟體執行畫面旋轉。
如果系統的顯示器是連在 I^2^C 匯流排上，可以利用 `i2c-tools` 套件中的工具來讀寫特定位置上的 EDID。

舊式的 VGA 顯示介面並不支援此功能，因此系統即使透過轉接器連上新式的數位顯示器，仍然無法獲得詳細的規格資料。
對於舊型不會提供 EDID 資料，卻又因為某種原因而無法換新的螢幕，可以直接利用內核參數來設定單一模式，但有可能會失去在內核空間中設定顯示模式的功能。
例如 `video=VGA-1:1920x1080-24@60e` 或 `video=DP-1:1920x1080D` ，其中的末尾字母 e 與 D 均表示強制顯示，而後者更強調是以數位模式。
如果真的想要獲得完整的顯示模式，還可以借用第三方套件 `edidbins` 提供的通用資料檔。
例如先將適當的項目加入初始記憶體檔案系統的檔案列表中：
====
root# *echo 'install_items+=" /usr/lib/firmware/edid/1920x1080.bin "' > /etc/dracut.conf.d/99-local-edid.conf*
====
接著以 `dracut -f` 指令配合引數來製作新的初始記憶體檔案系統，然後再加入內核參數 `drm_kms_helper.edid_firmware=edid/1920x1080.bin` 試試。

==== 顯示控制器
每個顯示裝置於開啟時會佔用一個**顯示控制器**(CRTC)，名稱源自舊式的**陰極射線管**顯示器。
最基礎的顯示控制，是以**影格緩衝區**(frame buffer) 的方式驅動，對應於系統中像是 `/dev/fb0` 之類的抽象裝置。
影格緩衝區的資料經過控制器與編碼器的處理，才會送出連結介面。
CRTCs 是指繪圖晶片上固定的的顯示控制器數量，也就是獨立的影格緩衝區數量，例如 0 1 代表了兩個控制器的編號順序。

顯示晶片的**色深**(color depth) 能力是用對應的位元數量來衡量，如果紅藍綠各以 8 位元(bpc/bit depth) 表示，合計就是 24 位元。
每塊影格緩衝區的大小也未必相同，依照不同顯示色深會使用不同的區塊，也有可能於高色深時使用多個區塊的組合。
以下指令顯示的是視窗系統所支援的色深列表，預設為排列在最前方的數值：
====
user$ *xdpyinfo | grep depths* +
　depths (7):    24, 1, 4, 8, 15, 16, 32
====
色深同樣是與總體顯示能力相關的因素之一，因此理論上可以利用減少色深來換取其他顯示能力的加強，衹是以 `xrandr` 命令的選項設定最大值時，色深 8 bpc（24 位元）以下的設定並無作用：
====
user$ *xrandr --output _DP-1_ --set "max bpc" 8*
====

如果顯示裝置數量大於 CRTCs，就會出現多個顯示裝置共用影格緩衝區的現象，
可能會影響效能或是導致裝置出現錯誤訊息而無法點亮，甚至在開機時造成內核模組錯誤而當機。

==== 連結介面
由於連結介面的種類太多，因此介面訊號、連接線、螢幕之間的相容性，也會影響顯示的表現。

有些機型為了節省主機板線路，讓不同的連結介面使用相容的後端佈局，也可能在軟體層面造成混淆。

DP(DisplayPort) 1.0, 1.1a, 1.2, 1.3, 1.4 是解析度與頻率的規格，其中 1.2 為目前主流，支援 4K 60Hz 以及可以串列連接多臺螢幕的**多重串流**(MST) 功能。
如果 DP 螢幕的 MST 功能關閉時，即使有串接多臺，系統仍然衹認到一臺，其他串接的螢幕衹會顯示由第一臺螢幕拷貝輸出的鏡像畫面。
DP\+\+(雙重模式 DP) 則指的是 DP 可相容/轉換為 DVI/HDMI 的規格。
USB Type-C 的 DP 介面，有可能會採取與原生介面互斥並存的方式，亦即無法同時使用兩個 DP 介面。

eDP 顧名思義即為適用於嵌入式裝置的 DP 介面，但刪除了對於音效的支援，而在更簡約的 SBC 系統上，還可以發現 DSI(串列顯示介面)。
LVDS 也是常用於嵌入式裝置的顯示連結介面，與 eDP 一樣具備較短的訊號線設計。
單一 LVDS 埠目前衹能支援 1366x768 的像素數量，因此嵌入式的 LCD 模組必須具備雙埠(dual-port) LVDS 的介面，才能達到 1920x1080@60 的顯示模式。


*SDM*(靈巧顯示模組) 是 Intel 為了配合 AIO 機型，將整個電腦系統做為一個螢幕的顯示模組所製訂的規格。
它與螢幕之間以 PCIe 介面相連，並與 CPU 的顯示介面相接，通常會選擇支援音效的連結介面。
BIOS 開機模式下可能因為未將 SDM 設為主螢幕，導致雙顯時開機過程出現黑屏，但熱插拔外接螢幕反而能點亮它。

==== 連接線
連接線是連結介面的延伸，可以是單純的訊號線，也有可能是內含訊號**轉換器**(converter) 的轉接線。
訊號線的問題雖然相對比較容易判別，通常是畫面出現缺少某些顏色或有垂直增長的黑線，但是它的線材品質與長度限制常常會被忽略。

轉接線大致可以分為**被動式**(passive) 與**主動式**(active)，前者構造與功能較簡單，即為一般所指的**轉接線**。
主動式轉接線中含有主動式晶片，多用於數位訊號轉換為類比訊號的場合（例如 DP 轉為 VGA）。
相同用途的主動式轉接線比被動式的成功機會要高，能夠支援的解析度範圍也比較完整。
不過需要注意的是，使用主動式轉接線時即使沒有接上螢幕，系統有可能會出現誤判的**幻影螢幕**(phantom screen)。

將非嵌入式裝置使用的繪圖晶片組用於嵌入式裝置時，由於內建螢幕通常衹支援 LVDS 介面，因此還需要轉換器將 DP 或 eDP 訊號轉為 LVDS，容易因此而導致螢幕辨識錯誤。
DP/eDP 訊號轉換為 LVDS 的晶片具備 DP AUX 介面，但是 Linux 尚不支援 AUX 與 I^2^C 之間的通道，
因此無法以 `i2cdetect -l` 指令找到存取的方式，而必須透過 Windows 工具程式才能更新螢幕韌體中的資訊。

NOTE: 轉接線的名稱通常會對應兩端的介面型式，而名稱排列則是依照「母頭－公頭」的順序。

=== 螢幕
目前主流的 TFT-LCD 螢幕是以 LED 做為背光元件，舊式的 CCFL 技術已不再使用。
螢幕顯示元件直接使用 LED 時，會面臨無法將顆粒微小化技術問題，因而有 OLED 與 micro-LED 的次世代開發競爭。

螢幕解析度的描述方式之一為 K 值，指的是螢幕的水平千位解析度，例如：2048x1080 和 1920x1080 稱為 2K, 3840x2160 和 4096x2160 則算作 4K。
另外也可以用垂直掃描線數來表示，例如：720p(漸進式 progressive), 1080i(交錯式 interlaced)…等等。 
2K 與 4K 之間的解析度並無一致的標準，雖然每種模式都有自己的代號，但未必會被顯示器納入支援的列表中。

最終顯示於螢幕上的模式，通常是驅動軟體與螢幕韌體之間協商的結果。
功能較多的螢幕會幫助效能不足的繪圖卡自動調整頻率，反而可能造成測試的誤判。
某些螢幕韌體衹支援固定的單一解析度，設定時也衹會出現一種解析度選項，如果手動加入新模式，可能會出現黑屏或拼貼畫面。

例如有些螢幕具備自動調整 HDMI 模式功能，會自動於 HDMI2.0(4K 60Hz) 與 HDMI1.4(4K 30Hz) 之間切換，
或是為了避免顯示黑屏，而自動調整為相同頻率的較低解析度，反而會造成系統其實並未進入指定的模式。

由於螢幕硬體未必有支援 32 位元的色深，因此不需要特別去測試此種模式。
甚至 LCD 的製造商為了追求更快速的反應速度，每種原色衹使用 6 位元來顯示，如此全部色深衹有 18 位元，和 24 位元的標準相差太多。
因此廠商又利用遞色產生半色調，將總共可以顯示的顏色數提升為 16.2 百萬色，從而接近 24 位元色深原本應有的 16.7 百萬色。

OSD(螢幕顯示設定) 可分為硬體或軟體型式，前者是由螢幕韌體控制，後者則是由桌面環境程式產生。
有些螢幕不會自動切換訊號來源，必須手動切換，尤其是以單一螢幕測試多重顯示之前要確認此一功能。
`ddccontrol` 是一個工具程式，對於有支援的螢幕可以設定原本衹能透過硬體面板才能設定的項目。
還可以試試它的圖形介面套件 `ddccontrol-gtk` ，或是另一套 `ddcutil` 螢幕工具軟體。

==== 熱插拔偵測
當螢幕熱插拔連接系統時，來自系統的電壓訊號會引起螢幕回應 HPD(熱插拔偵測) 訊號，此時如果電壓不足 5V，可能就不會引起回應。
系統接收到回應後，發出 EDID 要求並等待螢幕送出資料（有些規格即使螢幕無電源亦可使用）。
較不相容的螢幕，回傳訊號較慢，容易導致系統誤判為螢幕不存在而出現黑屏，如果允許修改系統韌體的話，可以透過加長其中的訊號等待時間來改善。

高解析度螢幕比較容易因為熱插拔而造成解析度下降或丟失，甚至導致系統宕機。
這個現象並不受 DPMS 的開關影響，也與何種 X 伺服程式的使用無關，單純源於系統效能與驅動程式能力。
不過舊式的 VGA 介面規格並不支援熱插拔，即使透過轉接線也未必能完全運作正常，
因此可能需要指定其為主顯示螢幕，而將熱插拔功能運用於其他螢幕。

早期使用**硬體抽象層**(HAL) 機制的 `hotplug` 命令已經過時，目前附於內核的顯示模組，是以配合 `udev` 偵測的規則檔案來回應熱插拔事件。
如果使用者想要對於螢幕熱插拔有額外的處理，可以增加下列檔案：

./etc/udev/rules.d/75-hotplug-monitor.rule
....
ACTION=="change", \
SUBSYSTEM=="drm", \
ENV{HOTPLUG}=="1", \
RUN+="/usr/local/bin/hotplug-monitor.sh"
....
並在設為可執行的 `/usr/local/bin/hotplug-monitor.sh` 中，編寫對應的命令稿程式。
而在偵錯的過程中，則可以使用 `udevadm` 的相關指令：
====
user$ *udevadm monitor --property* +
monitor will print the received events for: +
UDEV - the event which udev sends out after rule processing +
KERNEL - the kernel uevent +
 +
====
來即時偵測系統中的事件。

==== 多重顯示
進行多重顯示器測試時，儘量先以具備相同規格的螢幕（標準解析度、標準頻率）做測試。
測試組態順序建議為：開機時全部插滿、開機後逐臺熱插拔、開機後調整頻率再熱插拔。
如果產品具有投影功能，可能還需要加測鏡射顯示項目。

當測試規格中提到支援 4K 螢幕時，應該要確認所指的是單一顯示，還是多重顯示且可接受較低的掃描頻率。
4K 衹是反映硬體螢幕的畫面規格，而合併起來的軟體虛擬桌面，通常可以支援到 32K x 32K 的大小。
測試時系統配置的記憶體不應太少（至少需要 4GB），而插滿兩排雙通道的記憶體，確實會加強系統支援多顯的能力。

四重顯示器通常會排成擴展模式的田字型，因此需要在合併螢幕狀態下測試影片播映。
如果客戶有實際上的應用需求，才需要測試多重顯示器的旋轉組態。

FreeSync 為 AMD 開發的顯示器加強技術，需要螢幕、GPU、驅動程式三者的配合以支援動態重刷速率。
於多重顯示器環境下，如果會干擾其他螢幕頻率的分配，可以嘗試暫時關閉後再利用新版桌面環境支援的軟體實作來測試。

==== USB 螢幕
雖然主機板上的繪圖晶片普遍支援多個顯示裝置，適合做為第二螢幕或是多重顯示的來源，
但是在某些特殊的條件下，從 USB 延伸出的螢幕也能做為考慮的選項。

初期的 USB 螢幕內部具備顯示介面（例如 DVI），作用如同透過 USB 的外接繪圖卡再加上螢幕，
雖然需要額外安裝軟體驅動程式，對於系統資源的消耗也比較大，但是硬體的相容性比較高，
在沒有多餘顯示介面的嵌入式系統中，適合做為小尺寸且不需額外電源的附屬螢幕使用。
安裝這類 USB 螢幕的驅動程式時必須注意，內核可能缺少內建的模組或是版本已被棄用，
需要使用供應商（例如 DisplayLink）提供的專屬版本（有可能舊版才適用），或是藉由第三方的套件庫來安裝。

安裝前應確認是否安裝過散佈版官方提供的套件，如果有的話則最好先將其移除。
安裝完成後，舊版的模組應該利用黑名單停用以免干擾，如果有多個類似裝置，也要注意自動載入模組時的選項調整。
指令範例如下：
====
root# *echo evdi > /etc/modules-load.d/evdi.conf* +
root# *echo "options evdi initial_device_count=2" > /etc/modprobe.d/evdi.conf*
====
該裝置可能要到桌面環境啟動後才會被偵測到，設定時也要確認它在系統中的介面名稱。

新式的 USB 規格已經允許支援 DP 顯示介面的訊號，可以滿足高解析度的第二以上螢幕需求。
如果系統硬體的 USB Type-C 接頭支援此一功能，就可以利用適當的訊號線直接傳送到 DP 螢幕。

=== 作業系統之前


==== 系統韌體
哪些螢幕在多重顯示器組態時會出現開機畫面，以及指定**主顯示**(primary display) 的順序是由系統韌體設定。
系統韌體於偵測並識別出顯示裝置之後，依照設定決定是否啟用並排列順位，順位最高者即為主顯示，位於多螢幕組態的畫面最左側，並負責顯示開機時的訊息。

*VBIOS*(視訊韌體)（或稱 VGA Option ROM）是顯示裝置的韌體部分，存在於繪圖介面卡上或是內嵌於系統韌體中。
UEFI 中用來相容 BIOS 的模組(CSM)，其中的 VBIOS 有可能衹支援 64 位元，導致安裝 32 位元作業系統時，內核無法從系統韌體獲得正確的資訊。
這會造成內核無法進一步傳遞資訊給 X 顯示模組，因而出現顯示黑屏、亂碼、破圖、掉字等問題。
可以採用 64 位元的內核搭配 32 位元的使用者空間系統，如此還能解決純 UEFI 系統無法安裝與執行 32 位元作業系統的問題。

UEFI 中用來替代 VBIOS 的部分稱為 GOP 驅動器，與 VBIOS 一樣是由繪圖晶片廠商所提供再包入系統韌體之中。
GOP 運作時不需要 CSM 且有較佳的效能，並且具備自己的影格緩衝區模式。

對於配置 Intel 繪圖晶片的系統，套件 `igt-gpu-tools` 提供了一些與視訊韌體有關的命令，
否則就要根據顯示裝置所在的 PCI 識別號，嘗試直接從虛擬檔案系統（例如 `/sys/devices/_pci0000:00/0000:00:02.0_/rom` ）中存取資料。

==== 開機管理程式
以 GRUB 為例，開機管理程式需要載入自帶的基本模組才能在畫面上顯示文字。
如果設定檔中還要求顯示背景圖片或是萬國碼字元，就需要進入開機管理程式自己的影格緩衝區模式才能滿足。
設定檔中的相關指令像是 `set gfxpayload=text` ，表示在開機管理階段衹有文字模式，而 `set gfxpayload=1024x768` 則可提供基本的圖形顯示能力。
萬一螢幕介面剛好用到少了兩支接腳的非標準 VGA 連接線，就有可能因為 GRUB 不支援而卡住。

=== 內核模組
支援現代 GPU 中 *DRM*(直接潤算管理器) 且支援 *KMS*(內核顯示模式設定) 的驅動模組，通常編譯為外部模組的形式，例如 `amdgpu`, `i915`, `xe`, `nouveau` 。
當某個顯示裝置有了 DRM 類型的驅動模組之後，相關的影格緩衝區類型驅動模組通常就會被列入黑名單，以免干擾內核對於裝置的偵測。
另外有一些內核顯示驅動模組，專門用於虛擬機器，例如： `qxl`, `vmwgfx`, `hyperv_drm`, `vboxvideo` 以及 `virtio-gpu` 。

驅動顯示裝置的內核模組，還需要搭配載入軟體形式的裝置韌體，通常是由名稱像是 `*-firmware` 的套件所提供。
如果以手動方式更新了內核模組，就需要手動下載更新當前的裝置韌體版本，否則可能會出現找不到適當檔案的錯誤訊息。

適用於舊式繪圖晶片的 `vesafb` 影格緩衝區驅動模組，一般在編譯時已內建於內核，做為候補的裝置驅動模組使用。
內核參數 `nomodeset` 常用來強制載入影格緩衝區驅動模組，某些專屬顯示模組可能還要搭配它的相關參數值，例如 `i915.modeset=0` 。
除了以上利用內核參數去避免有問題的專屬顯示模組，也有可能需要強迫內核提早載入專屬顯示模組，例如運用內核參數 `rd.driver.pre=amdgpu` 。

舊式以 BIOS 為開機模式的系統，要在 GRUB 設定中利用 `linux16` 載入內核，並加入額外的 `xforcevesa` 以及像是 `vga=0x317` 的內核參數，來強制產生影格緩衝區裝置。
此時內核中具備 KMS 功能的專屬模組都會被強制停用，導致顯示效能降低、不支援多顯與熱插拔功能。
目前在新版的內核中，開發趨勢為逐漸棄用此類裝置。

對於最新開發的繪圖晶片，廠商出於維護技術機密的原因，再加上花費時間與使用授權的限制，常常衹會提供專屬的封閉原始碼驅動模組。
例如 NVIDIA 的廠商驅動模組，在 Fedora 系統中可以透過 RPM Fusion 第三方套件來安裝。
而硬體晶片與不同版本封閉原始碼內核模組之間的相容問題，常常會導致系統宕機或自動重新開機。

==== 模組參數
模組參數可以透過內核參數的形式來設定，以目前的 AMD 繪圖晶片為例：
如果訊號線接著但螢幕關閉時會偵測不到螢幕，可以加入內核參數 `amdgpu.dc=0` ；
如果沒有自動開啟 UVD(通用視訊解碼器) 或是出現閃爍與白屏，則可以試試 `amdgpu.si_support=1` 或 `amdgpu.sg_display=0` 。

使用者空間則提供 `modinfo` 命令來列出內核模組的資訊，其中也包含了所有可載入的韌體檔案，以及可設定的模組參數。
例如舊式的 AMD 繪圖晶片，藉由 `radeon.tv=0` 或 `radeon.agpmode=-1` 等內核參數來關閉特定的介面。
而以目前 Intel 繪圖晶片所用的 `i915` 來說，常用模組參數的內核參數設定形式如下：

[width="60%",options="header"]
|========================
|名稱|可能值|用途
|i915.invert_brightness=|1,0,-1|黑屏、外接 USB 顯示器
|i915.load_detect_test=|true,false|偵測過程宕機
|i915.preliminary_hw_support=|0,1|可能解決 Skylake 顯示問題
|i915.fastboot=|0,1|白屏或黑屏
|i915.enable_guc=|-1,0,1,2,3|解析度過低
|i915.enable_fbc=, i915.enable_psr=, i915.enable_dc, i915.enable_gvt|0,1|效能相關
|i915.force_probe=|GPU 裝置的 PCI 識別號|強制驅動新型號繪圖卡
|========================

要列出模組參數的目前值，可以安裝 `sysfsutils` 套件後執行 `systool -m _i915_ -av` 指令，
或是直接檢視 `/sys/module/_i915_/parameters/` 目錄下，與參數同名的檔案內容。

==== 開機訊息
載入內核的初始階段，預設會在**主控臺**(console) 上輸出大量的執行記錄。
不同的散佈版會利用不同的內核參數，例如 `rhgb`(redhat graphical boot) 或 `splash` ，來啟用開機時的圖形畫面。
如此就會改為顯示作業系統內建或來自系統韌體的標章(logo)，同時配合內核參數 `quiet` 來掩蓋對於一般使用者不太友善的技術訊息。

想要改變輸出位置或裝置，可以使用內核參數 `fbcon=map:1` 或 `console=ttyS0` 來變更主控臺的對應。
目錄 `/usr/lib/kbd/consolefonts/` 包括了可用於主控臺的字型，需要藉由像是 `fbcon=font:TER16x32` 的內核參數，或是使用者空間的 `setfont` 命令來指定。
萬一遇到了直式螢幕，還可以利用 `fbcon=rotate:1` 內核參數來旋轉文字輸出的方向。

標章如果無法顯示，可能是內核驅動程式無法識別繪圖晶片，或是螢幕具有固定的解析度而導致使用了不當的模式。
如果沒有顯示標章，又不想看到駁雜的開機記錄畫面，還可以利用以下設定檔案去阻擋一些訊息：

./etc/sysctl.d/99-printk.conf
....
kernel.printk = 3 4 1 7
....
甚至採取進一步的方式，直接使用內核參數 `vt.default_blu=0 vt.default_grn=0 vt.default_red=0` 來調色隱藏，
再加上 `vt.global_cursor_default=0` 來取消游標。

對於內核參數的增減或修改，如果希望在開機前期便發生作用的話，就必須再次產生初始記憶體檔案系統。

==== 介面設定
內核對於顯示介面的命名，可以參考 `/sys/class/drm/` 目錄中的軟式鏈結。
其中前置的 `card0-` 表示系統的第一個顯示裝置，後方則以字母加上數字做為介面名稱。
當內核參數需要指定某個介面時，就會使用這類介面名稱。

多重顯示器的數目除了受到繪圖晶片的設計限制，還會依據系統韌體於初始時的偵測來停用或啟用裝置。
內核初始時會自動偵測連結介面與顯示模式，並載入適當的內核模組。
如果驅動結果不滿意的話，可以利用 `video=` 內核參數來強制設定。
例如 `video=eDP-1:2560x1600@60` 表示將首個 eDP 介面的解析度設定為 2560x1600，重刷頻率設定為 60Hz。

LVDS 使用的驅動模組比較駁雜，內核參數可能要加上一些特殊的設定，例如 `video=mxcfb0:dev=ldb,LDB-T13,if=RGB24,bpp=16 ldb=spl0` 或
`video=davincifb:vid0=720x480x16,2025K` 。
某些版本的 Intel 專屬內核模組會自動打開 LVDS 顯示裝置，使得系統產生一個實際並不存在的幻影螢幕。
由於多出了一塊看不見的虛擬螢幕範圍，會造成滑鼠容易失去蹤跡，就可以利用 `video=LVDS-1:d` 內核參數來刪除此一裝置。
這種方法也能夠暫時解決多重顯示器安裝時，主顯示畫面出現於不當螢幕的問題，但是安裝後必須將其刪除，否則系統將辨識不到這個裝置。


=== 顯示函式庫
對於裝置的驅動，在韌體與內核模組以外的部分，都屬於使用者空間驅動軟體，通常是以函式庫的形式出現，方便應用軟體動態呼叫。
例如內核的 DRM 次系統實作了 KMS 的 *API*(應用程式介面) 後，再透過 `libdrm` 函式庫提供匯出。
後續的高階繪圖與計算函式庫，包括由 Mesa 3D 專案所實作的 OpenGL 與 Vulkan API ，提供給其他軟體應用。

另外還有負責提供**繪圖加速**(VA) 的 `libva` 函式庫（適用於 Intel 繪圖晶片），以及 `libvdpau` 函式庫（適用於 AMD, NVIDIA 繪圖晶片）。
前者可用 `libva-utils` 套件中的 `vainfo` 命令取得資訊，後者相應則是 `vdpauinfo` 套件中的 `vdpauinfo` 命令。
在 `/usr/lib64/dri/` 目錄下名稱結尾是 `_drv_video.so` 的檔案，就是不同類型裝置的 VA 驅動函式庫，目前較為常用者名稱前置為 `iHD` 與 `radeonsi` 。
通常散佈版會利用 `libva-vdpau-driver` 套件來安裝以 `libvdpau` 做為 `libva` 後端的驅動程式，
如此其他的軟體衹需要呼叫 `libva` 的應用程式介面，就能適用於大多數的繪圖晶片。

為了能夠更有效率地直接利用繪圖晶片上的功能，相關的套件組中還包括了各別晶片專屬的 *DRI*(直接潤算框架)，由 `/usr/lib64/dri/` 目錄下以 `_dri.so` 為檔名結尾的函式庫所負責。
Mesa 3D 套件組中也有包含開放原始碼適用不同晶片的 DRI 驅動程式，但被呼叫的優先權較低，效能亦不及專有的驅動程式。
舊式系統中的 `driconf` 命令已不再用於 DRI 的設定，而是由 OpenGL 依照驅動程式的支援程度，自動調整系統 DRI 的規格。
例如以下的指令，可以檢視目前應用 OpenGL 時能夠使用的 DRI 等級：
====
user$ *LIBGL_DEBUG=verbose glxinfo |& grep DRI* +
libGL: Using DRI3 for screen 0
====

與顯示相關的函式庫堆疊中，與一般應用軟體關係最接近的是影音函式庫（例如 `gstreamer`, `ffmpeg` ）。
如果前段所說的硬體驅動程式有支援的話，套件 `gstreamer1-vaapi` 就可以讓 `gstreamer` 使用到 `libva` 的 API。

=== 圖形模式
X 視窗系統(X Window System) 是 Linux 圖形服務系統的代表。
如果覺得以單一字母 X 做為代稱太過簡單的話，也可以稱其為 X-Window。
X 視窗系統是一套**伺服器－客戶端**(server-client) 架構的服務，桌面環境應用軟體扮演客戶端的角色，利用 X 協定與圖形伺服程式溝通。
NOTE: 使用 X 視窗系統英文名稱時，記得 Window 後面不要加上複數字尾。

進入圖形模式的過程，在早期的單機使用情境下是藉由 `startx` 命令稿去執行 `xinit` ，其中呼叫了 `X` 命令以建立視窗服務系統，最後再啟動所選的 X 作業階段程式。
目前標準的網路使用情境，是由一個**顯示管理程式**(display manager) 於呼叫 `X` 時，執行一個**接待程式**(greeter) 負責登入的工作，驗證通過後才啟動所選的 X 作業階段程式。

如果原本是以顯示管理程式啟動了 X 伺服程式，當系統想要再啟動另一個 X 伺服程式時，就需要採用 `xinit` 的另一種方式。
陽春的 X 作業階段衹有載入**視窗管理程式**(window manager) 或是單一的應用程式，複雜的 X 作業階段才會建構出完整的桌面環境。

==== X 伺服程式
X 視窗是一套遵循 X 協定的圖形服務系統，協定規格的最後一個主要版號是 11，因此也常以 X11 做為視窗函式庫的簡稱。
下面指令可以顯示相關的版本編號：
====
user$ *xdpyinfo | grep version* +
version number:    11.0 +
X.Org version: 1.20.14
====
視窗系統的伺服程式 `X` ，通常是真正伺服程式的軟式鏈結，傳統基於 X11 函式庫的系統會鏈結到 `Xorg` 程式，但是未來的趨勢則是使用基於 Wayland 函式庫的 `XWayland` 實作。
許多 X 相關的設定項目中，仍然可見更早期而已被棄用的 `XFree86` 伺服程式名稱。
另外有一些套件包含特殊用途的 X 伺服程式，可以在虛擬裝置中進行測試或是提供遠端桌面。

不同的顯示管理程式與作業階段，都有各自適用或偏好的 X 伺服程式，利用指令 `ps ax | grep X` 就可以看出目前系統所選用的程式。
也可以查看環境變數 `XDG_SESSION_TYPE` 的值，分別會以 x11 或 wayland 來代表 `Xorg` 或 `XWayland` ，或是安裝小程式 `xisxwayland` 進行檢測。
目前多數流行的散佈版是透過 GDM 來呼叫 X 伺服程式，接著啟動 GNOME 作業階段，做為進入桌面環境的方式。
GDM 的設定檔 `/etc/gdm/custom.conf` 中有一列 `#WaylandEnable=false` ，如果將前方的 # 號刪除，就表示禁用 `XWayland` 而回復以 `Xorg` 做為預設的 X 伺服程式。

==== Xorg 系統設定
`Xorg` 的系統設定，是由 `/usr/share/X11/xorg.conf.d/` 目錄中的檔案組成，本地設定則位於 `/etc/X11/xorg.conf.d/` 目錄之中。
如同大部分的設定目錄機制，這是起源自舊式的 `/etc/X11/xorg.conf` 單一設定檔案，為了便於個別套件的管理打散而成。
目前的 `Xorg` 伺服程式啟動時，自動偵測所產生的設定已經相當完善，但是在出現問題或是有特殊需求時，就需要使用者介入調整。

設定的內容結構是以區段(section) 組成，恰好適合分為不同作用的設定檔案。
其中與伺服程式有關的是 `ServerFlags` 區段，例如以下的設定檔案：

./etc/X11/xorg.conf.d/00-ignore-abi.conf
....
Section “ServerFlags”
    Option “IgnoreABI” “true”
    Option "DontVTSwitch" "true"
End Section
....
第一個選項是用於當 `Xorg` 伺服程式載入模組時出現 ABI 不支援的訊息，這通常發生於安裝了來自第三方套件庫的 X 模組。
第二個選項則可以用來停用切換至虛擬終端機的組合鍵。

與顯示設備有關的是 `Monitor` 與 `Screen` 區段，前者定義了實體設備的內容，而後者在前者與下下節提到的 `Device` 區段共同影響下，定義了邏輯設備的屬性。
`Screen` 區段指稱的對象是邏輯上的「螢幕」，而其內還有包含定義「畫面」的 `Display` 子區段，雖然這兩個詞在多數場合中都被混雜使用。
隨著裝置韌體的日益靈巧，即使自動組態結果有不足的地方，通常都可以藉由工具程式後續調整，而不再需要加入自訂設定檔案。

==== Xorg 顯示模組
`Xorg` 的顯示模組可以分為幾種類型：

[square]
* 簡單通用的 `fbdev` 模組，用來存取基於影格緩衝區的邏輯裝置
* 單一共用的 `modesetting` 模組，繼承內核支援 KMS 功能的驅動模組
* 各別晶片的專屬模組，例如 `amdgpu`, `intel`, `nouveau`
* 晶片供應商額外提供的封閉專屬模組，例如 `fglrx`, `amdgpu-pro`, `nvidia`
NOTE: 當前 Intel 繪圖晶片的內核驅動模組名稱與 `Xorg` 顯示模組名稱並不一致。

以往繪圖晶片的模組多是以額外的專屬模組形式存在，需要使用者自行去供應商網站下載，或是藉由第三方套件庫進行安裝。
目前許多供應商已不再釋出驅動程式修正給一般使用者，而是直接提交給內核開發小組。
於是驅動功能漸漸融入內核主線中的專屬模組，最終的目標則是併入單一共用的 `modesetting` 模組。
使用 `modesetting` 顯示模組的優點，除了不受個別晶片專屬模組的版本影響之外，對於多卡多顯的情況也比較容易處理。

萬一經由自動偵測機制而載入的模組，造成了系統或顯示上無法解決的問題，或是無法取得新款繪圖晶片的專屬模組，
就會需要藉由加入之前提到的 `nomodeset` 內核參數，以載入 `fbdev` 模組來驅動相容的影格緩衝區裝置。
載入 `fbdev` 時會自動呼叫適用個別繪圖晶片的次模組，通常都是依照晶片供應商但不分型號的通用模組。
由於 `fbdev` 提供的基本顯示模示功能有限，內核儘可能還是以載入共用或專屬的顯示模組為優先。
有些舊式而不具備模式設定功能的專屬模組，仍有可能會繞過取消 KMS 支持的限制而被載入。

`Xorg` 顯示模組預設存放在系統的 `/usr/lib64/xorg/modules/drivers/` 目錄中，檔案名稱形如 `modesetting_drv.so` 。
其中除了上述提到的顯示模組之外，還包括為了相容舊機型而保留下來的檔案，例如 `openchrome_drv.so` 與 `radeon_drv.so` 。
使用者還可以藉由指令 `lsof|grep modules/drivers` 來查看目前使用的 `Xorg` 顯示模組。

進入桌面環境之後，如果畫面有出來但是滑鼠游標可以移動卻不能點擊、鍵盤完全無動作，應該是 `Xorg` 顯示模組發生問題而宕掉的結果。

==== Xorg 顯示模組設定
如果希望 `Xorg` 優先使用晶片專屬模組而非 `modesetting` 模組，就可以利用下面的檔案（其中的選項依實際需要再取消註解）：

./etc/X11/xorg.conf.d/10-intel.conf
....
Section "Device"
    Identifier "Intel Graphics"
    Driver "intel"
#    BusID "PCI:0:2:0"
#    Option "DRI" "3"
#    Option "AccelMethod" "uxa"
#    Option "Backlight" "intel_backlight"
#    Option "TripleBuffer" "true"
#    Option "IgnoreEDIDChecksum" "DFP"
EndSection
....

也可以強制使用自行安裝的封閉專屬模組：

./etc/X11/xorg.conf.d/10-nvidia.conf
....
Section "Device"
    Identifier "NVIDIA Graphics"
    Driver "nvidia"
#    Option "RegistryDwords" "EnableBrightnessControl=1"
#    Option "CustomEDID" "DFP-0:/etc/X11/custom-edid.raw"
#    Option "UseEDID" "false"
#    Option "UseEDIDFreqs" "false"
#    Option "NoDDC" "true"
#    Option "DynamicTwinView" "false" #將可調頻率提升
#    Option "ModeValidation" "AllowNonEdidModes,AllowInterlacedModes"
#    Option "ModeValidation" "NoVesaModes,NoXServerModes"
#    Option "ModeValidation" "NoEdidModes"
EndSection
....

當然也可以用於在載入 `modesetting` 模組時，設定特定選項的值：

./etc/X11/xorg.conf.d/10-modesetting.conf
....
Section "Device"
    Identifier "Kernel Graphics"
    Driver "modesetting"
#    Option "AsyncFlipSecondaries" "On"
#    Option "Composite" "Enable"
#    Option "AccelMethod" "msdri3"
EndSection
....

另外還有一些選項，在多數顯示模組設定中都適用：

....
        ⋮        ⋮
#    Option "Present" "false"
#    Option "TearFree" "true"
#    Option "XvPreferOverlay" "true"
#    Option "Tiling" "false"
#    Option "LinearFramebuffer" "true"
#    Option "Throttle" "false"
        ⋮        ⋮
....

調整以上選項有可能解決的問題包括：畫面被分割、畫面破碎、出現橫紋、文字缺筆、鏡像滑鼠位置不一致、擴展螢幕中的視窗拉動殘影、無法調整螢幕亮度…等等。

==== XRandR 基礎
最常用的 X 顯示相關工具程式是 `xrandr`(X resize and rotate)，它屬於一類需要圖形環境的文字介面命令，
一般會在桌面環境的終端機模擬器視窗中執行：
====
user$ *xrandr* +
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384 +
VGA-1 disconnected primary (normal left inverted right x axis y axis) +
HDMI-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 600mm x 340mm +
　 3840x2160　　 30.00 +　30.00　　25.00　　24.00　　29.97 +
　 2560x1440　　 59.95 +
　 1920x1080　　 60.00*　 60.00　　59.94　　30.00　　24.00 +
　 1920x1080i　　60.00　　59.94 +
　 1600x900　　　60.00 +
　 1280x1024　　 60.02 +
　 1280x800　　　59.91 +
　 1152x864　　　59.97 +
　 1280x720　　　60.00　　59.94 +
　 1024x768　　　60.00 +
　 800x600　　　 60.32 +
　 720x480　　　 60.00　　59.94 +
　 640x480　　　 60.00　　59.94 +
DP-1 disconnected (normal left inverted right x axis y axis)
====
具體來說，這類軟體執行時會檢查命令殼環境變數 `DISPLAY` ，以確認系統是否有關聯的 X 伺服程式。
萬一真的有需要在虛擬終端機中執行這類程式，可以試試在命令的同一列中前置賦值指令 `DISPLAY=:0 xrandr` ，也許還能夠有限度地得到輸出。

`xrandr` 的輸出會列出系統目前偵測到的顯示介面，以及與該介面連接螢幕所支援的顯示模式。
其中頻率右側有註記加號者，是螢幕所建議的最佳模式，而星號註記則表示系統目前作用的模式。
萬一螢幕預設不支援某些解析度，顯示模組有可能會在螢幕的規格範圍內，自行模擬以添加一些常見的模式。

以 `xrandr` 命令設定多重顯示器時，需要將各螢幕的變更資料打在同一指令之中，並記得明確指定各螢幕的模式，如此才能讓所有設定值生效。
熱插拔後無法點亮的螢幕，如果能夠透過另一臺螢幕的終端機模擬器輸入命令（或是在確認適當的環境下盲打），將有問題的介面關閉：
====
user$ *xrandr --output _DP-2_ --off --output _DP-3_ --off*
====
此時可以再看一次 `xrandr` 的輸出，就會發現與螢幕的連接並未斷開，但該介面的模式列表中的星號註記已經消失。
當以命令再次開啟介面時：
====
user$ *xrandr --output _DP-2_ --auto --output _DP-3_ --auto*
====
如果可以點亮螢幕，表示有可能是系統與螢幕間的訊號溝通有問題。

==== XRandR 應用
旋轉畫面所使用的 `xrandr` 選項是 `--rotate` ，隨後的選項值包括：

[width="60%",options="header"]
|========================
|選項值|旋轉角度|旋轉模式
|normal|0|橫向(landscape)
|left|90|縱向翻轉(portrait-flipped)
|inverted|180|橫向翻轉(landscape-flipped)
|right|270|縱向(portrait)
|========================
由於畫面旋轉時會用到額外的記憶體區塊，因此如果發生了黑屏的現象，可以試試加大系統韌體中視訊記憶體相關的值。

在桌面環境已啟動的狀態下，可以透過 `xrandr` 的引數來傳遞設定選項給顯示裝置。
藉由指令 `xrandr --prop` 的輸出，就能看到每個輸出裝置透過 `--set` 選項所支援的設定項目以及允許值。
例如想要試試強制設定消除畫面斜紋：
====
user$ *xrandr --output _DisplayPort-0_ --set TearFree on*
====

簡單來說，顯示裝置的輸出來源就是系統中的繪圖晶片，可能內嵌於 CPU 中或是位於繪圖介面卡、系統主板之上。
指令 `xrandr --listproviders` 可以顯示系統中顯示訊號輸出來源的數量與資訊。
萬一硬體安裝的外接繪圖卡沒有開啟，可以再執行 `xrandr --setprovideroutputsource 1 0` ，嘗試將外接訊號來源併入系統之中。

如果想要清楚列出已連接的螢幕，可以透過命令殼的管線功能將命令組合後取得：
====
user$ *xrandr | grep "connected" | sed "s/ connected.\*//" | tr "\n" " "*
====
而對於列出已點亮的螢幕，`xrandr` 命令提供了現成的選項 `--listactivemonitors` ，就不需要使用者自行去堆砌指令了。

==== 介面名稱
`Xorg` 對於顯示介面的命名，與內核採用的格式不必然一致，不同顯示模組之間也會有差異，甚至某些模組還提供變更名稱的選項。
目前的趨勢是儘量使用 `modesetting` 模組，命名格式則會延續內核驅動模組的介面名稱。

以下列出常見模組的首組介面命名字串，做為使用 X 工具程式時引數的參考：

[square]
* `modesetting`: `VGA-1`, `LVDS-1`, `HDMI-A-1`, `DP-1`, `DVI-D-1` 
* `amdgpu`: `VGA-0`, `LVDS-0`, `HDMI-0`, `DisplayPort-0`, `DVI-0`
* `intel`: `VGA1`, `LVDS1`, `HDMI1`, `DP1`, `DVI1`

`XWayland` 並不會調用 `Xorg` 的顯示模組，且以形如 `XWAYLAND0` 的流水代號來統一命名所有的顯示介面。
有些自製的命令稿沒有考慮到介面名稱的差異性，可能因此會無法達到原本設想的功能。

畫面與游標的更新頻率不一致可能會出現滑鼠殘影，試看看是否能夠更換 X 伺服程式或是顯示模組。
使用轉接線時，X 顯示的介面名稱會與原生介面不同，甚至會依轉接線的型號而不同。
轉換硬體規格較高的螢幕以支援規格較低的介面時，容易出現最高解析度降低的情形。

==== 顯示模式
特定解析度與頻率的組合就稱為 X 的顯示模式，是決定圖形畫面表現的重要屬性。
顯示模式的本質則是由名為**模式列**(modeline) 的一串數字所設定，其中包含了螢幕垂直與水平的同步頻率，以及相關的掃描線數字。
即使是相同的螢幕下送出相同的 EDID 資料，但是不同的驅動模組對於相同名稱的顯示模式，所賦予的模式列內容仍然可能有細微差異。
如果想要知道目前顯示模式的模式列細節，可以在執行 `xrandr` 命令時加上 `--verbose` 選項，不過輸出結果比較繁雜。
要是衹想得到單一主顯示、符合設定格式的輸出，可以參考採用舊式的 `xvidtune` 命令：
====
user$ *xvidtune -show* +
"1920x1080"   148.50   1920 2008 2052 2200   1080 1084 1089 1125 +hsync -vsync
====

畫面更新延遲或是產生垂直水波紋，是因為時脈(clock)/間距(pitch) 不正確，水平水波紋則是因為相位(phase) 不正確。
這些由於不良顯示模式而造成的問題，當以螢幕截圖的方式來檢測時將會產生正常圖片，此時就需要嘗試重設顯示模式。
當 `xrandr` 命令列出的預設輸出中，缺少了目前螢幕應該有支援的某項顯示模式，或是使用者為了某種原因而需要特殊的解析度或頻率，
就可以同樣藉由這個命令來自訂顯示模式，但是要先準備好所需的模式列資料。

產生舊式類比螢幕的模式列是利用 `gtf` 命令，而新式的數位螢幕則要執行 `cvt` 命令：
====
user$ *cvt _2560 1440 60_* +
# 2560x1440 59.96 Hz (CVT 3.69M9) hsync: 89.52 kHz; pclk: 312.25 MHz +
Modeline "2560x1440_60.00"  312.25  2560 2752 3024 3488  1440 1443 1448 1493 -hsync +vsync
====

產生出來的模式列再配合 `xrandr` 的 `--newmode` 與 `--addmode` 選項，就可以在此次的 X 作業階段中新增一項自訂的顯示模式，
並且能夠透過 `xrandr` 命令選項 `--mode` 的標準方式來指定給輸出裝置：
====
user$ *xrandr --newmode "2560x1440_60.00"  312.25  2560 2752 3024 3488  1440 1443 1448 1493 -hsync +vsync* +
user$ *xrandr --addmode DP-1 "2560x1440_60.00"* +
user$ *xrandr --output DP-1 --mode "2560x1440_60.00"*
====
其中 `--newmode` 的反向選項為 `--rmmode` ，而 `--addmode` 的反向選項則是 `--delmode` ，
不過這些選項衹對使用者自訂的模式有效，無法刪除 X 伺服程式預設產生的項目。
對於硬體具備高解析度或高頻率的螢幕， `cvt` 的推算結果可能會出現偏差，此時可以加上 `-r(reduced)` 或 `-i(interlace)` 選項來產生新的一組模式列試試。
另外一種替代方案，是將螢幕接到其他可以正常顯示該種顯示模式的系統，取得當前的模式列數據之後，再將它應用到目標系統之中。

==== 解析度
一般提到的解析度，其實衹是螢幕在長寬兩個方向上的像素數量，它的真正含義應該是指 PPI/DPI 的數值。
*PPI*(每英吋像素數) 是由測量顯示裝置對角線上的像素密度而得，大小位於垂直與水平兩個相近密度值之間。
雖然與另外一個常用於評估印刷品質的 *DPI*(每英吋點數) 定義有些微差異，但是實務上仍然經常會混用。

以 `xdpyinfo` 或 `xrdb` 命令獲取設定值的輸出：
====
user$ *xdpyinfo | grep resolution:* +
　resolution:    96x96 dots per inch +
user$ *xrdb -query | grep dpi* +
Xft.dpi:	96
====
衹是經過硬體的熱插拔或桌面環境的縮放之後，顯示的結果未必是當前的實際值，還需要參考 `xrandr` 命令的輸出來進行計算。
關於字型顯示的問題，可以嘗試利用 `xrandr` 命令中的 `--dpi` 選項以及選項值來調整看看，可能的值包括 90, 96, 100, 120 或更高。
螢幕的實際尺寸除了由 EDID 內容取得之外，也會由長寬點數與 DPI 值計算而出，或是被 `xrandr` 命令的 `--fbmm` 選項值所覆寫。

某些顯示模式的組合會造成畫面黑屏，比較可能是軟體（內核驅動模組或 X 顯示模組）的問題。


==== 掃描範圍
當以電視螢幕做為顯示器時，有時會發生畫面出現黑邊或是邊緣被切掉的狀況。
除了在電腦部分調整解析度之外，電視螢幕自己的顯示模式可能也需要調整（16:9 或 16:10），尤其注意與**過掃描**(overscan) 相關的設定。
軟體層面的對策可以試試幾個 `xrandr` 的命令選項，例如 `--scale 0.95x0.95`, `--set underscan on` 或是 `--set "scaling mode" Full` 。
但其中設定選項值的部分，未必適用於所有的顯示模組，並且熱插拔後可能會失效。

==== 螢幕背光
如果螢幕開啟一段時間之後全部反白，或是喚醒後依然黑屏，但是系統似乎並未宕機且軟體操作正常，則可能是背光線路的問題。
背光調整問題包括了失去作用或作用相反的情況，請先試試內核參數 `acpi_osi=Linux` ，如果沒有作用的話再參考以下的內核參數以及可能的參數值：
`pcie_aspm=force|off` 或 `acpi_backlight=vendor|video|native|none|legacy` 或 `video.use_native_backlight=1|0。

`systemd` 初始系統模式下有一個服務，提供開機時重設背光值與關機時儲存背光值的功能。
如果使用者的散佈版有啟用它，可以嘗試先將其遮罩起來看看：
====
root# *systemctl mask systemd-backlight@.service*
====

桌面環境中常用的工具程式為 `xbacklight` ，作用是控制螢幕底層的背光強度，而 `xrandr` 的 `--brightness` 選項則是控制 X 伺服程式的亮度，
因此實際的表現結果是以 `xbacklight` 的值為基礎，再乘上 `xrandr` 所設定的比例：
====
user$ *xbacklight -set _90_* +
user$ *xrandr --output _DP-1_ --brightness _0.8_*
====
相關的值還可以參考虛擬檔案系統中 `/sys/class/backlight/*/brightness` 的內容。
另外有一個 `xgamma` 的工具程式，所調整的並非亮度而是顏色透明度。

==== 每秒影格數
繪圖效能的重要指標之一是 *FPS*(每秒影格數)，表示每一秒內連續顯示的畫面幀數。
透過眼睛感官的視覺暫留現象，FPS 對於動態畫面的流暢度有決定性的影響。
所謂的 FPS 在實務上有多種含義：

[square]
* 影片資料的影格率(frame rate)，記載了建立內容所使用的 FPS。
* 影片檔案設定的 FPS，表示製作該影片時預設播放用的 FPS。
* 播放程式實際播放影片時，產生畫面的 FPS。
* 螢幕硬體的 FPS 即為螢幕的刷新頻率，一般為 60Hz。

播放程式會依據影片檔案設定的 FPS 來播放，除非軟硬體的處理速度不足因而達不到要求。
如果播放程式處理每一影格的時間(frame time)小於影片檔案資料預設的 FPS 分之一，
那麼就表示播放程式在硬體與軟體的協助下，有能力達到更高的 FPS，但實際播放的結果仍然會被螢幕的 FPS 所限制。

當軟體的整個或部分視窗一直出現可見的重刷動作，或是播放影片時快速前進會造成宕機，表示動態顯示的 FPS 過低。

=== 桌面環境
載入 X 伺服程式與顯示模組之後，預設衹會出現一個單調灰色的桌面背景，以及一個形如 X 字母的滑鼠游標。


某些桌面環境要求有加速功能的顯示模組，因而基於影格緩衝區的模組將無法進入桌面環境。

滑鼠指標出現不正常跳動、殘影等問題，有可能是桌面環境的**合成器**(compositor) 所引起。

==== 熱插拔回應
GNOME 桌面環境的熱插拔回應，是由 `gnome-settings-daemon` 程式中的 RANDR 插件所控制。
它會將熱插拔之前曾經調整過的螢幕設定，記錄在 `$HOME/.config/monitors.xml` 檔案之中，
這使得解析度下降或丟失的問題較少出現，或是出現後藉由再次插拔而能夠自動復原。
GDM 也支援此一設定檔案，但是要先複製到 `/var/lib/gdm/.config/` 目錄中才會有作用。

MATE 桌面環境的設定則是依據下列結構描述的指令輸出而定：
====
user$ *gsettings get org.mate.settings-daemon.plugins.xrandr default-configuration-file* +
user$ *gsettings get org.mate.settings-daemon.plugins.xrandr use-xorg-monitor-settings*
====
預設是使用 `/etc/mate-settings-daemon/xrandr/monitors.xml` 檔案的內容，但是無法同樣應用於 LightDM。

==== 專屬程式
套件 `igt-gpu-tools` 包含了許多與 Intel GPU 相關的專屬程式，例如 `intel_gpu_top` 可用來顯示目前 GPU 的負載狀況；
`intel_reg` 命令可以用來顯示不同狀態下（例如系統懸置再喚醒）GPU 暫存器的值以提供比對。
套件 `radeontool` 中的專屬程式雖然可以用來檢驗顯示模組的參數，但僅僅適用於過時的 AMD Radeon 系列繪圖卡。

==== 應用軟體
顯示裝置的圖形介面設定軟體中，展示出的模式選項雖然也是基於顯示器傳來的 EDID 資料，
但是桌面環境有時會自行增刪解析度或掃描方式，導致設定後的結果與預期不符，或是熱插拔時發生黑屏或溢出範圍的情形。
如果直接執行對應的 `xrandr` 指令卻正常的話，就可以推測是圖形介面設定軟體的問題；
當然也有可能因為某臺顯示器的 EDID 資料無法被解析，而導致圖形介面設定軟體崩潰。

多數圖形環境登入所需的顯示管理程式以及視窗管理程式，仍然無法順利與 `XWayland` 配合。
有些 X 視窗系統的桌面環境應用軟體，衹能與 `Xorg` 伺服程式溝通，尚未被修改成與 `XWayland` 相容。
如果必要使用的軟體是封閉原始碼，就衹能期待供應商儘快完成移植工作。

有些軟體本身就支援不同的加速來源，也會對效能產生影響。
例如播放程式 `mpv` 的 `--hwdec` 選項接受 `auto|vdpau|vaapi` ，而 `--vo` 選項則接受 `opengl|vdpau|vaapi|gpu` 等選項值之一。
日益複雜的應用軟體為了提高效能，會逐漸增加自行處理繪圖機制的比例。
當畫面出現閃動或字形顯示不正常的情況，也許能夠透過關於伺服程式或加速程式的設定來解決，可以試試關閉個別的圖形加速選項，或是設定環境變數 `LIBGL_DRI3_DISABLE=true` 。

  
