== 檔案與目錄
簡單來說，操作電腦就是執行程式去處理資料，而程式與資料則是來自於儲存媒體上的軟體。
軟體在媒體上是以樹狀的邏輯形式儲存，作業系統則將其視為檔案與目錄的結構來管理。

關於 UNIX 類的作業系統，有一句常常會聽到的描述：「一切都是檔案」。
雖然並非百分之百正確，但是做為揭示 Linux 作業系統架構的特色，仍然是十分恰當的描述。

=== 檔案系統
檔案系統是對於磁碟分割區的格式化劃分。
如果將分割區看成是所有書頁未切割前拼成的一張大紙，那麼檔案系統就是書的編排格式。
譬如每頁的大小、每行或每列的間隔與長度，都會隨格式不同而有差異。
就像是漢字書籍可以用直式或橫式排版一樣，分割區上的檔案系統也十分多樣。

==== 種類
基於開發歷史、存取效率、功能需求、專利限制…等原因，每個作業系統都有其主流的檔案系統。
至於是否能夠支援舊式、罕用或是其他作業系統的檔案系統，取決於能否載入適當的驅動程式。
網路儲存裝置也有它們專用的檔案系統，通常是由負責的網路協定所決定。

[width="80%",options="header"]
|=============================
|作業系統| 主流檔案系統 | 舊式檔案系統 |次常用檔案系統| 網路檔案系統
|Linux|Ext4|Ext3, Ext2|ZFS, BtrFS, XFS|NFS
|Windows|NTFS|FAT32|exFAT, ReFS|CIFS, SMB
|DOS|FAT16|FAT12||NWFS
|=============================

==== 路徑
Linux 使用**路徑**(path) 來指明檔案或目錄在檔案系統中的位置。
路徑是由一連串的目錄與檔案名稱所組成，彼此以正斜線分隔，並依照檔案系統中的層級關係排列。

完整的路徑是由正斜線起始，表示檔案系統的**根目錄**(root directory)。
然後就從檔案系統樹狀結構的根部開始，列出途中經過的目錄名稱，最後到達目標的檔案或目錄。
這種完整的路徑表示方法稱為**絕對路徑**，而不以正斜線起始的表示方法則稱為**相對路徑**，意思是指相對於工作目錄的位置。
路徑的最大長度為 4096 字元，而不包含正斜線的單一名稱，可以算是最簡化的相對路徑。
如果沒有特別強調，提到路徑時即包括了絕對路徑與相對路徑，當然也包括了單一檔案名稱與單一目錄名稱。

=== 檔案系統階層
作業系統於執行期間所能控制的整個檔系統樹狀結構，即稱之為**檔案系統階層**(file system hierarchy)。
就像一棵由根目錄起始的大樹，向上分支出如同枝幹的目錄，而目錄中還會長出如同樹葉的檔案，或是再分支出子目錄。
由於檔案系統階層是一個邏輯性的概念，因此有可能涵蓋了多個儲存分割區上的檔案系統，同時包括了作業階段才建立的虛擬目錄。

在 Linux 檔案系統階層中，根目錄之下是一些屬於第一層的子目錄：
====
user$ *ls -F /* +
bin@   dev/  home/  lib64@  mnt/  proc/  run/   srv/  tmp/  var/ +
boot/  etc/  lib@   media/  opt/  root/  sbin@  sys/  usr/
====
即使不利用 `-F` 選項來為目錄與鏈結名稱附上辨識符號，目前 Linux 系統預設的 `ls` 命令也會以顏色來區分不同類型的檔案或目錄名稱。
如果想看看檔案系統階層的模擬樹狀結構，外部命令 `tree` 就可以滿足這個需求。
以下粗略地將其分為三類來介紹：系統目錄、個人目錄、虛擬目錄。

==== 系統目錄
開機後最先載入的**內核**(kernel) 程式，也是系統運行時期最重要的作業中心，一般都會放在 `/boot` 目錄之中。
檔案名稱通常是 `vmlinuz` 再加上版本號碼，以便與共存的其他版本做區分。
目錄中還包括了內核需要的**初始記憶體檔案系統**(initramfs)，以及其他同樣依版本區分的附帶檔案。
由於內核所在的檔案系統限制較多，又或者基於安全的考量，常會將 `/boot` 從 `/` 之下分離出來，做為獨立分割區的掛載點。

傳統的 UNIX 系統中，開機過程中有可能用到的命令程式會放在 `/sbin` 或 `/bin` 路徑之中，而前者所含的程式通常需要超級使用者(root) 的身分才允許執行。
適合較新 64 位元硬體架構的軟體函式庫，會存放在 `/lib64` 路徑之下，而適合舊式 32 位元硬體架構或與硬體架構無關者，則會置於 `/lib` 路徑之下。

`sbin`, `bin`, `lib`, `lib64` 等目錄名稱在 `/usr` 路徑下會再次出現，這是由於傳統大型主機將 `/usr` 做為獨立分割區的掛載點，甚至會使用網路檔案系統來掛載。
一些開機時期非必要、一般使用者才會用到的程式與函式庫，就被放到了 `/usr` 之下相對應的子目錄中。
但是經過了在個人電腦上的演變影響，分離掛載的 `/usr` 路徑已無太大的實用性，甚至還出現了合併 `sbin` 與 `bin` 兩個目錄的提議。
因此目前較流行的做法，是維持 `/` 與 `/usr` 在同一個分割區中，避免直接引用根目錄之下的前述四個目錄，
並將它們做為 `/usr` 路徑下同名目錄的軟式鏈結（參閱本章稍後的〈檔案屬性〉），以維持與傳統軟體的相容性。

由此可知 `/usr` 是檔案系統階層中最主要的分支，除了命令程式與函式庫之外，
還包括像是 `/usr/include` 之下的軟體開發標頭檔案(header files)，以及存放了各類資料檔案的 `/usr/share` 路徑。
另外 `/usr/libexec` 則儲存了一些雖然是可執行檔案，但是實際上不適合做為命令直接呼叫，而是由其他命令間接執行的程式。

系統中各項軟體的組態預設值，一般會儲存在 `/etc` 路徑的同名檔案或子目錄之中，做為該軟體的**全域設定值**(global settings)。
軟體在執行期間所動態產生的資料，通常會儲存在 `/var` 路徑下依照軟體性質與名稱分類的子目錄之中。
例如傳統上儲存於 `/srv` 之下的各類伺服器資料，許多已經轉移到 `/var` 或 `/var/lib` 中使用。
而某些特殊用途的系統，仍然會利用 `/opt` 路徑來儲存整套軟體。

==== 個人目錄
每次的命令殼作業階段，都會隨時記錄著一個稱為**工作目錄**(work directory) 的 `PWD` 變數，
做為使用者目前在檔案系統上所處位置的指標，而登入後預設會位於**家目錄**(home directory)。
一般使用者的家目錄是在 `/home` 路徑之下，與使用者賬號同名的子目錄。
例如使用者 user 的家目錄就在 `/home/user` ，但是超級使用者的家目錄固定預設為 `/root` 。
家目錄的位置會依照身分記錄在 `HOME` 變數中，而路徑如果是以波浪號(~)開頭，且做為單一目錄名稱使用的話，則會被命令殼代換為家目錄。
舉例來說， `~/Downloads` 代表的路徑等同 `$HOME/Downloads` ，都是表示常用的個人下載目錄。

家目錄中還有一些子目錄對映著系統目錄的角色，但是僅限於該使用者讀寫，而且衹對該使用者有作用。
例如 `$HOME/bin` 中含有可執行檔案， `$HOME/.local/share` 中含有各類資料檔案，而 `$HOME/.config` 則做為類似 `/etc` 的軟體**本地組態檔**(local configuration) 儲存位置。

==== 虛擬目錄
由於 Linux 是多人多工的作業系統，因此每位使用者都受到其身分的限制，尤其反映在對於檔案的存取能力上。
一般使用者除了家目錄以下具有完整的檔案讀寫權利之外，系統中大部分檔案對其而言都是唯讀的。
但是 `/tmp` 目錄較為特殊，一般使用者均允許在其中建立衹有自己才能讀寫的目錄與檔案。
做為暫時性的檔案存放位置，路徑 `/tmp` 預設衹存在於記憶體中的虛擬檔案系統，其中的資料於關機後就會消失。

Linux 系統上的硬體，都是以裝置檔案的形式，出現在檔案系統階層的 `/dev` 路徑之下。
例如 `/dev/sda1` 代表了第一顆 SATA/USB 磁碟上的第一個分割區，而 `/dev/mmcblk1p2` 代表了第二顆 eMMC/SD 磁碟上的第二個分割區。
NOTE: 每種裝置都有各自獨特的命名規則與初始編號數字。
而 `/media`, `/mnt` 主要用來**掛載**(mount) 其他儲存裝置分割區。

系統開機時需要存取的**內核映像**(kernel image) 與**初始記憶體檔案系統**(initial RAM filesystem)，固定儲存於 `/boot` 之中。
目前主流的 UEFI 開機模式，它的開機分割區需要 `vfat` 格式的檔案系統，
因此 Linux 的檔案系統階層，會將開機分割區（假設是 `/dev/sda1` 裝置）掛載於 `/boot/efi` 目錄之下，
而主要資料所在的根分割區（假設是 `/dev/sda2` 裝置）則掛載於 `/` ，成為檔案系統的根目錄。

**行程**(process) 表示系統運行時的個別執行程序，而作業系統運行階段的所有行程，集合起來成為行程階層。
命令 `ps` 將會列出目前由使用者所執行的行程，如果加上 `-aux` 命令列選項的話，就可以看到系統中所有行程的詳細列表。
行程列表中有一欄稱為 PID，代表該項行程的流水識別號，常用來做為其他命令的參數使用。
例如：執行 `kill -9 _PID_` 表示向相應的行程發送 KILL(砍除) 的訊號，用來強制該項行程的程式結束。
其他常用的類似命令還有 `pkill` 與 `xkill` ，分別依程式名稱與滑鼠點選來決定要強制結束的行程。
若是想看到樹狀的行程階層，則需要執行 `pstree` 外部命令，就會發現整個系統的行程都是由 `systemd` 這個行程所帶動的
（這個 PID 為 1 號的初始行程，可能仍維持著傳統的 `init` 程式名稱）。

行程階層是邏輯性的樹狀結構，完全衹存在於系統作業階段。
檔案系統階層中的 `/proc` 路徑以下，是行程階層的一種映射型式，動態對應著個別行程的資訊。
類似目錄還包括 `/sys` ，代表著系統軟硬體階層的映射，同時可以做為存取各組成設定值的介面。

=== 檔案類型
多數的檔案都支援**魔術字元**(magic number) 的自我標識，也就是以檔案開頭的固定位置、固定個數字元來標識類型。
其他軟體也是依靠這個方法，識別收到的資料是否屬於可以處理的對象。
文字模式的 `file` 工具程式，除了利用這個特性之外，還會配合解析檔案內容，讓使用者能夠初步識別某個檔案的類型。
====
user$ *echo _測試資料_ | gzip -c > foobar.unknown* +
user$ *file _foobar.unknown_* +
foobar.unknown: gzip compressed data, from Unix, truncated +
user$ *file _/usr/bin/file_* +
/usr/bin/file: ELF 64-bit LSB pie executable, x86-64, ...
====

=== 檔案屬性
每個檔案除了本身的名稱以及在檔案系統階層中所處的位置以外，還具備了一些**屬性**(attribute)。
利用後面小節〈相關命令：目錄操作〉中提到的 `ls` 命令，能夠列出檔案或目錄的屬性：
====
user$ *ls -la _$HOME_* +
總用量 24
drwx------ 3 user   user   4096  4月 16 12:58 . +
drwxr-xr-x 4 root   root   4096  4月 16 12:58 .. +
-rw-r--r-- 1 user   user     18  9月 27  2022 .bash_logout +
-rw-r--r-- 1 user   user    141  9月 27  2022 .bash_profile +
-rw-r--r-- 1 user   user    492  9月 27  2022 .bashrc +
drwxr-xr-x 4 user   user   4096  7月 23  2021 .mozilla
====
列出的資料如果以空格區隔，可以分為 9 欄，依次為：
屬性字串、鏈結數量、擁有使用者、擁有群組、資料大小、修改月分、修改日號、修改年分、名稱。

==== 屬性字串
儲存媒體上的一般資料可以視為是正規的檔案，在檔案屬性字串的第一個字元顯示為 `-`(減號)。
正規檔案是由一群向後鏈結的區段所組成，彼此在實際的儲存媒體上不必然會緊接在一起。
目錄也可以視為是一種檔案，就像書中的目次也佔據著書中的頁數，其中記載著成員（檔案或目錄）的名稱、屬性與鏈結，
檔案屬性字串首字元則標記為字母 `d` 。
`/dev` 目錄下常見的磁碟類型儲存裝置，會被歸類為**區塊**(block) 裝置，於檔案屬性字串的第一個字元標記為 `b` 。
至於大部分的輸出輸入類型裝置，則是以字母 `c`(communication) 做為檔案屬性字串首字元的標記。

屬性字串除去首字元之後的 9 個字元，決定了檔案或目錄的屬性。
其中每 3 個字元為一組，每個字元由左到右分別代表讀取(r)、寫入(w)、執行(x)的屬性，而 3 組則依次規定了這個檔案或目錄的擁有者(u)、擁有群組(g)以及其他人(o)的權限。
讀寫屬性中如果有字母標記的部分，表示該分組具備該屬性的權利，否則會以 `-` 來表示受到限制。
這三種屬性的權限對於檔案而言，很容易依照字面上的意思來理解，就是限定了是否能夠讀取(r)、寫入(w)以及執行(x)該檔案。
而對於目錄來說，則要注意可以執行(x)是表示允許列出其中所含的檔案或子目錄。
另外在較新的系統中，屬性字串還可能出現第 11 個字元，用來表示與 SELinux 有關的存取控制性質。

衹有檔案或目錄的擁有者或是超級使用者，被允許利用 `chmod`(change mode) 命令來修改屬性字串。
`chmod` 的第一個參數是讀寫屬性的設定值，可以接受權限代號或者八進制數字模式之一，而第二個之後的參數則為想要改變的檔案或目錄名稱。
最常使用的 `chmod` 命令選項是 `-R`(recursive) ，表示遞迴進入參數中的目錄以設定屬性。
====
root# *ll _file.ext_* +
-rwxrwxrwx 1 user   user   3628  5月 14  2023 file.ext +
root# *chmod 644 _file.ext_* +
root# *ll _file.ext_* +
-rw-r--r-- 1 user   user   3628  5月 14  2023 file.ext +
root# *chmod +x _file.ext_* +
root# *ll _file.ext_* +
-rwxr-xr-x 1 user   user   3628  5月 14  2023 file.ext
====
NOTE: Linux 還支援另一套獨立但功能強大卻較少使用的屬性，相關的命令包括 `lsattr` 與 `chattr` 。

==== 鏈結與大小
**軟式鏈結**(soft/symbolic link) 類似其他作業系統中的捷徑，是僅有一條內容的檔案，註記著建立鏈結的目標檔案或目錄位置。
軟式鏈結的檔案屬性字串首字元，是以字母 `l` 做為標記。
設定軟式鏈結是利用 `ln`(link) 命令加上 `-s` 選項，以及相對於目標的來源路徑與目標路徑，而取得鏈結的相關命令則為 `realpath` 與 `readlink` 。
較新的 Linux 系統，為了解決多版本軟體要決定預設的問題，所採取的**替代方案**(alternatives) 機制，也是基於軟式鏈結的特性。

屬性列表的第二欄，表示與其他檔案或目錄產生的鏈結數量。
對於目錄來說，相當於其中所含子目錄的數量（已經加上 `.` 與 `..` 兩者）。
檔案的鏈結數量通常為 1，並不會計入軟式鏈結的數量，除非曾經產生過**硬式鏈結**(hard link)。
依照檔案系統的內部處理觀點，鏈結數量降為 0 時，即表示檔案或目錄被完整刪除。

當命令輸出資料大小資訊時，通常是顯示實際內容所使用的位元組數量。
由於資料在媒體上是以區塊的形式儲存，因此檔案或目錄實際佔用的空間，要略大或等於它們實際的內容大小。

==== 擁有權
簡單來說，檔案或目錄的建立者就是它的擁有者，而該使用者所屬的群組，就成為了此檔案或目錄的預設擁有群組。
如果使用者並不符合屬性列表第三、第四欄所列出的身分，那麼對於這個檔案或目錄而言，就衹能做為其他人來看待。

變更檔案或目錄的擁有權則需要透過 `chown`(change ownership)，同樣衹允許擁有者或超級使用者執行命令。
第一個參數是擁有權的設定值，由新的擁有者與擁有群組以冒號相連而成，而第二個之後的參數則為想要改變的檔案或目錄名稱。
`chown` 最常使用的命令選項是 `-R`(recursive) ，表示遞迴進入參數中的目錄以設定擁有權。
====
root# *ll _file.ext_* +
-rwxr-xr-x 1 user   user   3628  5月 14  2023 file.ext +
root# *chown root:root _file.ext_* +
root# *ll _file.ext_* +
-rwxr-xr-x 1 root   root   3628  5月 14  2023 file.ext
====

==== 修改日期
屬性資料以第 6, 7, 8 欄，來顯示檔案或目錄的最近一次修改時間(change time)。
如果加上額外的選項，還可以選擇改為顯示它的建立時間(birth time)，或是最近一次的存取時間(access time)。
顯示的前兩欄分別代表月分與日號，第三欄通常是顯示年分，但是如果與現在時間相差半年以內的話，則改為顯示時分的值。

外部命令 `touch` 加上檔案或目錄名稱做為參數，以及透過 `--date=_DATETIME_` 選項設定的字串，可以用來修改時間的屬性資料。
假如工作目錄中不存在 `_file.ext_` 檔案，那麼在工作目錄中執行 `touch _file.ext_` 指令，就會建立一個名為 `_file.ext_` 的空檔案，
與 `echo -n > _file.ext_` 指令有相同的效果，而檔案的三項時間戳記，則會一致設為目前的時間。

==== 檔案名稱
Linux 的檔案名稱長度一般不能超過 255 個字元。由於一個常用漢字在 UTF-8 編碼中，相當於以 3 個字元來表示，
因此檔案名稱長度的限制，會小於或等於 85 個漢字。

雖然依照規範衹有正斜線(/) 與空字元(\0) 在檔案名稱中禁止出現，但是實務上會去避免使用〈命令列模式：命令殼〉中提到的中繼字元。
檔名後段常會以句號(.)分隔出一組較短的字串，習慣上稱之為**副檔名**(file extension)。
它的功用主要還是在方便使用者分辨檔案類型，對於作業系統本身並沒有意義。
大部分的軟體衹會將它做為參考，並不會因為副檔名而限制了處理的方式。

習慣上以句點做為起始的名稱，會被多數的應用軟體視為預設隱藏，而需要額外的選項或設定才會顯示。
這項性質並非來自系統層級，而是命名規則特例所產生的約定俗成效果。
其中還包括兩個特別的目錄名稱：.（單一句點）代表當前的工作目錄；..（雙重句點）代表上一層目錄。
除了單獨做為命令的參數使用，也可以混合在路徑名稱之中。

=== 常用命令
有些命令衹能用來操作目錄，而有些命令衹能用來操作檔案。
其實目錄可以視為一種特殊的檔案，因此許多命令都能混合接受目錄與檔案做為參數。

==== 檔案系統操作
在之前的小節中提到，檔案系統階層是依靠掛載來加入新的檔案系統裝置。
既有檔案系統中的任何一個空目錄，都可以做為**掛載點**(mount point) 來使用。
就好像在一段光秃秃的枝條上，再嫁接上一叢外部的枝葉。
掛載與取消掛載的外部命令分別是 `mount` 與 `umount` ：
====
root# *mkdir -p _/opt/data_* +
root# *mount _/dev/sdb1 /opt/data_* +
root# *cp -a _/root/data/\* /opt/data_* +
root# *umount /opt/data*
====
NOTE: `umount` 命令的拼法需要特別注意。

有些輸出中含有（檔案、目錄、分割區）容量大小的命令，如果加上了 `-h` 選項，
代表的並不是常見的求助(help)，而是人類可讀(human-readable) 的意思。
這會將與位元組數量有關的數值，以 1024 的倍數單位呈現。

如果想要知道檔案系統的大致情況，最常用的是外部命令 `df`(disk freespace)。
====
user$ *df -h* +
檔案系統	     容量   已用   可用  已用% 掛載點 +
devtmpfs        4.0M     0  4.0M    0% /dev +
tmpfs            16G     0   16G    0% /dev/shm +
tmpfs           6.3G  1.5M  6.3G    1% /run +
/dev/sda2        77G   61G   12G   84% / +
tmpfs            16G  4.0K   16G    1% /tmp +
/dev/sda1       599M   33M  567M    6% /boot/efi +
tmpfs           3.2G   56K  3.2G    1% /run/user/0
====

至於個別目錄分支所佔用的儲存容量，可以利用外部命令 `du`(disk usage)，搭配適當的引數獲得：
====
user$ *du -hs $HOME/\*/* +
166M	/home/user/bin/ +
4.0K	/home/user/Desktop/ +
1.5G	/home/user/Documents/ +
925M	/home/user/Downloads/
====

==== 目錄操作
列出目錄內容的內建命令 `ls`(list) 是最常用的命令殼動作。
對於想要列出內容的路徑，就將目錄或檔案名稱接在後方做為參數。
如果不加任何參數，則會列出工作目錄的內容。

`ls` 預設會以多行對齊的方式，將內容顯示於終端機畫面上。
如果加上最常用的 `-l` 選項，則會改為每項檔案或目錄都佔一列的詳細顯示方式。
為了方便使用者輸入，許多 Linux 散佈版也會將 `ll` 預設成 `ls -l` 的別名。
另外還有取消預設隱藏的 `-a` 選項，能夠將以 `.` 開頭的檔案或目錄也顯示出來。

內建命令 `cd`(change directory) 用來變更工作目錄的指標，也會相應改變 `PWD` 變數。
如果提示字串中含有工作目錄的話，就會更新為目前的值。
由於 `cd` 與當前的命令殼行程緊密地連結，因此做為相容目的而存在的 `/usr/bin/cd` 外部命令，甚至連替補的角色都無法扮演。

`cd` 後方通常接著一個目錄的路徑，可以是絕對路徑或相對路徑。
使用者當然也可以分層分批地多次輸入命令，最後仍然會到達目標的目錄位置。
一般使用 `cd` 的原因，是希望在之後輸入其他命令的參數時，可以使用相對路徑的簡單名稱；
或是在執行某些外部命令時，方便它在工作目錄中搜尋並調用相關的檔案。

實務上常常使用 `cd ..` 回到上一層目錄，或是執行 `cd ../_foobar_` 移動到同層的其他目錄。
當單獨使用一個減號(-) 做為參數時， `cd -` 特別表示回到之前的工作目錄。
如果不加任何參數，則會依照變數 `HOME` 的值，將工作目錄變更到使用者的家目錄。

目錄的建立與刪除則分別需要 `mkdir` 與 `rmdir` 內建命令。
如果 `mkdir`(make directory) 使用單一名稱做為參數，表示在工作目錄中以該名稱建立一個空的子目錄；
而以目錄路徑做為參數時，可能需要加上 `-p` 選項，才能依次建立上層的目錄，避免目錄不存在的錯誤發生。
需要注意的是， `rmdir`(remove directory) 的目標目錄，必須是不含檔案或子目錄的空目錄。

==== 檔案操作
有許多的方法可以用來新增一個檔案：
如果想將檔案拷貝一份，需要執行像是 `cp _file.ext_ _file.new_` 的指令；
但是如果想變更檔案名稱或是覆寫檔案，就要輸入類似 `mv _file.ext_ _file.new_` 這樣的指令。
指令 `ln _file.ext_ _file.lnk_` 會從 `file.ext` 建立出一個名為 `file.lnk` 的硬式鏈結檔案。
而指令 `ln -s _file.ext_ _file.lnk_` 則會建立出一個軟式鏈結檔案。

想要刪除檔案時則需要使用 `rm`(remove) 命令，後面接著一至多個檔案名稱。
`rm -r` 指令則可以接受目錄做為參數，能夠刪除即使含有檔案或子目錄的非空目錄。
利用指令 `mv _file.ext_ /dev/null` 將檔案搬移到特殊的空裝置，也同樣具有刪除的效果。
以上的方法衹會斷開檔案內容在目錄中的連繫，並不會抹除檔案的實際內容。

搜尋檔案或目錄主要有兩種方法：使用 `locate` 或是 `find` 外部命令。
執行 `locate` 命令前，需要先以超級使用者身分執行過 `updatedb` ，這會建立一個檔案系統階層的名稱資料庫，然後就可以利用 `locate` 加上部分名稱字串做為參數進行搜尋。
`find` 命令則是採取比較直接的方式，從使用者指定的目錄開始，比對以下層級的所有檔案或目錄，並依據指令中的條件過濾出顯示的結果。
====
user$ *sudo updatedb* +
user$ *locate _r8169_* +
/usr/lib/modules/6.2.14/kernel/drivers/net/ethernet/realtek/r8169.ko.xz +
user$ *find _/usr/lib/modules_ -name _r8169.ko.xz_* +
/usr/lib/modules/6.2.14/kernel/drivers/net/ethernet/realtek/r8169.ko.xz
====

當系統的儲存空間用盡，可能會出現很多奇怪的狀況：無法開機、無法顯示、無法登入、無法執行程式。
最好是利用外接系統開機，再掛載目標裝置後進行清理，藉由執行 `find _/mnt_ -size +1G` 指令來尋找巨大檔案。

=== 額外工具

* 徹底抹除檔案內容：`wipe`, `shred`, `scrub`
* 記憶變更的工作目錄並回復：`pushd`, `popd`
* 批次更改檔案名稱：`rename`, `mmv`
