== 環境初始化
作業系統在內核載入時期，程式碼是在**內核空間**(kernel space) 中執行，而之後的一般程式則執行於**使用者空間**(user space)。
這是兩個虛擬的程式運行層級，代表著程式對於系統的掌控位階。
更一般的說法則是將使用者空間對應為 *Ring3*(第 3 環)、內核空間對應為 *Ring0*(第 0 環)，
而 UEFI 以及 CPU 內嵌的小型作業系統，則對應到更內層的負數環。

=== 初始階段
等到內核成功掛載實際的根目錄檔案系統之後，便會卸載前面階段所用的記憶體檔案系統，
並且依照 `/etc/fstab` 檔案中的設定，掛載其他指定的儲存裝置做為實際運行的檔案系統階層。

==== 一號行程
內核運行進入第二階段後，第一個執行的外部命令為 `init` ，同時也獲得了**行程編號**(PID) 1。
傳統 SysV 作業系統沿續下來的 `init` 版本，會呼叫一連串、分門別類的 rc(run commands) 檔案，內容由命令稿組成。
目前較流行的實作，是將 `/usr/sbin/init` 鏈結到 `/usr/lib/systemd/systemd` 這個**守護程式**(daemon)，然後觸發各類型的**服務**(service)。
每項服務大致對應之前的 rc 檔案，呼叫一到多個能夠共同完成特定任務的程式，舊式的服務控制命令，則被導向並轉換為流行版本的 `systemctl` 命令。
例如啟動網站伺服器的 `service _httpd_ start` 指令，在 Systemd 模式下的寫法為 `systemctl start _httpd_` ；
而設定成自動啟用的 `chkconfig _httpd_ on` 指令，則需要改為執行 `systemctl enable _httpd_` 以達到作用。

==== 目標狀態
傳統的 SysV 模式將系統狀態分為不同的**執行層級**(runlevel)，而在 Systemd 模式的軟體架構下則稱之為**目標**(target)。
兩者之間的對應關係與代表意義如下：

[width="80%",options="header"]
|=============================
|執行層級|目標|代表意義
|0|poweroff|關機
|1|rescue|救援狀態（單人、無網路）
|2|(multi-user)|多人狀態（文字介面、罕用）
|3|multi-user|多人狀態（文字介面）
|4|(multi-user)|多人狀態（文字介面、罕用）
|5|graphical|圖形介面狀態
|6|reboot|重新開機
|=============================

桌面系統的預設狀態為圖形介面，是由 `systemctl set-default graphical` 指令所設定。
一般而言，達到圖形介面目標需要啟動以下軟體：

. **顯示管理程式**(display manager)：GDM、KDM 或 LightDM
. **視窗系統**(window system)：X（Xorg 或 XWayland）
. **接待程式**(greeter)：GDM Greeter 或 LightDM GTK Greeter
. **桌面環境**(desktop environment)：GNOME、KDE 或 MATE
. **作業階段管理程式**(session manager)：GNOME Session 或 KDE Session
. **視窗管理程式**(window manager)：Marco 或 KWin
. **桌面應面程式**(desktop application)：網頁瀏覽器或終端機仿真器

如果開機前想要進入文字介面，可以利用舊式的內核參數單一數字 `3` 來暫時變更此次的執行層級。
如果之後都衹想要進入文字介面，就需要執行 `systemctl set-default multi-user` 指令。
下次啟動時，系統就會停留在**虛擬終端機**(VT)與文字登入程式，登入成功後再由命令殼提供命令列操作模式。
大多數的 Linux 系統會支援多個虛擬終端機，但是整體的數量與之後替換為圖形介面的數量與位置，仍然會因散佈版而異。
使用者可以在 `/etc/systemd/logind.conf` 檔案中設定 `NAutoVTs` 項目的值，來決定自動生成的虛擬終端機數量。
以常見的 6 個虛擬終端機為例，可以透過按下組合鍵 kbd:[Ctrl - Alt - F1] 至 kbd:[Ctrl - Alt - F6] 之一的方式進入，而背後代表虛擬終端機的裝置則是 `/dev/tty1` ～ `/dev/tty6` 。

=== 初始化檔案
系統各階段都有許多的初始化檔案，大部分是由系統內部機制所控制，並不適合由超級使用者或一般使用者去修改。
另外有一小部分的檔案，預設會在系統各階段自動執行，同時適合進行客製化的編輯：

[square]
* 系統初始化
** `/etc/rc.d/rc.local`: 由 `/usr/lib/systemd/system/rc-local.service` 控制執行
** `/etc/systemd/system/*.service`: 由 `systemd` 控制執行
** `/etc/profile.d/*.sh`: 由 `/etc/profile` 呼叫執行
* 使用者初始化
** `$HOME/.bash_profile`: 由命令殼程式 `bash` 讀取執行
** `$HOME/.bashrc`: 由命令殼程式 `bash` 讀取執行
* 圖形階段初始化
** `/etc/X11/xinit/xinitrc.d/*.sh`: 由 `/etc/X11/xinit/xinitrc` 呼叫執行
** `/usr/share/xsessions/?.desktop`: 依據顯示管理程式的組態檔設定
** `/etc/xdg/autostart/*.desktop`: 由桌面環境的啟動程式讀取執行
** `$HOME/.config/autostart/*.desktop`: 由桌面環境的啟動程式讀取執行

==== rc-local 服務
`rc-local.service` 是 Systemd 基本內建的服務，主要是為了相容 SysV 系統初始模式中，本機自動執行命令稿 `rc.local` 的功能。
系統在文字模式初始化後期，會啟動 `rc-local.service` 服務來嘗試執行 `/etc/rc.d/rc.local`（或是 `/etc/rc.local` ）外部命令中的內容。

./etc/rc.d/rc.local
....
#!/usr/bin/bash
# 適用於伺服端：
/usr/bin/iperf3 -s &
(/usr/bin/sleep 16;/usr/bin/systemctl restart dhcpd dhcpd6)&
# 適用於客戶端：
dhclient -6 -nw
....

特別適合未被 `systemd` 納入為服務單元的伺服器，做為開機時的自動啟動命令稿，或是其他命令的補充機制。
建立檔案之後，要以 `chmod +x /etc/rc.d/rc.local` 指令將它設定為可執行。
需要注意的是，由於該時期的環境變數尚未設置完全，因此所有的外部命令最好以完整的路徑名稱來呼叫，或是先加入系統規範命令稿中所含的環境指令。
命令 `rc.local` 是以叉生方式執行，其中設定的命令殼變數並不會繼承給其他的程式使用，而且為了保險起見，其中的命令最好是附加 `&` 以丟到背景中執行。
由於還在文字模式中，因此無法執行需要圖形介面的程式，有些命令可能還需要停用 `selinux` 。

==== 自訂服務
藉由目前一號行程 `systemd` 的機制，可以很方便地建立一個初始執行的服務：

./etc/systemd/system/foobar.service
....
[Unit]
Description=_FooBar_ Service
After=network-online.target

[Service]
Type=forking
ExecStart=/usr/bin/_foobar_
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
....

由於是自訂的服務，因此需要自行啟動並/或設定為自動啟用。

==== 系統初始化
系統初始階段的主命令殼，會自動讀取系統規範命令稿 `/etc/profile` 的內容並執行，主要目的是設定系統全域所需的環境變數。
基於與舊版相容與未來擴充的考量，目前的 `/etc/profile` 已成為 `/etc/profile.d/` 目錄中所有規範命令稿的前端呼叫程式。
個別軟體可以視需要，在目錄中加入自己的規範命令稿，而不用去修改 `/etc/profile` 的內容。
一般來說，同一個軟體會準備兩個相同功能的規範命令稿，以 `.sh` 與 `.csh` 做為副檔名，
分別適用於兩種最常見的主命令殼類型，而最低限度至少要提供 `bash` 適用的 `*.sh` 版本。
如果是系統全域而非特定軟體相關，或是針對命令殼的設定，則可以直接寫在 `sh.local` 檔案中。

./etc/profile.d/sh.local (部分)
....
HISTSIZE=4096
HISTCONTROL=ignoredups:erasedups
HISTIGNORE=history:cd:exit:ls:pwd:man
export HISTSIZE HISTCONTROL HISTIGNORE
....

==== 使用者初始化
當使用者進入命令列互動模式時，都會先讀取並執行使用者家目錄中的 `.bashrc` 。
至於是從文字模式的虛擬終端機登入畫面而來，或是開啟自圖形模式的終端機仿真器，可藉由 `tty` 命令判斷。
若是使用者登入系統所用的**登入命令殼**(login shell)，則會讀取並執行 `.bash_profile` （有些散佈版是 `.profile` ）檔案。
雖然傳統上會區分適合放在兩個檔案中的命令，但是由於散佈版預設 `.bash_profile` 前段會先讀取並執行 `.bashrc` 的內容，
因此衹需要將命令寫在個人的命令殼規範命令稿 `.bash_profile` 內即可。

.$HOME/.bash_profile (部分)
....
PS1='\[\e[33m\]\u@\w> \[\e[0m\]'   <1>
LESS='-MXr'   <2>
MORE='-e'   <2>
export PS1 LESS MORE   <3>
alias df='df -h'   <4>
alias joe='joe --wordwrap'   <4>
....
<1> 設定命令殼提示符號
<2> 設定**換頁程式**(pager) 引數預設變數
<3> 確認變數可被環境中其他程式繼承
<4> 設定別名以方便命令輸入

==== 圖形階段初始化
在 Systemd 的系統初始模式中，是由 `graphical.target` 代表圖形階段的執行目標，並且會啟動顯示管理程式。
Linux 系統提供許多不同的顯示管理程式，而使用者所選用的就會軟式鏈結到被啟動的 `display-manager.service` 服務。
顯示管理程式接著執行 `X` 伺服器命令（通常是 `Xorg` 或 `Xwayland` 的軟式鏈結），以建立 **X 視窗系統** ，
同時執行 `/etc/X11/xinit/xinitrc` 去呼叫 `/etc/X11/xinit/xinitrc.d/` 中的命令稿程式，用以初始化圖形階段。

使用者在圖形階段下從登入到登出的操作過程，稱之為一次 **X 作業階段**(X session)。
當顯示管理程式所執行的**接待程式**(greeter) 處理完使用者的登入之後，顯示管理程式就會呼叫登入命令殼，然後在圖形階段的基礎上建立使用者的 X 作業階段。
最陽春的 X 作業階段畫面上，可能除了終端機仿真視窗之外空無一物，但一般的使用者還是期望看見一個能滿足各種需求的**桌面環境**(desktop environment)。
適用於桌面環境的程式，通常會有一個對應的組態檔(`*.desktop`)，用來指明軟體的名稱、路徑、描述、圖示、綁定類型等資料。
安裝好的 X 作業階段在 `/usr/share/xsessions` 目錄中會有對應的組態檔，做為承接顯示管理程式的呼叫，並且後續呼叫其他的組態檔。
對於較複雜的桌面環境而言，通常還會執行一個**作業階段管理程式**(session manager)，用來統一管理其中所有的軟體行程。
以下是一個筆者自製的簡單 X 作業階段 Thiny
footnote:[A Thin and Tiny X Session <https://github.com/bluebat/thiny-session>]的組態檔範例：

./usr/share/xsession/thiny.desktop (部分)
....
[Desktop Entry]
Type=Xsession
Name=Thiny
Comment=A Thin and Tiny X Session
Exec=thiny-session
....

為了解決軟體在不同的桌面環境之間的**互操作性**(interoperability)，多數的桌面環境都會遵循由 freedesktop.org 組織所倡議的 *XDG*(X 桌面工作群組) 標準：
包括了一些共用的環境變數，以及標準化的檔案名稱與路徑。
例如 `/etc/xdg/autostart/` 目錄存放了套用於所有桌面環境的自動啟動組態檔，個別的桌面環境還會讀取類似 `/usr/share/_gnome_/autostart/*.desktop` 檔案的內容，
而使用者自訂的自動啟動組態檔則可以放在 `$HOME/.config/autostart/` 之中。
另外 XDG 標準也建議了一些通行於不同散佈版或桌面環境的命令，例如 `xdg-user-dirs-gtk-update` 就是用來管理個人家目錄中，常用的子目錄名稱，
而指令 `xdg-settings set default-web-browser _firefox_.desktop` ，會將系統預設的網頁瀏覽器設定為 Firefox 。

如果是跳過圖形階段目標與顯示管理程式，直接從文字模式經由 `startx` -> `xinit` -> `X` 的方式進入圖形環境，
有的散佈版會讀取執行 `/etc/X11/Xsession` 以及 `/etc/X11/Xsession.d/` 目錄中的檔案，
然後讀取執行使用者家目錄中的 `.xinitrc` 、 `.xsession` 或是 `.Xclients` 命令稿檔案，
某些散佈版的 X 作業階段還會支援讀取 `$HOME/.xprofile` 的內容並執行。
使用者需要在以上檔案中自行啟動已安裝的桌面環境，或是手動執行自訂桌面環境所需的個別程式。
個人圖形環境自動執行命令稿的內容舉例如下：

....
xrandr --output HDMI-1 --mode 1920x1080   <1>
x11vnc -forever -repeat -passwd ******** &   <2>
rxvt -fg white -bg black -fn xft:size=20 &   <3>
Telegram -noupdate &   <4>
....
<1> 有些特殊的螢幕配置，無法利用桌面環境的圖形設定介面達成。
<2> 有些個人化的守護程式，沒有提供方便的執行方法。
<3> 萬一桌面環境沒有提供執行終端機仿真程式的方法，必須至少呼叫一個出來。
<4> 有些第三方的免費軟體，安裝後沒有提供啟動組態檔。當然也可以自製一個組態檔，放在個人的自動啟動目錄：

.$HOME/.config/autostart/telegram.desktop
....
[Desktop Entry]
Version=1.0
Type=Application
Encoding=UTF-8
Name=Telegram
Name[cmn_TW]=電報
Comment=Desktop version of Telegram Messenger
Comment[cmn_TW]=電報傳訊軟體桌面版
Exec=Telegram %U   <1>
Icon=telegram   <2>
Terminal=false   <3>
StartupNotify=false
Categories=Network;Application;
MimeType=x-scheme-handler/tg;
....
<1> `Telegram` 可執行程式應該安裝於環境變數 `$PATH` 所含的目錄中，否則需使用絕對路徑。
<2> 圖示檔案 `telegram.*` 應該安裝於系統會搜尋的圖示目錄中，否則需使用絕對路徑。
<3> 如果要執行的程式是文字介面，這裡就應該設為 `Terminal=true` 。

==== 語區初始化
豐富的**語區**(locale) 支援是自由軟體的特色之一，同樣一套系統就可以依照不同的語言與地區作出介面的改變。
語區的名稱長度並非固定的，從最原始的 `C` 到複雜的 `cmn_TW.UTF-8` 都有可能，而個別軟體的支援程度也不相同。
雖然基本的硬體測試都是以 *en_US*(英語－美國) 為標準，但是由於對使用者體驗有顯著影響，因此還是有需要了解一下。

開機管理程式 GRUB 雖然接受設定檔中的 `grub_lang` 做為語區的變數，但是一般並未特別去設定。
GRUB 指令列傳給內核的參數中，有時也會出現語區設定，通常也衹會影響記憶體檔案系統階段的畫面訊息。
進入實用系統時，則是依靠最主要的系統函式庫 `glibc` 來提供語區的支援機制。
標準的系統語區設定命令範例如下：
====
root# *localectl set-locale LANG=_en\_US.UTF-8_*
====

初始化階段可能具有影響力的檔案包括 `/etc/environment`, `/etc/locale.conf`, `/etc/default/locale`, `/etc/sysconfig/i18n` 。
部分顯示管理程式也可能會讀取諸如 `/var/cache/_lightdm_/dmrc/$USER.dmrc` 以及 `$HOME/.dmrc` 檔案中的設定。
即時的語區設定值，則是以 `LANG` 配合以 `LC_` 為名稱起始的一群環境變數所記錄，
因此對於國際化支援不佳的較舊程式，可以在執行前單獨設定語區為原始值試試：
====
user$ *LC_ALL=C _xload_*
====
要獲得完整的使用者體驗，還需要輸入部分：輸入法伺服程式、輸入法引擎、輸入法模組，以及輸出部分的支援：字型、本地化介面翻譯。

登入文字模式時，有些散佈版會直接或間接讀取執行 `/etc/profile.d/lang.sh` 的內容，其中可能將一些無法完全以 ASCII 字元編碼顯示的語區改回 `en_US` 。
如果在個人的規範命令稿中執行了 `fbterm` 之類的程式，讓虛擬終端機能夠顯示萬國碼字元，就可以將語區環境變數的值再修改回來。

.$HOME/.bash_profile (部分)
....
export LANG=cmn_TW.UTF-8
fbterm
....
同樣方式也適用於使用較新顯示機制的 `kmscon` 第三方軟體。

=== 自動登入設定
由於測試的需求，例如要進行長時間的重覆開關機測試，就需要將系統設定為不需詢問密碼而自動登入。

==== 空密碼限制
有些散佈版預設不允許直接以 `root` 身分登入，因此安裝時沒有設定 `root` 的密碼。
如果想要以 `root` 身分自動登入，就必須先設定好密碼，否則可能會被其他的機制所阻擋：
====
root# *passwd* +
更改使用者 root 的密碼。 +
新的密碼： ******** +
再次輸入新的密碼： ******** +
passwd：所有認證字組都已成功更新。
====
實際操作時，輸入的密碼 `********` 並不會顯示。

==== 圖形登入限制
如果仍然需要選擇使用者，但是希望不需輸入密碼即可登入，可以利用命令將使用者的密碼清空：
====
root# *passwd -d _user_*
====

如果希望固定以使用者 `user` 的身分自動登入，那麼依照顯示管理程式的不同，需要修改各自的設定檔：

./etc/gdm3/custom.conf (部分)
....
[daemon]
AutomaticLoginEnable=true
AutomaticLogin=user
....
./etc/lightdm/lightdm.conf (部分)
....
autologin-user=user
....
./etc/lxdm/lxdm.conf (部分)
....
autologin=user
....

==== 文字登入限制
如果之前執行過 `systemctl set-default multi-user` 指令，系統啟動後就會停留在文字登入畫面，
而這個畫面是由 `/usr/lib/systemd/system/getty@.service` 服務所控制。
由於虛擬終端機的畫面是基於影格緩衝區裝置，並且不是開機後最優先執行的軟體，因此需要等待一下才會準備完成。

通常想要修改系統服務時，不會去直接編輯系統目錄下的檔案，因此可以先拷貝到 `/etc/systemd/system/getty@.service` ，
然後再搜尋其中執行 `/sbin/agetty` 的指令，加入 `--autologin _user_` 的引數：

./etc/systemd/system/getty@.service (部分)
....
ExecStart=-/sbin/agetty --autologin _user_ --noclear - $TERM
....

==== PAM 限制
以上提到的各種限制，也可能會受到隨插式認證模組所管控。
設定檔案是位於 `/etc/pam.d/` 目錄中的文字檔，通常由各個軟體分別讀取名稱相關的固定檔案。
例如 `lightdm`, `lightdm-autologin`, `lightdm-greeter` 等檔案，負責控管顯示管理程式 LightDM 的認證過程。
另外還有一些常被軟體設定檔所包含，因而對於整個系統都有作用的設定檔，像是 `system-auth`, `password-auth` 等等。

如果想要設定為以 `root` 身分自動登入，而本章前述的限制都已解除，但是系統仍然拒絕通過，就有可能是受到 PAM 機制所阻擋。
可以在 `/etc/pam.d/*` 中搜尋以下條目，並且於列首加上註解符號(#) 後再試試：
....
#auth       required    pam_succeed_if.so user != root quiet_success
....

