== 環境初始化
作業系統在內核載入時期，程式碼是在**內核空間**(kernel space) 中執行，而一般的程式則執行於**使用者空間**(user space)。
這是一種虛擬的程式運行層級，代表著程式對於系統的掌控位階。
更一般的說法則是將使用者空間對應為 *Ring3*(第 3 環)、內核空間對應為 *Ring0*(第 0 環)，
而 UEFI 以及 CPU 內嵌的小型作業系統，則對應到更內層的負數環。

==== 一號行程
內核運行進入第二階段後，第一個執行的外部命令為 `init` ，同時也獲得了**行程編號**(PID) 1。
傳統 SysV 作業系統沿續下來的 `init` 版本，會呼叫一連串、分門別類的 rc(run commands) 檔案，內容由命令稿組成。
目前較流行的實作，是將 `/usr/sbin/init` 鏈結到 `/usr/lib/systemd/systemd` 這個**守護程式**(daemon)，然後觸發各類型的**服務**(service)。
每項服務大致對應之前的 rc 檔案，呼叫一到多個能夠共同完成特定任務的程式，
而傳統的 `service` 服務控制命令，則被導向並轉換為流行版本的 `systemctl` 命令。
例如啟動網站伺服器的 `service _httpd_ start` 指令，在 `systemd` 環境中的寫法為 `systemctl start _httpd_.service` 。

==== 目標狀態
傳統的 `init` 將系統狀態分為不同的**執行層級**(runlevel)，而在 `systemd` 軟體架構下則稱之為**目標**(target)。
兩者之間的對應關係與代表意義如下：

[width="80%",options="header"]
|=============================
|執行層級|目標|代表意義
|0|poweroff|關機
|1|rescue|救援狀態（單人、無網路）
|2|multi-user|多人狀態（文字介面、罕用）
|3|multi-user|多人狀態（文字介面）
|4|multi-user|多人狀態（文字介面、罕用）
|5|graphical|圖形介面狀態
|6|reboot|重新開機
|=============================

桌面系統的預設狀態為圖形介面，是由 `systemctl set-default graphical` 指令所設定。
一般而言，達到圖形介面目標需要啟動以下軟體：

. **顯示管理程式**(display manager)：GDM 或 LightDM 或 KDM
. **視窗系統**(window system)：Xorg 或 XWayland
. **接待程式**(greeter)：GDM Greeter 或 LightDM GTK Greeter
. **桌面環境**(desktop environment)：GNOME 或 MATE 或 KDE
. **作業階段管理程式**(session manager)：GNOME Session 或 KDE Session
. **視窗管理程式**(window manager)：Marco 或 KWin
. **桌面應面程式**(desktop application)：Browser 或 Terminal Emulator

如果開機後衹想要進入文字介面，可以執行 `systemctl set-default multi-user` 指令。
下次啟動時，系統就會開啟虛擬終端機與文字登入程式，登入成功後再由命令殼提供命令列操作模式。

=== 自動執行檔案
系統各階段相關的啟動檔案包括：

[square]
* 初始階段
** `/etc/rc.d/rc.local`: 由 `/usr/lib/systemd/system/rc-local.service` 控制
** `/etc/profile.d/*.sh`: 由 `/etc/profile` 呼叫
* 桌面階段
** `/usr/share/xsessions/?.desktop`: 依據顯示管理程式的組態檔設定
** `/etc/X11/xinit/xinitrc.d/*.sh`: 由 `/etc/X11/xinit` 呼叫
** `/etc/xdg/autostart/*.desktop`: 由桌面環境的啟動程式呼叫
** `$HOME/.config/autostart/*.desktop`: 由桌面環境的啟動程式呼叫
* 命令列模式
** `$HOME/.bash_profile`: 由命令殼程式 `bash` 呼叫
** `$HOME/.bashrc`: 由命令殼程式 `bash` 呼叫

==== rc-local 服務
`rc-local.service` 是 `systemd` 基本內建的服務，主要是為了相容於 SysV 初始系統模式中，本機自動執行命令稿 `rc.local` 的功能。
系統於文字模式初始化後期，會啟動 `rc-local.service` 服務來嘗試執行 `/etc/rc.d/rc.local` 外部命令中的內容。

./etc/rc.d/rc.local
++++
#!/usr/bin/bash
#適用於伺服端：
/usr/bin/iperf3 -s &
(/usr/bin/sleep 16;/usr/bin/systemctl restart dhcpd dhcpd6)&
#適用於客戶端：
dhclient -6 -nw
++++

特別適合未被 `systemd` 納入為服務單元的伺服器，做為開機時的自動啟動命令稿，或是其他命令的補充機制。
建立檔案之後，記得要以 `chmod +x /etc/rc.d/rc.local` 指令將它設定為可執行。
其中需要注意的是，由於該時期的環境變數尚未設置完全，因此所有的外部命令最好以完整的路徑名稱來呼叫；
同時由於還在文字模式中，因此無法執行需要圖形介面的程式。

