== 輸入裝置
各類輸入裝置雖然依功能可分為鍵盤裝置與指標裝置，但在使用者空間都會受到 `libevdev` 與 `libinput` 函式庫的管理。
`libevdev` 透過系統守護程式 `systemd-udevd` 來管理裝置事件，參考檔案位於 `/usr/lib/udev/hwdb.d/*.hwdb` （或是 `/lib/udev/keymaps/*` ）。
如果想要即時更新，可以執行 `systemd-hwdb update` 指令以取得最新的硬體資料庫。
對於本機專有的硬體裝置，則可以自行編輯 `/etc/udev/hwdb.d/_local_.hwdb` 來加入特殊的設定項目。
命令 `udevadm` 則提供了許多的子命令，用來顯示(`info -e`)、控制(`control`) 或測試(`test`) 裝置事件。

第三方套件 `input-utils` 中，也包含了一些基於 `libinput` 的工具程式。
從 `/proc/bus/input/devices` 的內容中，可以看到所有輸入裝置的另一些資料。
其中一項 Handlers: 顯示出的裝置代號，表示系統是以這些處理常式來對應它。
例如滑鼠的處理常式可能是 `mouse0` 和 `event2` ，代表系統會以 `/dev/input/mouse0` 和 `/dev/input/event2` 做為與裝置溝通的介面，
因此可以利用指令 `od -x /dev/input/event2` 來監看訊號。

命令 `evtest` 適合用於測試各種輸入事件，附加的 `--grab` 選項可以避免想要測試的事件去觸發其他的應用軟體。
執行命令後會出現所有輸入裝置的列表，例如在筆記型電腦上的結果像是：
====
user$ *evtest --grab* +
No device specified, trying to scan all of /dev/input/event* +
Available devices: +
/dev/input/event0:      Lid Switch +
/dev/input/event1:      Sleep Button +
/dev/input/event2:      Power Button +
/dev/input/event3:      AT Translated Set 2 keyboard +
/dev/input/event4:      Touchpad +
/dev/input/event5:      Video Bus +
/dev/input/event6:      WMI hotkeys +
/dev/input/event7:      HDA Intel PCH Headphone +
/dev/input/event8:      HDA Intel PCH HDMI/DP,pcm=3 +
/dev/input/event9:      USB OPTICAL MOUSE +
Select the device event number [0-9]: ▊
====
選擇想要測試的軟體介面編號之後，就可以進行輸入動作，並觀察顯示出來的事件訊息。

=== 鍵盤裝置
現代的電腦鍵盤是由早期的終端機鍵盤演變而來。
具備 84 顆按鍵配置的稱為 AT 型鍵盤，具備 101 鍵的則為 AT 加強型，
後續又發展出增加 kbd:[Super]（視窗鍵，即為 kbd:[Window]）與 kbd:[Menu]（選單鍵）的 103 鍵變體。
另外 kbd:[CapsLock]、kbd:[NumLock]、kbd:[ScrLock] 三個鎖定鍵，各自具備對應的狀態指示燈。

==== 介面
舊式電腦需要 i8042 控制器來驅動 PS/2 介面的鍵盤，接頭還有大型與小型的分別。
如果開機時沒有連接，系統會認不到熱插拔的裝置，甚至有可能導致宕機。
萬一開機時已連接卻仍無法找到裝置，也許可以試試內核參數 `i8042.nopnp` 以忽略與實際不符的 PNP(隨插即用) 資訊。
稍後的機型即使沒有 i8042 控制器，仍有可能開啟本來由其控制的鍵盤與外部裝置通訊埠，因而繼續支援 PS/2 介面。
另外有些機型即使具備 i8042 控制器，也可能會將不需使用的外部裝置通訊埠關閉。

目前除了部分筆記型電腦的內建鍵盤還會使用 PS/2 介面之外，大部分的新產品都採用 USB 介面。
由於鍵盤不需要快速的傳輸速度，因此大多衹支援舊式的 USB 1.1 規格。
雖然 USB 介面一般都有向下相容性，但是有些系統韌體仍需要額外開啟舊式 USB 的支援選項。

除了可以透過相關模組參數來設定裝置的輪詢間隔(polling interval)，或是加入共通的內核參數 `drm_kms_helper.poll=0` 之外，
有時仍要利用內核參數 `usbhid.quirks=` 來提供一些設定值，以滿足某些裝置未被自動識別出來的**怪癖**(quirk)。
經由 `lsusb` 命令可以辨識出來，通常被系統視為一種**人機介面裝置**(HID) 並由內核模組 `usbhid` 驅動，較特別的硬體則需要搭配額外的 `hid_*` 模組。
如果想要傾印 HID 裝置的描述或串流資料，可以參考 `usbhid-dump` 命令的使用說明。


鍵盤的硬體動作轉化為電子訊號送出時，會經過 ACPI 而觸發它的按鍵事件。
一般電腦的電源、重置按鈕以及筆記型電腦的上蓋，也都會觸發 ACPI 的按鍵事件。
另外某些具有額外按鍵的非標準鍵盤，如果出現了沒有輸出訊號的狀況，可以加入內核參數 `noapic nolapic iommu=soft` 試試。
萬一不得已必須透過介面轉接頭，即使選用了主動式的轉接頭，仍要注意可能有某些按鍵會失去作用。

==== 鍵盤碼
從鍵盤控制器傳送給系統的**掃描碼**(scancode)，會再轉換為**內核鍵碼**(kernel keycode)，然後由 udev 對應到**按鍵事件**(key event)的名稱。
但是 X 會自行解讀掃描碼，並將其轉換為 *X 鍵碼*(XKEYCODE)，然後進一步對應到 *X 鍵符*(XKEYSYM)的名稱。
X 視窗系統可以透過 `xinput` 命令來設定輸入裝置的組態，並且利用 `xev` 命令來顯示 X 事件的內容。
NOTE: X 還有一個類似名稱的 `xinputrc` 命令稿，於視窗系統初始時載入以設定多語言輸入法。

掃描碼實際上還有不同集合(set) 的區分，有些鍵盤支援多個集合，有些衹支援單一集合，可以透過通訊埠讀取或寫入設定。
透過附加內核參數 `acpi_osi=Linux` 的方式，用來確認通知系統韌體會轉換成適當的掃描碼集合，而作業系統接收到的，則是標準化後的掃描碼。
NOTE: PS/2 介面的非標準鍵盤經過 PS2USB 轉換後，某些掃描碼會被排除掉。一般的轉接頭衹有變更線路，需要主動式晶片才能進行較完整的轉換。
按下或放開按鍵時，分別會產生一個像是 `e05f` 與 `e0df` 的掃描碼（少數按鍵放開時不產生），兩者之間固定相差 `0x80` 。
對於未知而無法轉換為內核鍵碼的掃描碼，內核會將其過濾掉，除非加入了內核參數 `atkbd.softraw=0` 。

指令 `showkey --scancodes` 會顯示後續按鍵的掃描碼，而預設的選項 `--keycodes` 用來顯示內核鍵碼，相關的檔案是 `/usr/include/linux/input.h` 。
內核鍵碼所對應的按鍵事件，可以參考 `/usr/include/linux/input-event-codes.h` 檔案中的內容。
掃描碼與內核鍵碼的匹配列表，可以藉由 `kbd` 套件中的 `dumpkeys` 命令列出，變更時則要用到 `setkeycodes` 命令。

鍵碼是以 255 之內的整數來表示，但同一個按鍵的內核鍵碼與 X 鍵碼並不會相同。
X 鍵符通常是代表按鍵意義的英文單字或組合詞，其中的英文字多採首字母大寫。
執行指令 `xev -event keyboard` 之後，按下任意鍵就會顯示對應的 X 鍵碼與 X 鍵符。
命令 `xmodmap` 用來將 X 鍵碼（重新、附加）對應到 X 鍵符，可以透過命令列或檔案 `$HOME/.Xmodmap` 的方式來設定。
`xkeycaps` 是 `xmodmap` 的圖形前端程式，或是使用較新的 `setxkbmap` 工具。

==== 一般按鍵
鍵盤上的一般按鍵直接按下就會產生作用，像是送出英數字元或標點符點，以及常見的功能按鍵。
以下僅列出部分的 X 鍵符與事件代碼：

[width="80%",options="header"]
|=============================
|按鍵意義|X 鍵符|事件代碼|
|螢幕快照|Print|KEY_SYSRQ
|暫停動作|Pause|KEY_PAUSE
|=============================

如果要將標準的 kbd:[\](反斜線) 改為日文鍵盤特有的 kbd:[¥](日圓)：
====
user$ *xmodmap -e "keycode 132 = NoSymbol NoSymbol yen bar"*
====
其中 132 為該鍵的 X 鍵碼，而 yen 則為日圓的 X 鍵符。

kbd:[Pause]（暫停鍵）在常見的 Linux 系統中並沒有預設的功能。

==== 修飾鍵
**修飾鍵**(modifier)包含在特定按鍵組合中必須先按住的前導鍵，以及按下後會切換特定狀態的鎖定鍵。
它們的 X 鍵符與事件代碼如下：

[width="80%",options="header"]
|=============================
|按鍵意義|X 鍵符|事件代碼|
|左側位移|Shift_L|KEY_LEFTSHIFT
|右側控制|Control_R|KEY_RIGHTCTRL
|右側變動|Alt_R|KEY_RIGHTALT
|視窗|Super_L|KEY_LEFTMETA
|選單|Super_R|KEY_RIGHTMETA
|鎖定大寫|Caps_Lock|KEY_SCROLLLOCK
|鎖定數字|Num_Lock|KEY_SCROLLLOCK
|鎖定捲動|Scroll_Lock|KEY_SCROLLLOCK
|=============================

`xmodmap` 的預設選項 `-pm` 即為顯示目前修飾鍵的定義狀況，如果要顯示一般按鍵的定義狀況則使用 `-pk` ：
====
user$ *xmodmap* +
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses): +
 +
shift       Shift_L (0x32),  Shift_R (0x3e) +
lock        Caps_Lock (0x42) +
control     Control_L (0x25),  Control_R (0x69) +
mod1        Alt_L (0x40),  Alt_R (0x6c),  Alt_L (0xcc),  Meta_L (0xcd) +
mod2        Num_Lock (0x4d) +
mod3        ISO_Level5_Shift (0xcb) +
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf) +
mod5        ISO_Level3_Shift (0x5c)
====

kbd:[ScrLock]（捲動鎖定鍵）在虛擬終端機的純文字模式中的作用，反而比較像 kbd:[Pause]。例如執行：
====
user$ *for i in {1..10000}; do echo $i; done*
====
顯示連續的數字時，中途按下 kbd:[ScrLock] 就能暫停螢幕的輸出，再按一次則會繼續。
但是在 X 視窗系統下，如果按下 kbd:[ScrLock] 無法點亮捲動鎖定燈號，表示在 `/usr/share/X11/xkb/symbols/pc` 中並未設定該鍵。
藉由命令 `xmodmap` 還是可以暫時啟用它：
====
user$ *xmodmap -e "add mod3 = Scroll_Lock"*
====
這樣就可以利用 `xset` 命令來點亮或熄滅捲動鎖定燈號：
====
user$ *xset led named "Scroll Lock"* +
user$ *xset -led named "Scroll Lock"*
====
（在虛擬終端機環境下則要使用 `setleds` 命令）。
也可以在辦公室套件的試算表軟體 `oocalc` 中，測試 kbd:[ScrLock] 對於試算表捲動方式的切換功能。

==== 媒體鍵
筆記型電腦鍵盤上常見的**媒體鍵**(media key) 又稱為**動作鍵**(action key)，一般與**功能鍵**(function key) 共位。
有些機型可以藉由系統韌體的設定，來控制是否可以直接按下，或是需要搭配 kbd:[Fn] 形成組合鍵後才有作用。
這是因為 kbd:[Fn] 主要由韌體控制，或是可被部分特殊硬體的內核模組參數所影響。
媒體鍵也不像一般按鍵與修飾鍵一樣，受到輸入裝置中的標準鍵盤所控制，而是由 Video Bus(視訊匯流排) 或 WMI hotkeys(視窗管理儀表快速鍵) 之類的裝置來提供功能。
對於支援 MPRIS(媒體播放器遠端介面規格) D-Bus 介面的應用軟體，可以用 `playerctl` 命令來鏈結到特定按鍵。

以下列出常見媒體鍵的 X 鍵符與事件代碼：

[width="80%",options="header"]
|=============================
|按鍵意義|X 鍵符|事件代碼
|懸置|XF86Sleep|KEY_SLEEP
|減少亮度|XF86MonBrightnessDown|KEY_BRIGHTNESSDOWN
|增加亮度|XF86MonBrightnessUp|KEY_BRIGHTNESSUP
|切換顯示模式|XF86Display|KEY_SWITCHVIDEOMODE
|開關聲音輸出|XF86AudioMute|KEY_MUTE
|減少音量|XF86AudioLowerVolume|KEY_VOLUMEDOWN
|增加音量|XF86AudioRaiseVolume|KEY_VOLUMEUP
|開關聲音輸入|XF86AudioMicMute|KEY_MICMUTE
|開關觸控板|XF86TouchpadToggle|KEY_TOUCHPAD_TOGGLE
|上一首|XF86AudioPrev|KEY_PREVIOUSSONG
|播放/暫停|XF86AudioPlay|KEY_PLAYPAUSE
|下一首|XF86AudioNext|KEY_NEXTSONG
|開關無線網路|XF86WLAN|KEY_WLAN
|=============================

由於每種桌面環境的軟體組成不同，所採用的觸發機制與反應程序也都有些許差異。
有些硬體製造商為了要與特定作業系統相容，還可能會使用非標準的對應碼，甚至繞過產生鍵值的程序，直接以韌體來實作功能。

==== 數字鍵盤
標準鍵盤右側的**數字鍵盤**(keypad)，除了可以透過 kbd:[NumLock] 來切換鍵值之外，也可以用來操作螢幕指標：
====
user$ *setxkbmap -option keypad:pointerkeys*
====
執行以上命令之後，按下 kbd:[Shift - NumLock] 即可切換為滑鼠模式：
按鍵 kbd:[/]、kbd:[/]、kbd:[/] 分別切換對應要模擬的滑鼠左、中、右鍵；
數字鍵 kbd:[0] 表示接下來的按鍵保持按住狀態；數字鍵 kbd:[5] 模擬點擊動作；
小數點鍵 kbd:[.] 表示釋放按鍵的按住狀態；其他數字鍵則用來控制指標移動。

筆記型電腦如果採用小型的鍵盤配置，容易發生鍵盤右側受到整合的數字鍵盤控制的情況，
這是因為設定了開機時自動啟用 kbd:[NumLock] 所造成。

==== 電源按鈕
按下機器上的電源按鈕時，其實也是觸發一個按鍵輸入事件，由名為 Power Button 的輸入裝置所控制。
由於相同機器內 BIOS 與 UEFI 中的 ACPI 實作不同，因此不同開機模式下對於電源按鈕的反應可能會有差異。
在作業系統層級則是由 `systemd-logind` 服務所負責，相關設定可見 `logind.conf` 檔案：

./etc/systemd/logind.conf (部分)
....
PowerKeyIgnoreInhibited=no
HandlePowerKey=poweroff
....
電源按鈕的其他處理方式，還包括 `ignore` 或 `reboot` ，都必須要重啟服務才會立即生效。

==== 鍵盤佈局
系統會藉由偵測鍵盤的硬體資訊（例如供應商識別號或產品識別號），來判定使用何種的按鍵配置。
即使按鍵配置的規格相同，為了支援不同語言而進行的調整稱之為鍵盤佈局(layout)。
雖然不同的語言佈局具有不同的鍵面印刷，但是硬體訊號仍然相同，需要依靠軟體設定來解釋按鍵意義。
內核與 X 視窗系統的鍵盤佈局相關檔案，分別是由 `kbd-misc` 與 `xkeyboard-config` 套件所提供。

測試其他語言的鍵盤佈局時，最好使用客戶實際有使用的單一語言鍵盤，而不要以可切換多種語言佈局的裝置做為測試對象。
如果沒有非英語的鍵盤佈局可以測試時，簡便的方法是將英語佈局調成德語，就會發現其中的 Y 與 Z 兩鍵位置互換。

舊式系統韌體 BIOS 僅包含標準英語的鍵盤佈局，而 UEFI 則具備支援多語言鍵盤佈局的能力。
虛擬終端機的鍵盤語言設定位於 `vconsole.conf` ：

./etc/vconsole.conf
....
KEYMAP="us"
FONT="eurlatgr"
....
還可以利用 `kbd` 套件中的 `loadkeys` 命令，動態載入不同的鍵盤對應。
如果命令列模式下的鍵盤反應有些不正常，則有可能是改動了 `/etc/inputrc` 的內容所造成的。

舊版 X 視窗系統的鍵盤語言是依據相應的設定檔：

./etc/X11/xorg.conf.d/00-keyboard.conf
....
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
EndSection
....
其中未特別指明 `Driver` 項目，而會自動依情況選擇 `kdb`, `evdev`, `libinput` 之一。
目前的系統需要修改 `/etc/default/keyboard` 中的 `XKBLAYOUT="us"` 項目，或是利用 `localectl` 命令來變更它。

==== 按鍵模擬
Xorg 視窗系統下的 `xdotool` 命令能夠模擬按鍵動作，可惜與 Xwayland 不太相容。
假設想要模擬開關觸控板的特殊按鍵，可以輸入：
====
user$ *xdotool key XF86TouchpadToggle*
====
就會送出指定的 X 鍵符，但實際作用仍然取決於是否有對應的處理軟體。
另外 `xautomation` 套件中的 `xte` 程式，也可以用來模擬按鍵動作。

X 視窗環境下有一類稱為**螢幕鍵盤**(on-screen keyboard) 的應用軟體，可以做為實體鍵盤以外的測試參考。
而一些會顯示按鍵資訊的網站
footnote:[鍵盤測試網站 <https://keyboard-tester.com/> 或 <https://key-test.ru/>]，
由於網頁擷取按鍵事件的限制，衹能夠做為媒體鍵或多國語言佈局的輔助測試工具。

==== 命令對應
在圖形介面的桌面環境中，按鍵動作先經過 X 視窗系統轉譯為 X 鍵符，再交由後續的軟體處理。
對於功能鍵、媒體鍵、組合鍵等特殊的按鍵符號，許多桌面環境的應用軟體都包含了觸發機制，並且可以依據設定來執行對應的動作。
例如大部分的視窗管理程式，在接收到與視窗或工作區相關的按鍵時，都能做出適當的反應。

有一些專門用來設定快捷鍵的守護程式，例如利用以下的指令來設定 `xbindkeys` ：
====
user$ *xbindkeys --defaults > _xbindkeysrc_* +
user$ *xbindkeys -f _xbindkeysrc_ --key*
====
隨即按下想要設定的按鍵，就可以利用文字編輯器來修改檔案 `_xbindkeysrc_` 中該按鍵的對應命令。然後以：
====
user$ *xbindkeys -f _xbindkeysrc_*
====
來啟動它，另外還有 `sxhkd` 也是一個類似功能的守護程式。

=== 其他文字輸入裝置

==== 條碼掃瞄器
**條碼掃瞄器**(barcode scanner) 其實是一種模擬鍵盤的裝置，
以光學掃瞄條碼之後，再解析為代碼對應的文字。早期還有扮演簡易讀卡機的功能，
目前多用於快速輸入片段文數字的場合。

如果使用條碼掃描器或舊型鍵盤時偶爾會出現亂碼，可能是因為系統韌體設定中未開啟或不支援舊式的 USB 1.1 裝置。

==== RFID
**無線射頻辨識**(RFID) 的標準為非接觸式的 ISO 14443A/B，其他較不普遍的規格包括 ISO 15693 與 Mifare。
RFID 讀卡機介面傳統為序列埠，或是轉換後的 USB2COM(VCP)，目前也有出現 USB HID 介面的機型。

`rfdump` 是圖形介面的 RFID 標籤讀取軟體，可以讀取內容符合標準的卡片，
而某些測試軟體衹能識別特定的介面。



==== 讀卡機
內嵌晶片的**晶片卡**(IC card) 或稱**智慧卡**(smart card)，是用途相當廣泛的一種辨識卡片。
依照讀取時是否需要與卡片物理接觸，**讀卡機**(card reader) 可以分為「接觸式」與「非接觸式」兩大類。
接觸式的讀卡機通過物理接觸來讀取晶片中的資訊；非接觸式的讀卡機則以採用基於 RFID 的**近場通訊**(NFC) 技術為主。

舊型機種仍有可能使用 PS/2 或 RS-232 接頭，但多數的讀卡機是以 USB 介面連接到主板，因此可以利用 `lsusb` 命令看到它的廠商、產品識別號。
不過這衹表示硬體裝置識別成功，還是需要依此確認內核模組與驅動函式庫，才能進一步透過軟體讀取。
====
user$ *lsusb* +
ID 076b:3031 OmniKey AG OMNIKEY 3x21 Smart Card Reader +
ID 0ca6:0010 Castles Technology Co., Ltd EZUSB PC/SC Smart Card Reader +
                         ：                   ： +
user$ *lsusb -t* +
/:  Bus 05.Port 1: Dev 4, If 0, Class=Chip/SmartCard, Driver=usbfs, 12M +
/:  Bus 04.Port 2: Dev 6, If 0, Class=Chip/SmartCard, Driver=usbfs, 12M +
                         ：                   ：
====

晶片讀卡機遵循的統一軟體介面為 PC/SC(ISO 7816)，由 opensc 套件提供基本與加密介面函式庫。首先安裝基本的套件需求：
====
root# *dnf install opensc pcsc-lite pcsc-lite-ccid pcsc-tools*
====

其中 `pcsc-lite` 套件的 `pcscd` 守護程式負責讀取服務，而在 `lsusb -t` 的指令輸出可以看到歸類於 `Chip/SmartCard` 類別，並以 `usbfs` 軟體模組負責驅動。
如果系統支援熱插拔功能，該服務於讀卡機連接時就會自動啟用，同時也會預設附加 `--auto-exit` 的參數。

`libccid` 是 Linux 系統內建的標準驅動函式庫，支援大多數的讀卡機型號。
有些讀卡機的規格支援 `libccid` 卻無法驅動，是因為尚未登錄於裝置列表，
可以自行修改 `/usr/lib64/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist` ：
袛需要將相關資料加入 `ifdVendorID`, `ifdProductID`, `ifdFriendlyName` 三個鍵值段中，
成為同樣次序的陣列項目。如果測試成功，不妨順便依照 https://ccid.apdu.fr/ 中的說明提出登錄要求。
`libacsccid` 則是基於 `libccid` 的衍生驅動函式庫，同樣內建於大多數的 Linux 系統，它的裝置列表專門收錄 ACS 公司所生產的讀卡機型號。

要是手上的型號無法以 `libccid` 驅動，請先在散佈版的套件庫中搜尋，是否已經有打包好的特定型號驅動函式庫。
萬一套件庫中找不到，就需要去讀卡機廠商的網站，看看是否有提供 Linux 的驅動函式庫。
下面以安裝 Castles EZ100PU 的驅動程式為例：
====
root# *wget https://www.castlestech.com/wp-content/uploads/2016/08/201511920271676073.zip* +
root# *unzip 201511920271676073.zip* +
root# *cd EZUSB_Linux* +
root# *unzip EZUSB_Linux_x86_64_v1.5.3.zip* +
root# *cd EZUSB_Linux_x86_64_v1.5.3/driver_ezusb_v1.5.3_for_64_bit* +
root# *./install* +
root# *systemctl restart pcscd*
====

`pcsc-tools` 套件中的 `pcsc_scan` 用來掃描 PC/SC 裝置以及偵測卡片資料，
如果是手動執行 `pcscd` 並加上 `-f -d` 參數，也能達到類似效果。
在安裝完驅動函式庫並重新啟動服務之後，可以利用這個程式來驗證讀卡機與卡片的可用性。
在文字模式中執行之後，程式會顯示搜尋到的讀卡機型號，並等待使用者插入卡片。
插入卡片後，就會看到卡片狀態跟著變更。

NOTE: 同一套件中還有 `scriptor` 程式，是用來輸出讀卡機指令的文字介面，
但是每種讀卡機的指令集各自不同，需要參考規格才能正確操作。
另外還可以安裝 `esc` 套件，以獲得圖形介面的晶片卡管理程式。

對於某些比較舊或比較新的型號，仍然有機會透過調整系統來成功驅動。
舊型的讀卡機有可能同時受到 `libccid` 與廠商軟體的支援，如果同時安裝兩份驅動函式庫，
反而容易互相干擾。此時可以移除 `libccid` 套件，衹留下廠商的驅動函式庫試試。
由於驅動函式庫支援的型號，都會記錄在各自的純文字 XML 檔案 `Info.plist` 中。
新型的讀卡機如果無法驅動，也許衹是因為它的廠商識別號、產品識別號、產品名稱還沒有加入列表內容。
適當修改 `libccid` 或舊版廠商軟體的列表檔案，說不定就能順利驅動讀卡機。

NOTE: 有些較舊的散佈版與 `pcscd` 搭配的中介軟體是 `openct` 而非 `opensc` ，
對應 `pcsc_scan` 的測試程式則為 `openct-tool` ，但可能不支援新的驅動函式庫。

NOTE: 舊式具備 RS-232 介面的讀卡機，仍然需要序列埠(例如 `/dev/ttyS0` 或 `/dev/ttyUSB0`)，
還可能需要手動軟式鏈結至 `/dev/pcsc/1` 。
而設定檔案另外位於 `/etc/reader.conf.d/` ，內建其中衹有一個使用 `ccidtwin` 驅動程式的範例檔。
如果想要使用特殊的機型，就必須自行準備驅動程式，並修改出適當的設定檔。

NOTE: 某些讀卡機有支援*SAM*(安全存取模組)，通常是以 SIM 卡的型式存在，用來進行異動作業的加密與驗證。
因此在讀寫特殊卡片時，還需要安裝額外的軟體，才能存取到實際儲存的資料。

==== 刷卡機
舊式貼有磁條的卡片，需要利用刷卡機來讀取資訊。

=== 指標裝置

==== 滑鼠
舊式使用序列埠介面的滑鼠，X 是以 `xorg-x11-drv-mouse` 套件提供的 `mouse` 模組來驅動，但是現在已經揚棄不用。
替代方案則是安裝 `linuxconsoletools` 套件，但它衹是一個用來模擬滑鼠的應用軟體，而且似乎很久都沒有更新維護。
安裝後需要執行其中的 `inputattach` 命令以及必要的引數：
====
root# *inputattach --daemon --always _--mouseman_ _/dev/ttyS0_*
====
就會將該裝置加入 `/proc/bus/input/devices` 的內容中。
由於 `inputattach` 是以 `root` 身分執行的命令，指定裝置如果不存在，可能會造成行程無法關閉，即使強制關機也會延遲很久。
而與 X 視窗系統以及顯示驅動模組的相容問題，使得系統懸置也可能會導致它中斷執行。

目前各類介面的滑鼠在 `evtest` 命令中，都會被視為一種輸入裝置，名稱大多含有 Mouse 字串。
X 則將其歸類為指標裝置，統一由 `xorg-x11-drv-libinput` 套件中的 `input` 模組驅動。

無線滑鼠雖然免除了操作時線材的干擾，但是仍有電源、保密以及未經證實的影響健康疑慮。

==== 觸控板
**觸控板**(touchpad) 是一種常見於筆記型電腦的裝置，大多採用 PS/2 或 I^2^C 介面與系統連結。
舊版內核是以 `psmouse` 做為驅動模組，可以藉由模組參數 `proto=` 來設定不同的協定，新版內核則改由 `serio_raw` 模組負責。
在 `evtest` 的顯示中，如果看到含有 Touchpad 字串的名稱，通常就是代表負責控制的輸入裝置。

早期的 X 視窗系統是調用 `xorg-x11-drv-synaptics-legacy` 套件中的 `synaptics` 模組做為驅動介面，衹能支援簡單的手勢動作。
目前也是由 `input` 驅動模組來統一控制，負責觸發事件的支援，實際的多點觸控效果則是由應用軟體來解釋。
觸控板在 `xinput` 命令的輸出中，同樣被歸類於指標裝置。
確認過裝置的 ID（假設是 12）之後，就可以利用 `xinput` 來停用該裝置：
====
user$ *xinput disable _12_* +
user$ *xinput list _12_ | grep disabled* +
　　　　This device is disabled
====
舊式透過 `synaptics` 模組驅動的觸控板，則需要利用 `synclient` 命令來控制：
====
user$ *synclient TouchpadOff=1* +
user$ *synclient TapButton1=1 TapButton2=1 TapButton3=1* +
user$ *synclient VertEdgeScroll=1 VertTwoFingerScroll=1*
====
而有些桌面環境本身也提供了觸控板屬性的存取方式：
====
user$ *gsettings get org.gnome.desktop.peripherals.touchpad send-events* +
'enabled'
====

想要在觸控板上觸發滑鼠右鍵，通常是藉助軟體設定兩點點擊或是特定區域的單點點擊來模擬。
其他常用的手勢包括：兩點上下滑動表示捲動畫面、兩點對向滑動表示縮放畫面。

**數位板**(digitizer tablet)（或稱繪圖板）雖然外觀像是放大的觸控板，卻是由不同的機制所控制。
`xorg-x11-drv-wacom` 套件提供了 X 的驅動模組，內含的 `xsetwacom` 命令則可以加上 `list`, `get` 或 `set` 等選項來操作裝置。

==== 觸控螢幕
**觸控螢幕**(touchscreen) 依照機制可以分為：電容式(projected capacitive)、電阻式(resistive) 以及光學式(optical)。
電容式容易受到來自於電源供應器、主機板、液晶顯示模組的雜訊干擾，需要調整韌體中的參數以取得最適當的設定值。
光學式的發射器與接收器可能在螢幕角落或螢幕邊框，雖然解析度與精確度較差，但是不會影響螢幕玻璃透光度。

如果以連接介面來區分：舊式的機型會與鍵盤與滑鼠共用 PS/2 介面，萬一彼此產生衝突，可以試試內核參數 `i8042.nomux i8042.reset` 來停用晶片的多工選項。
之後出現了使用序列埠的機型，需要在使用者空間以套件 `linuxconsoletools` 中的 `inputattach` 命令來驅動：
====
user$ *inputattach --daemon --always _--mtouch_ _/dev/ttyS4_*
====
範例中假設裝置的協定相容於 MicroTouch 的機型，而連接的介面為 `/dev/ttyS4`(COM3)。
在嵌入式系統中，也可能利用 I^2^C 介面來連接觸控螢幕。


觸控螢幕的系統層級驅動函式庫，基於適用機型以及歷史的演變而利用過不同的機制，例如 `tslib`, `evdev`, `libinput` …等等。
X 視窗系統則以 `xorg-x11-drv-evdev`, `xorg-x11-drv-libinput` 做為調用介面，其中 `libinput` 仍在穩定開發中，適用於較新的輸入裝置。
有些廠商會提供專屬的驅動程式，可能會在系統驅動函式庫之外又產生了一個新裝置，需要注意是否應該停用原本的標準裝置以避免衝突。

X 應用軟體中有許多用來校正觸控螢幕的程式：例如 `touchcal` 套件是專屬於某類機型；
而 `xinput_calibrator` 則是較通用的設定套件，支援不同的格式，讓使用者可以將輸出做為 `xinput` 設定命令的參數使用，或是 X 設定檔的一部分：
====
user$ *xinput map-to-output _ID_ _HDMI-1_* +
user$ *xinput_calibrator --device _ID_ --output-type xorg.conf.d*
====
另外還可以參考看看第三方套件，像是 `x11-touchscreen-calibrator` 或 `xtcal` 所提供的命令。

多螢幕的觸控如果使用同一個驅動程式，需要注意不同介面而造成的不同設定，最好全部採用自動偵測，以免裝置名稱或裝置鮑率互相產生干擾。
多螢幕觸控的螢幕大小如果不同，可能需要自訂功能，其中螢幕範圍的決定是依照整體畫面中各螢幕的比例而定，然後再用校正程式微調。

如果驅動或設定程式無法提供觸控螢幕的右鍵事件，還可以利用 `mousetweaks` 命令將長按左鍵模擬成右鍵。
如果拖曳動作被長按觸發的右鍵事件所插斷，就會造成拖曳動作的中斷，而長按觸發的右鍵事件也有可能鏈結於釋放動作而非按下動作。
除了硬體與驅動程式必要的支援外，多點觸控功能的實作主要還是由軟體決定，因此如果要達到進階的控制或功能，還會需要安裝一個自動啟動的守護程式。

