== 作業系統安裝

=== 系統比較
網路上有數不盡的作業系統相關資源，例如 distrowatch.com 就是一個追蹤數以千計自由/開放原始碼作業系統動態的網站，
除了提供各個系統的鏈結與下載資訊，還有主要組成軟體的版本變動記錄，以及獲得關注的點擊率排名。

=== 散佈版選擇
由以上的說明可知，各類的 Linux 散佈版之間並沒有太大的實質差異。
主要不同的原因在於個別主導組織的政策，影響了所包括軟體套件的廣度與深度，
以及統合基礎套件後而得到的整體觀感。

實務上來說，無法針對所有散佈版進行測試，因此必須做出取捨。
首先要考慮客戶的需求，如果有明確指定、或是客戶將要使用的系統是基於某個散佈版，
那麼當然要將它列入測試名單之中。而對於通用型機種，則要考慮散佈版的普及度、易用性、
更新頻率、社群支援、符合標準等因素。

==== 硬體架構
這裡所謂的**架構**(architecture)，是指一組依不同晶片指令集而分類的 CPU 家族。

早期 PC 使用的是 32 位元的 x86 架構 CPU，包括 i386、i486、i586、i686 等等。
由於幾乎已不再生産此類硬體，因此許多散佈版都停止支援這類架構，在網路上也不容易找到舊版的安裝軟體。
如果真的需要安裝 32 位元作業系統，BIOS 必須支援並且調整為舊式(Legacy) 開機模式。

==== 安裝媒體
iso 檔案是包含光碟完整內容的映像檔格式，依照國際標準「ISO 9660」或稱之為**光碟檔案系統**(CDFS)。
早期的電腦書籍或雜誌中，常常會附贈實體的安裝光碟片。而現在一般的 GNU/Linux 散佈版，
衹會提供 .iso 格式的映像檔，讓使用者自行下載後，再以燒錄機製作出安裝光碟。

安裝光碟的用法是做為開機裝置才能進行安裝程序，因此必須將它設定優先啟動裝置。
BIOS 中的裝置選項可能會出現 CD/DVD 以及 UEFI:CD/DVD，表示這片安裝光碟同時支援 UEFI 與 Legacy 開機模式，
因此實際啟動的模式還會受開機模式的優先順序影響。

如果製作出來的安裝光碟無法讀取，除了確認映像檔與光碟的總和檢查值之外，
還可以檢查看看光碟的標貼(CDLABEL) 是否與光碟中開機載入程式設定檔的內容相同。
或者將光碟機接在不同的埠上（例如從 USB2 換到 USB3），甚至找一臺內接的 SATA 光碟機試試。

ISO 9660 並未使用開頭的 32K 位元組，因此可以填入額外資訊來模擬其他的儲存裝置。
由於 USB 隨身碟容量較大、價格便宜，又有重覆寫入的方便性，因此大部分的 .iso
映像檔都被製作成支援 USB 開機的功能。也就是說，使用者可以像操作磁碟映像檔(.img, .dd)
一樣，將 .iso 檔案以 *dd* 命令直接寫入 USB 隨身碟，製作出可開機的安裝媒體：
--
　　root> *dd if=_install_.iso of=/dev/_sdb_ bs=4M*
--
但是如此也增加了媒體損壞導致安裝過程失敗的風險，因此安裝前建議做好光碟版本的備案，
或是考慮使用精簡型的映像檔（以映像檔開機之後，需要連上網路才能進行套件安裝）。


=== 安裝準備

==== 周邊裝置
對一臺新的硬體型號進行安裝作業系統測試時，周邊裝置的組配應該要儘量簡化，才能減少測試時的變因。
出現問題時可能需要特別留意的地方：

[square]
* 顯示裝置如果規格太新，換一臺比較普通的機型。
* 如果還有支援，試試其他種類的顯示輸出。
* 儘量先不要透過轉接線來顯示輸出。
* 更換不同規格的 USB 連接埠(2.0/3.0)
* 更換不同位置的 USB 連接埠(前端/後端)

==== BIOS 設定
安裝前先確認套用 BIOS 的預設值通常是不錯的選擇，萬一安裝過程不順利或是安裝結果不滿意，才會有一個變更的基礎。
可能造成問題的設定包括了：

[square]
* 開機模式(UEFI/Legacy)
* 安全啟動(SecureBoot)
* 快速啟動(FastBoot)
* 快速儲存技術(RST)
* SATA 模式(IDE/AHCI/RAID)
* USB 的支援版本(1/2/3)
* eMMC 的讀寫速度(HS200/HS400)

==== 儲存裝置
安裝前必須先確認儲存裝置的容量，這會大大地影響安裝過程。隨著功能與複雜度的不斷提升，Linux 系統的大小也持續地增加。
8GB 的磁碟空間已經不敷常見散佈版的標準安裝所需（雖然安裝後實際佔用空間衹有 4~6GB），或是考慮以下〈安裝過程：目標裝置〉小節中所提到的變通方法。
如果安裝軟體有提供精簡版本（例如：LXDE 桌面、基本 X 視窗、最小化）的選項，也可以採用安裝後再自行加入所需軟體的方式，來建構您所想要的環境。

測試系統所用的儲存裝置，當然是以全新品最適合。不過由於常常需要重複測試，還是不可避免會用到安裝過作業系統的裝置。
用過的儲存裝置如果殘留之前的設定，尤其是沒有經過初始分割區表，整支用來儲存資料的隨身碟；
或是曾經被 *dd* 命令直接寫入過光碟映像檔的硬碟，再使用時就可能會造成安裝軟體的誤判。
最好先以外部系統開機（使用自活光碟或是系統閃碟），然後利用 *gdisk* 命令將目標儲存裝置重建空的分割區表。
萬一儲存裝置曾經是 LVM 的成員，卻需要保留舊資料而無法進行格式化，可以試試 *lvremove*, *vgremove*, *pvremove* 等命令。

有些內建混合型硬碟的機型，會發生安裝軟體無法識別的情形，可能是因為其中的兩顆硬碟曾經被加入 RAID 群組。
萬一也要保留舊資料而無法進行格式化，則需以外部系統進入後執行：
--
　　root> *dmsetup remove_all* +
　　root> *dmraid -x /dev/sdb* +
　　root> *dmraid -r -E /dev/sdb*
--
或是手動抹去最前與最後的 1024 位元組（2 個磁區）：
--
　　root> *dd if=/dev/zero of=/dev/sdb bs=1k count=1* +
　　root> *dd if=/dev/zero of=dev/sdb bs=1k seek=$((_磁區數_-2))*
--

更複雜的情況是想要保留儲存裝置上原有的系統，也就是安裝成多重開機的模式。
除了要確認可用空間足夠之外，開機載入軟體的正確安裝與否，將會是系統成敗的關鍵。
安裝順序較後的 Linux 通常都能自動整合安裝較先的其他 Linux，對於 Windows 系統也大多能正確識別，
但是對於 Android, BSD 等系統就需要特別注意。如果還想要使用原先安裝的開機載入軟體，
那麼先要確認對於檔案系統格式與大小的支援限制，以及安裝時必須小心不要將它覆蓋，之後恐怕也無法避免手動的調整。

=== 安裝過程

==== 安裝介面
使用者在安裝過程中面對的操作環境，通常是圖形、文字、網頁三種介面之一：

[square]
* 圖形介面::
標準的安裝介面，通常是功能最完整、操作最方便的模式。如果安裝媒體中的驅動程式支援不佳，
可以加入內核參數 nomodeset，看看能不能進入基本圖形模式，
而有些安裝媒體甚至提供遠端桌面（例如：VNC）的選項。
* 文字介面::
由於顯示器硬體或驅動程式的限制，做為實在無法進入圖形介面時的權宜之計。
不過有些安裝媒體在此介面下，還另外提供了專家模式，允許在安裝過程中進行更細微的調整。
* 網頁介面::
安裝媒體啟動後不提供文字或圖形介面，而是直接建立一個網頁伺服器。
使用者需要利用另一臺機器，透過系統中的瀏覽器來開啟該網路位址的網頁，
然後依照網頁中的功能進行安裝。

==== 內核參數
依據安裝軟體所使用的不同開機載入程式，使用者在安裝媒體啟動時立即按下 [Tab] 或 [e]，
就有機會手動輸入各種不同的參數（或稱密技碼），用來調整內核的執行以解決安裝過程中的問題：

[square]
* nomodeset: 無法進入圖形模式（舊版使用 xdriver=vesa）。
* nortc: 出現無法開啟 rtc 裝置的錯誤訊息。
* pci=nomsi: 裝置或內核較舊導致系統喚醒有問題。
* selinux=0: 載入內核之後出現長時間中止。
* extlinux: 想要安裝另一種開機載入程式。
* iommu=soft: 載入內核之後鍵盤沒有反應。
其他還有 noapic, nolapic, acpi=off 或 acpi=force 可以個別或組合嘗試。

==== 語言與地區
電腦系統中的**語區**(locale) 設定，包括語言設定與地區設定兩大類。
安裝時所選擇的語言，除了會影響安裝介面的顯示之外，也會成為安裝完成後系統的預設語言。
雖然系統語言可以隨時變更，但是由於安裝媒體的發行單位，未必充分驗證過英語以外的語言環境，
因此標準測試仍然應該選擇「英語－美國(en_US)」為優先的語區，
除非客戶的確是在非英語環境中使用，以避免複雜組態（例如：額外的字型、輸入法與空間需求）所造成的差錯風險。

**時區**(timezone) 是安裝過程中與地區設定相關的項目，大多會預設電腦硬體時鐘使用**世界協調時間**(UTC)，
再依照時區設定與配合網路對時的服務，決定系統顯示的時間。
有些系統的安裝過程會提供使用者較多的選擇權力，但有些系統則會根據時區而自動決定其他相關的地區設定。
比較保險的做法是在安裝時選擇美國的時區之一，而在安裝後進入系統執行變更的命令：
--
　　root> *timedatectl set-timezone _Asia/Taipei_*
--

==== 目標裝置
如果硬體中包含了一個以上的儲存媒體（例如內建裝置加上外接裝置），尤其是當您為了測試的可攜性，
而決定將系統安裝在 USB 閃碟之類的移動裝置時，必須注意安裝軟體是否預設選擇了您想要的目標。
萬一已過了選擇的步驟，卻發現預設的儲存裝置錯誤，通常可以藉由安裝軟體的上一步功能，回到之前的步驟來修正。
但是別忘了要同時變更開機載入程式的安裝位置，以免發生根檔案系統與開機載入程式不在同一個儲存裝置（除非是有意為之），
而造成無法單獨由目標儲存裝置開機的情況。

目標儲存裝置的剩餘空間不足，可能會導致安裝軟體的中斷執行，若是剛好稍微低於最小需求，可以採取一些變通方法：
在軟體偵測剩餘空間之前，先插入額外的隨身閃碟或硬碟，等到偵測通過之後再拔除。
如果安裝媒體是先進入**自活系統**(Live System)，再執行以指令稿語言編寫的安裝軟體，
那麼就有機會手動去修改一下程式中的變數值，以繞過空間檢測的限制。

以目前業界標準將開機模式設定為 UEFI 來說，儲存媒體的分割區模式必須採用**全域唯一識別碼分割區表**(GPT)，
相較於舊式 Legacy BIOS＋**主開機記錄**(MBR) 的組合要複雜許多。
因此在安裝過程中，最安全的做法是讓安裝軟體自動産生預設的分割區表（示例如下）：
[width="80%",options="header"]
|===============================================
|分割區	|掛載點		|分割區標籤	|檔案系統
|sda1	|/boot/efi	|ESP		|vfat
|sda2	|/boot		|Linux Native	|ext4
|sda3	|/		|Linux Native	|ext4
|sda4	|		|Linux Swap	|swap
|===============================================

假如您需要手動規畫分割區表，必須注意一定要存在一個 ESP 分割區。
雖然預設會建立第一個分割區，大小約為 500MB 的 FAT32 檔案系統，但是如果 BIOS 與內核的相容性（容錯程度）較高時，
不必位於裝置最前方、280 MB 或更小的容量、FAT12/FAT16 的檔案系統，甚至使用 MBR 分割區模式都是有可能接受的。

/boot 掛載點還可以併入根檔案系統(/)，除非您使用了不支援做為開機分割區的特殊檔案系統。
至於**置換分割區**也可以省略，尤其是當系統具備充足的記憶體時，而其他的決定依據可以參考〈儲存裝置：檔案系統〉章節。

==== 套件選擇
除了精簡型的網路安裝光碟之外，一般的安裝媒體都支援離線安裝，同時在偵測到有網路連線時，
自動更新或下載部分套件。某些安裝軟體還可以讓安裝者依據自身需要，決定是否加入含有非自由軟體的套件庫。
如果安裝後重新開機發生問題，可以試試採用離線安裝的方式，方便確認問題的來源。

==== 命令列模式
先進入桌面環境再執行的安裝軟體，直接打開終端機模擬視窗就能進入命令列模式；
否則可以試試按下組合鍵 [Ctrl-Alt-F2]，看看是否能打開虛擬主控臺。
某些額外的安裝需求衹能藉由輸入命令達到：
像是重建**初始記憶體檔案系統**(initramfs) 來加入支援儲存裝置的內核模組，或是設定固定時間之後自動關機。
--
　　root> *chroot /mnt/sysimage* +
　　root> *dracut -f --add-drivers "sdhci-pci xhci-pci" /boot/initramfs-_內核版本_.img _內核版本_* +
　　root> *sleep _預估安裝完成安全秒數_ ; poweroff*
--
安裝成功進入系統之後，當然不要忘記修改 /etc/dracut.conf.d/ 或 /etc/initramfs-tools/modules，
才能在萬一內核更新而 *dracut* 仍未更新時，繼續保有儲存裝置的支援。

=== 安裝後續
如果安裝過程順利，重新開機後卻無法進入桌面環境，可能有以下幾種原因：

[square]
* BIOS 的開機模式與安裝時不一致。
* 開機載入程式或系統根檔案系統的安裝位置不正確。
* 開機載入程式無法讀取此類型儲存裝置。
* 系統內核不支援或未載入儲存裝置的驅動模組。
* 系統內核對繪圖晶片的支援不佳。
請參考本章之前各節的說明，尋求解決問題的方案。
安裝後的首次啟動，系統預設將會執行一些必要設定。

==== 一般使用者
有些安裝軟體允許衹設定系統管理員 root 的帳號，但是仍然建議不要跳過一般使用者的帳號與密碼設定。
雖然對於臨時的測試系統而言，直接以管理員帳號登入在操作時會十分方便，卻無法準確模擬未來真實的使用情境。
通常安裝軟體都會自動賦予一般使用者暫時切換為管理員的權力，也就是輸入 *sudo* 之後加空格不換列，
再緊接著輸入需要管理員身分的命令，並回答一般使用者的密碼即可。如果一般使用者不具備 *sudo* 的執行權力，
則需要改為輸入命令 *su -* 並回答管理員密碼，才能夠切換成管理員身分。
--
　　user> *sudo dnf update* +
　　[sudo] password for user: +
　　user> *su -* +
　　Password: +
　　root>
--

==== 套件更新
進入系統桌面後的第一件事，建議是立即連上網路進行套件更新。如果更新作業不成功，請查看是否網路未通、
防火牆設定阻擋，或是套件庫的設定不正確。

