== 輸入輸出埠
電腦系統常用的輸出輸入裝置，多隸屬於更上層的**字元裝置**(character device) 類型。

由於 USB 介面的興起，因此新近的輸出輸入裝置多採用 USB 或網路介面，而舊式或是對於速度要求不高的機型，則以 USB 轉出的方式繼續使用。
常見的 USB 轉輸入輸出埠的晶片類型有 FTDI, PL2303, AX781x0 等等，不同型號的晶片所提供的序列埠/平行埠數量有所不同，內核模組的支援程度也有差別。

輸入輸出裝置隨附的記憶體，通常稱為該裝置的暫存器。
裝置暫存器可能對應到一塊系統記憶體位址，亦即經由 `/dev/mem` 存取的 MMIO 機制；或是基於**通訊埠映射輸入輸出**(PMIO) 去對應 `/dev/port` 中的窗口位址。
直接使用時還須注意要關閉安全啟動，並以系統管理者身分執行。例如：
====
root# *printf '\x0b\x83' | dd of=/dev/port oflag=seek_bytes seek=112 conv=notrunc*
====
可以用來停用 RTC 的功能。

=== 列印裝置

==== 連接介面
早期印表機的標準連接介面是**平行埠**(parallel port)，內核所賦予的裝置名稱為 `/dev/lp_N_` ，其中的 `_N_` 是從 0 開始的數字。
例如其他作業系統對於第一個平行埠的稱呼 `LPT1:` ，在 Linux 系統中即為 `/dev/lp0` 。

如果使用了 USB 轉出平行埠的晶片或轉接線，或是印表機本身支援 USB 介面，那麼內核就會載入 `usblp` 內核模組做為驅動程式。
萬一內核沒有正確偵測到，就需要手動載入，才能順利產生 `/dev/usb/lp0` 的裝置名稱，以及 `/dev/usblp0` 的符號鏈結。
也有可能因為將其他 USB 設備誤判為列印裝置，使得 `/dev/usb/lp0` 被佔據，印表機就會分配到 `/dev/usb/lp1` 的裝置名稱。

==== 列印服務
Linux 上的列印功能，也是基於伺服器－客戶端的架構來完成。
CUPS(通用 UNIX 列印系統) 是目前的主流列印服務軟體，在 `systemd` 系統初始模式中是以名為 `cups.service` 的單元形式作用：
====
root# *systemctl start cups* +
root# *systemctl enable cups*
====
實際上執行的程式為 `cupsd` ，負責偵測、驅動與管理可用的列印裝置。
當其他的應用軟體需要列印功能時，就向 CUPS 提出需求，並將待印資料排入佇列之中。

列印服務動作的記錄可由指令 `journalctl -u cups` 顯示，列印任務的記錄會儲存於 `/var/cache/cups/job.cache` 檔案，而列印任務的內容則暫存在 `/var/spool/cups/` 目錄之中。

CUPS 服務的設定檔位於 `/etc/cups/printers.conf` ，可以利用工具程式 `lpadmin` 或是透過它的網頁介面 `http://localhost:631/` 來管理。



對外支援多種列印協定，並提供**統一資源識別碼**(URI) 做為連接的形式：

[square]
* Linux 列印伺服器(LPD)：提供相容於舊式 Linux 系統的印表服務
* 網際網路列印(IPP)：ipp: 提供基於 HTTP 的印表服務
* 網路芳鄰分享(SMB)：smb://username:password@servername/printername 提供相容於 Windows 網路芳鄰印表機服務
* (JetDirect)：提供相容於 HP 所開發的列印服務
* USB
* 平行埠： parallel:/dev/usblp0
* 藍牙： bluetooth:

其中前幾項是網路印表協定，後面幾項則為本機印表協定。
實務上直接連接印表機的情境愈來愈少，因此測試網路印表機的使用有其必要性。

==== 驅動模組
傳統的列印裝置登載檔案位於 `/etc/printcap` ，目前僅僅保留做為相容用途，並由列印服務自動產生。

CUPS 的列印裝置驅動方式，是依靠 *PPD*(PostScript 印表機描述) 類型的文字格式檔案，其中包含了多項的設定值。
在 `/usr/share/ppd/cupsfilters/` 與 `/etc/cups/ppd/` 之中，或者 `/usr/share/cups/model/` 下個別列印型號的目錄內，可以找到對應不同列印裝置的 `*.ppd` 檔案。
例如 `hplip` 及其相關套件，就提供了 HP 廠牌的多款印表機的驅動描述檔案。

對於各種不同格式的列印來源，CUPS 會藉助一或多個**過濾程式**(filter)，最終產生適合印表機直接處理的內容格式（通常是 PostScript）。
目錄 `/usr/lib/cups/filter/` 中存放了許多可執行的過濾程式，提供 CUPS 需要轉換列印內容時呼叫。
例如列印測試頁所用的檔案 `/usr/share/cups/data/testprint` ，會依據範本格式並代入目標印表裝置資訊以產生測試頁內容。
依據目錄 `/usr/share/cups/mime/` 所含檔案的內容，檔頭標註的 `#PDF-BANNER` 就會間接對應到使用 `bannertopdf` 過濾程式來處理。

安裝列印裝置驅動模組時失敗，可能是因為適用的 CUPS 版本不同而導致安裝路徑不正確，或是過濾程式依存的函式庫不相容。

為了設計成本的考量，部分印表機直接以 Windows 系統定義的 *GDI*(圖形裝置介面) 所驅動（角色相當於自由軟體的 cairo），導致在 Linux 系統中無法使用。
變通方法則是在可以驅動該類印表機的 Windows 系統上，安裝適當的過濾程式以及通訊埠轉發程式，或是以虛擬印表機提供網際網路列印服務。

==== 公用程式
由於列印的設定比較複雜，因此大部分的散佈版都提供了圖形介面的組態程式，文字介面的工具衹需要知道名稱即可。

許多與列印相關的公用程式有著類似 `lp*` 形式的名稱，這是因為早期的 UNIX 列印伺服程式名為 `lpd` ，因此將這個命名傳統延續下來。
目前系統中的 `lp`, `lpc`, `lpq`, `lpr`, `lprm`, `lpstat` 等命令，多為 CUPS 軟體所實作程式的鏈結。

大型組織可能還需要更上層的整合系統，做為統一的列印入口，負責管理所有的列印服務與裝置。
除了眾多的專屬套裝選項之外，也可以考慮開放原始碼的 SavaPage
footnote:[SavePage 開放列印入口 <https://www.savapage.org/>]
軟體。

==== 裝置設定
使用收據印表機時，列印紙張一般而言較窄，列印時需要調整將列印的資料靠左放置，以免無法印出東西。
如果印表機是以熱感應方式列印，安裝紙卷時必須注意紙張正反面，因為衹有其中單面才有熱感應效果。

印表機本身的傳輸鮑率必須配合連接埠的設定，通常先按住送紙鍵再打開電源即會印出目前設定。

==== 測試方式
大部分的印表裝置都接受純文字格式的資料，因此對於連接於本機的印表機，可以直接傳送純文字到連接埠：
====
root# *echo 123 test > /dev/_ttyS0_*
====
但是有些以頁為批次列印單位的印表機，需要多送一個**換頁字元**(form feed) 才會開始動作：
====
root# *echo -e 123 test '\f' > /dev/usb/_lp0_*
====

如果此時印表機印出了輸入的文字，就表示兩端的基本連接沒有問題。
萬一印表機有反應卻是印出了亂碼，可能要檢查連接是否確實，或是傳輸設定是否正確。

假設待測印表機支援 ESC/POS 指令集，且接於主機的第一個平行埠，就可以分別傳送初始化與自我測試的指令如下：
====
root# *echo -en "\x1B\x40" > /dev/lp0* +
root# *echo -en "\x1F\x40" > /dev/lp0*
====



=== 序列埠裝置


==== 板端硬體
主機板上的 *UART*(通用非同步收發傳輸器) 晶片，扮演提供序列通訊功能的角色，能夠支援的介面標準包括：RS232, RS449, RS423, RS422, RS485 等等（較新的名稱字首可能改為 EIA-）。
電腦系統上所稱的**序列埠**(serial port)，一般指的就是最常見的 RS232 介面，支援資料的傳送與接收，而像是 RS485 則為簡單 2 線的通訊標準，必須設定為傳送端或接收端之一。
序列埠介面的型式通常使用傳統的 D-sub 連接器，或是常用於電話線的 RJ11 接頭。

常見的型號 8250 晶片一顆可以支援 6 個 UART 埠，如果要增加埠數，需要增加晶片或更換為支援更多埠的型號；
如果是要補足未滿的介面數，則可以採取外接**擴充板**(add-on board) 的方式。
有些散佈版的內核未必啟用全部的 UART 埠，而會透過內核參數 `8250.nr_uarts=4` 衹開啟 4 個埠。
軟體若預設開啟超過硬體規格的埠數，也可能會造成不小心存取到該裝置名稱而產生難以預料的結果，例如關機或重開機時出現延遲，此時使用者就可依需求以類似上述的設定來回復。


==== 裝置名稱
序列埠連接介面通常會被內核賦予 `/dev/ttyS_N_` 形式的裝置名稱，這是由 TTY(電傳打字機) 加上 S(序列)，再加上從 0 開始的數字編號所組成。
例如系統中的 `/dev/ttyS0` 裝置名稱，就相當於其他作業系統用來代表第一個序列埠的 `COM1:` 。

由於配備序列埠晶片、介面的主機與周邊愈來愈少，或是因為想要避免傳統序列埠太多而造成的干擾與系統資源衝突，為了要相容舊式設備，於是就需要支援 USB 轉序列埠的轉換晶片或轉接線。
內核會以類似 `/dev/ttyUSB_N_` 的抽象裝置，來代表經由 USB 介面而連接的序列埠，又可稱為**虛擬序列埠**(VCP) 介面。



==== 中斷請求與通訊埠
輸出輸入裝置的**通訊埠**(communication port)與**中斷請求**(IRQ)，通常是由裝置與系統韌體共同決定。
兩者都是系統的有限資源，周邊設備如果太多可能導致分配不足，因此還引入了熱插拔與共用等機制。
序列裝置的可變性較大，一般會在系統韌體設定中開放，提供使用者調整對應值的機會。

系統目前的中斷請求列表，可以參看 `/proc/interrupts` 檔案的內容，或是經由 `procinfo` 套件中的 `lsdev` 命令檢視。
依據裝置的熱插拔機制不同，以下的內核參數都有可能會影響中斷請求的配發： `isapnp=pci_scan`, `noisapnp`, `pnpbios=on`, `pnpacpi=off` 。

虛擬檔案 `/proc/ioports` 的內容則是系統目前的通訊埠使用分配表。

==== 裝置屬性
經由指令 `dmesg|grep tty` 可以看到關於 TTY 裝置的一些硬體初始資訊， `lsof /dev/ttyS_N_` 則是顯示相關的軟體資訊。
另外在虛擬檔案 `/proc/tty/drivers` 中記錄了負責各類 TTY 裝置的內核模組名稱，而 `/proc/tty/driver/serial` 則可看到個別序列埠裝置所對應的中斷請求。

==== 設定
已停止維護的 `setserial` 命令可以處理較為低階的序列埠設定，可惜已不再收錄於官方的套件庫中。
想要顯示所有序列埠裝置的屬性，可以執行 `setserial -ag /dev/ttyS*` 指令，而設定個別序列埠裝置的指令範例如下：
====
root# *setserial /dev/_ttyS0_ baud_base _19200_*
====

目前多以工具程式 `stty` 來設定 TTY 裝置的屬性，不過像是 `ttyUSB_N_` 之類的裝置，衹能應用 `stty` 而無法使用 `setserial` 。
想要 `stty` 列出序列埠裝置的基本設定值可以輸入：
====
root# *stty -F /dev/_ttyS0_* +
speed 19200 baud; line = 0; +
-brkint -imaxbel
====

標準的序列埠基本設定為 9600 鮑率加上所謂的 N81 格式，分別對應 `-parenb`, `cs8`, `-cstopb` 等引數。
設定之後利用選項 `-a` 再執行一次指令，來確認一下詳細的設定值：
====
root# *stty -F /dev/_ttyS0_ 9600 -parenb cs8 -cstopb* +
root# *stty -a -F /dev/_ttyS0_* +
speed 9600 baud; rows 0; columns 0; line = 0; +
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; +
min = 1; time = 0; +
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts +
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8 +
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0 +
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
====

印表裝置的鮑率通常比一般的序列埠裝置高，如果是從 USB 轉出的訊號，鮑率的設定可能要更高。例如：
====
root# *stty -F /dev/_ttyUSB0_ 115200 -echo -icrnl -ixon*
====
不同裝置的設定要求也會有所不同，需要參考裝置所附的使用手冊。
例如當連接的是屬於**原始**(raw) 類型的裝置，設定的選項就需要 `raw -echo -echoe -echok` ，或者要額外開啟硬體流量控制 `crtscts` 。

==== 測試
要確認系統已經偵測到某個序列埠，可以輸入：
====
root# *udevadm info --name=/dev/_ttyS0_ --query=path* +
/devices/pnp0/00:05/00:05:0/00:05:0.0/tty/ttyS0
====

利用命令列可以進行對於序列埠的最簡單測試，就是重覆地發送資料到抽象裝置檔案，然後觀察設備是否有接收的反應：
====
while true; do echo X > /dev/_ttyS0_; sleep 2; done
====
對於熟悉 Python 程式語言的使用者，可以在程式中匯入 `pyserial` 模組來呼叫相關功能。
至於較複雜的序列埠通訊軟體，可供選擇的有文字介面的 `minicom` ，以及圖形介面的 `putty` 。

=== 序列埠設備



==== 數據機
有些使用序列埠的**數據機**(MODEM) 周邊設備，內核會載入 `cdc_acm` 驅動模組，並額外建立形如 `/dev/ttyACM_0_` 的裝置名稱。
但是當數據機是以 USB 介面連接，裝置就可能同時會具有 `ttyACM_N_` 以及 `ttyUSB_N_` 兩個代號，容易造成應用軟體無法識別或誤判。
嘗試的解決方法包括：停用初始系統模式下的 `ModemManager` 服務，或者自行設定 `udev` 的規則以正確產生所需裝置的符號鏈結。


==== 錢箱
在俗稱收銀機的**銷售點**(POS) 應用電腦系統中，會用到稱為**錢箱**(cash drawer) 的序列埠設備。
連接錢箱所用的序列埠必須也有提供電源，通常使用簡單的 RJ11 接頭。
錢箱設備惟一需要的設定值是它的**鮑率**(baud rate)。
假設目前的錢箱是接在系統的第 5 個序列埠上，那麼指令 `stty -F /dev/ttyS4` 就可以顯示包括鮑率的簡單資訊，而設定的範例如下：
====
root# *stty -F /dev/ttyS4 _110_*
====

向序列埠發送任何資料就可以打開錢箱：
====
root# *echo > /dev/ttyS4*
====
如果是間接透過印表機，則要依照印表機所用的指令規範，例如：
====
root# *echo -e _"\033\0160\0\031"_ > /dev/tty_USB0_*
====

==== 真空螢光顯示器
**真空螢光顯示器**(VFD) 常出現在 POS 應用電腦系統，做為一種**客戶顯示器**(customer display) 使用。
如果手邊的機型有提供序列埠介面，就很適合拿來做為測試設備，但是通常需要在系統韌體設定中，先開啟 5V 的供電。

雖然在配備較高的系統中，VFD 的功能會被**第二螢幕**(second monitor) 所取代，
但是由於通訊協定簡單，基本上衹需要傳送純文字給對應的序列埠，就可以將文字顯示出來，適用於顯示簡單訊息的情境。
不過也因此容易於開機時，受到其他軟體的干擾而產生亂碼。

==== 跳接
如果想要連接的兩端都屬於**資料終端設備**(DTE)，而非依附主機的周邊裝置，那麼就需要以跳接(crosslink) 過的連接線來連接角色對等的設備。
依此製作的序列埠轉接器/線又稱為**空數據機**(null MODEM)，甚至在以往網路尚未普及的年代，用它做為兩臺主機之間直接傳送檔案的工具。
連線此類小型主機需要搭配支援專屬協定的軟體，例如用來管理其他自動化控制電子設備的**可程式邏輯控制器**(PLC)，或是用來盤點貨物的盤點機。


如果問題發生於使用一段時間之後，斷斷續續地出現，最後完全無法使用，可能是硬體佈線問題，例如溫度、濕度、灰塵、磨損等因素造成的短路。
此時為了要排除周邊裝置的因素，就需要進行迴路(loopback) 測試，這項測試也常常出現在一般的壓力測試計畫之中。

序列埠的迴路接法與跳接接法原理相似，但迴路接法衹有一個接頭，其中的針腳形成迴路，讓測試主機同時扮演輸出與輸入的角色。
測試迴路時可以開啟兩個終端機仿真視窗，然後在第一個視窗中執行 `cat /dev/_ttyS0_` 指令以進行等待狀態，接著在第二個視窗中輸入 `echo test-data > /dev/_ttyS0_` 。
此時就應該會在第一個視窗中出現 `test-data` 的輸出，表示迴路的基本功能正常。

當利用跳接或迴路所接收的資料，含有不可印出字元的話，可以透過管線配合 `hexdump -b` 或 `xxd -g 1` 指令來檢視讀取到的內容。
如果想要將十六進位的字元直接寫入裝置中，可參考下面的例子：
====
root# *echo -en _'\x01\x01\xCA\x60\x00\x03\xA9'_ > /dev/_ttyUSB0_*
====
或是藉助 xxd -r -p 命令，先進行轉換再輸出：
====
root# *echo -n '_01 01 CA 60 00 03 A9_' | xxd -r -p > /dev/_ttyUSB0_*
====

=== 其他裝置

==== 終端機
這裡的終端機是指系統中的主控臺與虛擬終端機，它們其實是屬於字元裝置而非顯示裝置，衹是通常依附在用來顯示的螢幕上。

==== 指示燈
電腦系統與周邊設備上，常常會配備基於**發光二極體**(LED) 的指示燈，做為顯示鍵盤、網路、影音、儲存等裝置狀態的人機介面。
有些指示燈是由裝置直接控制，有些則具備程式可控的介面，例如虛擬的檔案目錄 `/sys/class/leds/` 中，就包含了部分的指示燈資訊。

某些裝置必須透過特定的存取方式，例如硬碟抽取盒的指示燈需要 `ledmon` 套件中的 `ledctl` 命令來控制。

==== Super I/O
主機板上的 *Super I/O*(超級輸入輸出) 晶片，用來做為低頻寬設備的介面，以往需要透過 ISA 匯流排與 CPU 連接，目前則透過南橋晶片上的 LPC 匯流排。
常用來偵測溫度，也同時會提供 *Watchdog Timer*(看門狗計時器) 的功能。
`coreboot-utils` 套件中有 `superiotool` 程式，可以偵測並提供暫存器內容。
如果在系統啟動時期被 ACPI 占住資源，可以利用內核參數 `acpi_enforce_resources=lax` 來排除問題。

==== GPIO
內核於系統初始化時，如果偵測到 *GPIO*(通用型輸入輸出) 就會產生 `/dev/gpiochip0` 的對應裝置，裝置的資訊則可以從 `/sys/kernel/debug/gpio/` 中得到。
安裝 `libgpiod-utils` 套件（或者名為 `gpiod` ）後，就可以使用其中的 `gpioinfo`, `gpiodetect`, `gpioget`, `gpioset` 等工具程式。

或是利用舊式的 `/sys/class/gpio/` 介面來初始化與使用 GPIO：
（範例中的腳位編號需要以公式計算出來）
====
root# *echo _42_ > /sys/class/gpio/export* +
root# *echo in > /sys/class/gpio/_gpio42_/direction* +
root# *echo out > /sys/class/gpio/_gpio42_/direction* +
root# *echo 1 > /sys/class/gpio/_gpio42_/value* +
root# *echo _42_ > /sys/class/gpio/unexport*
====

GPIO 在嵌入式系統中，常以 *SPI*(序列周邊介面) 做為傳輸介面，後者是由四條線路組成的簡單傳輸匯流排，但未來可能會被以 SD 介面連接外部裝置的 *SDIO* 所取代。

==== IIO
由 `libiio` 函式庫控制的**工業輸入輸出**(Industrial IO) 裝置，相關的套件像是 `iio-sensor-proxy` ，但 Linux 整體支援仍有不足。
例如**重力感測器**(g-sensor) 或是稱為**加速計**(accelerometer) 的裝置，大多運用於平板電腦之中。
由於各類裝置的歧異度很大，因此需要的驅動軟體也有多種形式，常常衹適用於特定的裝置與環境。

==== 指紋辨識器
一般的指紋辨識器需要 `fprintd-pam`, `fprintd`, `libfprint` 等套件，分別提供了認證模組、系統服務、函式庫的功能。
其中還包括了一些工具程式，例如利用 `fprintd-enroll` 來登錄指紋資料（通常是刷右手食指五次）。

==== 安全鑰匙
通常是外觀類似隨身碟的 USB 裝置，於需要**多因子認證**(MFA) 的場合做為**通用第二因子**(U2F) 使用。
一般先以專屬程式初始化裝置之後，將產生的金鑰密碼複製於需要保護的軟體系統（無關硬體或使用者）。
接著安裝相應的 PAM 模組，依據裝置規格選擇通用形式或專屬形式，並且導入設定檔的目標程序之中。

下列指令是 Yubico
footnote:[Yubico 網站 <https://www.yubico.com/>] 銷售的安全鑰匙裝置設定範例：
====
root# *tar xvf yubico-authenticator-7.1.1-linux.tar.gz* +
root# *cd yubico-authenticator-7.1.1-linux* +
root# *./authenticator* +
	⋮		⋮ +
root# *dnf -y install pam-u2f pamu2fcfg* +
root# *sed -i '/^@include common-auth/a auth required pam_u2f.so' /etc/pam.d/gdm-password* +
	⋮		⋮ +
user$ *mkdir -p $HOME/.config/Yubico* +
user$ *pamu2fcfg > ~/.config/Yubico/u2f_keys*
====
其中的專屬程式 `yubico-authenticator` 是從廠商網站下載而來，確切的指令內容請依據實際情況進行調整。
認證過程除了檢查裝置是否存在之外，注意還需要手指踫觸金屬部分以發送金鑰。



