== 輸入輸出介面
由於 USB 介面的興起，因此新近的輸入輸出裝置多採用 USB 或網路介面，而舊式或是對於速度要求不高的機型，則以 USB 轉出的方式繼續使用。

=== 裝置類型
常見的 USB 轉輸入輸出埠的晶片型號有 FTDI, PL2303, AX781x0(MCS78x0) 等等，不同型號的晶片所提供的序列埠/平行埠數量有所不同，內核模組的支援程度也有差別。
如果某型號的晶片已有支援的內核模組，卻想要安裝廠商提供的專有驅動程式，請記得先將內核模組列入模組黑名單之內。

電腦系統常用的輸入輸出裝置，多隸屬於內核裝置類型中的**字元裝置**(character device)，傳輸的型式則可分為序列式（又稱串列式）或平行式。
雖然直覺上序列式的傳輸速度要比平行式來得慢，但是因為免去了同步的機制與干擾的因素，再加上本身的成本優勢，反而成為許多新一代傳輸協定所採取的方式。

輸入輸出裝置隨附的記憶體，通常稱為該裝置的暫存器。
裝置暫存器可能對應到一塊系統記憶體位址，亦即經由 `/dev/mem` 存取的 MMIO 機制，或是基於**埠映射輸入輸出**(PMIO) 去對應 `/dev/port` 中的窗口位址。
直接使用時還須注意要關閉安全啟動，並以超級使用者身分執行。例如：
====
root# *printf '\x0b\x83' | dd of=/dev/port oflag=seek_bytes seek=112 conv=notrunc*
====
就可以用來停用 RTC 的功能。


=== 列印裝置
列印裝置是電腦系統中不可或缺的輸出設備，提供將資訊實體化與可攜化的方式。
硬體類型包括標籤印表機、點陣印表機、噴墨印表機與雷射印表機，但以下並未涉及運作機制略有不同但潛力無窮的 3D 列印機。

==== 連接介面
早期印表機的標準連接介面是**平行埠**(parallel port)，內核所賦予的裝置名稱為 `/dev/parport__N__` 。
不過除非是想要直接跟平行埠溝通，否則一般都會透過抽象的列印裝置節點 `/dev/lp__N__` ，其中的 `_N_` 是從 0 開始的數字。
例如，其他作業系統對於第一個平行埠印表機的稱呼 `LPT1:` ，在 Linux 系統中即為 `/dev/lp0` 。

如果使用了 USB 轉出平行埠的晶片或轉接線，或是印表機本身支援 USB 介面，`lsusb -t` 指令就能識別出 `Class=Printer`，內核便會載入 `usblp` 模組做為驅動程式。
萬一內核沒有正確偵測到，就需要手動載入，才會順利產生 `/dev/usb/lp0` 的裝置名稱，以及 `/dev/usblp0` 的符號鏈結。
也有可能因為將其他 USB 設備誤判為列印裝置，使得 `/dev/usb/lp0` 被佔據，印表機就會被分配到 `/dev/usb/lp1` 的裝置名稱。

==== 列印服務
Linux 上的列印功能，也是基於伺服器－客戶端的架構來完成。
由 `cups` 套件所提供的 CUPS(通用 UNIX 列印系統)，是目前的主流列印服務。
在 Systemd 系統初始模式中，是以名為 `cups.service` 的單元形式發揮作用：
====
root# *systemctl start cups* +
root# *systemctl enable cups*
====
實際上執行的程式為 `cupsd` ，負責偵測、驅動與管理可用的列印裝置。
當其他的應用軟體需要列印功能時，就向 CUPS 提出需求，並將待印資料排入佇列之中。

列印服務動作的記錄可由指令 `journalctl -u cups` 顯示，列印任務的記錄會儲存於 `/var/cache/cups/job.cache` 檔案，而 `/var/spool/cups/` 目錄下則會暫存列印任務的內容。
CUPS 服務的組態檔位於 `/etc/cups/printers.conf` ，負責將印表機映射到列印裝置的節點。
利用工具程式 `lpadmin` ，或是透過它的網頁介面 `https://localhost:631/admin` 來進行管理，訪問 `http://localhost:631/` 則如同執行 `lpstat -t` 指令，可以獲得列印服務的一般資訊。

CUPS 支援多種列印協定，並提供**統一資源識別碼**(URI) 做為連接的形式：

[square]
* Linux 列印伺服器(LPD)：<lpd://伺服器位址/佇列名稱> 相容於舊式 Linux 系統的列印服務。
* 網際網路列印(IPP)：<ipp://伺服器位址:631/ipp> CUPS 或網路印表機的列印服務。
* 網路芳鄰分享(SMB)：<smb://使用者名稱:密碼@伺服器位址/印表機名稱> 相容於 Windows 網路芳鄰列印服務。
* JetDirect：<socket://伺服器位址> 相容於 HP 所開發的列印服務。
* 通用序列匯流排：<usb://廠商名稱/系列名稱/型號名稱?serial=裝置序號> 自動生成的 USB 列印服務。
* 平行埠：<parallel:/印表裝置節點> 連接於本機 LPT/USB2LPT 平行埠裝置的列印服務。
* 藍牙：<bluetooth://藍牙裝置號碼/> 連接於本機藍牙裝置的列印服務。

其中前面四項是網路印表協定，後面三項則為本機印表協定。
實務上直接連接印表機的情境愈來愈少，因此測試網路印表機的使用有其必要性。

==== 驅動模組
傳統的列印裝置登載檔案位於 `/etc/printcap` ，目前僅僅保留做為相容用途，並由列印服務自動產生。

CUPS 的列印裝置驅動方式，是依靠 *PPD*(PostScript 印表機描述) 類型的文字格式檔案，其中包含了多項的設定值。
在 `/usr/share/ppd/cupsfilters/` 與 `/etc/cups/ppd/` 之中，或者 `/usr/share/cups/model/` 下個別列印型號的目錄內，
可以找到對應不同列印裝置的 `*.ppd` 檔案。
例如 `hplip` 及其相關套件，就提供了多款 HP 廠牌印表機的驅動描述檔案。

對於各種不同格式的列印來源，CUPS 會藉助一或多個**過濾程式**(filter)，最終產生適合印表機直接處理的內容格式（通常是 PostScript 或 PDF）。
目錄 `/usr/lib/cups/filter/` 中存放了許多可執行的過濾程式，提供 CUPS 需要轉換列印內容時，依據 PPD 檔案所指定的程式名稱來呼叫。
例如列印測試頁所用的檔案 `/usr/share/cups/data/testprint` ，會依據範本格式並代入目標印表裝置資訊以產生測試頁內容。
依據目錄 `/usr/share/cups/mime/` 所含檔案的內容，檔頭標註的 `#PDF-BANNER` 就會間接對應到使用 `bannertopdf` 過濾程式來處理。

安裝列印裝置驅動模組時失敗，可能是因為適用的 CUPS 版本不同而導致安裝路徑不正確，或是過濾程式依存的函式庫不相容。

為了設計成本的考量，部分印表機直接以 Windows 系統定義的 *GDI*(圖形裝置介面) 所驅動（角色相當於自由軟體的 Cairo 函式庫），導致在 Linux 系統中無法使用。
變通方法則是在可以驅動該類印表機的 Windows 系統上，安裝適當的過濾程式以及網路埠轉發程式，或是以虛擬印表機提供網際網路列印服務。

==== 裝置設定
由於列印的設定比較複雜，因此大部分的散佈版都提供了圖形介面的組態程式。
目前一般印表機都是隨插即用的 USB 介面，桌面環境中的印表機設定也會自動完成適當的組態。
如果桌面環境未附帶印表裝置的設定功能，那麼除了上述提到的網頁介面之外，還可選擇傳統的 `system-config-printer` 套件，否則就要利用以下的命令列工具了。

許多與列印相關的公用程式有著類似 `lp*` 形式的名稱，這是因為早期的 UNIX 列印伺服程式名為 `lpd` ，因此將這個命名傳統延續下來。
目前系統中的 `lp`, `lpc`, `lpq`, `lpr`, `lprm`, `lpstat` 等命令，多為 CUPS 軟體所實作程式的鏈結，一般衹是做為圖形介面與網頁介面的備用方案。
例如，藉由執行 `lpstat -p` 指令列出印表機名稱之後，再執行 `lp -d _印表機名稱_ /usr/share/cups/data/default-testpage.pdf` 以列印標準測試頁。

使用收據印表機時，列印紙張一般而言較窄，列印時需要調整將列印的資料靠左放置，以免無法印出東西。
如果印表機是以熱感應方式列印，安裝紙卷時必須注意紙張正反面方向，因為衹有其中單面才有熱感應效果。
印表機本身的傳輸鮑率必須配合連接埠的設定，通常先按住送紙鍵再打開電源即會印出目前設定。

大型機構可能還需要更上層的整合系統，做為統一的列印入口，負責管理所有的列印服務與裝置。
除了眾多的專屬套裝選項之外，也可以考慮開放原始碼的 SavaPage
footnote:[SavaPage 開放列印入口 <https://www.savapage.org/>]
軟體。

==== 測試方式
大部分的印表裝置都接受純文字格式的資料，因此對於連接於本機的印表機，可以直接傳送純文字到連接埠：
====
root# *echo _TEST 1234_ > /dev/_ttyS0_*
====
但是有些以頁為批次列印單位的印表機，需要多送一個**換頁字元**(form feed) 才會開始動作：
====
root# *echo -e _TEST 1234_ '\f' > /dev/usb/_lp0_*
====

如果此時印表機印出了輸入的文字，就表示兩端的基本連接沒有問題。
萬一印表機有反應卻是印出了亂碼，可能要檢查連接是否確實，或是傳輸設定是否正確。

假設待測印表機支援 ESC/POS 指令集，且接於主機的第一個平行埠，就可以分別傳送初始化與自我測試的指令如下：
====
root# *echo -en "\x1B\x40" > /dev/lp0* +
root# *echo -en "\x1F\x40" > /dev/lp0*
====


=== 序列埠裝置
**通訊埠**(communication port) 是早期用途最廣泛的**序列埠**(serial port)，因此這兩個名稱常常會互相指代。
序列埠介面的型式一般使用傳統的 D-sub 連接器，或是借用常見於電話線的 RJ11 接頭。

==== 板接晶片
主機板上的 *UART*(通用非同步收發器) 晶片，扮演提供序列通訊功能的角色，能夠支援的介面標準包括：RS-232, RS-449, RS-423, RS-422, RS-485 等等（較新的名稱字首可能改為 EIA-）。
電腦系統上所稱的通訊埠，一般指的就是最常見的 RS-232 介面，支援資料的傳送與接收。
而像是 RS-485 則為簡單 2 線的通訊標準，必須設定為傳送端或接收端之一，但支援多節點與遠距離傳輸。

UART 晶片一般包含於 Super I/O 晶片組，常見的型號為 8250 與 16550。
一顆晶片可以支援 6 個 UART 埠，如果要增加埠數，需要增加晶片或更換為支援更多埠的型號。
例如要補足未滿的介面數時，可以採取外接**擴充板**(add-on board) 的方式。
有些散佈版的內核未必啟用全部的 UART 埠，而是透過內核參數 `8250.nr_uarts=4` 衹開啟 4 個埠，可依需要手動重新設定。
軟體若預設開啟超過硬體規格的埠數，也可能會造成不小心存取到該裝置名稱而產生難以預料的結果，例如關機或重開機時出現延遲，此時使用者就可依需求以類似上述的設定來解決。

==== 裝置名稱
序列埠連接介面通常會被內核賦予 `/dev/ttyS__N__` 形式的裝置名稱，這是由 TTY(電傳打字機) 加上 S(序列)，再加上從 0 開始的數字編號所組成。
例如系統中的 `/dev/ttyS0` 裝置名稱，就相當於其他作業系統用來代表第一個序列埠的 `COM1:` 。

由於配備序列埠晶片、介面的主機與周邊愈來愈少，也許是因為想要避免傳統序列埠太多而造成的干擾與系統資源衝突，而為了要相容舊式設備，便需要支援 USB 轉序列埠的轉換晶片或轉接線。
內核會以類似 `/dev/ttyUSB__N__` 的抽象裝置，來代表經由 USB 介面連接的序列埠，又可稱為**虛擬序列埠**(VCP) 介面。

==== 輸入輸出埠與中斷請求
裝置的**輸入輸出埠**(I/O port) 與**中斷請求**(IRQ)，通常是由裝置與系統韌體共同決定。
兩者都是系統的有限資源，周邊設備如果太多就可能導致分配不足，因此便引入了熱插拔與共用等機制。
序列裝置的可變性較大，一般會在系統韌體設定中開放，提供使用者調整對應值的機會。

虛擬檔案 `/proc/ioports` 的內容，是系統目前的輸入輸出埠使用分配表。
例如在 0x0000 ~ 0xFFFF 的 64 KB 空間中，分配給序列埠的典型基底位址為 0x3F8, 0x2F8, 0x3E8, 0x2E8 等等。
系統目前的中斷請求列表，可以參看 `/proc/interrupts` 檔案的內容，或是經由 `procinfo` 套件中的 `lsdev` 命令檢視。
依據裝置的熱插拔機制不同，以下的內核參數都有可能會影響中斷請求的配發： `isapnp=pci_scan`, `noisapnp`, `pnpbios=on`, `pnpacpi=off` 。

==== 裝置屬性
經由指令 `dmesg|grep tty` 可以看到關於 TTY 裝置的一些硬體初始資訊， `lsof /dev/ttyS__N__` 則是顯示相關的軟體資訊。
另外在虛擬檔案 `/proc/tty/drivers` 中記錄了負責各類 TTY 裝置的內核模組名稱，而 `/proc/tty/driver/serial` 則可看到個別序列埠裝置所對應的中斷請求。

==== 設定
已停止維護的 `setserial` 命令可以處理較為低階的序列埠設定，可惜已不再收錄於官方的套件庫中。
想要顯示所有序列埠裝置的屬性，可以執行 `setserial -ag /dev/ttyS*` 指令，而設定個別序列埠裝置的指令範例如下：
====
root# *setserial /dev/_ttyS0_ baud_base _19200_*
====

目前多以工具程式 `stty` 來設定 TTY 裝置的屬性，不過像是 `ttyUSB__N__` 之類的裝置，衹能應用 `stty` 而無法使用 `setserial` 。
想要利用 `stty` 列出序列埠裝置的基本設定值，可以輸入：
====
root# *stty -F /dev/_ttyS0_* +
speed 19200 baud; line = 0; +
-brkint -imaxbel
====

標準的序列埠基本設定為 9600 鮑率加上所謂的 N81 格式，分別對應 `-parenb`, `cs8`, `-cstopb` 等引數。
設定之後加上選項 `-a` 再執行一次指令，來確認一下詳細的設定值：
====
root# *stty -F /dev/_ttyS0_ 9600 -parenb cs8 -cstopb* +
root# *stty -a -F /dev/_ttyS0_* +
speed 9600 baud; rows 0; columns 0; line = 0; +
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; +
min = 1; time = 0; +
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts +
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8 +
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0 +
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
====

印表裝置的鮑率通常比一般的序列埠裝置高，如果是從 USB 轉出的訊號，鮑率的設定可能要更高。例如：
====
root# *stty -F /dev/_ttyUSB0_ 115200 -echo -icrnl -ixon*
====
不同裝置的設定要求也會有所不同，需要參考裝置所附的使用手冊。
例如當連接的是屬於**原始**(raw) 類型的裝置，設定的選項就需要 `raw -echo -echoe -echok` ，甚至要額外開啟硬體流量控制 `crtscts` 。

==== 測試
想要確認系統已經偵測到某個序列埠，可以輸入：
====
root# *udevadm info --name=/dev/_ttyS0_ --query=path* +
/devices/pnp0/00:05/00:05:0/00:05:0.0/tty/ttyS0
====

利用命令列可以進行對於序列埠的簡單測試，亦即重覆地發送資料到抽象裝置節點，然後觀察設備是否有接收反應：
====
root# *while true; do echo _TEST_ > /dev/_ttyS0_; sleep 2; done*
====
對於熟悉 Python 程式語言的使用者，可以在程式中匯入 `pyserial` 模組來呼叫相關功能。
例如要讀取 ISO14443A 卡片的部分資訊，可以利用下列程式：

.serial-test.py
....
#!/usr/bin/python3
import serial
device = serial.Serial('/dev/ttyUSB0', 19200)
header = device.read(4)
print(header.encode('hex').upper())
....

至於較複雜的序列埠通訊軟體，可供選擇的有文字介面的 `minicom` ，以及圖形介面的 `putty` 。

=== 序列埠設備

==== 數據機
有些使用序列埠的**數據機**(MODEM) 周邊設備，內核會載入 `cdc_acm` 驅動模組，並額外建立形如 `/dev/ttyACM__0__` 的裝置名稱。
但是當數據機是以 USB 介面連接，裝置就可能同時會具有 `ttyACM__N__` 以及 `ttyUSB__N__` 兩個代號，容易造成應用軟體無法識別或誤判。
嘗試的解決方法包括：停用系統初始模式下的 `ModemManager` 服務，或者自行設定 UDEV 的規則以正確產生所需裝置的符號鏈結。

當使用者不再藉由類比式線路撥號上網之後，數據機便退出了周邊設備的舞臺，但是它仍不失為一種方便測試序列埠的裝置。
例如將數據機開啟並與電腦第一序列埠連接，再執行設定鮑率以及發送撥號訊息的指令：
====
root# *stty -F /dev/ttyS0 19200* +
root# *echo _ATDT123456_ > /dev/ttyS0*
====

==== 錢箱
在俗稱收銀機的**銷售點**(POS) 應用電腦系統中，會包括稱為**錢箱**(cash drawer) 的序列埠設備。
連接錢箱所用的序列埠必須要提供電源，通常使用簡單的 RJ11 接頭。
錢箱設備惟一需要的設定值是它的**鮑率**(baud rate)。
假設目前的錢箱是接在系統的第 5 個序列埠上，那麼指令 `stty -F /dev/ttyS4` 就可以顯示關於它的簡單資訊，而設定時衹需要再加上鮑率的參數：
====
root# *stty -F /dev/ttyS4 _110_*
====

操作時向序列埠發送任何資料就可以打開錢箱：
====
root# *echo > /dev/ttyS4*
====
如果是間接透過印表機，則要依照印表機所用的指令規範，例如：
====
root# *echo -e _"\033\0160\0\031"_ > /dev/tty__USB0__*
====

==== 真空螢光顯示器
**真空螢光顯示器**(VFD) 也常常出現在 POS 應用電腦系統，做為一種**客戶顯示器**(customer display) 使用。
如果手邊的機型有提供序列埠介面，就很適合拿來做為測試設備，但是同樣需要在系統韌體設定中，先開啟 5V 的供電。

雖然在配備較高的系統中，VFD 的功能可能會被**第二螢幕**(second monitor) 所取代，
但是由於通訊協定簡單，基本上衹需要傳送純文字給對應的序列埠，就可以將文字顯示出來，適用於顯示簡單訊息的情境。
不過也因此容易於開機時，受到其他軟體的干擾而產生亂碼。
使用者可以在設定適當的鮑率之後，立即送出初始化的指令字串：（假設裝置接於第四序列埠且支援 ESC/POS 指令集）
====
root# *stty -F /dev/ttyS3 _9600_* +
root# *echo -en "\033@" > /dev/ttyS3*
====

套件 `lcdproc` 並非用於簡單的單列或雙列客戶顯示器，而是應用於另外一類較複雜的多列 LCD 顯示器。
該套件本身就附有多種裝置型號的驅動函式庫，一般做為系統資訊顯示器使用。

==== 跳接
如果想要連接的兩端都屬於**資料終端設備**(DTE)，而非依附主機的周邊裝置，那麼就需要以跳接(crosslink) 過的連接線來連接角色對等的設備。
依此製作的序列埠轉接器/線又稱為**空數據機**(null MODEM)，甚至在以往網路尚未普及的年代，用它做為兩臺主機之間直接傳送檔案的工具。
搭配支援專屬協定的軟體就可以連線此類小型主機，例如用來管理其他自動化控制電子設備的**可程式邏輯控制器**(PLC)，或是用來盤點貨物的盤點機。

如果序列埠於使用一段時間之後，斷斷續續地出現問題，最後甚至完全無法使用，有可能是硬體佈線問題，例如溫度、濕度、灰塵、磨損等因素造成的短路。
此時為了要排除周邊裝置的因素，就需要進行迴路(loopback) 測試，這項測試也常常出現在一般的壓力測試計畫之中。

序列埠的迴路接法與跳接接法原理相似，但迴路接法衹有一個接頭，其中的針腳形成迴路，讓測試主機同時扮演輸出與輸入的角色。
測試迴路時可以開啟兩個終端機仿真視窗，然後在第一個視窗中執行 `cat /dev/_ttyS0_` 指令以進行等待狀態，接著在第二個視窗中輸入 `echo 1234TEST > /dev/_ttyS0_` 。
此時就應該會在第一個視窗中出現文字 1234TEST 的輸出，表示迴路的基本功能正常。

當利用跳接或迴路所接收的資料，含有不可印出字元的情況，可以透過管線導向，配合 `hexdump -b` 或 `xxd -g 1` 指令來檢視讀取到的內容。
如果想要將十六進位的字元直接寫入裝置中，可以參考下面的例子：
====
root# *echo -en _'\x01\x01\xCA\x60\x00\x03\xA9'_ > /dev/_ttyUSB0_*
====
或是藉助 `xxd` 命令，先進行轉換再輸出：
====
root# *echo -n '_01 01 CA 60 00 03 A9_' | xxd -rp > /dev/_ttyUSB0_*
====


=== 其他裝置

==== 終端機
這裡的終端機是指系統中的終端機裝置節點，它們其實是屬於字元裝置而非顯示裝置，衹是通常依附在用來顯示的螢幕上。
主控臺與虛擬終端機是開機後就產生的文字模式操作環境，**假擬終端機**(pseudo terminal) 則是提供給終端機仿真器使用的虛擬裝置。
萬一散佈版的內核沒有自動建立假擬終端機，可以利用下列指令手動建立並進行初始化：
====
root# *mkdir -v /dev/pts* +
root# *mount -vt devpts -o gid=4,mode=620 none /dev/pts*
====

至於當前使用的終端機是連接到文字模式的虛擬終端機，或是開啟自圖形模式的終端機仿真器，可以藉由 `tty` 命令來判斷
（前者輸出 `/dev/tty__N__` 而後者輸出 `/dev/pts/__N__` ）。

==== 掃描器
**掃描器**(scanner) 是將外部的圖片或文字，以光學掃描後利用圖片的形式傳回電腦系統的裝置。
Linux 的掃描功能，目前藉由 SANE(Scanner Access Now Easy) 軟體系統來達成。
後端是 `sane-backends-daemon` 套件包含的 `saned` 守護程式，加上與其配合的系統服務所負責；
套件 `sane-backends` 提供了各類型裝置的組態檔案，以及一些像是 `sane-find-scanner` 的工具程式。
另外還有 `airscan-discover` 命令，用來偵測網路上的掃描器，通常是屬於多功能事務機的一部分；
前端的應用軟體則包括 `simple-scan`, `xsane` 或是 `skanlite`。

==== 指示燈
電腦系統與周邊設備上，常常會配備基於**發光二極體**(LED) 的指示燈，做為顯示鍵盤、網路、影音、儲存等裝置狀態的人機介面。
有些指示燈是由裝置控制，有些則具備程式可控的系統介面，例如假擬的檔案目錄 `/sys/class/leds/` 中，就包含了部分的指示燈資訊。
如果想要停用電源按鈕指示燈的話，可以試試：
====
root# *echo 0 > /sys/class/leds/led0/brightness* +
root# *echo none > /sys/class/leds/led0/trigger*
====

某些裝置則必須透過特定的存取方式，例如硬碟抽取盒的指示燈需要 `ledmon` 套件中的 `ledctl` 命令來控制。

==== 看門狗計時器
**看門狗計時器**(Watchdog Timer) 的內核驅動模組核心即為 `watchdog` ，需要搭配特定的裝置驅動模組，例如 `wdat_wdt`, `iTCO_wdt` 或是軟體模擬的 `softdog` 。
若是具備看門狗計時器裝置卻無適當的驅動程式，有可能造成開機或關機時延遲，或是系統韌體中啟用該裝置後，系統雖能正常開關機，卻會在運行時自動重新開機。

有時內核中雖有相應廠牌的驅動模組，但是型號不支援，可以試著修改模組程式，簡單加入定義與實例，再抽出成為外掛模組後編譯使用。
如果沒有被黑名單機制阻擋，正確載入驅模組後應該就會出現 `/dev/watchdog` 虛擬字元裝置。

使用者空間中相應的系統服務與套件名稱，同樣也是稱為 `watchdog` ，用來設定與控制硬體/軟體的看門狗機制：
當系統沒有定時提供正常運行的訊號，就會觸發看門狗的重新開機動作。

==== GPIO
內核於系統初始化時，如果偵測到 *GPIO*(通用型輸入輸出) 晶片模組，就會產生 `/dev/gpiochip0` 的對應裝置，裝置的資訊可以從 `/sys/kernel/debug/gpio/` 目錄中得到。
安裝 `libgpiod-utils` 套件（名稱或者是 `gpiod` ）後，就能夠使用其中的 `gpioinfo`, `gpiodetect`, `gpioget`, `gpioset` 等工具程式。

也可以利用舊式的 `/sys/class/gpio/` 假擬目錄介面來初始化與使用 GPIO：
（範例中的腳位編號需要以公式計算出來）
====
root# *echo _42_ > /sys/class/gpio/export* +
root# *echo in > /sys/class/gpio/_gpio42_/direction* +
root# *echo out > /sys/class/gpio/_gpio42_/direction* +
root# *echo 1 > /sys/class/gpio/_gpio42_/value* +
root# *echo _42_ > /sys/class/gpio/unexport*
====

GPIO 在嵌入式系統中，常以 *SPI*(序列周邊介面) 做為傳輸介面，後者是由四條線路組成的簡單傳輸匯流排，但未來可能會被以 SD 介面連接外部裝置的 *SDIO* 所取代。

==== IIO
由 `libiio` 函式庫控制的**工業輸入輸出**(Industrial IO) 裝置，相關的套件像是 `iio-sensor-proxy` ，但 Linux 整體支援仍有不足。
例如**重力感測器**(g-sensor) 或是稱為**加速計**(accelerometer) 的裝置，大多運用於平板電腦之中。
由於各類裝置的歧異度很大，因此需要的驅動軟體也有多種形式，常常衹適用於特定的裝置與環境。

==== 指紋辨識器
一般的指紋辨識器需要 `fprintd-pam`, `fprintd`, `libfprint` 等套件，分別提供了認證模組、系統服務、函式庫的功能。
其中還包括了一些工具程式，例如利用 `fprintd-enroll` 來登錄指紋資料（通常是刷右手食指五次）。

==== 安全鑰匙
安全鑰匙的外觀大多是類似隨身碟的 USB 裝置，在需要**多因子認證**(MFA) 的場合做為**通用第二因子**(U2F) 使用。
一般先以專屬程式初始化裝置之後，將產生的金鑰密碼拷貝到需要保護的軟體系統（無關硬體或使用者）。
接著安裝相應的 PAM 模組，依據裝置規格選擇通用形式或專屬形式，並且導入組態檔的目標程序之中。

下列指令是 Yubico
footnote:[Yubico 網站 <https://www.yubico.com/>] 銷售的安全鑰匙裝置設定範例：
====
root# *tar xvf yubico-authenticator-7.1.1-linux.tar.gz* +
root# *cd yubico-authenticator-7.1.1-linux* +
root# *./authenticator* +
... +
root# *dnf -y install pam-u2f pamu2fcfg* +
root# *sed -i '/^@include common-auth/a auth required pam_u2f.so' /etc/pam.d/gdm-password* +
... +
user$ *mkdir -p $HOME/.config/Yubico* +
user$ *pamu2fcfg > $HOME/.config/Yubico/u2f_keys*
====
其中的專屬軟體 `yubico-authenticator` 是從廠商網站下載而來，確切的指令內容請依據實際情況進行調整。
認證過程除了檢查裝置是否存在之外，注意還需要手指碰觸金屬部分以發送金鑰。

==== 偽字元裝置
還有一些裝置節點並沒有跟實際的硬體設備相連，而是建立了特殊的虛擬節點，提供類似字元裝置的存取方式。

[square]
* `/dev/zero` ：提供其他程式不間斷的零值輸入來源。
* `/dev/null` ：提供其他程式一律靜默接收的輸出目標。
* `/dev/urandom` ：提供其他程式不間斷的偽亂數值輸入來源。
* `/dev/random` ：提供其他程式近似隨機亂數值輸入來源。
