== 作業系統安裝
____
飛行特技不一定比單車特技困難
____
所有在電腦硬體上執行的軟體，都可以包括在廣義的作業系統之中。
狹義的作業系統（或是稱之為作業系統核心）則僅包含內核、基本系統函式庫、基本應用函式庫以及基本應用程式。
各階層之間乃是依靠程式介面進行溝通，而與使用者接觸的介面即稱之為**使用者介面**(user interface)。

=== 系統比較
常聽到的作業系統包括：DOS, Windows, macOS, Linux, Android, BSD, …等等。
雖然更精確的說法是以「使用者空間核心╱內核空間核心」的組合來稱呼，但是一般都以 Linux 來代表 GNU/Linux、以 Android 來代表 Android/Linux。
當我們想要比較它們之間的差異時，利用＜軟體概述：軟體架構＞的觀點可以得到幾個分類的依據：

[square]
* POSIX ↔ 非 POSIX：除了少部分的應用程式，其他都不同（明顯可見的差異之一為檔案系統）。
* **單內核**(monolithic kernel) ↔ **微內核**(microkernel)：內核與系統函式庫所包含的組成比例不同。
* GNU libc ↔ BSD libc：基本系統函式庫中的 C 標準函式庫來源不同。
* 文字模式 ↔ 圖形模式：應用函式庫與應用程式所包含的軟體不同，造成使用者介面的差異。

網路上有數不盡的作業系統相關資源，例如 distrowatch.com 就是一個追蹤數以百計自由/開放原始碼作業系統動態的網站，
除了提供各個系統的鏈結與下載資訊，還有主要組成軟體的版本變動記錄，以及獲得關注的點擊率排名。

==== 散佈版
Linux 散佈版之間的差異，在於是由不同的社群組織或商業公司，將各種函式庫與應用程式整合在一起。
除了都是基於 POSIX 的框架標準之外，主要不同的原因在於個別主導者的政策，
影響了所包括軟體套件的廣度與深度，以及統合基礎套件後而得到的整體觀感。

一般來說，社群組織主導的散佈版收錄較多通用的軟體，提供免費或僅需材料費的安裝與使用（像是 Fedora 或 Debian）。
由商業公司所主導的免費散佈版（像是 openSUSE 或 Ubuntu），能夠找到比較豐富的文件
如果想要專業的軟體以符合特定的需求，或是注重後續的維護服務，可能就需要選擇商業公司所提供的付費版本（像是 RHEL, SLE 或 Ubuntu Pro）。
也就是說，各類的 Linux 散佈版之間並沒有實質上的差異，僅是適用的環境不同而已。

==== 版本選擇
實務上來說，無法針對所有散佈版進行測試，因此必須做出取捨。
首先要考慮客戶的需求，如果有明確指定、或是客戶將要使用的系統是基於某個散佈版，
那麼當然要將它列入測試名單之中。而對於通用型機種，則要考慮散佈版的普及度、易用性、
更新頻率、社群支援、符合標準等因素。

散佈版的更新頻率取決於負責的開發組織或個人，可能是半年一次、一年一次或是不定期釋出新版。
版本之間通常以版本編號來區分，或是配合釋出代號以方便推廣或記憶。
編號多半由年月分或是單純的流水號所組成，而主要版本之間的小改版，則以附加一位小數做為區別。
一般而言，測試是針對最接近的主要版本，並且更新至最新的小改版。
有些散佈版會標記所謂的**長期支援版本**(LTS)，
表示該版本的維護時間，會比其他一般版本更長 (通常是指提供重要的安全性更新)。
因此限制以長期支援版本做為測試標準，也是一種較為穩定的選擇。

==== 硬體架構
這裡所謂的**架構**(architecture)，是指依不同晶片指令集而分類的一組 CPU 家族。

早期 PC 使用的是 32 位元的 x86 架構 CPU，包括 i386、i486、i586、i686 等等。
由於幾乎已不再生產此類硬體，因此許多散佈版都停止支援這類架構，在網路上也不容易找到舊版的安裝軟體。
如果真的需要安裝 32 位元作業系統，系統韌體必須支援並且調整為舊式的 BIOS 開機模式。

==== 虛擬機器
安裝到虛擬機器時，最好跳過**無人值守**(unattended) 模式，否則難以除錯預設的操作程序。
特殊組合按鍵可能需要先調成全螢幕模式才能接收，或是衹能透過虛擬機器軟體選單來間接發送。
安裝完成之後，經由套件管理系統或是虛擬機器軟體選單，來安裝**客端擴充**(guest addition) 套件。
虛擬機器的網路拓樸模式設定，會影響到與其他實體或虛擬機器的連線架構。

=== 安裝準備

==== 安裝媒體
ISO 檔案是包含光碟完整內容的映像檔格式，依照國際標準「ISO 9660」或稱之為**光碟檔案系統**(CDFS)。
早期的電腦書籍或雜誌中，常常會附贈實體的安裝光碟片。而現在一般的 Linux 散佈版，
衹會提供 `*.iso` 格式的映像檔，讓使用者自行下載後，再以燒錄機製作出安裝光碟。

安裝光碟的用法是做為開機裝置才能進行安裝程序，因此必須將它設定優先啟動裝置。
BIOS 中的裝置選項可能會出現 CD/DVD 以及 UEFI:CD/DVD，表示這片安裝光碟同時支援 UEFI 與 BIOS 開機模式，
因此實際啟動的模式還會受開機模式的優先順序影響。

如果製作出來的安裝光碟無法讀取，除了確認映像檔與光碟的總和檢查值之外，
還可以檢查看看光碟的標貼(CDLABEL) 是否與光碟中開機載入程式設定檔的內容相同。
或者將光碟機接在不同的埠上（例如從 USB2 換到 USB3），甚至找一臺內接的 SATA 光碟機試試。

ISO 9660 並未使用開頭的 32K 位元組，因此可以填入額外資訊來模擬其他的儲存裝置。
由於隨身碟容量較大、價格便宜，又有重覆寫入的方便性，因此大部分的 ISO 映像檔(`\*.iso`)，
都被製作成支援 USB 開機的功能。也就是說，使用者可以像處理磁碟映像檔(`*.img`, `*.dd`)一樣，
將 ISO 檔案以 `dd` 命令直接覆寫隨身碟，製作出可開機的安裝媒體：
====
root# *dd if=_install_.iso of=/dev/_sdb_ bs=4M*
====
但是如此也增加了媒體損壞導致安裝過程失敗的風險，因此建議同時考慮安裝方式的備案，
例如使用另外的儲存裝置做為安裝媒體，或是考慮使用精簡型的光碟映像檔（開機之後，需要連上網路才能進行套件安裝）。

另外還有將 ISO 檔案內容拆散後，利用 PXE 伺服器進行的網路開機安裝模式，以及本章稍後會介紹的還原備份映像檔方法。

==== 周邊裝置
對一臺新的硬體型號進行安裝作業系統測試時，周邊裝置的組配應該要儘量簡化，才能減少測試時的變因。
出現問題時可能需要特別留意的地方：

[square]
* 顯示裝置如果規格太新，換一臺比較普通的機型。
* 如果還有支援，試試其他種類的顯示輸出。
* 儘量先不要透過轉接線來顯示輸出。
* 更換不同規格的 USB 連接埠(2.0/3.0)
* 更換不同位置的 USB 連接埠(前端/後端)

==== BIOS 設定
安裝前先確認套用 BIOS 的預設值通常是不錯的選擇，萬一安裝過程不順利或是安裝結果不滿意，才會有一個變更的基礎。
可能需要確認的設定包括了：

[square]
* 開機模式(UEFI/BIOS)
* 安全啟動(SecureBoot)
* 快速啟動(FastBoot)
* 快速儲存技術(RST)
* SATA 模式(IDE/AHCI/RAID)
* USB 的支援版本(1/2/3)
* eMMC 的讀寫速度(HS200/HS400)

==== 儲存裝置
安裝前必須先確認儲存裝置的容量，這會大大地影響安裝過程。隨著功能與複雜度的不斷提升，Linux 系統的大小也持續地增加。
8GB 的磁碟空間已經不敷常見散佈版的標準安裝所需（雖然安裝後實際佔用空間衹有 4~6GB），或是考慮以下〈安裝過程：目標裝置〉小節中所提到的變通方法。
如果安裝軟體有提供精簡版本（例如：LXDE 桌面、基本 X 視窗、最小化）的選項，也可以採用安裝後再自行加入所需軟體的方式，來建構您所想要的環境。

測試系統所用的儲存裝置，當然是以全新品最適合。不過由於常常需要重複測試，還是不可避免會用到安裝過作業系統的裝置。
用過的儲存裝置如果殘留之前的設定，尤其是沒有經過初始分割區表，整支用來儲存資料的隨身碟；
或是曾經被 `dd` 命令直接寫入過光碟映像檔的硬碟，再使用時就可能會造成安裝軟體的誤判。
最好先以外部系統開機（使用自活光碟或是系統隨身碟），然後利用 `gdisk` 命令將目標儲存裝置重建空的分割區表。
萬一儲存裝置曾經是 LVM 的成員，卻需要保留舊資料而無法進行格式化，可以試試 `lvremove`, `vgremove`, `pvremove` 等命令。

有些內建混合型硬碟的機型，會發生安裝軟體無法識別的情形，可能是因為其中的兩顆硬碟曾經被加入 RAID 群組。
萬一也要保留舊資料而無法進行格式化，則需以外部系統進入後執行：
====
root# *dmsetup remove_all* +
root# *dmraid -x /dev/sdb* +
root# *dmraid -r -E /dev/sdb*
====
或是手動抹去最前與最後的 1024 位元組（2 個磁區）：
====
root# *dd if=/dev/zero of=/dev/sdb bs=1k count=1* +
root# *dd if=/dev/zero of=dev/sdb bs=1k seek=$((_磁區數_-2))*
====

更複雜的情況是想要保留儲存裝置上原有的系統，也就是安裝成多重開機的模式。
除了要確認可用空間足夠之外，開機載入軟體的正確安裝與否，將會是系統成敗的關鍵。
安裝順序較後的 Linux 通常都能自動整合安裝較先的其他 Linux，對於 Windows 系統也大多能正確識別，
但是對於 Android, BSD 等系統就需要特別注意。如果還想要使用原先安裝的開機載入軟體，
那麼先要確認對於檔案系統格式與大小的支援限制，以及安裝時必須小心不要將它覆蓋，之後恐怕也無法避免手動的調整。

=== 安裝過程

==== 安裝介面
使用者在安裝過程中面對的操作環境，通常是圖形、文字、網頁三種介面之一：

[square]
* 圖形介面：
標準的安裝介面，通常是功能最完整、操作最方便的模式。如果安裝媒體中的驅動程式支援不佳，
可以加入內核參數 `nomodeset` ，看看能不能進入基本圖形模式，
而有些安裝媒體甚至提供遠端桌面（例如：VNC）的選項。
* 文字介面：
由於顯示器硬體或驅動程式的限制，做為實在無法進入圖形介面時的權宜之計。
不過有些安裝媒體在此介面下，還另外提供了專家模式，允許在安裝過程中進行更細微的調整。
* 網頁介面：
安裝媒體啟動後不提供文字或圖形介面，而是直接建立一個網頁伺服器。
使用者需要利用另一臺機器，透過系統中的瀏覽器來開啟該網路位址的網頁，
然後依照網頁中的功能進行安裝。

==== 內核參數
依據安裝軟體所使用的不同開機載入程式，使用者在安裝媒體啟動時立即按下 kbd:[Tab] 或 kbd:[E]，
就有機會手動輸入各種不同的參數（或稱密技碼），用來調整內核的執行以解決安裝過程中的問題：

[square]
* `nomodeset`: 如果無法進入圖形模式（舊版使用 `xdriver=vesa`）。
* `nortc`: 如果出現無法開啟 rtc 裝置的錯誤訊息。
* `pci=nomsi`: 如果裝置或內核較舊導致系統喚醒有問題。
* `selinux=0`: 如果載入內核之後出現長時間中止。
* `extlinux`: 如果想要安裝另一種開機載入程式。
* `iommu=soft`: 如果載入內核之後鍵盤沒有反應。
其他還有 `noapic`, `nolapic`, `acpi=off` 或 `acpi=force` 可以個別或組合嘗試。

==== 語言與地區
電腦系統中的**語區**(locale) 設定，包括語言設定與地區設定兩大類。
安裝時所選擇的語言，除了會影響安裝介面的顯示之外，也會成為安裝完成後系統的預設語言。
雖然系統語言可以隨時變更，但是由於安裝媒體的發行單位，未必充分驗證過英語以外的語言環境，
因此標準測試仍然應該選擇「en_US(英語－美國)」為優先的語區，除非客戶的確是在非英語環境中使用，
以避免複雜組態（例如：額外的字型、輸入法與空間需求）所造成的差錯風險。

鍵盤佈局當然是以實際操作所用的型式為準，以免出現鍵面字元與送出字元不符的情況。
預設會與語言的選擇一致，如果操作起來不順利，就試試通用的「English(US)」佈局，
或是檢查一下 kbd:[Caps Lock]/kbd:[Num Lock] 的狀態是否正確。

**時區**(timezone) 是安裝過程中與地區設定相關的項目，大多會預設電腦硬體時鐘使用**世界協調時間**(UTC)，
再依照時區設定與配合網路對時的服務，決定系統顯示的時間。
有些系統的安裝過程會提供使用者較多的選擇權力，但其他則會根據時區而自動決定其他相關的地區設定。

==== 目標裝置
如果硬體中包含了一個以上的儲存媒體（例如內建裝置加上外接裝置），尤其是當您為了測試的可攜性，
而決定將系統安裝在隨身碟之類的移動裝置時，必須注意安裝軟體是否預設選擇了您想要的目標。
萬一已過了選擇的步驟，卻發現預設的儲存裝置錯誤，通常可以藉由安裝軟體的上一步功能，回到之前的步驟來修正。
但是別忘了要同時變更開機載入程式的安裝位置，以免發生根檔案系統與開機載入程式不在同一個儲存裝置（除非是有意為之），
而造成無法單獨由目標儲存裝置開機的情況。

從安裝軟體自動偵測到的裝置名稱，可以初步確認是否正確指定了目標裝置。
例如 `/dev/sda` 代表第一個偵測到的 SCSI 介面相容儲存裝置，包括傳統硬碟、固態硬碟、隨身碟，
而 `/dev/sda1` 則代表該項裝置上的第一個分割區。但是 eMMC 或是 SmartCard 類型的儲存裝置，
卻有不一樣的裝置名稱，例如 `/dev/mmcblk0p1` 就是代表第一個該類型裝置上的第一個分割區。

目標儲存裝置的剩餘空間不足，可能會導致安裝軟體的中斷執行，若是剛好稍微低於最小需求，可以採取一些變通方法：
在軟體偵測剩餘空間之前，先插入額外的隨身碟或硬碟，等到偵測通過之後再拔除；
或者如果安裝媒體是先進入**自活系統**(Live System)，再執行以指令稿語言編寫的安裝軟體，
那麼就有機會手動去修改一下程式中的變數值，以繞過空間檢測的限制。

==== 安裝類型
以目前業界標準將開機模式設定為 UEFI 來說，儲存媒體的分割區模式必須採用 *GPT*(全域唯一識別碼分割區表)。
UEFI 相較於 BIOS 開機模式複雜許多，後者一般搭配 *MBR*(主開機記錄) 與 DOS 分割區模式。
因此在安裝過程中，最安全的做法是讓安裝軟體自動產生預設的分割區表（示例如下）：
[.center,width="80%",options="header"]
|====
|分割區	|掛載點		|分割區標籤	|檔案系統
|sda1	|/boot/efi	|ESP		|vfat
|sda2	|/boot		|Linux Native	|ext4
|sda3	|/		|Linux Native	|ext4
|sda4	|		|Linux Swap	|swap
|====

以上設定會將第一個 SCSI 相容儲存裝置全部分配給新的系統使用，原有的系統將被完全覆寫。
如果您真的需要建立一個多重開機的系統，而安裝軟體又沒有提供保留舊系統的選項，
或是系統剩餘的儲存空間已經不夠讓新系統共存，那麼就衹好選擇手動的選項。

假如您需要手動規畫分割區表，必須注意一定要存在一個 ESP 類型，並以 FAT 檔案系統將它規格化。
如果系統會頻繁開關機，而又非常重視妥善率的話，甚至可以考慮建立第二個完全相同的 ESP 做為備援。
雖然預設會建立第一個分割區，大小約為 500MB 的 FAT32 檔案系統，但是如果 BIOS 與內核的相容性（容錯程度）較高時，
不必位於裝置最前方、280 MB 或更小的容量、FAT12/FAT16 的檔案系統，甚至使用 MBR 分割區模式都是有可能接受的。

其中 `/boot` 掛載點還可以併入根檔案分支(/)，或是將 `/home` 從根檔案分支分離出來成為獨立的分割區。
至於**置換分割區**也可以省略，尤其是當系統具備充足的記憶體時，而其他的決定依據可以參考〈儲存裝置：檔案系統〉章節。

==== 套件選擇
除了精簡型的網路安裝光碟之外，一般的安裝媒體都支援離線安裝，同時在偵測到有網路連線時，自動更新或下載部分套件。
某些安裝軟體還可以讓安裝者依據自身需要，決定是否加入含有非自由軟體的套件庫。
如果安裝後重新開機發生問題，不妨試試改採離線安裝的方式，以方便確認問題的來源。

常見的散佈版都是基於套件的組合式系統，因此大多允許使用者在安裝時選擇套件。
安裝軟體通常會提供適用於「桌面」、「伺服器」、「特殊需求」或是「最小化」的整合選項，以方便使用者快速選擇，而不需要擔心套件之間的依存問題。
例如在「桌面」類別之下，包括了「GNOME」、「KDE」、「MATE」、「LXDE」…等選項；在「伺服器」類別之下，則包括了「網頁」、「資料庫」…等選項。

==== 命令列模式
某些額外的安裝需求衹能藉由輸入命令達到，此時就要設法先進入命令列模式。
對於先進入桌面環境再執行的安裝軟體，可以直接打開終端機仿真視窗，
否則試試按下組合鍵 kbd:[Ctrl - Alt - F2]，看看是否能打開一個虛擬終端機。

像是重建**初始記憶體檔案系統**(initramfs) 來加入支援儲存裝置的內核模組：
====
root# *chroot /mnt/sysimage* +
root# *dracut -f --add-drivers "sdhci-pci" /boot/initramfs-$(uname -r).img $(uname -r)* +
====
安裝成功進入系統之後，當然不要忘記修改 `/etc/dracut.conf.d/` 或 `/etc/initramfs-tools/modules` ，
才能在萬一內核更新而 `dracut` 仍未更新時，繼續保有儲存裝置的支援。

==== 主機與使用者名稱
主機名稱要以滿足識別的需求為主，最好可以看到名稱就能知道是哪一臺機器。
如果安裝時並未連上網路，更需特別注意未來在區域網路中的名稱獨一性。

有些安裝軟體允許衹設定超級使用者 root 的賬號，但是仍然建議設定一位一般使用者的賬號與密碼，
至少可以做為超級使用者賬號無法進行管理時的備援機制。

如果衹是做為內部測試用途，那麼建議設定賬號時使用 user 或 tester 之類容易記憶的名稱。
另外可以利用一或多個小寫英文單字，組合而成的長字串做為密碼，以方便其他人員後續測試。
如果是私人用途，習慣上會以英文姓名的簡化組合做為賬號，其中可以穿插數字或底線符號，但不要以數字起始。
密碼則需包括多種類型的字元以及足夠的長度，注意要以自己容易記憶為前提。

=== 安裝後續
如果安裝過程順利，系統會要求使用者重新開機，並且自動將安裝媒體退出。
使用者必須確認於下次啟動時，新安裝的系統會是優先開機的分割區裝置。
萬一無法進入桌面環境，可能有以下幾種原因：

[square]
* BIOS 的開機模式與安裝時不一致。
* 開機載入程式或系統根檔案系統的安裝位置不正確。
* 開機載入程式無法讀取此類型儲存裝置。
* 系統內核不支援或未載入儲存裝置的驅動模組。
* 系統內核對繪圖晶片的支援不佳。
請參考本章之前各節的說明，尋求解決問題的方案。
安裝後的首次啟動，系統預設將會執行一些必要設定。

==== 操作身分
雖然對於臨時的測試系統而言，直接以超級使用者賬號登入在操作時會十分方便，卻無法準確模擬未來真實的使用情境。
安裝軟體可以設定是否自動賦予一般使用者暫時切換為超級使用者的權力，也就是輸入 `sudo` 之後加空格不換列，
再緊接著輸入需要超級使用者身分的命令，並回答一般使用者的密碼即可執行。如果一般使用者不具備 `sudo` 的執行權力，
則需要改為輸入命令 `su -` 並回答超級使用者密碼，便能夠完整切換成超級使用者身分。
====
user$ *sudo _dmidecode_* +
[sudo] password for user: +
user$ *su -* +
Password: +
root#
====
如果具備 `sudo` 執行權力的一般使用者，想要連續以超級使用者身分輸入命令，
還可以結合上面的兩項命令，衹要回答一般使用者的密碼，就可以維持切換成超級使用者身分：
====
user$ *sudo su -* +
[sudo] password for user: +
root#
====
某些安裝完的系統，預設拒絕直接以超級使用者身分登入。
這是利用了 *PAM*(隨插式認證模組) 的功能，相關的設定位於 `/etc/pam.d/` 目錄。

==== 系統調整
如果在安裝時沒有設定好系統時區或時間，可以進入系統後再執行變更的命令：
====
root# *timedatectl set-timezone _Asia/Taipei_* +
root# *timedatectl set-time _"2025-10-04 14:08:00"_*
====

==== 套件更新
進入系統桌面後的第一件事，建議是立即連上網路進行套件更新，並加裝一些個人習慣使用，卻不在預設安裝列表中的套件。
====
root# *dnf update* +
root# *dnf install _joe_*
====
如果更新或安裝作業不成功，請查看是否網路未通、防火牆設定阻擋，或是套件庫的設定不正確。

萬一安裝後的系統實際佔用空間，已經接近儲存媒體的大小，也就是說剩餘的可用空間很少。
那麼就要考慮清理不需要的套件，或是停用基於檔案的置換分割區機制。
另外根據個人操作習慣的不同，「省電設定」與「螢幕保護」也是安裝後常常需要調整的項目。

除了散佈版官方的套件庫之外，使用者還可以自行加入一些由組織或個人提供的非官方套件庫
footnote:[Fedora 社群最常用的 RPM Fusion <https://rpmfusion.org/>]
footnote:[筆者所建立的 RPM Sphere <https://rpmsphere.github.io/>]。
這些第三方套件庫包含了官方套件庫中未收錄的軟體，也許是使用授權不符合收錄的標準，
或是不允許再散佈的專有軟體，亦或是單純因為沒有引起任何套件製作者的興趣。
從第三方套件庫網站取得安裝套件後，以下列指令安裝（直接將檔案網址做為參數亦可）：
====
root# *rpm -Uvh rpmfusion-free-release-_40_.noarch.rpm* +
root# *rpm -Uvh rpmfusion-nonfree-release-_40_.noarch.rpm* +
root# *rpm -Uvh rpmsphere-release-_40_-1.noarch.rpm*
====

==== 備份與還原
所謂的**安裝系統**(installer)，本質上其實就是一套極簡的作業系統，衹是在系統初始化後，自動執行特定的安裝程式。
安裝過程結束後則會關閉系統，通常不會讓使用者有進到桌面或命令列模式的機會。
製作這類可以讓其他人使用的全自動安裝系統，需要藉由特殊的軟體，或是具備程式編寫能力與對於系統深入的了解。
如果衹是為了個人以後使用的手動備份與還原動作，則可參看〈儲存裝置〉中的說明。

而介於兩者之間的半自動備份與還原動作，則有一些開放原始碼軟體可以達成。
例如：Clonezilla
footnote:[Clonezilla 磁碟複殖 <https://clonezilla.org/>]
是一種開放原始碼的磁碟複殖系統。
利用命令稿將許多磁碟映像相關的工具整合在一起（例如 `dd`, `parted`, `partclone`, `partimage` ），搭配基礎開機軟體而以自活光碟映像檔的形式釋出。
啟動系統後可依據選單引導，進行磁碟的映像複製、備份、還原等作業。
將映像檔燒錄到隨身碟或光碟之後，確認系統韌體中的設定，並以其在來源裝置所在的機器上開機。
開機後建議插入額外的隨身碟，做為儲存映像檔目錄或是還原光碟映像檔的裝置。
還原時可直接以還原光碟映像檔所燒錄的自活裝置開機，或是以 Clonezilla 系統配合額外的映像檔目錄儲存裝置來完成。

==== 多重開機
將多個作業系統安裝於同一套硬體系統中，稱之為**多重開機**(multi-booting)。
開機模式當然會受限於系統韌體的支援程度，但是同一個儲存裝置上安裝的作業系統，應該要使用同一種開機模式較為方便。

如果開機韌體無法提供適合的開機選單，通常就需要一個具備選單功能的開機載入程式，
而這類軟體可以是安裝作業系統時附帶，或是由使用者額外安裝。
因此，由於各個開機載入程式的功能與相容性不同，使得安裝作業系統的先後順序也會影響多重開機的結果。
