== 準備工作

=== 需求

客服同事轉發客戶通知時，有時會加上自己的解讀，因此要問清楚哪一部分是客服同事自行補充的資料，最好能要求看到客戶回應的原文內容。

測試內容的擬定應該是基於客戶的實際需求，
把為了達到這些需求而必要的功能列舉出來，
再將能夠確認這些功能的操作型手法做為測試的步驟。

=== 環境
非導體、抗靜電、低磁場、無易燃物

=== 網路
進行測試時所需的資料檔案，一般會放在內部網路的檔案伺服器上，
可能是以 SMB 或是 FTP、HTTP 的協定形式分享出來。

偶爾需要拷貝別臺電腦中的檔案時，通常是以**隨身碟**(Flash Stick) 做為交換的媒介，
因為臨時要啟用一個檔案分享服務，或是先將檔案上傳到伺服器再下載，都似乎稍嫌麻煩。

如果需要互相傳輸檔案的機器都位於同一內部網路的話，其實還有更簡便的方法：
使用 netcat 套件中的命令，就可以實現互傳檔案的功能。
先在接收端輸入以下命令：
====
user$ *nc -l > _foo.bar_*
====

此時接收端會進入等待狀態，直到發送端輸入命令：
====
user$ *nc _192.168.1.2_ < _foo.bar_*
====

其中 _192.168.1.2_ 請替換為接收端的網路位址，而 _foo.bar_ 則代表想要傳輸的檔案名稱。
如果命令與輸入資料都正確，卻出現無法連線的錯誤訊息，有可能是被接收端的防火牆所阻擋。
請先在接收端停止防火牆服務，再重新進行前述的操作即可：
====
root# *systemctl stop firewalld*
====

=== 系統
安裝於隨身碟上

增加額外套件庫

關閉 selinux

關閉螢幕保護

有些散佈版預設停用「自動開啟網路」，可以依據需要在測試前啟用。

安裝合用編輯器

=== 硬體組裝

==== 電源開關
當主板上採用的不是焊接好的開關型式，那就要搭配符合接頭的開關元件。
一般來說都有防呆機制，因此問題不大。如果萬一臨時找不到，
除非能夠確定正負極的腳位，否則切勿使用鑷子將開關插座中的針腳快速短路的方法，
以免為了一時的方便而損壞了主板。

==== 電池
有時故意地將電池拆下，等待數分鐘或是將電池座中的正負接頭短路，
可以重置系統韌體因誤設而造成的混亂內容。但是如果在未留意的狀況下，
電池的電力耗盡或是接點接觸不良，反而會導致系統韌體設定的不正常行為，
造成軟體系統後續無法預期的錯誤出現。

==== 中央處理器
類 PC 系統中的處理器，大多採用**單晶片系統**(SoC) 的型式，於工廠生產時便已焊接於主板之上。
除了少數系統使用**處理器模組**(SoM) 的外插型式，通常測試人員並不需要自行安裝。

如果需要對於試作生產的裸板進行測試時，最常遇到散熱相關的問題。
要注意散熱膏與散熱鰭片的安裝是否正確，否則處理器過熱會導致測試中出現許多不穩定的狀況，
必要時還應準備冷卻噴劑。

==== 記憶體
雖然記憶體的世代變換非常快速，自 DDR2...DDR5 一路以來不斷更新，
但是不同規格的模組都有不同的防呆缺腳，因此安裝方面相對簡單。
有時需要注意母板與模組之間，彼此的低電壓規格是否搭配。另外，
測試用的記憶體模組容易因為頻繁的插拔而沾染到一些油漬或灰塵，
可以利用橡皮擦來清潔金手指的部分。

==== 固態硬碟
固態硬碟從外形上主要分為晶片內包的封裝型式，以及晶片外露的模組型式。
封裝型式大多採用 SATA 或 USB 介面，前者應注意是否需要外加一條電源線，
模組型式的介面則可能是 SATA Slim、mSATA 或 M.2 的插口。
對於測試用的治具，除了注意金手指部分的清潔之外，還要避免過高的磁場與過於頻繁的讀寫，
才能有效延長模組的使用壽命。

==== 周邊裝置
外接裝置的接頭有方向之分，通常標誌的圖案會朝上方，或是大拇指按住的地方，或是離主機板較遠的一側。


=== 方法論

相關不表示因果

盲點之一是想要窮盡所有的組態組合

盲點之二是想要用盡所有手邊的工具

=== 伺服服務
Port Number	Service	Use Case
20, 21	FTP	File Transfer
22	SSH	Secure Remote Login
53	DNS	Domain Name Resolution
80	HTTP	Serving Web Pages
443	HTTPS	Secure Web Pages
631	CUPS	Printer Management and Networking
5900	VNC	Remote Desktop Access

有些情況網路服務無法使用的原因，是由於本機時間與伺服器差別太大。

==== FTP
由於協定規格中對於資訊安全的防護較弱，因此有逐漸減少這類服務的趨勢。

./etc/vsftpd/vsftpd.conf (部分)
....
anonymous_enable=YES
local_enable=YES
write_enable=YES
local_umask=022
....

FTP 的客戶端程式可選用文字模式的 `lftp` 或是圖形模式的 `gftp` 。
FTP 測試出問題的可能原因有以下設定：語區、主動╱被動、SELinux、防火牆、使用配額。

==== HTTPS

==== DNS

==== VPN

==== SPICE

==== GIT

==== SMB

==== CUPS

==== RDP
Linux 系統是以 `xrdp` 套件來提供使用 RDP 協定的遠端桌面，安裝後即會啟動 `xrdp` 服務。
連線此服務時會執行自帶的顯示管理程式，使用者登入後，接著執行系統的預設的作業階段管理程式。
因此有需要，先將其鏈結至想要的真實作業階段管理程式：
====
root# *update-alternatives --set x-session-manager _/usr/bin/xfce4-session_*
====
上述範例即會由作業階段管理程式導引至 XFCE 桌面環境。

==== firewalld
網路組態中的**防火牆**(firewall) 設置，主要在日常使用的開放環境系統中，負責阻斷未經允許的網路輸入輸出。
但是在封閉的測試環境下，有可能因為疏忽反而造成其他伺服程式的不便。
防火牆的通用服務名稱為 `firewalld` ，在 Systemd 系統初始模式下可以依照一般使用 `systemctl` 命令的方式，搭配 `stop` 或 `disable` 選項分別予以停止或停用。
即使確定之後不會用到防火牆功能，但由於套件依存關係而不方便直接移除，也可以再利用 `systemctl` 命令的 `mask` 選項來阻止它被其他軟體啟動。

=== 伺服程式

==== x11vnc
如果衹有單純的遠端桌面需求，可以安裝支援 VNC/RFB 協定的 `x11vnc` 伺服程式，然後輸入指令：
====
user$ *x11vnc -forever -repeat -passwd _連線密碼_ &*
====
即可藉由其他系統的 VNC 客戶端軟體連至目前的桌面：
====
user$ *vncviewer -DotWhenNoCursor -passwd _密碼檔案_ _網路地址_*
====
其中的__密碼檔案__即儲存了所需的__連線密碼__。

==== iperf

==== croc

==== nc
