== 準備工作

=== 硬體組裝

==== 電源開關
當主機板上採用的不是焊接好的開關型式，那就要搭配符合接頭的開關元件。
一般來說都有防呆機制，因此問題不大。如果萬一臨時找不到，
除非能夠確定正負極的腳位，否則切勿使用鑷子將開關插座中的針腳快速短路的方法，
以免為了一時的方便而損壞了主機板。

==== 電池
有時故意地將電池拆下，等待數分鐘或是將電池座中的正負接頭短路，
可以重置系統韌體因誤設而造成的混亂內容。但是如果在未留意的狀況下，
電池的電力耗盡或是接點接觸不良，反而會導致系統韌體設定的不正常行為，
造成軟體系統後續無法預期的錯誤出現。

==== 中央處理器
類 PC 系統中的處理器，大多採用**單晶片系統**(SoC) 的型式，於工廠生產時便已焊接於主機板之上。
除了少數系統使用**處理器模組**(SoM) 的外插型式，通常測試人員並不需要自行安裝。

如果需要對於試作生產的裸板進行測試時，最常遇到散熱相關的問題。
要注意散熱膏與散熱鰭片的安裝是否正確，否則處理器過熱會導致測試中出現許多不穩定的狀況，
必要時還應準備冷卻噴劑。

==== 記憶體
雖然記憶體的世代變換非常快速，自 DDR2...DDR5 一路以來不斷更新，
但是不同規格的模組都有不同的防呆缺腳，因此安裝方面相對簡單。
有時需要注意母板與模組之間，彼此的低電壓規格是否搭配。另外，
測試用的記憶體模組容易因為頻繁的插拔而沾染到一些油漬或灰塵，
可以利用橡皮擦來清潔金手指的部分。

==== 固態硬碟
固態硬碟從外形上主要分為晶片內包的封裝型式，以及晶片外露的模組型式。
封裝型式大多採用 SATA 或 USB 介面，前者應注意是否需要外加一條電源線，
模組型式的介面則可能是 SATA Slim、mSATA 或 M.2 的插口。
對於測試用的治具，除了注意金手指部分的清潔之外，還要避免過高的磁場與過於頻繁的讀寫，
才能有效延長模組的使用壽命。

==== 周邊裝置
外接裝置的接頭有方向之分，通常標誌的圖案會朝上方，或是大拇指按住的地方，或是離主機板較遠的一側。



=== 環境與工具
測試場所的環境與工具，對於測試的進行也非常重要。
待測機器應放置於可移動的層架中，各層以略大於待測機器的空間分隔，但也要考慮到插拔線路與周邊等操作方便。
測試用治具則放置於不可移動的較大分層架中，通常位於長桌中央以方便兩邊共用。
測試桌面必須是非導體、不易滑動、不易燃的材質，尤其注意不可有金屬的釘孔或邊條，還要避免容易產生靜電、磁場的環境。

==== 網路
進行測試時所需的資料檔案，一般會放在內部網路的檔案伺服器上，
可能是以 SMB 或是 FTP、HTTP 的協定形式分享出來。












=== 伺服服務/程式
Port Number	Service	Use Case
20, 21	FTP	File Transfer
22	SSH	Secure Remote Login
53	DNS	Domain Name Resolution
80	HTTP	Serving Web Pages
443	HTTPS	Secure Web Pages
631	CUPS	Printer Management and Networking
5900	VNC	Remote Desktop Access

有些情況網路服務無法使用的原因，是由於本機時間與伺服器差別太大。
須先確認來源機器 IP 並與目標機器連網且無防火牆 (可用 ping 程式測試)
測試出問題的可能原因有以下設定：語區、主動╱被動、SELinux、防火牆、使用配額。

==== 檔案服務
由於 FTP 協定規格中對於資訊安全的防護較弱，因此有逐漸減少這類服務的趨勢。
常用的伺服服務套件是 `vsftpd` ，提供同名的 Systemd 服務，而預設的資料根目錄則位於 `/var/ftp/` 。
組態設定檔中比較重要的部分包括：

./etc/vsftpd/vsftpd.conf (部分)
....
anonymous_enable=YES
local_enable=YES
write_enable=YES
local_umask=022
....
FTP 的客戶端程式可選用文字模式的 `lftp` 或是圖形模式的 `gftp` 。


HTTP/HTTPS
測試網站是否支援 TLS 1.2：
====
user$ *openssl s_client -connect __網站網路位址__:443 -tls1_2*
====

除了啟動正式的網頁伺服服務之外，也可以執行臨時的網頁伺服程式來提供檔案分享。
假設伺服器中想要分享的檔案位於當前的目錄，在安裝並執行 `mongoose` 命令之後，就可以在客戶端利用 `wget http://__網路位址__:8000/__檔案名稱__` 來取得檔案。
另外一個在伺服端建立臨時網頁伺服器的方法，是利用 `python` 語言提供的模組來執行 `python3 -m http.server` 指令。
客戶端若要取得臨時分享目錄中的所有檔案，則可用指令 `wget -r -nH wget http://__網路位址__:8000/` 。




SMB 服務在新版內核中已經成為一個模組。

GIT 是一種**原始碼管理**(SCM) 軟體，提供分散式地控制與管理原始碼版本的服務。
可安裝 gitlab 或 gogs, Gitea 網頁應用
最好還是利用 github 服務，如果有保密疑慮可購買私有服務



==== 遠端登入
同樣附屬於 SSH 協定的還有 SFTP 服務，預設伺服器端的設定是禁止以管理者身分登入。
無法登入時還要先確定不是因為鍵盤接觸不良所導致的輸入亂碼，還有可能是使用者登入後自動執行過程出現錯誤。

Linux 系統是以 `xrdp` 套件來提供使用 RDP 協定的遠端桌面，安裝後即會啟動 `xrdp` 服務。
連線此服務時會執行自帶的顯示管理程式，使用者登入後，接著執行系統的預設的作業階段管理程式。
因此有需要，先將其鏈結至想要的真實作業階段管理程式：
====
root# *update-alternatives --set x-session-manager _/usr/bin/xfce4-session_*
====
上述範例即會由作業階段管理程式導引至 XFCE 桌面環境。

另外還有 Linux 上的**獨立計算環境簡單協定**(SPICE) 開放標準，適用於虛擬環境的遠端桌面顯示，一般應用較不常見。
以下僅列出設置伺服端時最重要的**網路橋接**(network bridge) 設定，提供使用者需要時參考：
====
root# *systemctl enable libvirtd* +
root# *systemctl disable firewalld* +
root# *nmcli connection add type bridge autoconnect yes con-name br0 ifname br0* +
root# *nmcli connection modify br0 ipv4.addresses _10.10.2.78/24_ ipv4.method manual* +
root# *nmcli connection modify br0 ipv4.gateway _10.10.2.254_* +
root# *nmcli connection modify br0 ipv4.dns _10.10.1.2_* +
root# *nmcli connection modify br0 ipv4.dns-search _yourdomain.com_* +
root# *nmcli connection del _eth0_* +
root# *nmcli connection add type bridge-slave autoconnect yes con-name _eth0_ ifname _eth0_ master br0*
====

傳統由 X 視窗顯示管理程式所提供的 *XDMCP* 連線方式，目前必須要修改設定檔才會啟用：

./etc/gdm/custom.conf (部分)
....
[xdmcp]
Enable=true
Port=177
....
並且可能要刪除檔案 `/usr/share/polkit-1/org.freedesktop.color.policy` ，以避免連線時要求建立色彩描述檔。
客戶端的連線指令範例如下：
====
user$ *Xephyr :1 -fullscreen -br -bs -render default -dpi 96 +xinerama -reset -terminate -query _伺服端網路位址_*
====

如果衹有單純的遠端桌面需求，可以安裝支援 VNC/RFB 協定的 `x11vnc` 伺服程式，然後輸入指令：
====
user$ *x11vnc -forever -repeat -passwd _連線密碼_ &*
====
即可藉由其他系統的 VNC 客戶端軟體連至目前的桌面：
====
user$ *vncviewer -DotWhenNoCursor -passwd _密碼檔案_ _網路位址_*
====
其中的__密碼檔案__即儲存了所需的__連線密碼__。

如果遠端連線的性能要求不高，伺服端又不想安裝完整的伺服軟體，客戶端也希望衹需要網頁瀏覽器就能連線，那就可以考慮採用遠端桌面閘道服務：
例如開放原始碼的 DWService
footnote:[DWS 遠端桌面閘道服務<https://www.dwservice.net/>]，免費註冊時還可選擇「傳統字漢語」網頁介面，而於伺服端安裝自動執行的代理程式後即可分享控制；
或是嘗試自行架設 Apache Guacamole
footnote:[Apache Guacamole 遠端桌面閘道軟體<https://www.dwservice.net/>]，當然也必須面對有可能被防火牆擋住，而無法提供外部連線的問題。

==== 網路相關
網路組態中的**防火牆**(firewall) 設置，主要在日常使用的開放環境系統中，負責阻斷未經允許的網路輸入輸出。
但是在封閉的測試環境下，有可能因為疏忽反而造成其他伺服程式的不便。
防火牆的通用服務名稱為 `firewalld` ，在 Systemd 系統初始模式下可以依照一般使用 `systemctl` 命令的方式，搭配 `stop` 或 `disable` 選項分別予以停止或停用。
即使確定之後不會用到防火牆功能，但由於套件依存關係而不方便直接移除，也可以再利用 `systemctl` 命令的 `mask` 選項來阻止它被其他軟體啟動。

iperf



==== 檔案傳送
偶爾需要拷貝別臺電腦中的檔案時，通常是以**隨身碟**(Flash Stick) 做為交換的媒介，
因為臨時要啟用一個檔案分享服務，或是先將檔案上傳到伺服器再下載，都似乎稍嫌麻煩。
如果需要互相傳輸檔案的機器都位於同一內部網路的話，其實還有更簡便的方法：
使用 `netcat` 套件中的命令 `nc` ，就可以實現互傳檔案的功能。
先在接收端輸入以下命令：
====
user$ *nc -l > _檔案名稱_*
====
此時接收端會進入等待狀態，直到發送端輸入命令：
====
user$ *nc _網路位址_ < _檔案名稱_*
====
此時接收端就會開始接收傳輸並儲存成指定名稱的檔案。
對於需要指定網路埠號並且傳輸整個目錄的狀況下，接收端的命令可改為：
====
user$ *nc -l -p 31337 | tar xvf -*
====
相應的發送端指令範例則是：
====
user$ *tar cvf - _目錄路徑_ | nc _網路位址_ 31337*
====
如果命令與輸入資料都正確，卻出現無法連線的錯誤訊息，有可能是被接收端的防火牆所阻擋。

有些散佈版還會提供工具軟體 `croc` ，可以很方便地在區域網路中傳檔，而且是由發送端先啟動。
輸入指令 `croc send --code _臨時密碼_ _檔案或目錄_` 之後，發送端就進入等待傳輸狀態，然後再由接收端輸入 `croc _臨時密碼_` 即可開始傳送。


=== 外部測試系統

==== 自活系統
最簡單的方式就是利用各種散佈版所提供的自活系統，通常已經和散佈版的安裝系統整合在一起。
將下載來的 ISO 檔案燒錄到光碟上，或是以 `dd` 命令寫入隨身碟後，就可以用來做為外部系統開機。
如果手上有多個 ISO 檔案，還可以先製作一支 Ventoy
footnote:[Ventoy: 新的可開機 USB 解決方案 <https://www.ventoy.net/>]
隨身碟，再將所有的可開機 ISO 檔案收集、整合在一起。

如果想利用自活系統簡單、快速的特性，來執行特定的開機後單一動作，也可以嘗試進行自活系統的客製化。
以常見的自活系統 SystemRescue
footnote:[SystemRescue: 系統救援工具箱 <https://www.system-rescue.org/>]
為例：首先準備好 `systemrescue-12.01-amd64.iso` 並編輯所需的 `data/autorun` 與 `data/datafile` 檔案；
然後利用十六進位編輯程式（ `hexedit` 或 `ghex` ），將 ISO 檔案中的 `timeout=90` 字串改為 `timeout=0 ` ；
接著執行指令：
====
user$ *growisofs -Z /dev/sr0=systemrescue-12.01-amd64.iso* +
user$ *growisofs -M /dev/sr0 -J -R data/*
====
將 ISO 檔案以及附加替代檔案燒入，以重新壓製(remastering) 光碟，之後還可用 `dd` 命令將光碟內容備份出新的 ISO 檔案。

==== 完整系統
安裝於隨身碟上
製作專用的測試系統，將其安裝於 USB 上，如果能做成支援雙重開機模式更好。
測試系統所用的使用者名稱與密碼，應該要與其他測試人員協調一致，以便於交叉複測的進行。
增加額外套件庫

關閉 selinux

關閉螢幕保護

有些散佈版預設停用「自動開啟網路」，可以依據需要在測試前啟用。

安裝合用編輯器



=== 個人準備

==== 釐清需求

客服同事轉發客戶通知時，有時會加上自己的解讀，因此要問清楚哪一部分是客服同事自行補充的資料，最好能要求看到客戶回應的原文內容。

測試內容的擬定應該是基於客戶的實際需求，把為了達到這些需求而必要的功能列舉出來，再將能夠確認這些功能的操作型手法做為測試的步驟。

==== 方法論

相關不表示因果

盲點之一是想要窮盡所有的組態組合

盲點之二是想要用盡所有手邊的工具

==== 基本技能
測試相比於一般操作需要更多時間待在命令列視窗中，因此具備英文盲打技能將會使過程更順利。



