== 開機前執行環境
NOTE: 沒有建置 PXE 需求的讀者，可先略過本章內容。

*PXE*(開機前執行環境) 可以視為由韌體提供具有網路功能的軟體載入器，具備通用的網路卡驅動模組，
能夠從網路上直接載入整個作業系統，或是間接載入內核，又或是先載入前端的開機管理程式。
網路開機與本機開機的流程類似，衹是軟體部分經由網路取得，而非來自本機儲存裝置。

PXE 實際上是一項網路技術，提供此項技術的軟體稱為「PXE 伺服應用」；而提供此項技術的硬體則稱之為「PXE 伺服主機」，兩者均常以通稱「PXE 伺服器」來代表。
關於網路的基本設定，請參閱〈網路裝置〉中的說明；而從〈準備工作：伺服服務與程式〉小節的內容，則已介紹了部分服務的設定。

=== 建置安裝
作用於區域網路的 PXE 技術，客戶端與基本的伺服端機器必須位於同一個區域網路，但是提供檔案的伺服器則沒有這個限制。
通常現有的辦公用區域網路都已經具備了動態主機設定服務，並不適合做為 PXE 技術測試環境，因為很容易造成相互干擾。
最好將客戶端與伺服端連接於一臺額外的交換器(switch) 或集線器(hub)，建置一組獨立的測試用區域網路。
如果兩端各衹有一臺測試機，也可以直接用一般的網路線相連（目前的網路晶片已不再需要跳線）。

==== 客戶端系統韌體
支援 PXE 技術的客戶端機器，必須能夠經由系統韌體設定為網路開機，設定時還要注意優先順序以及想要使用的網路協定。
PXE 開機時如果出現記憶體不足的訊息，可以試試藉由網路載入作業系統的內核參數 `mem=` 或 `ramdisk_size=` 來增加可以運用的記憶體，或是降低系統韌體設定中的 DVMT(動態視訊記憶體技術) 用量。
如果在開機過程中無法使用鍵盤或滑鼠，可以試試停用系統韌體設定中的 Fast Boot(快速開機) 功能，
或是調整其他與 USB 有關的項目；直接改換不同的 USB 插口(socket) 也可能會有幫助。

==== 伺服端安裝套件
為了建置 PXE 網路技術，需要安裝以下套件：
（不同的散佈版所使用的套件名稱可能不同，有些還會載入其他依存的套件，可以藉由搜尋重點檔案是否包含來確認。）

[square]
* `dhcp-server`: 提供 DHCP(動態主機組態協定) 服務，重點檔案為 `dhcpd`, `dhcpd.service` 與 `dhcpd6.service` 。
* `tftp-server`: 提供 TFTP(簡易檔案傳輸協定) 服務，重點檔案為 `in.tftpd`, `tftp.socket` 與 `tftp.service` 。
* `httpd`: 提供 HTTP(超文字傳輸協定) 服務，重點檔案為 `httpd`, `httpd.socket` 與 `httpd.service` 。
* `nfs-utils`: 提供 NFS(網路檔案系統) 服務，重點檔案為 `nfs-server.service` 。
* `syslinux`: 提供 BIOS PXE 開機載入程式，重點檔案為 `pxelinux.0` 。
* `grub2-efi-x64`: 提供 UEFI PXE 開機載入程式，重點檔案為 `grubx64.efi` 。

==== 伺服端網路設定
首先賦予 PXE 伺服器一個自訂的主機名稱：
====
root# *hostnamectl set-hostname _pxe.lab.local_*
====
`/etc/hostname` 的內容即成為設定的主機名稱。
然後看一下目前的網路裝置組態：
====
root# *nmcli connection show* +
NAME　　UUID　　　　　　　　　　　　　　　　　　　　TYPE　　　 DEVICE +
eth0　　92225193-b020-3257-9c4c-d0fa2a06cadf　ethernet　eno1 +
lo　　　e36fa446-245d-454c-962e-97a0e1e9327e　loopback　lo
====
指令中的 `connection` 可以簡寫為 `c` ，而輸出的第一欄 `NAME` 或第二欄 `UUID` 的值，可以做為其他指令中用來指定裝置的參數名稱。
接著設定為固定 IP：
====
root# *nmcli c modify _eth0_ ipv4.address _192.168.0.1/24_* +
root# *nmcli c modify _eth0_ ipv4.gateway _192.168.0.254_* +
root# *nmcli c modify _eth0_ ipv4.dns _192.168.0.254_* +
root# *nmcli c modify _eth0_ ipv4.dns-search _lab.local_* +
root# *nmcli c modify _eth0_ ipv4.method manual*
====
如果也想支援 IPv6 的話，需要進行相應的設定：
====
root# *nmcli c modify _eth0_ ipv6.address _fd::1/64_* +
root# *nmcli c modify _eth0_ ipv6.gateway _fd::fd_* +
root# *nmcli c modify _eth0_ ipv6.dns _fd::fd_* +
root# *nmcli c modify _eth0_ ipv6.dns-search _lab.local_* +
root# *nmcli c modify _eth0_ ipv6.method manual*
====
檔案 `/etc/hosts` 的內容加上：

./etc/hosts
....
192.168.0.1     pxe.lab.local
fd::1           pxe.lab.local
...
....

同時不要忘記檢查一下，是否網路裝置已經設定為開機後自動連線，否則就應該要執行設定指令：
====
root# *nmcli -f name,autoconnect c* +
NAME　　　　AUTOCONNECT +
eth0　　　　否 +
lo　　　　　否 +
root# *nmcli c modify _eth0_ connection.autoconnect yes*
====
相關設定會儲存於 `/etc/NetworkManager/system-connections/` 目錄中的檔案。
假設有需要手動將裝置連線的話，可以輸入：
====
root# *nmcli c up _eth0_*
====

=== 服務需求
基本的 PXE 技術是由兩項網路服務所組成：DHCP 與 TFTP。
前者負責配送網路位址與相關網路資訊，後者則負責提供開機檔案，兩者可建置於單一主機，或是分散於兩臺主機。
進階的 PXE 技術則包含了 HTTP 與 NFS 服務，提供更快速的檔案傳輸以及功能更完整的網路檔案系統。

==== TFTP 服務
提供 TFTP 服務的主機稱為 TFTP 伺服器，它是 DHCP 服務預設搭配的簡易檔案傳輸協定，
因此又稱為 next-PXE 伺服器，而在 DHCP 的組態檔中是以 `next-server:` 的項目來指定網路位址。
預設放置傳輸檔案的位置在 `/var/lib/tftpboot/` 目錄之下，這也被稱為 TFTP 的根目錄，其中的檔案建議都要開啟可讀的屬性。

TFTP 服務是藉由 `tftp.socket` 的形式所觸發，因此嘗試啟用的命令為：
====
root# *systemctl enable tftp.socket*
====
亦即正常狀況下，當 DHCP 服務需要進一步提供檔案時，才會引發 TFTP 服務（雖然還是可以手動啟動它）。

==== HTTP 服務
如果將上述的 TFTP 改為 HTTP 則稱之為 PXE-HTTP 網路技術，衹有較新的系統韌體才會提供。
雖然支援 PXE-HTTP 的系統韌體一般也會支援 PXE-HTTPS，但是在伺服端還是以建置 HTTP 服務較為方便。
目前的 `httpd` 套件，預設為安裝 Apache HTTP 伺服器。
做為提供靜態檔案的服務，組態檔的內容通常不需要修改，除非想要更動一些預設值：

./etc/httpd/conf/httpd.conf
....
Listen 80
DocumentRoot "/var/www/html"
...
....

做為測試目的而將 HTTP 與 TFTP 服務由同一臺伺服器提供時，可將兩者的根目錄鏈結為同一位置：
====
root# *rmdir /var/www/html* +
root# *ln -s ../lib/tftpboot /var/www/html*
====

嘗試啟動 `httpd.service` 之後，如果運作正常，就可以將它設定為啟用：
====
root# *systemctl start httpd* +
root# *systemctl enable httpd*
====

==== NFS 服務
除了傳送並執行開機檔案之外，透過 PXE 技術載入具備網路模組的內核，然後再接續掛載網路檔案系統，就可以達成「無碟系統」的功能。
NFS 是最普遍使用的 Linux 網路檔案系統，由於內核已具備客戶端的模組，因此可將其編譯為內建，或是包含在初始記憶體檔案系統中。
常見的 NFS 服務，是由運行在內核空間中的內核模組所提供的。
提供 NFS 服務的伺服器，就是無碟系統檔案所**寄存**(hosted) 的地方。

./etc/exports
....
/var/nfs *(rw,no_root_squash,sync,no_all_squash)
....

嘗試啟動 `nfs-server.service` 之後，利用命令 `exportfs` 可以在伺服器上列出目前分享的目錄。
如果運作正常且確認未受防火牆影響，就可以將它設定為啟用：
====
root# *systemctl start nfs-server* +
root# *exportfs* +
/var/nfs　　　　 <world> +
root# *systemctl enable nfs-server*
====

==== DHCP 服務
提供 DHCP 服務的主機，稱為 DHCP 伺服器。
為了區分 IPv4 與 IPv6，系統套件提供 `dhcpd.service` 與 `dhcpd6.service` 兩個分開的服務，實際的單元檔案則位於 `/usr/lib/systemd/system/` 目錄之中。
兩個服務雖然呼叫同一個程式，但是利用不同的選項使得各自的功能獨立，並且讀取不同的組態檔：

./etc/dhcp/dhcpd.conf
....
option domain-name "lab.local";
option domain-name-servers 192.168.0.254;
option routers 192.168.0.254;
ddns-update-style none;
authoritative;
option arch code 93 = unsigned integer 16;
next-server 192.168.0.1;

subnet 192.168.0.0 netmask 255.255.255.0 {
  range 192.168.0.100 192.168.0.250;
  if option arch = 00:07 {
    filename "uefi/grubx64.efi";
  } else if option arch = 00:10 {
    option vendor-class-identifier "HTTPClient";
    filename "http://192.168.0.1/uefi/gentoo.efi";
  } else {
    filename "pxelinux.0";
  }
}
....

./etc/dhcp/dhcpd6.conf
....
option dhcp6.domain-search "lab.local";
option dhcp6.name-servers fd::fd;
option dhcp6.preference 255;
option dhcp6.bootfile-url code 59 = string;
option dhcp6.vendor-class code 16 = {integer 32, integer 16, string};
option dhcp6.client-arch-type code 61 = array of unsigned integer 16;

subnet6 fd::/64 {
  range6 fd::10 fd::df;
  if option dhcp6.client-arch-type = 00:07 {
    option dhcp6.bootfile-url "tftp://[fd::1]/uefi/grubx64.efi";
  } else if option dhcp6.client-arch-type = 00:10 {
    option dhcp6.vendor-class 0 0 "HTTPClient";
    option dhcp6.bootfile-url "http://[fd::1]/uefi/gentoo.efi";
  } else {
    option dhcp6.bootfile-url "tftp://[fd::1]/pxelinux.0";
  }
}
....

對於這兩個服務的嘗試啟動與啟用，當然必須分別執行：
====
root# *systemctl start dhcpd* +
root# *systemctl enable dhcpd* +
root# *systemctl start dhcpd6* +
root# *systemctl enable dhcpd6*
====

WARNING: dhcpd 與 dhcpd6 兩個服務如果由於網路尚未連線而過早啟動導致失敗，可以考慮加入 `ExecStartPre=/usr/bin/sleep 10` 的延遲設定於單元檔案的 `[Service]` 段落。

一般區域網路的電腦系統，都預設為自動發送 DHCP 需求以取得網路位址，如果需要手動發送則可執行 `dhclient` 命令。
想要偵測網路中是否有 IPv4 DHCP 服務存在，可以執行 `nmap --script broadcast-dhcp-discover` 指令。

=== 主要功能
DHCP 組態檔中 `filename` 項目所分發的檔案，開啟了後續的 PXE 主要功能。
需要網路開機的裝置，會從 DHCP 伺服器的回應中，得到 TFTP 伺服器以及 PXE 開機檔案的位置資訊。
系統韌體利用 TFTP 協定取得檔案之後，隨即將其載入記憶體中並轉移系統控制權給它。

==== 開機載入
在 BIOS 開機模式下，傳統的 PXE 選單功能是由 `pxelinux.0` 這個檔案所提供。
它是 SYSLINUX 軟體家族中，類似 GRUB 且具有網路功能的開機載入程式。
建置者通常會將 PXE 的主體以及需要的工具與模組檔案，拷貝到 TFTP 的根目錄下：
====
root# *mkdir -p /var/lib/tftpboot/pxelinux.cfg* +
root# *cd /usr/share/syslinux* +
root# *cp pxelinux.0 memdisk *.c32 /var/lib/tftpboot/* +
====

在 UEFI 模式下與本地開機類似，PXE 開機載入功能也可由 `grubx64.efi` 這個檔案提供，有時依情況藉助 `BOOTx64.efi` 或是支援安全啟動的 `shimx64.efi` 等檔案間接引入。
雖然 SYSLINUX 軟體家族也有提供相應的 `syslinux.efi` （或稱 `pxelinux.efi` ），但是一般來說使用並不普遍。
如果 PXE 伺服主機同樣以 UEFI 模式開機，那麼所需檔案可以直接從 `/boot/efi/EFI/_散佈版_/` 目錄中拷貝過來。
在之前的 DHCP 組態檔範例中，相關的檔案是放在 TFTP 根目錄下的 `uefi/` 子目錄內。

PXE 開機檔案也可以是具有自我完備功能的單一檔案，例如 BIOS 模式下可開機的 `\*.iso` 檔案，或是 UEFI 模式下可獨立運作的 `*.efi` 檔案。
不過由於需要將整個檔案載入記憶體，因而導致開機時間可能過長或者軟體功能有所限制。

==== 開機選單
`/var/lib/tftpboot/pxelinux.cfg/default` 是 `pxelinux.0` 的預設組態檔。
PXELINUX 如同 SYSLINUX 家族中的其他軟體一樣，組態檔的結構其實與 GRUB 相差不多。

./var/lib/tftpboot/pxelinux.cfg/default
....
ui vesamenu.c32
prompt 0
timeout 50
default dos

label dos
  menu label FreeDOS 1.4 Live
  kernel memdisk
  append initrd=image/FD14BOOT.img
...
....

如果想要依個別的網路卡號分別設定，還可以在 `pxelinux.cfg/` 目錄中建立像是 `_nn-xx-xx-xx-xx-xx-xx_` 的檔案。
檔名中的 _nn_ 是以數字表示的優先順序，_xx-xx-xx-xx-xx-xx_ 則是小寫的網路卡號，內容格式則與 `default` 檔案相同。

UEFI 模式的 `grubx64.efi` 預設會讀取同一目錄中的 `grub.cfg` 做為組態檔，而不同網卡的設定可以放在 `grub.cfg-_nn-xx-xx-xx-xx-xx-xx_` 名稱格式的檔案中。

./var/lib/tftpboot/uefi/grub.cfg
....
terminal_output console
set timeout_style=menu
set timeout=5
insmod all_video
set gfxpayload=keep
insmod efinet
insmod gzio
insmod part_gpt
insmod ext2
insmod chain
set root=tftp,192.168.0.1
set default="0"

menuentry 'UEFI Shell 2.2' {
  chainloader uefi/Shell.efi
}
...
....
在 IPv6 的網路環境中，需要修改相應的網路位址，亦即將上例中的 `192.168.0.1` 改為 `fd::1` 。

==== 載入光碟映像檔
PXELINUX 利用軟體隨附的 `memdisk` 程式扮演簡化的內核角色，直接將初始記憶體磁碟指定為要載入的映像檔路徑，但並不適用於大容量的檔案：

./var/lib/tftpboot/pxelinux.cfg/default
....
...
label slitaz
  menu label Slitaz 5.0rc Live
  kernel memdisk
  append initrd=image/slitaz-rolling-core64.iso iso raw
...
....

GRUB 則需要先以 `loopback` 指令將映像檔掛載之後，再載入其中的內核與初始記憶體檔案系統，因此僅適用於 Linux 類的作業系統：

./var/lib/tftpboot/uefi/grub.cfg
....
...
menuentry 'TinyCore 16.1' {
  set iso=image/TinyCorePure64-16.1.iso
  loopback loop ${iso}
  linuxefi (loop)/boot/vmlinuz64 cde iso-scan/filename=${iso}
  initrdefi (loop)/boot/corepure64.gz
}
...
....

==== 載入網路作業系統
透過網路開機所載入的軟體中，最實用的目標當然就是一個寄存的無碟 Linux 作業系統。
由於 TFTP 傳輸的速度較慢，而且有限的功能無法做為適當的網路檔案系統，
因此 PXE 技術通常衹負責傳送開機載入程式、內核與初始記憶體檔案系統，剩下的部分則由內核自行掛載。

不過，有些散佈版的標準初始記憶體檔案系統組態並不支援網路開機，這可以藉由 `lsinitrd -m` 指令的輸出來確認，因此必須先在原系統中重建初始記憶體檔案系統：
====
root# *dracut -a "network nfs" --add-drivers "_r8169_ nfsv4" initramfs.img $(uname -r)*
====

製作前要確認是否已安裝 `dracut-network` 與 `nfs-utils` 套件，也要包含無碟系統的網路卡內核驅動模組，這樣新產生出來的 `initramfs.img` 才能用於網路開機。
假設給 PXE 的傳送檔案想要放在 TFTP 根目錄下的 `linux/` 子目錄中，就要將網路寄存系統的 `vmlinuz` 與 `initramfs.img` 檔案拷貝過來，並且記得設為所有人可讀。
如果有多個內核與初始記憶體檔案系統同時存在，就要在檔名加上版本號碼或是其他可供區分的標示。
另外最好在原系統中就停用 `selinux`, `firewalld`, `auditd` 等功能或服務。

首先以外部的作業系統（例如安裝於隨身碟上的 Linux），將想要寄存的整個檔案系統打包出來
（假設原系統的根目錄位於 `/dev/sda2` ，而 `/dev/sdb` 是外部的隨身碟裝置）：
====
root# *mount /dev/_sda2_ /mnt* +
root# *cd /mnt* +
root# *tar -czvf _/root/rootfs-for-nfs.tar.gz_* *
====
然後再於 NFS 伺服器上掛載隨身碟，接著解開整個檔案系統打包檔，並匯入 NFS 根目錄中預定分享的目錄：
====
root# *mount /dev/_sdb2_ /mnt* +
root# *cd _/var/nfs/linux_* +
root# *tar -xvf _/mnt/root/rootfs-for-nfs.tar.gz_*
====

無碟系統的內核與初始記憶體檔案系統，已經藉由 PXE 技術載入，而開機載入的相關檔案在這裡也不會用到，因此如果空間有限的話，可以將分享目錄中原系統的 `/boot/` 子目錄移除。
（通常用於 UEFI 開機模式且存放在 `/dev/sda1` 中的 `/boot/efi` 掛載目錄，也不需要進行打包與匯入。）
載入時被指定分享的目錄，將成為無碟系統中的根目錄，原系統 `/etc/fstab` 檔案中關於掛載的設定將不再需要，應該將其修改或移除。
另外可以在 `/etc/dnf/dnf.conf` 檔案的 `[main]` 區段內，加入 `exclude=shim-x64 grub2-efi-x64 kernel-*` 以避免未來更新系統時動到了開機相關的檔案。

分別適用於 BIOS 與 UEFI 開機模式的網路作業系統組態，內容舉例如下：

./var/lib/tftpboot/pxelinux.cfg/default
....
...
label linux
  menu label Linux Diskless System
  kernel linux/vmlinuz
  append initrd=linux/initramfs.img rw ip=dhcp root=nfs:192.168.0.1:/var/nfs/linux
...
....

./var/lib/tftpboot/uefi/grub.cfg
....
...
menuentry 'Linux Diskless System' { 
  linuxefi linux/vmlinuz rw ip=dhcp root=nfs:192.168.0.1:/var/nfs/linux
  initrdefi linux/initramfs.img
}
...
....
在 IPv6 的網路環境中需要修改相應的值，也就是範例中的 `dhcp` 改為 `dhcp6` 、 `192.168.0.1` 改為 `[fd::1]` 。
載入內核時，除了網路檔案系統必要的參數之外，還要參考原系統的開機載入設定，決定是否需要附上特殊的內核參數。
另外，由於網路傳輸速度與本機的落差，可能還要加上 `rootwait` 或 `rootdelay=5` 等參數。

=== 補充方案
PXE 技術對於伺服端與客戶端都有一定的配置要求，如果伺服端提供的硬體資源或網路服務無法滿足，
或是客戶端的系統韌體無法支援網路開機，那麼就要尋求一些補充方案，才有可能達到網路開機的效果。

==== RA 服務
由於 PXE 技術原本是基於 IPv4，而 IPv6 的規格並不支援舊有 DHCP 的所有功能。
尤其是想要以 IPv6 協定載入網路作業系統時，還需要 RADVD(路由器宣傳守護程式) 服務才能獲得完整的網路環境。
需要安裝的系統套件包含了 `radvd.service` 這個重點檔案，而組態檔 `/etc/radvd.conf` 的內容範例如下：

./etc/radvd.conf
....
interface eth0
{
  AdvSendAdvert on;
  MinRtrAdvInterval 30;
  MaxRtrAdvInterval 100;
  prefix fd::/64
  {
    AdvOnLink on;
    AdvAutonomous on;
    AdvRouterAddr off;
  };
};
....
嘗試啟動 `radvd.service` 之後，可能會出現未設定 IPv6 **轉發**(forwarding) 的警示訊息，
但是如果測試環境不需要與外網連結，那麼還是可以將其忽略並設定為啟用：
====
root# *systemctl start radvd* +
root# *systemctl enable radvd*
====

==== DNSmasq
如果有架設 DNS、DHCP、TFTP 於同一臺伺服器的需求，可以考慮利用 DNSmasq 軟體來同時提供這三項服務。
這個方案適用於小型簡單的區域網路，並且省下安裝與建置其他軟體的工作。

./etc/dnsmasq.conf
....
enable-tftp
tftp-root=/var/lib/tftpboot
dhcp-match=set:legacy,option:client-arch,0
dhcp-match=set:uefi,option:client-arch,7
dhcp-boot=tag:legacy,pxelinux.0
dhcp-boot=tag:uefi,grubx64.efi
...
....

要是已經使用了其他提供相同服務的軟體，就必須停用 DNSmasq 中的相關項目。

==== iPXE
PXE 應用需要系統韌體與網路卡韌體的同時支援，而對於達不到這項要求的系統，還可以利用混合本地與網路開機的替代方案：
例如 iPXE 專案
footnote:[iPXE - 開放原始碼開機韌體 <https://ipxe.org/>]
就是從本地或網路的儲存裝置，先載入精簡且特化的內核，包括網路卡與網路協定的驅動程式，
再由內核空間發出客戶端的請求，接著從各種網路服務（不限於 TFTP）連鎖載入開機檔案。

所需的檔案可以從 `ipxe-bootimgs` 套件中取得，但舊版套件庫收錄的名稱也許是 `gpxe` 或 `etherboot` 。
可以利用 `linux16` 與 `initrd16` 指令載入，將它做為 BIOS GRUB 組態檔中的選項之一：

./etc/grub2.cfg
....
...
menuentry 'BIOS iPXE' {
  linux16 ipxe/ipxe.lkrn
  initrd16 ipxe/menu.ipxe
}
...
....
但在 UEFI GRUB 組態檔中的寫法則不相同：
（如果打開了安全啟動，那麼沒有經過數位簽章的 `ipxe.efi` 將無法通過查核。）

./etc/grub2-efi.cfg
....
...
menuentry 'UEFI iPXE' { 
  chainloader ipxe/ipxe.efi
}
...
....
而 iPXE 的組態檔內容範例如下，會產生自己的選單畫面：

.menu.ipxe
....
#!ipxe
menu Selection
item freedos FreeDOS
item slitaz Slitaz Linux
item fedora Fedora Linux
item local Local Drive
choose os && goto ${os}

:freedos
kernel memdisk bigraw fastboot
initrd image/FD14BOOT.img
boot

:slitaz
sanboot image/slitaz-rolling-core64.iso

:fedora
kernel linux/vmlinuz rw root=nfs:192.168.0.1:/var/nfs/linux
initrd linux/initramfs.img
boot

:local
sanboot --no-describe --drive 0x80
....

或是利用官方的 `ipxe.iso` 燒錄成光碟開機後，按 kbd:[Ctrl]+kbd:[B] 進入 iPXE Shell 執行：
====
iPXE> *dhcp* +
iPXE> *chain _\http://192.168.0.1/ipxe/menu.ipxe_*
====
來讀取網路上的組態檔，進一步達到網路開機的效果。
另一種應用方式則是在組態檔案 `dhcpd.conf` 或 `dhcpd6.conf` 的 UEFI 段落中呼叫 `ipxe.efi` ：

.dhcpd.conf
....
...
    if exists user-class and option user-class = "iPXE" {
      filename "http://192.168.0.1/ipxe/menu.ipxe";
    } else {
      filename "ipxe/ipxe.efi";
    }
...
....

.dhcpd6.conf
....
...
option dhcp6.user-class code 15 = string;
...
    if exists dhcp6.user-class and substring(option dhcp6.user-class, 2, 4) = "iPXE" {
      option dhcp6.bootfile-url "tftp://[fd::1]/ipxe/menu.ipxe";
    } else {
      option dhcp6.bootfile-url "tftp://[fd::1]/ipxe/ipxe.efi";
    }
...
....

也可以依照 iPXE 專案中的說明，於**重製**(re-mastering) `ipxe.*` 時內嵌自訂的組態檔，即可獲得獨立執行的能力。

==== iVentoy
與前一章〈準備工作〉所提到 Ventoy 相關的 iVentoy 專案
footnote:[iVentoy: 新的網路開機解決方案 <https://www.iventoy.com/>]，
提供免費版本的 PXE 伺服套裝軟體，藉由啟動各種光碟映像檔，就能符合多數情境的需求。

安裝好標準 Linux 作業系統並下載與安裝 iVentoy 軟體，再將希望從網路啟動的可開機 ISO 檔案拷貝到指定位置。
執行 iVentoy 啟動程式之後，可以透過訪問 \http://127.0.0.1:26000 網頁來進行設定，或是從外部以伺服器的網路位址連入。
一旦組態設定完成並且儲存後，衹要加上自動啟動的選項來執行 iVentoy：
====
root# *./iventoy.sh -R start*
====
以後每次開機完就能依照儲存的組態自動啟動，並提供開機前執行環境的服務。
