== 軟體概念
在介紹一些重要的軟體概念之前，我們要先對軟體的定義有所認識，
而藉由它的相對概念-硬體來切入將會容易得多。
硬體一般而言是指那些看得到.摸得到的實體，
實際上來說就是由零件（機械構造，電子元件）所組成的功能集合。
軟體相對於硬體則是由符號（程式，資料）所組成的功能集合，
實體上是以電磁（或光碟上的凹點）形式存在於媒體上的數位記錄。

=== 系統階層
如果我們將軟體與硬體簡化為兩個相鄰的方塊，合起來就構成一個電腦系統。
方塊中從底部的基礎元件一直到頂端接觸使用者部分，可以分成彼此堆疊的區塊稱之為階層。
硬體部分的階層之間都有介面可以連通，最後則是與使用者的身體進行交互作用；
軟體部分的階層則可分為內核、系統函式庫、應用函式庫與應用程式，彼此之間也有介面可以連通，最後則是與使用者的心理進行交互作用。
軟體與硬體兩大區塊之間，並非隨處都有互相連通的管道，而是靠雙方最底層的元件——內核與中央處理器來溝通。

在硬體與軟體最底層的地方，各自有一塊特別的部分，而這兩塊部分一般都稱之為韌體。
硬體中這塊具有軟體特性的地方就是 BIOS，雖然它也是一組程式，但是被刷錄在晶片中之後，就幾乎不會再去更動。
內核之中也有一群稱之為韌體的檔案，它主要記載了特定裝置的參數資料，提供內核中的裝置驅動程式調用。
對於嵌入式系統而言，由於它的軟體部分通常容量較小、通用性較低、變動機會較少，
因此常常將軟體視為硬體的一部分，所以也會將軟體部分稱之為整體系統的韌體。

軟體階層的底端稱之為內核，是整個軟體系統最基礎的部分。
由於目前內核的架構採取將驅動程式含入的方法，雖然可以確保每次內核釋出時原有驅動程式的相容性，
卻也造成新增或修改驅動程式時的不方便。
系統函式庫包括了 C 語言函式庫、數學函式庫，以及其他支持系統基本運作的重要函式庫。
它們承接了上層應用函式庫的呼叫，再將其轉化為對於內核功能的呼叫。
應用函式庫與系統函式庫的區別並不十分明確，應用函式庫通常不是系統運作所必需的，而是做為支持特定類別應用程式而存在。
應用程式則是負責軟體系統與使用者實際接觸的部分，命令列或桌面環境指的就是最外層與使用者之間的介面：
不但將底層軟體的結果輸出給使用者，同時將使用者的輸入回送給底層的軟體去處理。

=== 軟體框架
**框架**(framework) 是指編寫程式時遵循的特定規範或規則，由一組互相搭配的系統函式庫與應用函式庫所組成。
通常框架於開發初期，都有其偏好適用的程式語言（例如：MFC&C，Qt&{cpp}，Glib/GTK&C），
甚至是當創造原生語言時，做為其標準的開發框架而被同時提出（例如：.NET&C#，Cocoa&Objective-C）。
泛用的框架代表它也可以支援原生語言之外的程式語言，也就是說，您可以利用熟悉的語言來撰寫符合特定框架的程式，
但是可用性就比不上原生語言。

依照框架來開發軟體有許多優點：有固定的執行邏輯可以遵循、有標準的程式結構可以套用、有完整的函數功能可以呼叫。
雖然限制了一些可能性，但是可以大幅增進開發的效率。
假如新的平臺上也有這個框架的實作，那麼原始碼最多衹需要小幅修改，就能在新平臺上編譯運行。
除非是像 Spring&Java，.NET&C#，Flash&ActionScript 之類達到了虛擬平臺層級的框架，
才能夠達成所謂跨平臺的要求。（請參考下一節〈系統平臺〉）

=== 系統平臺
要說明平臺的概念，首先我們可以看一下之前的系統階層圖，其中軟體與硬體分列左右兩側，
如果將它改為軟體在上、硬體在下的系統結構圖，就可以用來說明平臺的概念。
系統平臺可以分為軟體平臺與硬體平臺，軟體平臺建立於硬體平臺之上，而應用軟體則建立於軟體平臺之上。

硬體平臺就是指一群特定硬體的組合，成員包括中央處理器、前期載入程式與周邊裝置。
**中央處理器**(CPU) 的主要架構包括 X86, ARM, PowerPC, MIPS, RISC-V，
所處理的位元長度目前主要為 32 或 64，這是由 8bit, 16bit 一路發展上來的，未來也將會出現 128bit 的架構。
各類軟體標示硬體平臺的代號也很繁雜，就以作業系統內核對其的稱呼為例：

[square]
* 三十二位元(32bit)：i386, armhf, powerpc, mips, riscv
* 六十四位元(64bit)：x86_64, aarch64, powerpc64, mips64, riscv64 +

其中 X86 架構（包括 i386, x86_64）屬於**複雜指令集電腦**(CISC)，其餘架構歸類為**精簡指令集電腦**(RISC)。
一家晶片商可能會生產多種不同架構的產品，而同一種架構的 CPU 也可能有多家廠商生產。
X86 架構所搭配的前期載入程式，一般燒錄於主板的晶片上，早期搭配 16bit 的舊式 BIOS，目前的趨勢是採用 64bit 的新式 UEFI。
其他處理器架構的主板可能並未配置 BIOS 或 UEFI 晶片，因此需要類似 uboot/redboot 的程式做為前期載入程式。

軟體平臺可以簡單地理解為具有相同應用程式介面的作業系統。
常見的作業系統分類之下又有許多小的作業系統分支，彼此不同但相容的作業系統，
例如 MSDOS/FreeDOS, Windows/ReactOS 可以視為相同的軟體平臺。
軟體平臺同樣會依其內部處理的位元長度區分為 16bit, 32bit, 64bit...等等。

一種軟體平臺加上一種硬體平臺就形成了一種系統平臺，所謂的 lintel 就是指 Linux 加上 X86 的組合。
軟體平臺與硬體平臺的組合，主要衹需考慮處理的位元長度是否符合。
由於硬體設計時多半有考慮到向下相容，因此實務上軟體平臺處理的位元長度，至少必須要小於（且相容）或等於硬體平臺處理的位元長度。
intel 的 ia64 架構本來是做為 ia32(i386/i686) 的 64bit 版本，但是因為設計時未考慮向下相容，
反而隨著代號一齊沒落，將接班地位讓給了 AMD 主導的 x86_64(x64/AMD64/EM64T)。

平臺依存性通常指的是：二進位可執行檔案衹能在特定系統平臺上運行。
跨平臺軟體則意指該軟體可以在不同平臺上運行，一般分為下列幾種情況：

[square]
* 跨平臺編譯語言原始碼：各平臺都有編譯器的實作（C, {cpp}）
* 跨平臺編譯語言執行檔：達到虛擬平臺程度的框架（Java, .NET）
* 跨平臺解譯語言指令稿：各平臺都有解譯器的實作（Python, Shell）
* 跨平臺網頁語言指令稿：以瀏覽器做為虛擬平臺（JavaScript）

=== 虛擬機器
**虛擬機器**(system virtual machine) 是指利用軟體所構建出來的硬體平臺**仿真器**(emulator)，
通常用來模擬既有的硬體種類，當然也可以做為設計新硬體時，未製造出實體之前的測試機器。
在虛擬機器上安裝軟體平臺之後，才能成為完整的系統平臺，可以執行適用於該平臺的程式。

從軟體開發角度而言，仿真器與**模擬器**(simulator) 的差別在於：
前者建構了硬體層面（例如 QEMU 自由軟體），而後者衹在軟體層面建構
footnote:[https://saucelabs.com/amp/blog/simulators-vs-emulators-whats-the-difference-anyway]。
更一般的說法則是：仿真器較着重細節，藉此受測的對象會以為處於真實的環境；
模擬器則較着重概念，藉此受測的對象能夠認知到這並非真實的環境，甚至其本身亦為簡化的版本。

=== 軟體分類
軟體於執行期間，使用者藉由使用者介面和軟體產生互動。
依照介面不同可以分為以下幾種模式：

[square]
* 文字命令列(command-line)：輸入命令名稱與引數（其中包括選項或參數），用來執行單純的輸入輸出功能。
* 文字強制前景(modal)：運行畫面佔據整個終端機視窗，允許使用者利用按鍵或選單來執行功能。
* 圖形單一視窗(single-window)：運行於桌面環境的單一視窗之中，接受以鍵盤或滑鼠進行複雜的操作。
* 圖形多重視窗(multi-window)：於桌面環境中產生多個視窗，彼此之間還可以相互連動。

如果是依照執行時的網路需求，也可將軟體以另一種分類模式來表示：

[square]
* **單機**(standalone) 架構：運行時不需要網路，軟體不扮演任何網路角色。
* **客戶端－伺服器**(client-server) 架構：運行時需要網路，軟體扮演客戶端或伺服器的角色。
* **點對點**(point-to-point) 架構：運行時需要網路，軟體扮演端點的角色。

=== 軟體執行
手動執行軟體的方式：

[square]
* 輸入程式名稱：於命令列模式或執行視窗。
* 雙擊程式圖示：於軟體選單或檔案管理視窗。
* 按下快捷鍵
* 觸發硬體事件：熱插拔裝置或媒體。

