== 儲存裝置
電腦系統需要儲存裝置在離線時儲存資料，並且在運作時提供資料的輸入與輸出。

如果將儲存裝置類比於一本書，那麼開機區就像封面、分割區表就像目次、分割區類型就像書頁尺寸，而檔案系統則像排版方式。

=== 硬體類型
舊式儲存資料的裝置，例如**磁帶**(tape)、**軟碟**(FD)、**IDE 硬碟**(HD)，現在已經很難見到了。
傳統機械式硬碟在引入包括 SCSI 或 SATA 的進階介面之後，似乎也遇到了發展的瓶頸。
即使曾經是劃時代的**光碟**(CD) 產品，以光學記錄短暫地超越磁性記錄的方式，仍然無法阻擋以半導體做為儲存媒體的趨勢。
雖然儲存資料的原理已不再限基於磁性物質，但是習慣上仍然以**磁碟**做為多數儲存裝置的泛稱。

==== 固態磁碟
**固態磁碟**(SSD) 是所有晶片形式儲存裝置的總稱，以產品型式而言可分為：

[square]
* 載於主機板：eMMC, eUFS, SATAμSSD, eUSB
* 載於**磁碟模組**(DOM)：SATA Slim, mSATA, miniPCIe, M.2
* 插槽╱插卡：SATA, UFS, SD, USB Flash, CF

利用指令 `lsblk -O` 所顯示的區塊裝置詳細資訊，可以根據其中的 ROTA 項目看出該裝置是否會旋轉，
以此做為固態或機械式磁碟的判定，或是查看 `/sys/block/_sda_/queue/rotational` 檔案的內容。

固態儲存裝置出問題的原因，可能是晶片讀寫壽命已至造成的毀損（又可分為是儲存晶片、控制晶片或韌體的問題）；
或是外力造成的毀損，例如接觸到靜電或磁性物質。

*USB Flash*(隨身碟) 已經成為目前最流行的可攜式儲存裝置。

由於 *SD(card)*(安全數位卡) 的規格、型式與產品眾多，當系統採用內建式讀卡機時，與系統韌體也需要密切配合。
尤其是熱插拔前要以低電位偵測裝置是否存在，再以高電位傳送訊號與資料，如果判斷錯誤就會無法存取。

*eMMC*(嵌入式多媒體卡) 是控制器與儲存體整合在一起的晶片，因此所需的驅動過程會比單純的儲存體複雜。
eMMC 的規格在歷經數代版本之後，匯流排速度有 Legacy, HS, HSDDR(DDR52), HS200, HS400 等各種模式。
有些系統韌體可以讓使用者設定 eMMC 的速度模式，以及適用的驅動韌體型式。
開機後還需要開機管理程式的支援，才能經由內核偵測來決定 eMMC 的匯流排速度模式，再藉以設定其他項目。
更新系統韌體時如果更動磁碟編號順序或是幾何位置，可能會造成無法正常開機。

UFS/eUFS 原本想要分別取代 SD/eMMC，並以如同 LVDS 的串列傳輸取代並列傳輸，且一樣整合了控制器，但通訊模式則由半雙工進階到全雙工。

雖然規格較佳，但價格較貴且有些晶片組不支援，因此目前衹有部分平臺的高階機型才有配備。

適用於 M.2 插槽的固態磁碟模組有兩種型式：**NVMe**(高速非揮發性記憶體) 與 SATA。
NVMe 固態磁碟是透過 PCIe 而非 SATA 介面與主板連接，傳輸速度比 SATA 固態磁碟快 3~4 倍。
前者模組上的缺口模式為 M key（搭配腳座為 M key），後者缺口為 M+B key（腳座為 B key）。
由於 B key 與 M key 並非左右對稱，因此即使翻面插入也不會插錯。

SATA 固態磁碟 M.2 模組的裝置名稱，仍然依照介面的驅動以 `/dev/sdX` 的形式配發；
但是 NVMe 固態磁碟較為特別，第一組的整塊裝置名稱形如 `/dev/nvme0n1` ，而其中第一分割區的名稱則為 `/dev/nvme0n1p1` 。
因為 NVMe 固態磁碟的規格較新，因此未更新的系統韌體、開機管理程式以及作業系統內核，都有可能出現支援不完整的問題。


==== 裝置驅動
內核將儲存裝置視為**區塊裝置**(block device) 的一員，依據負責驅動的模組來決定對應的虛擬裝置名稱。
裝置的供應商與型號，需要從 `dmesg` 以及 `lspci` 或 `lsusb` 等命令的輸出中取得。
如果變更了系統韌體設定中的 SATA 選項（IDE/RAID/AHCI），將會導致原本安裝好的系統無法開機。
驅動所有 SATA 系列儲存裝置的程式，目前都已併入 SCSI 型式磁碟的內核模組之中，
還包含了所有透過 `usb-storage` 內核模組驅動的 USB 介面儲存裝置，因此它們的虛擬裝置檔案，都會設定為 `/dev/sda`, `/dev/sdb` 等等依序附加英文字母的名稱。

SD 與 eMMC 都源自 MMC 規格，內核中均由 `mmc` 子系統負責，需要載入 `sdhci_pci` 及其依存的 `sdhci` 內核模組，前者和電源管理、是否能做為開機裝置有關。
各廠牌的讀卡機還需要各自的內核驅動模組，例如 `rtsx_pci_sdmmc` 與 `rtsx_pci` 模組適用於 Realtek 廠牌的機型。
內核對於此類硬體整顆所指定的虛擬裝置，則為類似 `/dev/mmcblk0` 的名稱。
不過也有可能因為硬體線路或系統韌體的關係，導致內核從 `/dev/mmcblk1` 開始編號。
尾碼一般是由 0 開始編號，但仍然可能會因為佈線、系統韌體、內核版本而有所偏差。
UFS/eUFS 的形式雖然類似 SD/eMMC，卻是採用 SCSI 架構，因此內核將其裝置名稱歸類為 `/dev/sd*` 而非 `/dev/mmcblk*` 。

固態磁碟所使用的晶片顆粒多為 NAND Flash(反及閘快閃記憶體)，之後 Intel 提出新的 Optane 儲存晶片，
但是由於舊版 Linux 並不支援 Optane 專有的 RST/Optane 存取模式，因此作業系統衹能使用相容的 AHCI 模式。
如果開機時無法識別 NVMe 裝置，先嘗試停用系統韌體設定中的 Intel RST/Optane/VMD 項目，亦即磁碟開機模式需要從 Optane/RAID/IDE 改為 AHCI。
萬一仍然不成功，可以再加入內核參數 `nvme_load=YES nvd_load=YES` 或 `nvme_core.default_ps_max_latency_us=5500/0/200/1000` 。
另外還有可能試試 `pcie_aspm=off acpi=off pci=biosirq` ，以避免受到其他裝置的影響。

==== 速度指標
磁碟驅動的讀寫速度利用了**直接記憶體存取**(DMA) 的加快方式，其他還有 PIO, UDMA 等存取方式。
內核參數 `libata.dma=3` 會開啟第三級的 DMA 功能，當大量資料解壓或移動時，可能會因為相容問題而造成讀取錯誤。
如果設定為內核參數 `libata.dma=0` 便能關閉 DMA 功能，但會使用較低的加速模式，導致讀寫速度降低但相容性會提高。
目前系統所用的 DMA 值，儲存在虛擬檔案中：
====
user$ *cat /proc/dma* +
 4: cascade
====
如果想要在使用者空間設定 DMA 值，可以試試系統是否有支援 `hdparm -X -d -k` 指令。

對於固態磁碟來說，可以試試內核參數 `slice_idle=0` 也許能夠增加部分效能。

=== 分割區
一般而言，容量超過 256GB 的儲存裝置建議使用 GPT 模式來分割磁碟。

一個儲存體本身可以視為是一個儲存裝置，不過隨著容量日趨增大，就需要將儲存體劃分為若干個**分割區**(partition)，而每個分割區都被系統視為一個獨立的儲存裝置。

`fdisk` 是 BIOS 開機模式適用的傳統分割區工具程式，而 UEFI 開機模式的機型則使用相應的 `gdisk` 命令。

由於 GPT 規格的特意制定，有可能透過使用者手動設定，讓儲存裝置同時支援 MBR 與 GPT 分割區模式。
雖然可以進一步設定為同時支援 BIOS 與 UEFI 兩種開機模式的 **混合型開機**(hybrid boot)，但也容易使得其他作業系統或工具軟體產生誤判而無法順利存取磁碟。

==== 資料分割區
類似 `/dev/sda` 形式命名的儲存體，尾端加上由 1 開始的編號做為所屬的分割區名稱，例如 `/dev/sda1`, `/dev/sda2` 。
儲存體 `/dev/mmcblk0` 之下的分割區裝置名稱則為 `/dev/mmcblk0p1`, `/dev/mmcblk0p2` ……等等，是以加上字母 p 與由 0 開始的編號組成。

使用舊式的 BIOS 開機模式時，最簡單的狀況下衹需要將整個系統安裝於單一分割區，也就是建立一個掛載點為根目錄 `/` 的分割區。
新式的 UEFI 開機模式，規格需要一個代號為 EF00 的 *ESP*(EFI 系統分割區)，但許多系統韌體亦接受一般的 0700(Windows 資料) 分割區代號。
由於 Windows 作業系統預設會隱藏 ESP 代號的分割區，可以避免使用者轉換系統時不慎寫入。
*ESP* 目前要求具備 `vfat` 檔案系統格式，Linux 通常會掛載到實際運作系統中的 `/boot/efi` 目錄。

在更複雜的系統中，基於歷史習慣、分散容量、平臺權限…等原因，還會將個別的分離儲存裝置，掛載到 `/boot` 、 `/home` 或其他的目錄上。

==== 置換分割區
除了用來儲存資料的分割區之外，額外建立一個**置換分割區**(swap partition) 也是常見的組態。
置換分割區的適當大小為系統記憶體的 1.5 倍，它的功能是提供系統記憶體的暫時置換容量，如果系統記憶體夠多、沒有休眠需求或者儲存裝置容量有限，是可以跳過建立置換分割區的步驟。

如果想要使用**休眠**(hibernate) 的功能，請確認置換分割區有足夠的容量。
如果系統沒有順利自動偵測到置換分割區，就可能需要手動加入類似 `resume=_/dev/sda3_` 這樣的內核參數，才能確保啟用休眠功能（亦即進入 S4 狀態）。

安裝作業系統時所建立的置換分割區，會依靠檔案 `/etc/fstab` 中的記錄而自動掛載，指令 `swapon -s` 則可以查出目前系統所使用的置換分割區。
如果在既有的系統中想要增加一個置換分割區，可以依需要先縮減原有分割區，再建立新的置換分割區。
然後利用命令 `mkswap` 與 `swapon` 來格式化並開啟置換功能，確認正常後再記入 `/etc/fstab` 檔案。
也可以利用**置換檔**(swap file) 來代替置換分割區，相對應的指令範例如下：
====
root# *dd if=/dev/zero of=/_swapfile_ bs=4k count=1M* +
root# *mkswap /_swapfile_* +
root# *swapon /_swapfile_* +
root# *echo "/_swapfile_ swap swap defaults 0 0" >> /etc/fstab*
====

如果置換分割區的內容出現混亂而需要重新整理時，必須先以命令 `swapoff` 停用，然後再同樣利用 `dd` 命令以零值將分割區填滿。
接著根據 `/etc/fstab` 中參照分割區的方式（藉由 LABEL 或 UUID），做為選項值來重新執行 `mkswap` 命令。
也可以利用第三方套件 `secure-delete` 中的 `sswap -z` 指令，來達到清空置換分割區的目的。

取消置換功能時同樣必須先停用，再註解掉檔案 `/etc/fstab` 中的項目，最後才能將分割區或檔案刪除。
如果變動後忘記更新 `/etc/fstab` 的內容，重新啟動時可能會無法順利開機，就需要進入救援模式再去修改 `/etc/fstab` 才行。

置換功能的動作參數記錄在 `/proc/sys/vm/swappiness` 虛擬檔案中，但透過加入 `vm.swappiness=15` 這列設定到 `/etc/sysctl.d/99-sysctl.conf` 之中，可以將預設值 60 變更為 15。

==== 分割區操作

如果想要在命令稿中進行分割區操作，就要尋求非視窗（不論是圖形或文字）模式的方法。
例如下列指令用來在第一個 SCSI 相容儲存裝置上，建立單一的分割區：
====
root# *echo -e "o\nn\np\n1\n\n\nw" | gdisk /dev/_sda_*
====
而下列指令可以刪除第一個 MMC 儲存裝置上的分割區表：
====
root# *sgdisk -Z /dev/_mmcblk0_*
====

==== 分割區變更

如果儲存裝置上還有閒置的空間，可以利用圖形介面的 `gparted` 程式來放大或縮小分割區，或是使用 `cloud-utils-growpart` 套件中的 `growpart` 程式。

執行 `dd` 命令時，如果輸入對象的大小超過了輸出對象的空間，在空間以內的部分雖然會被寫入，但是超出的部分則會造成錯誤而失敗。
製作磁碟映像的輸入碟時，儘量在容量小的儲存體上進行，或是刻意將分割區避開後段的儲存空間。
如果以 `dd` 命令強制還原至較小容量儲存體後，就可以在執行 `gdisk` 後先記下目前的分割區資料，再手動刪除並立刻重建最後一個分割區，但不要對分割區重新進行格式化。
如果原分割區未超過磁碟邊界，則以相同大小重建；萬一原分割區已超過磁碟邊界，則以較小的允許值重建，然後再設法修復檔案系統。

由於磁碟末端區域會被用來存放分割區表副本，因此映像檔寫入不完全就會造成副本的缺失。
文字工具程式 `parted` 可以修復缺失的分割區表副本，也可以嘗試看看前面提到的 `gparted` 圖形工具程式。

另外要注意 `util-linux` 套件中的 `partx` 與 `resizepart` ，衹是當內核沒有自動偵測到分割區的異動時，用來通知內核更新資訊的命令，並不會實際改變裝置上的分割區表。

==== 進階架構
在基本的磁碟分割區架構之上，為了滿足使用者對於速度、容錯與擴充的需求，還有像是 *RAID*(容錯式磁碟陣列)、**LVM**(邏輯卷冊管理器) 等進階架構可供應用。
早期的 RAID 功能是由硬體實作，需要特殊的擴充介面卡，並且在系統韌體中整合外掛的韌體。
依照規格可以將 RAID 功能分為不同的等級，通常都要求系統具有額外充足的磁碟空間。
Linux 支援部分 RAID 功能的軟體實作，詳細的用法請參閱相關的說明文件。
以下僅列出要救援 RAID 磁碟時的範例指令：
====
root# *mdadm --assemble --run /dev/_md0_ /dev/_sdX1_* +
root# *mount /dev/_md0_ /mnt*
====

LVM 提供了一個將多個物理分割區整合為一個邏輯分割區的架構，管理所用的套件為 `lvm2` ，詳細的用法同樣請參閱相關的說明文件。
基本的顯示命令包括 `pvscan`, `vgscan`, `lvscan`, `vgdisplay`, `lvdisplay` ，以下僅列出啟用後的掛載範例指令：
====
root# *mount /dev/mapper/sys-root /mnt*
====
而動態放大 LVM 裝置的空間則需要使用 `lvresize`, `lvextend`, `fsadm` 等命令，或者使用支援 LVM 的 `blivet-gui` 磁碟管理套件。

儲存裝置也有可能重複具備 RAID 與 LVM 功能，操作時需要注意先後套用的順序。
如果要將相關功能於開機時強制關閉，可以參考內核參數 `raid=noautodetect` 以及 `rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0` 。

=== 檔案系統
檔案系統的表現，取決於內核的定址空間、檔案系統的規格以及驅動模組的效能。

==== 格式化
在已經區分好的儲存體分割區上建立檔案系統，就是將分割區**格式化**(formatting)，以便於後續結構性地儲存資料。
Linux 是依照掛載來源所含檔案系統的類型，將其掛載於檔案系統階層的掛載點上。
當檔案系統掛載入檔案系統階層後，就可以進行一致的檔案與目錄操作。

標準是以 `mkfs._檔案系統類型代碼_` 形式的命令來建立檔案系統，實際的程式則由各檔案系統相關的套件提供，並同時建立一些常見別名的檔案鏈結。
例如傳統上 Linux 掛載於根目錄的儲存裝置，是以 Ext4 檔案系統做為格式化類型，建立命令則是本質上相同的 `mke2fs` 與 `mkfs.ext4` 命令。
目前各散佈版安裝時，預設檔案系統有設為 BtrFS 的趨勢，相應的建立命令則為 `mkfs.btrfs` 。
不同的檔案系統建立命令具有不同的用法，詳細的選項與參數意義需要參考各自的說明文件。

vFAT 是 Linux 用來代表常用於 Windows 作業系統的 FAT 系列檔案系統統稱，包括了 FAT12, FAT16 與 FAT32。
例如以 `mkfs.vfat` 命令建立檔案系統的寫法如下：
====
root# *mkfs.vfat -F32 -s128 /dev/sdb1*
====
將會對於 `/dev/sdb1` 裝置，強制以 FAT32 進行格式化（預設是以適合目標分割區大小的檔案系統為優先）。
同時每個**磁簇**(cluster) 中的**磁區**(sector) 數則設為 128，在讀取較大檔案時可能會增加一點速度。 
利用另外一個格式化工具程式的指令 `parted -l` ，可以顯示分割區的詳細資料，尤其是確認 FAT16/FAT32 的格式。

exFAT 如同其名稱所指，是擴展規格的 FAT 檔案系統，內核需要同名的驅動模組才能支援，而使用者空間操作則需要安裝 `exfatprogs` 套件。

如果想要保持與 Windows 系統相容，那就選擇 exFAT 做為檔案系統。

==== 掛載
**掛載**(mount) 的動作就好比是在飛機上加掛彈藥或油箱，或是比喻為植物上的接枝處理。
舊版 Windows 作業系統所用的分割區，通常使用 FAT16 檔案系統，掛載時指定的類型也是 `vfat` ，但是需要加上選項 `-o codepage=950,iocharset=utf8` 。

對於像是 `/tmp` 這樣使用虛擬檔案系統 `tmpfs` 的掛載點，如果想要動態擴大容量，可以執行指令：
====
root# *mount -o remount,size=_16G_,noatime /tmp*
====
`devfs` 與 `sysfs` 也屬於特殊的虛擬檔案系統，會在系統初始階段自動產生。
原本是根據 `devfs` 產生 `/dev` 虛擬目錄之下的虛擬裝置結構，後來被 `sysfs` 機制所取代。
而 `/sys` 虛擬目錄則是使用 `systemd` 提供的 `udev` 機制所建立，用來補足 `/dev` 結構中各裝置的資訊，亦即 `udev` 是使用者空間利用 `sysfs` 來實現 `devfs` 功能的機制。

SquashFS 是壓縮過的唯讀檔案系統，通常以單一檔案的形式存在。掛載時利用指令：
====
root# *mount -t squashfs -o loop _foobar_.squash /mnt*
====

另外有一類適用網路儲存空間的檔案系統，包括普遍用於 UNIX 類作業系統的 *NFS*(網路檔案系統)，以及 Windows 類作業系統常用的 *CIFS*(網路檔案分享系統)，
後者原本稱為 *SMB*(伺服器訊息區塊)…等等。假設 NFS 伺服器已提供可用的服務，將其掛載的指令範例如下：
====
root# *mount -t nfs _xxx.xxx.xxx.xxx:/var/nfs_ /mnt*
====

==== 對拷
作業系統下的兩個檔案系統，可以使用 `tar` 工具來對拷，範例如下：
====
root# *mount /dev/_sdb1_ /_opt_* +
root# *mount /dev/_mmcblkp1_ /_mnt_* +
root# *cd /_opt_* +
root# *rm -rf /_mnt_/\** +
root# *tar cf - . | tar xvf - -C /_mnt_*
====

==== 調整工具
由於最普遍的檔案系統是 Ext4，因此相關的工具種類最多也最常被使用：
`dumpe2fs` 命令用來檢視磁碟的非資料區塊內容；而 `tune2fs` 命令則可以檢視或設定檔案系統的各項特性參數。

調整大小可以先用 `resize2fs -M` 指令縮減檔案系統，再用 `gdisk` 刪除並重建一個較小的分割區。

一般而言，Linux 中的檔案系統並不需要進行額外的磁碟清理動作，例如適用於 `ext4` 檔案系統的 `e4defrag` 工具。

==== 捨棄未使用區塊
要查看裝置是否支援捨棄（確實清空鏈結）未使用區塊的功能，可以檢視下列虛擬檔案系統中的檔案內容：
====
root# *cat /sys/block/_sda_/queue/discard_granularity* +
512
====
顯示了裝置 `/dev/sda` 的**捨棄粒度**為 512 位元組。
雖然可以在掛載時加上 `-o discard` 選項來強制啟用未用區塊的重整，仍然要注意未必適用於所有裝置。
系統預設的捨棄未使用區塊定時服務，可以使用指令 `systemctl status fstrim.timer` 來查看，在啟用狀態下會自動執行 `fstrim` 命令。

另外還有以整個區塊裝置為對象的 `blkdiscard` 命令，會將裝置上的所有區塊重置，便於重頭安裝新的系統。

==== 檢查與修復
檔案系統的修復是由 `fsck` 命令系列所負責，它通常會自動依照檔案系統的類型來呼叫適當的附屬命令，例如適用於 `ext4` 檔案系統的 `fsck.ext4` 程式。
====
root# *e2fsck -cfpv /dev/_sda1_*
====
以上的命令會對磁碟裝置 `/dev/sda1` 檢查鏈結完整性、搜尋損壞的磁軌，以及進行可能的修復作業。

萬一系統韌體中的時間被調到過去，會造成開機時的磁碟檢查過程出現錯誤，因為偵測到不合理的未來檔案時間戳記。
依據掛載設定檔 `/etc/fstab` 的內容，每列的最後一欄決定開機時是否自動執行 `fsck` 命令。
如果該欄的值由預設的 1 改為 0 即可繞過此一檢查，有可能加快開機過程。


如果分割區大小經過手動調整後，與其中的檔案系統大小不同步，就需要額外再調整檔案系統的大小。
`resize2fs` 工具程式可用來變更既有的 `ext4` 檔案系統，對於 `vfat` 檔案系統則是使用 `fatresize` 命令：
====
root# *resize2fs -f /dev/_sdb3_*
root# *fatresize -s max /dev/_mmcblk0p4_*
====
以上的指令範例，分別將兩個檔案系統填滿所在的分割區大小。
擴展的動作可用於已掛載的分割區，但是分割區未掛載時才能進行縮減。


==== 清除記號
命令 `blkid` 會輸出系統中各個分割區的識別資訊，但是並不一定會照名稱順序輸出，因此建議執行時加上管線排序：
====
root# *blkid | sort* +
/dev/sda1: UUID="EEA9-6A81" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="a29738ba-01" +
/dev/sda2: LABEL="System" UUID="39e45ea7-eae3-4431-a71b-d587025c45e9" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="a29738ba-02" +
/dev/sda3: UUID="b32c9379-f1bb-4e50-bc18-2e3caa12b3e5" TYPE="swap" PARTUUID="a29738ba-03"
====
如果想要修改既有檔案系統的**標貼**(label)，可以使用與檔案系統類型相應的命令，例如 `ntfslabel`, `fatlabel`, `exfatlabel` 或 `e2label` 。
建立每個分割區時都會自動產生一組 *UUID*(泛用惟一識別符號)，通常做為開機管理程式與內核識別分割區的依據，但是不要與整機系統的 UUID 混淆。
萬一有需要在外接系統中修改原本系統的儲存裝置 UUID，範例指令 `tune2fs -U _UUID_ /dev/sdb2` 或 `tune2fs -U random /dev/sdb2` 適用於 Ext4 檔案系統，
但是對於 vFAT 檔案系統則需要 `mtools` 命令才能變更。
另外還有一項名為 PARTUUID 的資訊，與上述的 UUID 相似但不同並較少使用，可以藉由 `gdisk` 命令中的功能來修改。

當磁碟受過各種的分割與寫入、進行過 LVM 或 RAID 格式的設定，或是被映像檔覆寫過，
其中的非資料區會存有一些特殊的標記，可能會影響後續的正常使用。
利用以下的指令範例：
====
root# *wipefs -a -f /dev/_sdb_*
====
就可以除去裝置上的特殊標記，執行後最好先經過物理性重置（重開機或重插拔）再開始使用。

每個分割區還有一個較少使用的旗標，會將裝置設定為唯讀。
萬一裝置發生了不明原因的無法寫入問題，可以試試 `blockdev --setrw` 或 `hdparm -r0` 加上裝置名稱做為參數的指令。


==== 分析
`smartmontools` 套件中的 `smartctl` 命令，可用來檢測磁碟資訊與磁碟健康狀況。

對於 NVMe 固態磁碟來說，安裝 `nvme-cli` 套件後執行指令 `nvme smart-log /dev/nvme0n1` ，才能取得裝置的相關資訊。

對於檔案系統的進一步分析，可以參考 `sleuthkit` 套件所含的各項工具程式。


=== 磁碟映像
磁碟的映像檔是將整個儲存體上的資料，以原始的記錄型態儲存於檔案之中。
映像檔的基本形式是單一檔案，但常常為了因應其大小而會先進行分割或壓縮的處理。
磁碟映像檔就相當於整個系統的備份，可以用於後續的轉移、還原或安裝等作業。

記載磁碟原始資料的映像檔，很可惜並沒有一致的副檔名，依據不同的製作軟體來源，會看到 `.dd`, `.img`, `.raw`, `.nrd` 等等不同的檔案附加名稱。
更有不少應用軟體，在此原始資料的基礎上加入了檔頭、檔尾，或是額外的編碼、壓縮等動作，所以必須注意這些細微的差異以免遇到不相容的問題。

==== 容量
指令 `fdisk -l _/dev/sdb_` 可以檢視磁碟裝置的基本資訊，包括分割區表模式與真實大小。
指令 `blockdev --getsize64 /dev/mmcblk0` 也可以直接取得裝置的容量，適合應用於命令稿中。
標示同樣容量的磁碟，不同廠牌不同型號也可能會有些微差別。
規格書上的標示容量，很少會符合以 GiB 為計算單位，部分能夠符合以 GB 為計算單位，而有些產品連後者的規格都無法達到
（雖然廠商解釋還要加上保留給控制專用的記憶體數量）。例如同樣標示容量為 8GB 的儲存裝置：

[square]
* F*e 廠牌某型 mSATA: 8075870208 位元組
* I*k 廠牌某型 mSATA: 8012390400 位元組
* S*k 廠牌某型 eMMC:  7820083200 位元組
* S*g 廠牌某型 eMMC:  7818182656 位元組
* K*n 廠牌某型 eMMC:  7818182656 位元組


==== 基本操作
`dd` 用來讀取與寫入磁碟的原始資料，因此成為映像檔的標準操作工具。
檔案操作中的拷貝指令，就像是對於文件的謄寫動作，而使用 `dd` 工具則如同影印機般運作。

====
root# *dd if=/dev/sdb of=/dev/sdc bs=4M status=progress*
====
指令中的 `if=`(input file) 與 `of=`(output file) 選項分別指明輸入與輸出的對象，可以是磁碟裝置名稱、分割區裝置名稱，也可以是檔案名稱。
如果不指定 `if=` 或 `of=` 時，分別就是以標準輸入或標準輸出做為預設值。
非必要的 `bs=`(block size) 選項決定每次讀寫的區塊大小，預設為 512 位元組，一般可設定為 4M 或 8M。
新版程式的 `status=` 選項已支援 `progress` 的選項值，舊版範例中常見經由管線指令 `pv -f` 顯示進度的手法已不再需要。

製作映像檔前，輸入與輸出裝置都必須要先卸載，最好是將輸入裝置所屬的作業系統關機後，再以外接的作業系統開機製作。
如果輸入或輸出是一般檔案的話，則需注意不要同時有其他程式正在開啟或存取該檔，另外有些自活系統會自動掛載所有可掛載的儲存裝置，因此需要額外手動再進行卸載。
如果輸入於讀取時仍在掛載或存取狀態，讀出的資料會不完整；如果輸出在掛載或存取狀態，寫入內容未必會和來源一致，甚至有可能造成檔案系統損毀，使得還原後被要求執行 `fsck` 以進行修復。

如果 `dd` 對拷的輸入輸出都是 USB 裝置：

[square]
* 優先選擇規格較高、速度較快的 USB 埠
* 輸入與輸出儘量不要接在同一個 USB 集線器上
* 如果兩個埠速度不同，則較慢的用於讀取，較快的用於寫入

==== 進階讀取
輸入或輸出對象也可以透過管線機制，導向為壓縮過的映像檔，甚至直接來自網路檔案系統或網路鏈結：
====
root# *ssh _IP_* +
root> *dd if=/dev/_sdb_ | gzip -c > _/var/www/html/disk-image.dd.gz_* +
root> *exit* +
root# *curl _http://IP/disk-image.dd.gz_ | gunzip -c | dd of=/dev/_sdb_*
====

為了增大壓縮的效率，可以在製作映像檔之前，先將分割區的檔案系統中沒有使用到的區域以零值填滿：
如果是 `ext4` 檔案系統，需要執行類似 `zerofree /dev/_sdb1_` 的指令；而適用於 `ntfs` 檔案系統的範例則是 `ntfswipe -apf /dev/_sdc1_` ;
對於其他較少用的檔案系統，可以看看第三方套件 `wipefreespace` 或 `secure-delete` 中的 `sfill` 命令是否有支援。
最差的情況下，還可以利用 `dd` 命令將零值持續寫入一個暫時檔案，讓它塞滿磁碟剩下的空間後，再將它刪除也能達到類似效果。

==== 進階寫入
命令 `bmaptool` 來自於套件 `bmap-tools` ，可以視為是 `dd` 命令輸出部分的加強版，拷貝映像檔的操作範例如下：
====
user$ *bmaptool create -o _disk-image_.bmap _disk-image.dd.zst_* +
root# *bmaptool copy --bmap _disk-image_.bmap _disk-image.dd.zst_ /dev/_sdb_*
====
做為指令參數的映像檔，是由 `dd` 命令所產生，可以直接使用壓縮過的檔案。
副檔名為 `.bmap` 的**區塊圖**(block map) 檔案，是一種 XML 格式的磁碟映像描述檔。
當磁碟區塊於描述檔中被標記為未使用，在拷貝磁區的動作中就會被忽略，因此能夠大幅減少拷貝所需的時間。

如果映像檔寫入磁碟的過程看起來正常，結果卻是沒有寫入，還可以試試類似的進階工具 `dcfldd` 。
當然也有可能是儲存體的韌體發生問題，那就需要另外的工具程式才能修正。

==== 檢查
由於映像檔是磁碟裝置內容的完全複製，因此原本針對磁碟裝置的指令，也可以將參數替換為映像檔名稱來使用。
例如，指令 `file -s _disk-image.dd_` 會顯示磁碟映像前段開機記錄的狀態（如果存在的話）。


由於映像檔的大小已經不適合使用逐一檢查位元組的比對方式，因此會利用產生**總和檢查碼**(checksum) 的程式來協助。
舊式 `checksum` 命令衹適用於較小檔案，所支援的 CRC 演算法也已經過時，衹剩下 CRC32 還有零星應用。
目前較常用來產生總和檢查碼的命令包括 `md5sum`, `sha1sum`, `sha512sum` ，而內嵌於光碟 ISO 檔的特殊情況則要使用 `isomd5sum` 。

比較映像檔的總和檢查碼時，需要注意以下幾點：

[square]
* 目標與對象均不可處於掛載狀態
* 確認目標與對象的大小相同
* 產生總和檢查碼的演算法相同

==== 掛載
如果是從單一分割區製作出來的映像檔，可以利用**迴圈**(loop) 模式掛載：
====
root# *mount -o loop _partition-image.dd_ /mnt*
====
不過大部分的映像檔都是來自整個磁碟裝置，因而無法如此直接掛載。
以往的方法需要先算出目標分割區前方的**偏移值**(offset)，再將其指定於 `mount` 命令的選項之中，但是新的掛載程序較為簡單：
====
root# *losetup --partscan --find --show _disk-image.dd_* +
/dev/loop0
root# *mount -rw /dev/loop0p1 /mnt*
====
注意使用此方法前，要先關掉會自動掛載檔案系統的服務。
處理完 `/mnt` 中的檔案並且正常卸載之後，還需要**卸離**(detach) 迴圈虛擬裝置：
====
root# *umount /mnt* +
root# *losetup --detach /dev/loop0*
====

映像檔當然也繼承了輸入對象的開機模式，尤其是利用虛擬機器來運行磁碟映像時，
不像實體機器的系統韌體那樣具有雙重開機模式的容錯機制，而需要在指令中指定：
====
user$ *qemu-system-x86_64 -m _2G_ -drive file=_disk-image.dd_*
====
上述指令是以 BIOS 開機模式為例，如果要仿真 UEFI 開機模式，必須再加上 `-bios /usr/share/edk2/ovmf/OVMF_CODE.fd` 選項。

如果系統中的多個儲存裝置，都是從同一個映像檔所製作的輸出對象，那麼在系統韌體的開機選項中，具有相同 UUID 的裝置可能衹會出現一個；
或是雖然出現多個，但選擇後都會固定進某一個裝置；或是不論選擇哪一個都會造成開機失敗。


==== 光碟映像
由於光碟並無分割區的概念，整片光碟是以 `iso9660`(CD) 或 `iso13346`(DVD) 的檔案系統格式劃分，
因此光碟資料的映像檔，一般就簡稱為 *ISO*(國際標準化組織) 檔案。

許多 Linux 散佈版是以 ISO 檔案的形式在網路上流通，原本是燒錄到光碟做為**自活光碟**(Live CD/DVD) 使用，
但也可以當做磁碟映像來寫入隨身碟裝置，就能製作出如同可開機光碟的**自活隨身碟** 。

以虛擬機器來運行光碟映像的方式與磁碟映像類似：
====
user$ *qemu-system-x86_64 -m _2G_ -cdrom _dvd-image.iso_*
====
如果同時也有掛載可開機的磁碟映像，就需要額外加上 `-boot d` 選項以指定優先從光碟開機。

由於影音光碟與資料光碟不同，可以接受某種程度的有損(lossy) 複製，因此對於受到刮傷而無法順利讀取的光碟，可以試試用 `ddrescue` 來製作映像檔：
====
user$ *ddrescue -d -r 3 -R -b 2048 /dev/sr0 _dvd-image.iso_ _dvd-image.map_*
====
該指令會重覆三次逐段讀取光碟上的資料，讀到的資料將儲存到 `.iso` 檔案相應的位置，而讀取記錄則儲存在 `.map` 檔案。
即使中途將光碟拿去物理性清潔或修補，重新執行指令時也能依據記錄跳過已經成功讀取的部分。

另外還會見到源自 Windows 作業系統的 `.wim` 格式映像檔案（或是經過壓縮的 `.esd` 格式），可以透過 `wimlib-utils` 套件中的 `wimtools` 命令來操作。

==== 變更大小
當然也可以在還原映像檔之前，先嘗試修正映像檔以避免產生錯誤，不過這項步驟比較困難：
需要自行計算目標對象的磁碟容量，並且注意不要破壞到原有的檔案系統。

然後再用 `truncate` 或 `dd` 之類的命令強制縮減檔案大小。
QEMU 軟體計畫提供的 `qemu-img` 程式，包含了許多針對映像檔的強大功能。
例如其中的 `resize` 功能選項，會強制切除尾端空間到指定的大小，但是並未一併修正分割區表。

=== 工具軟體
在對於磁碟裝置進行讀寫測試之前，不論工具軟體是否要求，都建議使用者先卸載目標裝置，並且備份好裝置上的重要資料。

標準安裝的 GNOME 桌面環境中，就有提供圖形介面的磁碟工具程式 `gnome-disks` 。
除了顯示所選磁碟的基本資料、提供基本的格式化與映像檔操作外，也可以進行讀取與寫入的速度測試。


`hdparm` 命令用來取得或設定磁碟裝置的資訊，其中 `-i` 選項用來顯示磁碟的內核相關項目，而 `-I` 選項則是顯示硬體的相關內容。
由於 `hdparm` 衹支援 `/dev/sd*` 而不支援 `/dev/mmcblk*` 類型的磁碟裝置，因此對於後者則需要執行 `mmc-utils` 套件中的 `mmc` 指令：
====
root# *mmc csd read /sys/class/mmc\_host/_mmc0_/_mmc0_:0001* +
type: 'MMC' +
version: MMC v4.0-v4.3 +
card classes: 11, 7, 6, 5, 4, 2, 0, +
capacity: 1.00Gbyte (1073741824 bytes, 2097152 sectors, 512 bytes each) +
root# *mmc extcsd read /dev/_mmcblk0_ | grep "Firmware Version:"* +
eMMC Firmware Version: 68130320QP
====
另外從虛擬檔案 `/sys/kernel/debug/mmc0/ios` 的內容，或是經由 `udevadm info /sys/block/mmcblk0` 指令，都可以獲得更多的裝置資訊。

萬一在精簡的系統中未提供以上的工具時，命令 `dd` 也能做為簡單的磁碟讀寫測試工具。
例如測試寫入速度可以輸入：
====
user$ *dd if=/dev/zero of=_testfile_ bs=4M count=1K oflag=dsync*
====
而測試讀取速度的指令則可利用剛剛寫入的檔案：
====
user$ *dd if=_testfile_ of=/dev/null bs=4M iflag=dsync*
====

`testdisk` 是另外一個文字介面的工具程式，可以修復磁碟或映像檔的分割區問題，其中的 `photorec` 項目還有可能救回已刪除的檔案。

Clonezilla
footnote:[Clonezilla 軟體首頁 <https://clonezilla.org/>]
是開放原始碼的磁碟映像複殖軟體。
利用命令稿將許多磁碟映像相關的工具整合在一起，搭配基礎開機軟體而以自活光碟映像檔的形式釋出。
啟動系統後可依據選單引導，進行磁碟的映像複製、備份、還原等作業。

將映像檔燒錄到隨身碟或光碟之後，確認系統韌體中的設定，並以其在來源裝置所在的機器上開機。
開機後建議插入額外的隨身碟，做為儲存映像檔目錄或是還原光碟映像檔的裝置。
還原時可直接以還原光碟映像檔所燒錄的自活裝置開機，或是以 Clonezilla 系統配合額外的映像檔目錄儲存裝置來完成。

