== 軟體安裝
安裝完作業系統之後，代表這臺電腦已經具備基本的功能。
如果作業系統的安裝程序沒有同時安裝想要的項目，或是內建的應用軟體無法滿足實際的需求，
不論是函式庫、驅動程式、工具程式還是遊戲，就得必須自己想辦法安裝。
本章先介紹傳統從原始碼開始組建的安裝方式，接著是如何利用軟體包安裝，最後介紹比較友善的套件安裝方式。

=== 程式分類
相對於「資料」的「程式」型態檔案，指的是具有執行或被執行「潛力」的軟體，而程式檔案的分類，與實作它的程式語言並沒有絕對的關係。

==== 依可否執行
在作業系統的語境中，習慣將程式區分為**可執行**(executable) 與不可執行兩類，但從另一個面向來看，還可以利用是否能夠「被」執行做為分類依據。
可以直接經由呼叫檔案名稱而如同命令般執行的檔案，就稱為可執行檔案，當然是在滿足檔案屬性已經設定為可執行的前提之下；
而可以做為其他命令的參數來被執行的檔案，則屬於可以被執行的檔案，如此交叉劃分就可以得到四種類型的程式檔案。

NOTE: 雖然在某種意義上，自主執行的檔案仍然可以視為是一種被執行的檔案。

程式檔案在執行類型之間的轉換與執行，可以透過以下幾種處理方式：

[square]
* *組譯*(assemble)：將組合語言程式碼翻譯為**機器碼**(machine code) 再執行。
* *編譯*(compile)：例如將 C 語言程式碼翻譯為機器碼（中間可能會經過組合語言）再執行。
* *解譯*(interpret)：例如將 Python 語言程式碼翻譯為**位元組碼**(bytecode)，再由虛擬機執行；或是將 Shell 語言程式碼逐句解析，再由直譯器執行。
* *轉譯*(transpile)：例如將某種語言程式碼翻譯成 C 或 Python 語言程式碼，再接續進行處理。

==== 依介面
程式於執行期間，使用者藉由使用者介面和軟體產生互動。
依照介面類型不同可以分為以下幾種模式：

[square]
* 文字**命令列**(command-line)（CLI）：輸入命令名稱與引數（包括選項或參數），執行單純的服務或輸入輸出功能。
* 文字**強制前景**(modal)（TUI）：運行畫面佔據整個終端機視窗的使用者介面，允許使用者利用按鍵或選單來調用子功能。
* 圖形**單一視窗**(single-window)（GUI）：運行於桌面環境的單一視窗之中，接受以鍵盤或滑鼠進行複雜的操作。
* 圖形**多重視窗**(multi-window)（GUI）：於桌面環境中產生多個視窗，彼此之間還可以相互連動。

==== 依網路
依照執行時的網路需求，也可將程式以另一種分類模式來表示：

[square]
* *單機*(standalone) 架構：運行時不需要網路，軟體不扮演任何網路角色。
* *客戶端－伺服器*(client-server) 架構：運行時需要網路，軟體扮演客戶端或伺服器的角色。
* *點對點*(point-to-point) 架構：運行時需要網路，軟體互相扮演端點的角色。

==== 依調用方式
可執行程式可以經由以下一種或多種的方式被調用：

[square]
* 輸入程式名稱：於命令列模式或執行視窗。
* 雙擊程式圖示：於軟體選單或檔案管理視窗。
* 按下快捷鍵：按鍵動作透過常駐程式呼叫。
* 硬體事件觸發：經由熱插拔周邊裝置或資料媒體。


=== 來自原始碼
最原始的軟體安裝方式，就是直接從開發者釋出的原始碼來安裝。
即使安裝者沒有開發軟體的經驗，仍然必須具備基本的軟體開發概念，才能夠順利進行安裝作業。

軟體之間普遍都存在著依存性，也就是在組建、安裝或執行某個軟體之前，需要先安裝好其他特定的軟體。
有些依存的軟體在組建階段就是必須的，因此能夠在早期方便地識別出來；
但是有些軟體的必要性卻不明顯，甚至需要實際執行軟體之後，才能依靠試誤的過程辨別出來。

在像 Linux 這樣的多人系統中，雖然允許軟體衹安裝在個人目錄之下而且衹提供個人使用，
但是由於整個系統通常就衹有一位使用者，因此將軟體安裝在系統目錄中反而比較方便。
不過要記得，安裝在系統目錄前必須先變更身分為超級使用者 root。

==== 原始碼取得
如果能找到開發者的個人網頁或是軟體的首頁，那麼直接從這裡下載的原始碼無疑是較為安全且即時的版本。
目前許多的自由/開放原始碼軟體，都會利用網路上的版本控制系統建立軟體專案，藉以寄存並維護原始碼。
因此直接在 Github, Gitlab 或 SourceForge 網站中搜尋軟體，比較容易獲得有用的結果，
不然就衹能利用一般的搜尋引擎，再去逐項過濾搜尋到的結果是否符合所需。

開發者釋出的原始碼，一般都是以封裝且壓縮過的檔案形式存在，除了在瀏覽器中直接點擊下載之外，
也可以在終端機仿真視窗中，利用 `wget` 命令配合檔案網址取得。
例如使用以下的指令之一：
====
user$ *wget _https://www.專案名稱.org/download/專案名稱-3.0.zip_* +
user$ *wget _https://專案名稱.sourceforge.net/專案名稱-0.1.2.tar.bz2_* +
user$ *wget _https://github.com/計畫名稱/專案名稱/archive/refs/tags/v2.1.tar.gz -O 專案名稱-2.1.tar.gz_*
====

WARNING: 透過瀏覽器下載時，檔案名稱可能會自動變更後才儲存。

萬一開發者或網站未提供適合的封裝檔案，使用者仍然可以利用標準的版本控制系統指令來下載：
====
user$ *git clone --recursive _https://github.com/計畫名稱/專案名稱.git_*
====
所得到的 `專案名稱/` ，即為含有軟體原始碼的複殖目錄。

==== 打包與解包
要進入到下一階段的組建步驟之前，需要先將原始碼展開為原本的檔案目錄形式。
如果取得的是封裝過的檔案，表示曾經利用 `tar` 或 `cpio` 之類的格式，將多個原始碼檔案彼此銜接，產生具有對應副檔名的單一檔案。
如果取得的是壓縮過的檔案，則代表利用各類不同的演算法將個別檔案進行壓縮，產生分別具有 `gz`, `bz2`, `xz` 或 `zst` 副檔名的單一檔案。

實務上常用的打包命令，則允許將這兩個動作結合起來，而不需要使用者去執行兩條命令，還避免了可能產生的中間暫時檔案。
但是也有些格式像是 `rar`, `zip` 或 `7z` ，同時具備封裝與壓縮的功能，能夠一次就滿足將整個檔案目錄打包起來的需求。
例如：
====
user$ *tar -czvf _專案名稱-2.1.tar.gz 專案名稱/_*
====
或
====
user$ *zip -r _專案名稱-3.0.zip 專案名稱-3.0/_*
====
而使用者要熟悉的動作，則是如何將其解開：
====
user$ *tar -xvf _專案名稱-2.1.tar.gz_*
====
或
====
user$ *unzip _專案名稱-3.0.zip_*
====
有些打包檔在製作時，不是以一個目錄做為打包來源，導致解開後會在當前工作目錄中產生一堆零散的檔案。
如果能先建立好一個新的目錄，進入後再從目錄中解開上層的打包檔，就可以避免這種**打包炸彈**(tarbomb) 造成的不便：
====
user$ *mkdir _專案名稱-0.1_* +
user$ *cd _專案名稱-0.1_* +
user$ *unzip ../_專案名稱-0.1.zip_*
====
但要注意手動建立的暫時目錄名稱不要包含空格或其他特殊字元，因為有些組建命令稿可能會因此而發生錯誤。

==== 原始碼組建
解開後的打包檔大致上包含了三類檔案：文件檔、程式檔、資料檔。
雖然其中的文件檔通常不是必要的部分，但是卻可能記載了組建、安裝與使用過程中，關鍵的操作步驟。
首先應該從名稱包含 `LICENSE` 的檔案中，確認軟體的授權是否為使用者能夠接受的類型。
再來從名稱包含 `README` 的檔案中，可以了解軟體相關的介紹，以及進一步參考的資訊。
由於原始碼可能的組建方式非常多樣，如果幸運的話，文件中會列出正確的命令與適當的引數範例，
否則衹能依靠經驗來推測組建流程。

依照軟體本身的複雜程度不同，原始碼的組建工作也會有很大的差別。
簡單的命令稿程式可能根本不需要這個步驟，但以編譯語言編寫的大型軟體，甚至需要合乎規格的硬體才能完成組建。
組建動作大致上包括：

[square]
* 適當修改程式內容，以配合不同平臺的特性。
* 如果需要產生二進位的程式，則利用相關工具鏈軟體進行作業。
* 安排目錄與檔案的名稱與位置，準備後續的安裝。

通常這代表著一個接著一個的相關指令，當全部過程順利執行之後，就表示完成了組建。
大部分開發者採用傳統的 Make 工具做為組建管理機制，主要是由 `make` 命令與預設的組態檔所組成。
拿到原始碼的使用者，一般衹需要在解開後的目錄中執行：
====
user$ *make*
====
就會讀取開發者於工作目錄中事先寫好的 `Makefile` 純文字檔案，並依照其中設定目標的指令規則來執行（習慣上以 `all` 做為排在第一個的預設目標）。
如果目錄中存在名為 `makefile` 或 `GNUmakefile` 的檔案，預設同樣會被讀取，當然也支援藉由引數來指定的組態檔名稱。

有些𠩤始碼需要特別的組建參數，萬一開發者沒有將適當的 `Makefile` 檔案附上，安裝者衹能依據文件與經驗自行嘗試。
例如，組建內核模組的指令範例：
====
user$ *make -C /lib/modules/$(uname -r)/build SUBDIRS=$PWD modules*
====
或是衹有簡單 C/C++ 語言程式檔案的情況，還能依賴 `make` 的內建規則：
====
user$ *make _專案名稱_* +
cc 　　專案名稱.c 　-o 專案名稱
====

比較複雜的軟體則需要多一層的機制，用來偵測系統平臺的差異，以產生可用於 `make` 命令的 `Makefile` 。
常見的上層工具包括：

[square]
* Imake：存在 `Imakefile` 組態檔案，執行的命令是 `xmkmf`
* Autoconf：存在可執行的 `configure` 檔案，需要直接執行 `./configure`
* QMake：存在類型為 `\*.pro` 的組態檔案，執行的命令是 `qmake`
* CMake：存在 `CMakeLists.txt` 組態檔案，執行的命令是 `cmake`

實務上常常會加上額外的引數，甚至還可能存在更上一層的機制。

組建過程中會導致中斷的可能原因有很多，例如：

[square]
* 使用不適合的命令
* 檔案或目錄的屬性不正確
* 拼錯命令或檔名
* 缺少組建工具鏈中的某個軟體
* 沒有正確設定或呼叫工具鏈軟體
* 缺少需要的開發函式庫
* 組態檔的語法或內容與平臺不相容
* 原始碼本身的程式錯誤

即使難免遇到了阻礙，至少還有軟體的原始碼可供修改（或是請別人幫忙研究）。
如果一切順利，就會產生準備好可供安裝的檔案。

==== 原始碼安裝
傳統的安裝過程同樣也是使用 Make 機制，習慣上則以 `install` 做為目標參數：
====
user$ *make install*
====
如果原始碼軟體包不支援此項機制或是沒有適當的安裝目標，也未提供其他可用的機制或安裝命令稿，那就衹能手動在系統中建立目錄，再將需要的檔案拷貝過去。
標準的做法是呼叫 `install` 命令，利用選項來組態檔案權限，並以來源路徑與目標路徑做為參數，而這也是大部分 `make install` 指令所實際執行的動作。
安裝目標通常位於系統目錄，因此就需要先切換為超級使用者身分。安裝一般工具程式的指令範例如下：
====
root# *install -Dm755 _檔案路徑_ /usr/bin/_命令名稱_*
====
而手動安裝內核驅動模組的指令則像是：
====
root# *install -d /lib/modules/$(uname -r)/updates* +
root# *install -m644 _模組名稱_.ko /lib/modules/$(uname -r)/updates*
====

在 Make 組建管理機制中，習慣會以 `uninstall` 目標參數來呼叫解除安裝的動作：
====
user$ *make uninstall*
====
但是並非所有的開發者都會將它實作在 `Makefile` 檔案中。
如果真的必須解除安裝，就衹能參考原本安裝的詳細過程，然後手動將它們逐一反向操作。

上面提到的組建與安裝步驟，主要源自於以 C/C++ 程式語言開發的軟體，下表列出一些其他開發語言也可能採用的機制（已省略部分引數）：

[.center,width="95%",cols="4h,6,10,10",options="header"]
|====
|開發語言|判斷依據|組建指令|安裝指令
|Python|setup.py|python setup.py build|python setup.py install
|Rust|Cargo.toml|cargo build|cargo install
|Ruby|Rakefile|rake|rake install
|Haskell|*.cabal|cabal build|cabal install
|Go|main.go|go build|install
|Java|build.xml|ant|install
|Perl|Makefile.PL|perl Makefile.PL|install
|====

=== 來自軟體包
軟體包通常是以單一檔案的型式散佈，內容則為原始碼先經過組建之後，再加上一些方便安裝的機制後打包所構成，但未附有特定格式的後設資料。
對於不是自由/開放原始碼的軟體而言，散佈二進位檔案時並不用附上原始碼或提供取得原始碼的途徑。
對於使用者來說，雖然無法取得原始碼而不能自由地使用軟體，不過如果是在流行的平臺上運行，卻也省去了自行組建軟體的麻煩，安裝的步驟一般也會更方便。

==== 軟體包取得
取得軟體包的方法與取得原始碼的方法類似，通常可以在開發者的個人網頁或是軟體的首頁中找到。
而在網路版本控制系統的軟體專案中，開發者也常常會針對流行的平臺，額外提供事先組建好的軟體包。

從網路下載後，同樣也可能需要進行解開的步驟（參考本章前段〈原始碼取得〉小節）。
另外建議儘量在 Linux 環境與檔案系統下解開軟體包，因為其他作業系統的解開程序，可能會造成輸出檔案的名稱大小寫、存取權限不相容。

==== 軟體包安裝
既然安裝軟體包不需要先經過組建的步驟，因此通常並不會像從原始碼安裝那樣使用 Make 機制。
建議先閱讀隨附的文件，或是找找看是否已經有寫好的安裝命令稿，方便直接執行安裝。
====
root# *./install.sh*
====
有些軟體包是以單一的執行檔案形式散佈，副檔名可能是 `sh`, `bin`, `bundle` ，或是沒有副檔名。
檔案通常經過特殊的封裝、壓縮甚至加密的方式，而且不需要先由使用者自行解開。
確認檔案具備可執行屬性之後（參考〈檔案與目錄〉一章），就可以直接在工作目錄中執行它：
====
root# *./_專案名稱-16.3.2-linux64.bin_*
====
安裝內容簡單的軟體，可能在執行完此一步驟後就直接結束命令；
比較複雜的軟體，則會先將自己在暫存目錄中解開壓縮，並在執行過程中詢問一些安裝選項。

如果安裝過程不順利，或是安裝完成後的結果不如預期
（例如：軟體圖示沒有出現在系統選單上，或者直接執行命令沒有動作），
可以先研究一下安裝命令是否還有提供其他引數，或是嘗試以不同的輸入來回答安裝命令的詢問。
萬一問題依然存在，衹能期望安裝命令或是軟體本身，會不會剛好是純文字的指令稿程式，
否則就算看出問題發生的原因，也極難再去更動二進位檔的內容。

有些軟體包還有附帶解除安裝的程式，通常是和安裝動作類似的命令，
衹是檔名中的 `install` 字串換成了 `uninstall` ，或是原本的安裝命令再加上 `--uninstall` 的選項。
如果找不到隨附的命令，文件裡面又沒有提到解除安裝的方法，那就衹能依靠經驗，自行去刪除目錄與檔案。

特別要注意的是，有些軟體提供類似以下的單列指令安裝方法：
====
user$ *curl -fsSL _https://www.專案名稱.net/install.sh_ | bash*
====
實際上是直接執行透過網路傳輸而來的不明指令。雖然簡單方便，卻也帶來相當大的安全疑慮，
尤其是會提出切換成超級使用者身分執行的要求時。

=== 來自套件
目前流行的各類作業系統都會將常用的應用軟體以特定的格式封裝起來，包裝成免費的資源或是附加的商品，提供給使用者下載或購買。
每一組封裝起來的軟體稱之為**套件**(package)，而提供許多套件的軟體集合則稱為**套件庫**(package repository)。

常見的 Linux 系統所使用的主要套件格式包括 RPM 與 deb 兩種，分別由 Fedora, openSUSE, Rocky,… 以及 Debian, Ubuntu, Mint,… 等散佈版所支持。
另外存在許多次要的套件格式，雖然結構邏輯類似，但是組成的細節並不相同，而僅見於較為小眾的散佈版。
如果類比於適用 Windows 系統的 MSIX 格式，那些提供大量 Windows 應用軟體的商店網站，就相當於 Windows 系統的套件庫。

由於打包的格式是公開的規範，因此除了原本作業系統的發行者製作的官方套件之外，還有一些由愛好者所製作、頁獻的非官方套件。
同樣地，除了官方套件庫之外，也存在著不少由這些非官方套件集合而成的第三方套件庫。
如果在官方套件庫中找不到某個軟體，而自己又不熟悉製作套件的過程，就可以藉助像是 pkgs 網站
footnote:[Packages for Linux and Unix <https://pkgs.org/>]
的資料庫，在多種散佈版的各類套件庫中搜尋套件名稱、套件描述以及內含檔案。

==== 套件構成
個別套件通常是以單一檔案的形式存在，由高度相關的各類檔案加上後設資料後，經過封裝與壓縮而成。
套件與套件之間可以設定依存性，做為安裝或移除時彼此串連的根據。
整個軟體系統即可藉由套件疊加所組成，實際的數量則依系統複雜度不同而包含數百至數千個套件。

製作套件時，除了必要的軟體原始碼之外，還需要事先準備好組建的環境：
包括組建所需的命令、函式庫、目錄結構，以及編寫控制整個組建流程的**規格檔**，
之後就可以在模擬環境中進行編譯、安裝與打包。
產生出來用於安裝軟體的套件稱為**安裝套件**，而依照不同的套件格式規範，
有的還會產生方便日後重新組建的**原始碼套件**，以及方便執行時除錯的**除錯套件**。

如果將製作的套件集合起來並建立索引，再公開網路資源的存取位址，就能夠提供套件庫的服務。
使用者衹要加入套件庫的存取資訊，就可以方便地搜尋、安裝或更新套件。
但是要特別注意本地端的系統時間必須正確，否則可能會被套件庫拒絕服務，或是取得不即時的資訊。

==== 套件命令
安裝後的套件是由作業系統中的**套件管理系統**負責管理，套件資訊則記錄於本地的資料庫中，
因此可以在離線的狀態下，進行套件的查詢或移除。
依照打包格式的不同，常見的套件檔案名稱可能會以 `rpm` 或 `deb` 結尾。
如果使用者先透過拷貝或下載而取得套件檔案，也可以不必連結套件庫就能直接進行套件的安裝或更新。

在 RPM 套件管理系統中，用於套件庫與套件檔案的命令分別為 `dnf` 與 `rpm` ，
而對應於 deb 套件管理系統的命令，則分別為 `apt` 與 `dpkg` 。

NOTE: `dnf` 命令的前身為 `yum`，而 `apt` 的前身為 `apt-get` ，有時還會在舊版或其他散佈版的說明範例中看到。

以下列出最常用的套件命令引數範例：

[.center,width="90%",cols="5h,6,7",options="header"]
|====
|功能╲格式|RPM|deb
|套件更新|dnf update|apt update; apt upgrade
|套件資訊整理|dnf clean all|apt clean all
|套件字串搜尋|dnf search __搜尋字串__|apt search __搜尋字串__
|套件安裝|dnf install __套件名稱__|apt install __套件名稱__
|套件檔安裝|dnf install __套件檔案__|apt install __./套件檔案__
|套件移除|dnf remove __套件名稱__|apt remove __套件名稱__
|內含檔案搜尋|dnf provides __檔案名稱__|apt-file search __檔案名稱__
|套件移除|rpm -e __套件名稱__|dpkg -r __套件名稱__
|套件列表|rpm -qa|dpkg -l
|套件資訊|rpm -qi __套件名稱__|dpkg -s __套件名稱__
|套件檔資訊|rpm -qip __套件檔案__|dpkg -I __套件檔案__
|套件內容|rpm -ql __套件名稱__|dpkg -L __套件名稱__
|套件檔內容|rpm -qlp __套件檔案__|dpkg -c __套件檔案__
|套件檔安裝╱更新|rpm -U __套件檔案__|dpkg -i __套件檔案__
|====

不論是針對套件庫或是針對套件檔案的命令，有些動作其實可以透過不衹一種命令完成。例如：
====
root# *dnf install _專案名稱_* +
... +
root# *dnf install _專案名稱-3.0-1.x86_64.rpm_* +
... +
root# *rpm -i _專案名稱-3.0-1.x86_64.rpm_* +
...
====
以上三條適用於 RPM 套件系統的命令，都是為了要安裝__專案名稱__軟體，
但是執行前提與過程細節會略有差異，實際使用時需要參考說明文件而留意一下。
