== 軟體安裝
安裝完作業系統之後，代表這臺電腦已經具備基本的功能。
如果作業系統的安裝程序沒有同時安裝其他的項目，或是內建的應用軟體無法滿足您的需要，
不論是函式庫、驅動程式、工具程式還是遊戲，就得必須自己想辦法安裝。
本章先介紹傳統從原始碼開始組建的安裝方式，接著是如何利用軟體包安裝，最後介紹友善的套件安裝方式。
使用者閱讀時，可以根據實際需求而不必按照順序參考。

=== 來自原始碼
最原始的軟體安裝方式，就是從開發者釋出的原始碼來安裝。
即使安裝者沒有開發軟體的經驗，仍然必須具備基本的軟體開發概念，才能夠順利進行安裝作業。

軟體之間都會存在著依存性，也就是說當您要組建、安裝或執行某個軟體時，需要先安裝好其他特定的軟體。
有些依存的軟體在組建階段就是必須的，因此能夠方便地識別出來；
但是有些軟體的必要性卻不明顯，甚至需要實際執行軟體之後，才能依靠試誤的過程辨別出來。

在像 Linux 這樣的多人系統中，雖然允許軟體衹安裝在個人目錄之下而且衹能由個人使用，
但是由於整個系統通常就衹有一位使用者，因此將軟體安裝在系統目錄中反而比較方便。
不過要記得，安裝在系統目錄前必須先變更身分為超級使用者 root。

==== 原始碼取得
如果能找到開發者的個人網頁或是軟體的首頁，那麼直接從這裡下載的原始碼無疑是較為安全且即時的版本。
目前許多的自由╱開放原始碼軟體，都會利用網路上的版本控制系統建立軟體專案，以寄存並維護原始碼。
因此直接在 Github, Gitlab 或 SourceForge 網站中搜尋軟體，比較容易獲得有用的結果，
不然就衹能利用一般的搜尋引擎，再去逐項過濾搜尋結果是否符合。

開發者釋出的原始碼，一般都是以封裝且壓縮過的檔案形式存在，除了能在瀏覽器中直接點擊下載之外，
也可以在終端機模擬視窗中，利用 `wget` 命令配合檔案網址取得。
例如：
====
user$ *wget _https://www.foobar.org/download/foobar-3.0.zip_* +
user$ *wget _https://github.com/foo/bar/archive/refs/tags/v2.1.tar.gz_* +
user$ *mv _v2.1.tar.gz bar-2.1.tar.gz_*
====
NOTE: 透過瀏覽器下載時，檔案名稱可能會自動變更再儲存。

要進入到下一階段的組建步驟之前，需要先將原始碼展開為原本的檔案目錄型式。
如果取得的是封裝過的檔案，表示曾經利用 TAR 或 CPIO 之類的格式，將多個原始碼檔案彼此銜接，產生具有相應小寫副檔名的單一檔案。
如果取得的是壓縮過的檔案，則代表利用了 LZ77, Burrows-Wheeler 或 LZMA 等演算法，將個別檔案進行壓縮，產生分別具有 `gz`, `bz2` 或 `xz` 副檔名的單一檔案。
實務上常用的打包命令，則允許將這兩個動作結合起來，而不需要使用者去執行兩條命令，還避免了可能產生的中間臨時檔案。
但是也有些格式像是 `rar`, `zip` 或 `7z` ，同時具備封裝與壓縮的功能，能夠一次就滿足將整個檔案目錄打包起來的需求。
例如：
====
user$ *tar -czvf _bar-2.1.tar.gz bar/_* +
user$ *zip -r _foobar-3.0.zip foobar-3.0/_*
====
而使用者要熟悉的動作，則是如何將其解開：
====
user$ *tar -xvf _bar-2.1.tar.gz_* +
user$ *unzip _foobar-3.0.zip_*
====
有些打包檔在製作時，不是以一個目錄做為打包來源，導致解開後會在當前工作目錄中產生一堆零散的檔案。
如果先建立好一個新的目錄，再從目錄中解開上層的打包檔，就可以避免這種**打包炸彈**(tarbomb)造成的不便：
====
user$ *mkdir _foobar-0.1_* +
user$ *cd _foobar-0.1_* +
user$ *unzip ../_foobar-0.1.zip_*
====
但要注意手動建立的暫時目錄名稱不要包含空格或其他特殊字元，因為有些組建命令稿可能會因此而發生錯誤。

==== 原始碼組建
解開後的打包檔大致上包含了三類檔案：文件檔、程式檔、資料檔。
雖然其中的文件檔通常不是必要的部分，但是卻可能記載了組建、安裝與使用過程中，關鍵的操作步驟。
首先應該從名稱包含 `LICENSE` 的檔案中，確認軟體的授權是否為使用者能夠接受的類型。
再來從名稱包含 `README` 的檔案中，可以了解軟體相關的介紹，以及進一步參考的資訊。
由於原始碼可能的組建方式非常多樣，如果幸運的話，文件中會列出正確的命令與適當的引數範例，
否則衹能依靠經驗來猜測組建流程。

依照軟體本身的複雜程度不同，原始碼的組建工作也會有很大的差別。
簡單的命令稿程式可能根本不需要這個步驟，但以編譯語言編寫的大型軟體，甚至需要高規格的硬體才能完成組建。
組建動作大致上包括：

[square]
* 適當修改程式內容，以配合不同平臺的特性。
* 如果需要產生二進制的程式，則利用相關工具鏈軟體進行作業。
* 安排目錄與檔案的名稱與位置，準備後續的安裝。

通常這代表著一個接著一個的相關命令，當全部過程順利執行之後，就表示完成了組建。
大部分開發者採用傳統的 Make 工具做為組建管理機制，主要是由 `make` 命令與預設的設定檔所組成。
拿到原始碼的使用者，一般衹需要在解開後的目錄中執行：
====
user$ *make*
====
就會讀取開發者於工作目錄中事先寫好的 `Makefile` 純文字檔案，並依照其中設定的命令順序來執行。
如果目錄中存在名為 `makefile` 或 `GNUmakefile` 的檔案，同樣預設會被讀取，當然也支援藉由引數來指定的設定檔名稱。

有些𠩤始碼需要特別的組建參數，萬一開發者沒有將適當的 `Makefile` 附上，安裝者衹能依據文件與經驗自行嘗試。
例如組建內核模組的指令範例：
====
user$ *make -C /lib/modules/$(uname -r)/build SUBDIRS=$(pwd) modules*
====

比較複雜的軟體則需要多一層的機制，用來偵測系統平臺的差異，以產生可用於 `make` 命令的 `Makefile` 。
常見的上層工具包括：

[square]
* Autoconf：存在可執行的 `configure` 檔案，執行的命令是 *./configure*
* CMake：存在 `CMakeLists.txt` 設定檔案，執行的命令是 *cmake  .*
* QMake：存在檔名類型為 `*.pro` 的設定檔案，執行的命令是 *qmake-qt5*

實務上常常會加上額外的引數，或是改用其他較少見的工具，甚至還需要更上層的機制，那就要靠說明文件與以往經驗來判斷。
組建過程中會導致中斷的可能原因有很多，例如：

[square]
* 使用不適合的命令
* 檔案或目錄的屬性不正確
* 拼錯命令或檔名
* 缺少組建工具鏈中的某個軟體
* 沒有正確設定或呼叫工具鏈軟體
* 缺少需要的開發函式庫
* 設定檔的語法或內容與平臺不相容
* 原始碼本身的程式錯誤

即使難免遇到了阻礙，至少還有軟體的原始碼可供修改（或是請別人幫忙研究）。
如果一切順利，就會產生準備好可供安裝的檔案。

==== 原始碼安裝
傳統的安裝過程同樣也是使用 Make 機制，習慣上則以 `install` 做為目標參數：
====
user$ *make install*
====
如果原始碼軟體包不支援 Make 的安裝目標，也沒有其他可用的機制或安裝命令稿，
就衹能手動在系統中建立目錄，再將需要的檔案拷貝過去。

通常在 Make 組建管理機制中，會以 `uninstall` 目標參數來呼叫解除安裝的動作：
====
user$ *make uninstall*
====
但是並非所有的開發者都會將它實作在 `Makefile` 檔案中。
如果真的必須解除安裝的話，衹能參考安裝的詳細過程，然後手動將它們逐一反向操作。

=== 來自軟體包
軟體包通常也是以打包成為單一檔案的型式散佈，內容則為原始碼先經過組建之後，再加上一些方便安裝的機制所構成。
對於不是自由╱開放原始碼的軟體而言，散佈二進制檔案時就不用附上原始碼。
對於使用者來說，雖然無法取得原始碼而不能自由地使用軟體，不過如果是在流行的平臺上運行，
卻也省去了自行組建軟體的麻煩，安裝的步驟一般也會更方便。

==== 軟體包取得
取得軟體包的方法與取得原始碼的方法類似，通常可以在開發者的個人網頁或是軟體的首頁中找到。
而在網路版本控制系統的軟體專案中，開發者也常常會針對流行的平臺，額外提供事先組建好的軟體包。
從網路下載後，同樣也可能需要進行解開的步驟（參考本章前段〈原始碼取得〉小節）。

==== 軟體包安裝
雖然安裝軟體包不需要先經過組建的步驟，但是通常並不會像從原始碼安裝那樣去使用 Make 機制。
建議先閱讀隨附的文件，或是找找看是否已經有寫好的安裝命令稿，方便直接執行安裝。
====
root# *_./install.sh_*
====
有些軟體包是以單一的執行檔案型式散佈，副檔名可能是 `sh`, `bin`, `bundle` ，或是沒有副檔名。
檔案通常經過特殊的封裝、壓縮甚至加密的方式，而且不需要先由使用者設法解開。
確認檔案具備可執行屬性之後（參考〈檔案與目錄〉），就可以直接在工作目錄中執行它：
====
root# *_./foobar-16.3.2-linux64.bin_*
====
安裝內容簡單的軟體，可能在執行完步驟後就直接結束命令；
比較複雜的軟體，則會先將自己在暫存目錄中解開壓縮，並在執行過程中詢問一些安裝選項。

如果安裝過程不順利，或是安裝完成後的結果不如預期
（例如：軟體圖示沒有出現在系統選單上，或者直接執行命令沒有動作），
可以先研究一下安裝命令是否還有提供其他引數，或是嘗試以不同的輸入來回答安裝命令的詢問。
萬一問題依然存在，衹能期望安裝命令或是軟體本身，會不會剛好是純文字的指令稿程式，
否則就算看出問題發生的原因，也極難再去更動二進制檔的內容。

有些軟體包還有附帶解除安裝的程式，通常是和安裝動作類似的命令，
衹是檔名中的 `install` 換成 `uninstall` ，或是原本的安裝命令再加上 `--uninstall` 的選項。
如果找不到隨附的命令，文件裡面又沒有提到解除安裝的方法，那就衹能依靠經驗，自行去刪除目錄與檔案。

=== 來自套件
目前流行的各類作業系統都會將常用的額外應用軟體以特定的格式封裝起來，
包裝成附加的商品或是免費的資源，提供給使用者購買或下載。
每一組封裝起來的軟體稱之為**套件**(package)，而外部提供許多套件的集合則稱為**套件庫**(package repository)。

各類 Linux 系統所使用的主要套件格式包括 RPM 與 DEB 兩種，分別由
RHEL、Fedora、CentOS、openSUSE,… 以及 Debian、Ubuntu、Mint,… 等散佈版所支持。
另外存在許多次要的套件格式，雖然結構邏輯類似，但是組成的細節並不相同，而僅見於小眾的散佈版之中。
如果類比於適用 Windows 系統的 MSI 格式，那些提供大量 Windows 應用軟體的網站，
就相當於 Windows 系統的套件庫。

由於封裝的格式是公開的規範，因此除了原本作業系統的發行者所製作的官方套件之外，還有一些貢獻者會製作非官方的套件。
同樣地，除了官方套件庫之外，也存在著不少由非官方套件集合而成的第三方套件庫
footnote:[例如筆者所建立的 RPM Sphere <https://rpmsphere.github.io/>]。
如果在官方套件庫中找不到某個軟體，而自己又不熟悉製作套件的過程，
就可以藉助像是 pkgs.org 網站的資料庫，在多種散佈版的各類套件庫中搜尋套件。

==== 套件構成
個別套件通常是以單一檔案的形式存在，由高度相關的各類檔案經過封裝與壓縮而成。
套件與套件之間可以設定依存性，做為安裝或移除時彼此串連的根據。
整個軟體系統即可藉由套件疊加所組成，實際的數量則依系統複雜度不同而包含數百至數千個套件。

製作套件時，除了必要的軟體原始碼之外，還需要事先準備好組建的環境：
包括組建所需的命令、函式庫、目錄結構，以及編寫控制整個組建流程的**規格檔**，
之後就可以在模擬環境中進行編譯、安裝與打包。
產生出來用於安裝軟體的套件稱為**安裝套件**，而依照不同的套件格式規範，
有的還會產生方便日後重新組建的**原始碼套件**，以及方便執行時除錯的**除錯套件**。

如果將製作的套件集合起來並建立索引，再公開 HTTP 或 FTP 的存取位址，就能夠提供套件庫的服務。
使用者衹要加入套件庫的存取資訊，就可以方便地搜尋、安裝或更新套件。
但是要特別注意本地端的系統時間必須正確，否則可能會被套件庫拒絕服務，或是取得不正確的資訊。

==== 套件命令
安裝後的套件是由作業系統中的**套件管理系統**負責管理，套件資訊記錄於本地的資料庫中，
因此可以在離線的狀態下，進行套件的查詢或移除。
依照打包格式的不同，常見的套件檔案名稱可能會以 `rpm` 或 `deb` 結尾。
如果使用者先透過拷貝或下載而取得套件檔案，也可以不必連結套件庫就能進行套件的安裝或更新。

在 RPM 套件管理系統中，用於套件庫與套件檔案的命令分別為 `dnf`, `rpm` ，
而用於 DEB 套件管理系統的命令，則分別為 `apt`, `dpkg` 。
NOTE: `dnf` 命令的前身為 `yum`，而 `apt` 的前身為 `apt-get` 。
以下列出最常用的命令引數範例：

[width="80%",options="header"]
|=============================
|套件格式|RPM|DEB
|套件更新|dnf update|apt update; apt upgrade
|套件資訊整理|dnf clean all|apt clean all
|套件字串搜尋|dnf search __搜尋字串__|apt search __搜尋字串__
|套件安裝|dnf install __套件名稱__|apt install __套件名稱__
|套件檔安裝|dnf install __套件檔案__|apt install __./套件檔案__
|套件移除|dnf remove __套件名稱__|apt remove __套件名稱__
|套件移除|rpm -e __套件名稱__|dpkg -r __套件名稱__
|套件列表|rpm -qa|dpkg -l
|套件資訊|rpm -qi __套件名稱__|dpkg -s __套件名稱__
|套件檔資訊|rpm -qip __套件檔案__|dpkg -I __套件檔案__
|套件內容|rpm -ql __套件名稱__|dpkg -L __套件名稱__
|套件檔內容|rpm -qlp __套件檔案__|dpkg -c __套件檔案__
|套件檔安裝╱更新|rpm -U __套件檔案__|dpkg -i __套件檔案__
|=============================

不論是套件庫命令或是套件檔案命令，有些動作其實可以透過不衹一種命令完成。例如：
====
root# *dnf install _foobar_* +
root# *dnf install _foobar-3.0-1.x86_64.rpm_* +
root# *rpm -i _foobar-3.0-1.x86_64.rpm_*
====
以上三條適用於 RPM 套件系統的命令，都是為了要安裝 _foobar_ 軟體，
但是執行前提與過程細節會略有差異，實際使用時需要參考說明文件留意一下。

