== 文字檔
文字檔是使用電腦時最容易處理的檔案格式，不僅方便讀取，也方便進行新增、修改、刪除等編輯作業。
文字檔所儲存的內容主要是各類文件，當然也包括了眾多的電腦語言程式原始碼。
即使是圖片或音樂，也有可能以文字描述的格式記錄下來。
甚至任何類型的資料，都可以透過某些特殊的編碼而轉換為文字格式。
例如以下是由 Base64
footnote:[「六十四基底」編碼於維基百科的說明 <https://zh.wikipedia.org/wiki/Base64>]
編碼過的筆者電子郵件信箱地址：

.email.b64
....
Ymx1ZWJhdEBtZW1iZXIuZnNmLm9yZwo=
....

=== 文字檔類型
如果依照廣義的說法，所謂的文字檔就是：檔案內容需要符合某種字元集的編碼規範，而解碼後所得到的，都是畫面可顯示、使用者可讀的文字。
其中可以包含一些換列、換頁、檔案結尾等簡單的控制字元，而不會出現複雜的非文字格式字元。
狹義的文字檔常被稱為**純文字檔**(text file)，它的編碼符合 *UTF-8*(八位元萬國碼編碼形式) 或是相容的子集合 *US-ASCII*(美國標準資訊交換碼)。

US-ASCII 是固定長度的編碼，衹需要 7 個位元的空間，但是因為一般資訊處理都是以一個位元組（8 個位元）為單位，所以實際的編碼就用一個位元組來儲存一個字元。
UTF-8 是基於**萬國碼**(Unicode) 字元集的一種變動長度的編碼，每個字元會由 1~4 個不等的位元組來表示，而每個漢字通常需要 3~4 個位元組的儲存空間。
外部命令 `iconv` 雖然可以用來轉換編碼，但是是否成功仍取決於原始與目標字元集的相容程度，以及內容涵蓋的字元集範圍。

有些作業系統或軟體為了相容的原因，還在純文字檔的最前方加上兩個字元，用來區別硬體架構的**尾序**(endianness)。
但是這種稱為 *BOM*(位元組順序標記) 的魔術字元，在 Linux 系統上的使用並不普遍。
WARNING: 使用前置 BOM 的純文字檔，可能會造成讀取或執行時的錯誤。

即使是純文字檔這樣相對比較簡單的類型，在不同的作業系統上仍然有細微的差異。
就以換列來說，Linux 或其他 UNIX 相容系統是使用 LF(ASCII 10) 字元，macOS 是使用 CR(ASCII 13) 字元，
而 DOS 與 Windows 系統則使用 CR+LF 兩個字元，做為標示每列結束的符號。
對於 BOM 以及換列的問題，外部命令 `dos2unix` 提供了方便的格式轉換工具。

=== 處理文字檔
Linux 中許多類型的檔案，都是以文字的格式呈現，
或是存在著文字的轉換格式，因此處理文字檔就成了操作系統必備的技能。

==== 初始建立
最簡單建立文字檔的方法，是透過將命令的輸出重導至一個檔案名稱所產生的。
但是要注意隨著重導符號的不同，會造成內容被覆蓋或是附加的結果。
使用外部命令 `cat`(concatenate) ，可以顯示參數中的檔案內容（也就是輸出到終端機視窗中）。
萬一檔案內容太多，導致前面的資料來不及看清楚，還可以使用 `more` 或 `less` 讓輸出成為分頁的模式。
====
user$ *echo _初始的內容_ > _file.txt_* +
user$ *echo _覆蓋的內容_ > _file.txt_* +
user$ *cat _file.txt_* +
覆蓋的內容 +
user$ *echo _新增的內容_ >> _file.txt_* +
user$ *cat _file.txt_* +
覆蓋的內容 +
新增的內容
====

==== 簡單編輯
習慣上，**文字編輯軟體**的功能僅限於處理純文字格式，而**文書處理軟體**則用來產生比較複雜的正式文件。
對於終端機環境中的文字編輯器，Linux 使用者一直以來都是各有所好。
即使是比較流行的 `nano`, `joe`, `vi` 等程式，操作概念與方法都有不小的差異。
使用者需要實際嘗試看看，才能找出適合自己的工具，同時至少了解其他編輯器的基本操作，以備不時之需。
環境變數 `EDITOR` 會指向系統預設的文字編輯器，使用者可以在 `$HOME/.bashrc` 檔案中，重新將它指定成慣用的命令路徑。

將檔名做為參數來打開有相容問題的文字檔時，每種文字編輯器的表現也可能不盡相同。
以〈文字檔：文字檔類型〉中所提到含有 BOM 的 DOS 換列格式為例，就有可能看到以下的編輯畫面：
====
[underline]##<FEFF>##覆蓋的內容 [underline]#M# +
新增的內容 [underline]#M#
====
應該足以提醒使用者要注意，並採取適當的前處理方式，再進行任何形式的編輯：
====
user$ *file _file.txt_* +
file.txt: Unicode text, UTF-8 (with BOM) text, with CRLF line terminators +
user$ *dos2unix _file.txt_* +
dos2unix: 正在轉換 file.txt 至 Unix 格式… +
user$ *file _file.txt_* +
file.txt: Unicode text, UTF-8 text
====

在圖形環境中，可以選擇的文字編輯軟體就更多了，而文書處理軟體也都有匯入與匯出文字檔的功能。
值得一提的是，不論使用滑鼠雙擊或拖曳將一段文字反白之後，在 Linux 環境中直接按下滑鼠滾輪鍵，
就會將文字貼上游標所在的位置，還可以多次操作，這通常要比軟體中原本的拷貝╱貼上功能更為快速與方便。

==== 批次處理
當要對多個大型的文字檔案進行處理，而每個檔案又有多處需要更動的部分時，
那麼以編輯器逐檔載入後修改，顯然不是一個有效率的操作方式。
以下列舉幾個常用的外部命令，適合批次處理文字檔案：

[square]
* `wc`(word count): 計算檔案內容的列、字詞、字元數量。
* `cut`: 將指定欄位的內容分割出來。
* `sort`: 依照指定順序條件重新排列各列位置。
* `grep`(global regular expression search and print): 篩選出含有指定**胚騰**(pattern) 的文字列。
* `sed`(stream editor): 依照指定胚騰進行內容的新增、刪除、替代操作。
* `awk`(Aho, Weinberger, Kernighan): 以簡單程式語言逐列處理內容。

上述工具大致按照功能由簡單到複雜排列，建議讀者可依需求循序學習。
其中提到的胚騰遵循著**正規表示式**(regular expression) 的規範，是學習進階文字處理必備的知識。
大部分使用者衹有認識基本的萬用匹配，但是它與正規表示式都應該被深入了解，而且重要的是兩者不要搞混。
如果需要混合使用多個工具，實務上會利用管線符號(|) 將命令組合起來，甚至會寫成一個簡單的命令稿。
（雖然在試驗階段可能還是需要將個別命令分開執行，才能確認中間產生的臨時檔案內容無誤。）

=== 標記語言檔
最簡單也是最常見的文字內容格式，是以列為單位的**序列化**(serialization) 輸出。
如果想要表現更有組織性的內容，可以按照**標記語言**(markup language) 的規範來達成。

==== 頁描述
文字檔案儲存內容的首要目的，自然是用來輸出文件。
單調的無格式輸出，顯然不能符合大部分應用情境的需求。
以下嘗試幾種頁描述類型的標記語言，來顯示類似的文件格式內容：

.article.html
....
<ul>
  <li><em>項目一</em>：內容一。</li>
  <li><em>項目二</em>：內容二。</li>
</ul>
....

.article.md
....
- *項目一*：內容一。
- *項目二*：內容二。
....

.article.adoc
....
* __項目一__：內容一。
* __項目二__：內容二。
....

.article.tex
....
\begin{itemize}
  \item \emph{項目一}：內容一。
  \item \emph{項目二}：內容二。
\end{itemize}
....

==== 資料集合
有非常多的標記語言可以用做資料集合，以下利用幾種常見的格式來表示相同的記錄內容：

.data.csv
....
類別,項目,數值
類別一,項目一,數值一
類別一,項目二,數值二
類別二,項目一,數值三
....

.data.conf
....
[類別一]
項目一=數值一
項目二=數值二
[類別二]
項目一=數值三
....

.data.xml
....
<類別一>
  <項目一>數值一</項目一>
  <項目二>數值二</項目二>
</類別一>
<類別二>
  <項目一>數值三</項目一>
</類別二>
....

.data.json
....
{
  類別一:
  {
    "項目一": "數值一",
    "項目二": "數值二"
  }
  類別二:
  {
    "項目一": "數值三"
  }
}
....

==== 多媒體
雖然有些文字格式所用的標記語言語法複雜，而且檔案所佔空間較大，並不適合直接編輯，
但是因為具有方便取得編輯工具的優點，又能夠在多種平臺上處理，因此常常做為不同軟體之間的交換格式。

這種情況在多媒體應用上尤其顯著，讀者可以自行參考做為像素圖形的 XPM 格式、向量圖形的 SVG 格式，
以及聲音效果的 ABC 格式。

=== 程式語言檔
程式是多個電腦語言指令組成的集合，通常是由機器語言編碼組成的二進位格式，可以直接交給處理器執行；
也可能是由語言敘述組成的文字格式，由語言的**解譯器**(interpreter) 負責讀入執行；
或是由**位元碼**(bytecode) 組成的中介代碼格式，透過**虛擬機**(process virtual machine) 的載入器間接執行，
或是在基於瀏覽器的虛擬平臺上執行。

==== Python 語言
下面是一個以 Python 指令稿語言編寫的九九乘法表程式，先利用文字編輯器將它輸入到檔案：

.mt9x9.py
....
#!/usr/bin/python3
for i in range(1, 10, 3):
    for j in range(1, 10):
        for k in [i, i+1, i+2]:
            print(f"{k}x{j}={k*j:2}", end='\t')
        print(end='\n')
    print()
....

就能藉由輸入 `python3 mt9x9.py` 指令，來呼叫 `python3` 程式去解譯並執行這個指令稿。
也可以先用 `chmod +x mt9x9.py` 指令將其屬性設定為可執行之後，再輸入 `./mt9x9.py` 來執行它。
實際的過程中，內核仍然會先呼叫檔案開頭 `#!` **井歎符號**(shebang) 後方的程式，再以該文字檔案做為參數去執行。

==== C 語言
做為對照的 C 程式語言，先將以下內容存入檔案：

.mt9x9.c
....
#include <stdio.h>
int main(int argc, char *argv[]) {
    int i, j, k;
    for(i = 1; i <= 9; i += 3) {
        for(j = 1; j <= 9; j++) {
            for(k = i; k <= i+2; k++)
                printf("%dx%d=%2d\t", k, j, k*j);
            printf("\n");
        }
        putchar(10);
    }
}
....

然後呼叫 C 的編譯程式 `gcc` （如果系統中不存在此外部命令，則需要先安裝好相關套件），將它編譯為二進位格式的機器語言檔案。
如果順利的話，就會產生已經帶有可執行屬性的 `mt9x9` 檔案，可以直接輸入 `./mt9x9` 來執行它：
====
user$ *gcc _mt9x9.c_ -o _mt9x9_* +
user$ *_./mt9x9_*
====
程式語言衹是一種規範，有多種可能的方式能讓它實際運作。
常用的 C 編譯程式並非衹有一種，還可以使用 `clang` 做為替代方案之一。
這裡的 `gcc` 或 `clang` 其實衹是**編譯器**(compiler) 代表，與**組譯器**(assembler)、**鏈結器**(linker)…等元件，共同組成一套複雜的**工具鏈**(toolchain)。

某種程式語言寫成的檔案是否需要經過編譯，或是解譯後即可執行，其實並不具有絕對的關係。
如果能找到適當的 C 語言解譯程式
footnote:[Tiny C Compiler <http://bellard.org/tcc> 加上 -run 選項]，
就可以不經編譯而直接解譯後執行 `mt9x9.c` 檔案。
有興趣的讀者，可以看看其他程式語言輸出相同結果的實作
footnote:[Multiplication Table in Various Programming Languages <https://github.com/bluebat/mt9x9>]。
