== 自由軟體
為什麼要用自由軟體？
一般人對於軟體的分類，衹有免費軟體或是付費軟體兩種。
與自由軟體相對的概念，通常稱之為專有軟體，市面上銷售的軟體商品大多屬於這一類
(當然我們並不會故意用不自由軟體來稱呼它們)。

所謂的自由軟體，最早是由 Richard Stallman 所提出的概念，
他認為軟體使用者有四項基本的自由，分別是使用的自由、散佈的自由、修改的自由，以及再散佈的自由。
而滿足這些要求的軟體才能稱之為自由軟體，而推廣這個概念的運動就稱為軟體自由運動。

=== 開放原始碼
另外一個常常聽到的名詞是開放原始碼軟體，顧名思義這表示軟體的原始程式碼是可以公開看到的。
它其實包含了所有的自由軟體，一些不屬於自由軟體的開放原始碼軟體，以及少部分的專有軟體。

以軟體自由的觀點而言，將程式原始碼開放僅僅是滿足了修改的自由而已，正如同某些專有軟體也宣稱自己是開放原始碼一樣，
其實使用者根本無法獲得其他三項自由，而其他自由度介於一項與四項之間的軟體，則分佈於自由軟體外圍的部分。

如果將這些對於使用者自由的規定予以條文化，就是今日所看到各式各樣的使用授權，常見的有：
GPL, MIT, BSD, Public Domain 分別代表不同類型的軟體，同時還衍生出許多次類型。

那麼免費軟體/付費軟體與自由軟體/專有軟體這兩種分類之間有什麼關係呢？
簡單地來說，並沒有必然的相關性，也就是說，雖然自由軟體大部分免費，但並未限制不可以拿來銷售；
專有軟體雖然大部分需要付費，但是也有可以免費取得的版本。

=== 推廣的好處
那麼，推廣自由軟體究竟有什麼好處呢？我們可以分別用以下四類人的角度來說明：

跟一般人切身相關的，就是做為一個軟體使用者來說，使用自由軟體雖然會少掉一些便利性，
因為畢竟專有軟體是由財力雄厚的大型軟體開發公司所維護的。
不過專有軟體最糟糕的部分，並不是因為你要付費購買，反而是因為常常是沒有付費就取得：
也許你認為盜拷這件事並不算是什麼道德上的瑕疪，甚至在你的家人或朋友之間也覺得這是一件無傷大雅的事：
別人要限制你的自由，所以我偷偷拿回來一點似乎是很正當的行為。

對於使用者組織來說，這裡通常指的就是家庭、公司、機關而言，使用專有軟體常常會帶來一筆不小的經濟負擔。
即使所用的軟體是隨附在硬體之中，其實成本也已轉嫁到硬體之上。許多專有軟體並非賣給你軟體的所有權，
而是限時、限地、限機器、限功能、限使用者的苛刻授權，當你想要進行任何的擴充，就必須再付出高額的代價。

另外還有安全與隱私的顧慮，由於無法看到原始的程式碼，沒有人知道專有軟體除了表面的工作之外，
還在你的電腦中執行了哪些動作，這種隱憂在上網的環境中變得更加嚴重。
使用自由軟體的解決方案，才算擁有軟體使用的主導權。
你並不需要具備修改軟體的能力，而是獲得了自由選擇軟體服務商的能力。

如果你是一個開發者，不論是系統分析、程式設計或是軟體測試，專有軟體使得你的技術始終存在盲點，
縱然你有再大的熱情、再豐富的知識，也無法確認其他專有軟體中的疑點，
而你從某個專有軟體獲得的經驗，也並不容易套用到其他專有軟體之上。
程式設計者的心血在於一列一列的原始碼，不論你寫得再好，在專有軟體中永遠不會被很多人看到，
甚至往往審查程式的人根本看不懂你所寫的東西。
一旦所負責的專案消失，或是離開了這個職位，你的心血可能從此就煙消雲散。

對於一間軟體開發公司來說，公司的産品是建立在許多的黑箱之上，當一切都很順利時，並不會有什麼問題，
但是當問題出現時，通常衹能靠修改自己的産品解決，即使問題可能出自上游的軟體，
想要尋求支援都不是一件簡單的事，更不用說要付出多少代價才能得到徹底的解決方案。
由於專有軟體的不開放，公司雇用的開發者也被限定在特定的技術，不僅新人都需要從頭培養，
無法招募其他領域優秀的開發者，即使培養出有經驗的工程師，對於其他領域的問題也是一籌莫展。

=== 影響
最後，正如 Richard Stallman 所主張，目前世界上已有部分國家開始採納的意見一樣，軟體專利權是不合理的規定。
這並非表示硬體發明也不應該享有專利權，不過事實上的確已經出現了一些開放硬體，例如樹莓派的 SBC 或是 RISC-V 的 CPU
同樣這也並非否定軟體的著作人格權，而是認為軟體的著作財産權應該有更適當的規定。

