[abstract]
== 前言
Linux 相容性測試人員是指在資訊系統硬體製造的公司中，
針對所生產的各款機型，進行 GNU/Linux 作業系統的運作測試，
包括系統安裝、驅動程式、執行效能等項目。
在不斷推陳出新的硬體型號與軟體版本雙重考驗下，測試人員需要依靠手邊的筆記，隨時記錄過程中的動作細節，
希望能在下次遇到問題的時候，少花一點搜尋的時間與試誤的次數。

限於筆者本身的技術程度，對於實證有效的對策，並未每項提供充分的理論解釋，
而許多相關的補充手法也無法逐條驗證，衹能附記在旁做為爾後類似狀況的參考。
有些實驗性質的步驟，僅適用於測試硬體，而非辦公或生產用機臺。
如果讀者手邊的電腦已經負有重要的任務，請在應用這些方法前，務必再三確認。

由於硬體相容性測試人員面對的是碎片化的工作，因此本書的目標並不在於涵蓋全面的知識，
而是希望藉由依照問題分類的編排，能夠加速確認問題發生的原因，以及縮短找到解決方法的時間。
對於已經具備實務經驗而想要深入某個主題的讀者，書末列出了幾本相關的書籍與一些參考的網頁，
可以提供各位進一步的探究。

資訊用語的翻譯，向來是寫作相關書籍時難以迴避的問題。
筆者依據個人偏好所挑選的譯詞，或許與常見的用法有些出入；
因而外來詞彙在首次出現時，大部分都會附上原文或縮寫，應該不至於產生混淆。
內文中的重要名詞會以粗體字強調，而命令、引數、檔案、變數名稱則以等寬字顯示。
指令的執行過程會展示於縮排的段落，並且以粗體字代表由使用者輸入的文字、斜體字標記可變的部分。
上下相接的兩列粗體字，通常是因為版面寬度的限制所致，實際操作時請於同一列中輸入。
做為範例的檔案內容，則在段落區塊中襯以淺色背景顯示。

本書的指令主要是在 Fedora Linux 系統中進行測試，同時參考了一些來自 Ubuntu Linux 系統的使用經驗。
撰寫內容時依照 ASCIIDoc 的格式，藉由 `joe` 編輯器輸入後，以 `asciidoctor` 軟體搭配其 `pdf` 與 `pdf-cjk` 模組產生 PDF 檔案。
雖然它的排版效果目前比不上「所見即所得」的文書處理軟體，但是十分適合個人出版或網路協力形式的書籍寫作。
封面與封底的背景是藉助 ChatGPT 所產生，書皮與內嵌的圖表則是先在 LibreOffice 繪製，再匯出為圖片檔案。
數位輸出時的字型使用了「Google Noto Serif」、「Google Noto Sans Mono」、「Liberation Mono」以及「芫荽(iansui)」。
電子書檔案以及排版前的內容，將會在紙本出版之後公開，提供有興趣的自由寫作者參考。

<<<
[discrete]
=== 致謝
特別感謝「公信電子」王英傑副總、陳翔奇經理與其他部門長官的指導，以及許多提供寶貴意見的同事（依姓名傳統字筆畫排列）：
李佳峻、何晏民、吳家慶、林坤盛、林思宇、林俊廷、林顺长、林㿨穆、姚惠雯、徐大皓、徐偉倫、高銘鴻、郭玉平、郭汶瑜、張俊源、
陈绍伟、許惠玲、許喻富、陳蓉萱、黃承堯、黄祥、游騏豪、葉晉廷、劉盈諄、鍾乘禮、魏永旭、羅民君、罗信添。
與各位的腦力激盪，是形成本書內容不可或缺的過程。
另外還要感謝「中華民國軟體自由協會」的幫忙，本書才得以順利出版。

除了同事與個人實際測試的經驗之外，多數的專業資訊來自於網路上的文件，集合了眾多網友分享於手冊、部落格、論壇…中的知識與智慧，
恕我無法一一指名致謝。由於收錄的資料駁雜，如果讀者遇到任何有需要增減修改的地方，還請不吝指正。

____
[.text-right]
{empty} +
{empty} +
趙惟倫
____
[.text-right]
bluebat＠member.fsf.org +
2026年3月

<<<
