[abstract]
== 前言
Linux 相容性測試人員是指在資訊系統硬體製造的公司中，
針對所生產的各款機型，進行 GNU/Linux 作業系統的運作測試，
包括系統安裝、驅動程式、執行效能等項目。

限於筆者本身的技術程度，對於實證有效的對策，並未每項提供充分的理論解釋，
而許多相關的補充手法也無法逐條驗證，衹能附記在旁做為爾後類似狀況的參考。
有些實驗性質的步驟，僅適用於測試硬體，而非辦公或生產用機臺。
如果讀者手邊的電腦已經負有重要的任務，請在應用這些方法前，務必再三確認。

由於相容性測試人員面對的是碎片化的工作，因此本書的目標並不在於涵蓋全面的知識，
而是希望藉由依照硬體問題分類的編排，能夠加速搜尋問題發生的原因，以及縮短找到解決方法的時間。
對於已經具備實務經驗而想要深入某個主題的讀者，書末列出了幾本相關的參考書籍，
可以提供各位進一步的探究。

資訊用語的翻譯，向來是寫作相關書籍時難以迴避的問題。
筆者依據個人偏好所挑選的譯詞，或許與常見的用法有些出入；
因而外來詞彙在首次出現時，大部分都會附上原文，應該不至於產生混淆。
內文中的重要名詞會以粗體字強調，而命令、檔案、變數名稱則以等寬字顯示。
指令的執行過程會顯示於縮排的區塊，並且以粗體字表示由使用者輸入的文字，同時使用斜體字標記可變的部分。
做為範例的檔案內容，則在縮排的區塊中襯以淺色背景顯示。

本書的指令主要是在 Fedora 系統中進行測試，同時參考了一些來自 Ubuntu 系統的使用經驗。
撰寫內容時依照 ASCIIDoc 的格式，藉由 `joe` 或 `gedit` 編輯器輸入後，
以 `asciidoctor` 軟體搭配 `asciidoctor-pdf` 與 `asciidoctor-pdf-cjk` 模組產生 PDF 檔案。
輸出時使用的字型是 Google Noto Serif、Google Noto Sans Mono 與 Liberation Mono。
電子書檔案以及排版前的內容，將會在出版之後公開，提供有興趣的自由寫作者參考。

<<<
[discrete]
=== 致謝
特別感謝「公信電子」王英傑副總、陳翔奇經理和其他長官的指導，以及許多提供寶貴意見的同事（依姓名筆畫排列）：
李佳峻、何晏民、吳家慶、林坤盛、林思宇、林俊廷、林順長、林嚦穆、徐偉倫、姚惠雯、徐大皓、高銘鴻、
郭玉平、郭汶瑜、張俊源、陳紹偉、許惠玲、許喻富、陳蓉萱、黃承堯、黃祥、游騏豪、葉晉廷、劉盈諄、鍾乘禮、魏永旭、羅民君、羅信添。
與各位的腦力激盪，是形成本書內容不可或缺的過程。
另外還要感謝「中華民國軟體自由協會」的幫忙，本書才得以順利出版。

除了個人實際測試的經驗之外，多數的資訊來自於網路上的文件，集合了眾多網友分享於手冊、部落格、論壇…中的智慧與經驗，
恕我無法一一指名致謝。由於收集的資料繁雜，如果讀者發現了需要增減修改的地方，還請不吝指正。

[.text-right]
　 +
　 +
趙惟倫 +
bluebat＠member.fsf.org +
2025-9
